### ISSUE TITLE
2 instances of "riseapi" command

### ISSUE THREAD

**Issue by newuni** [deepmipt/DeepPavlov#1001]
Hello,

I'm trying to raise two "riseapi" commands for two different models in the same machine.

The first one runs on port 5000, the second on port 6001 using the port parameter overload.

Sadly, when I issue a POST request to the second one, at port 6001 I get an error 400: got empty request

Are there any recommendations for this situation?

Thanks in advance.

**Comment by yoptar** [comment]
Hi @newuni,
Looks like there's a mismatch of parameter names. Does an example request from swagger work? You can try it out if you open http://localhost:6001/

**Comment by newuni** [comment]
My fault, one models was in a previous version.

I've updated both to 6.0 version.

Thanks for your prompt reply.

Regards,
