### ISSUE TITLE
BERT Classification files

### ISSUE THREAD

**Issue by AnnaTumanova** [deepmipt/DeepPavlov#1003]
Sorry for bothering I was wondering could I do classification the pdf files to different folders by the context of the file. For example, I have 3 folders invoices, cv, and input folder and could I train with bert nlp folders cv and invoices so when smb will put the pdf file to the input folder it will automatically decide what it is cv or invoice.

**Comment by mu-arkhipov** [comment]
The straightforward way to do so is to convert the `pdf` files to text and then apply our [classifier](http://docs.deeppavlov.ai/en/master/features/models/classifiers.html) to the annotated files.

**Comment by anna-pol** [comment]
so, basically I can restore a saved model (https://github.com/deepmipt/Slavic-BERT-NER#bert-usage),  remove last layer of classification, in this case, right?

**Comment by mu-arkhipov** [comment]
You need to gather the data in the following [format](http://docs.deeppavlov.ai/en/master/features/models/classifiers.html#how-to-train-on-other-datasets), and use the BERT based classifier like in [this](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/classifiers/insults_kaggle_bert.json) config. You need to create a copy of this config and replace the paths
of `vocab_file`, `bert_config_file` and `pretrained_bert` with paths to the BERT model you want to use. Then follow train part of [this](http://docs.deeppavlov.ai/en/master/features/models/classifiers.html#python-code) guide.

**Comment by anna-pol** [comment]
it will work also for the polish language?

**Comment by mu-arkhipov** [comment]
Yes, if you use Slavic model.
