### ISSUE TITLE
Can this  open source library process the Chinese language?

### ISSUE THREAD

**Issue by wangsz05** [deepmipt/DeepPavlov#1007]
If  I want use the libary to prcess the Chinese language, what should I do ?  Support it?

**Comment by yoptar** [comment]
Hi @wangsz05,
What tasks do you have in mind?
Our [multilingual Bert-based question-answering model](https://demo.deeppavlov.ai/#/mu/textqa) should already work in some capacity. For most of other tasks the most obvious problems are tokenization and training data.
