### ISSUE TITLE
[question] Is it possible to get the "original" question to an answer in Frequently Asked Questions skill?

### ISSUE THREAD

**Issue by newuni** [deepmipt/DeepPavlov#1012]
Hi,

is it possible to get the "original" question to an answer in Frequently Asked Questions skill?

By original I mean the "question" column of the CSV with which the FAQ dataset_reader is configured.

Regards,

**Comment by vaskonov** [comment]
Hey @newuni ,
By Frequently Asked Questions skill I assume you mean **SimilarityMatchingSkill**, if so, that the best option is to load _csv_ file externally by using the **data_path** parameter.

**Comment by newuni** [comment]
Hi,

I refer to http://docs.deeppavlov.ai/en/master/features/skills/faq.html section.

When I interact with the model with python -m deeppavlov interact fidf_autofaq I get the answer to the question, but I can't get the "original" question related with this answer and contained in CSV.

Maybe it is not possible.

Regards,

**Comment by newuni** [comment]
Maybe my questions comes by the fact that having 43 lines in CSV, I only get in return an array with 34 score[0,1] values, I was thinking that the array with score should be the same size as lines on CSV.

Regards,

**Comment by vaskonov** [comment]
You can alter the configuration file to output the original **question**. For example, in _tfidf_logreg_en_faq_ you can add **y_pred_ids** variable in the **out** section of the file, as result the model will return the index of the selected **answer**. Similar manipulations can be performed with other configurations.

**Comment by newuni** [comment]
Thanks,
