### ISSUE TITLE
Network used for pre-trained NER and citing DeepPavlov

### ISSUE THREAD

**Issue by sudeshna-d** [deepmipt/DeepPavlov#1014]
Q1: I am unable to find whether CNN or RNN was used to train the CoNLL-2003 pre-trained English NER model in the documentation or [config file](https://github.com/deepmipt/DeepPavlov/blob/0.6.0/deeppavlov/configs/ner/ner_conll2003_bert.json). Please clarify.

Q2: Should the paper mentioned in #815 be cited if we use the pre-trained English NER model?

**Comment by vikmary** [comment]
Hi @sudeshna-d,

Q1: The NER model is based on BERT architecture (adds dense layer on top of last hidden BERT representations), so it uses no RNN or CNN. See [slides](https://docs.google.com/presentation/d/1kQXR_jTWMuCrivlohqz4Eni-_-LXUgAIvvjFxq5MG4w/edit#slide=id.g515708b90f_2_97) for details.

Q2: I'll be able to answer the question a little later.

**Comment by vikmary** [comment]
Q2: You should cite the paper from https://github.com/deepmipt/DeepPavlov/issues/815

**Comment by sudeshna-d** [comment]
Thanks so much!
