### ISSUE TITLE
ModuleNotFoundError: No module named 'deeppavlov' in Jupyter notebook

### ISSUE THREAD

**Issue by weig2000** [deepmipt/DeepPavlov#1025]
Hi everyone,

I've creates a virtual environment deepnlp and installed deeppavlov. Within the env, I can start python3 at the command line and execute 'import deeppavlov' without any problem. But when I run the same code in the Jupyter notebook within the kernel deepnlp selected, I got the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'deeppavlov'

Has anyone run into the same problem and found the problem?

I have the deeppavlov 0.6.1, and python 3.6.8.

Thanks.

**Comment by yoptar** [comment]
Hi @weig2000,
This kind of looks like you have different environments selected. You can run
```
import sys
print(sys.executable)
```
In both to make sure that the environment is the same.

**Comment by weig2000** [comment]
@yoptar Thanks. Indeed, they have different environments after running the statements as you suggeste above. 

Somehow the python in the jupyter notebook used a different python, not the one in the virutal envirnment (deepnlp) even though the notebook was run in that env.

I simply removed the kernel (deepnlp) from jupyter and reinstall it, make sure everything is correct. This time it worked.
