### ISSUE TITLE
Multi-hot additional features in NER

### ISSUE THREAD

**Issue by BloodSource** [deepmipt/DeepPavlov#1028]
I am trying to use additional features in NER (ner_rus model), but I have problems with modifiyng your code for this task. Could you help me with some advice? In my case each token has from 1 to 11 different features from one list, so it would be nice represent this by multi-hot vector, however, as I know, deeppavlov doesn't have multi-hot vectorizer. I was trying to use 11 one-hot vectorizers and sum up resulting vectors, but they should have one aggregate vocabulary to have the same dimentionality. From your config jsons (example below) I assumed that if I write config like below, I would create "sem" vocabulary and automaticaly create "sem_ind" feature to each token and transform it to "sem_one_hot" - one-hot vector for each token. But I need to have the first two steps separately - create one vocabulary (from all of my "feat1", "feat2" etc. altogether) and then use it to crate indices and one-hot vectors for each of "feat1", "feat2" etc. What is the easiest way to do that? Or maybe there is a simplier approach to add multi-hot features?
        {
        "in": ["sem_all"],
        "id": "sem_vocab",
        "class_name": "simple_vocab",
        "pad_with_zeros": true,
        "fit_on": ["sem_all"],
        "save_path": "{MODELS_PATH}/ner_rus/sem.dict",
        "load_path": "{MODELS_PATH}/ner_rus/sem.dict",
        "out": ["sem_ind"]
      },
      {
        "in": ["sem_ind"],
        "class_name": "one_hotter",
        "depth": "#sem_vocab.len",
        "pad_zeros": true,
        "out": ["sem_one_hot"]
      },

**Comment by dilyararimovna** [comment]
Hello!

This is very simple to perform such operation.
Preprocessor `one_hotter` actually supports multi-label one-hot vectorization. If you initialize one-hotter with the following params, you will obtain one-hot multi-label vectorization.
```
{
"in": ["sem_ind"],
"class_name": "one_hotter",
"depth": "#sem_vocab.len",
"pad_zeros": false,
"single_vector": true
"out": ["sem_one_hot"]
},
```
