### ISSUE TITLE
Add tests for BERT tf.keras PR

### ISSUE THREAD

**Issue by yoptar** [deepmipt/DeepPavlov#1034]
We need to add some tests to #895: tests for classes themselves or a config that uses them.
Or we can decide that we don't need it anymore and just close the PR

**Comment by nikolay-bushkov** [comment]
PR could be closed in favor of https://github.com/huggingface/transformers/releases/tag/v2.0.0

**Comment by yoptar** [comment]
@nikolay-bushkov will it work with tf-1.14.0?

**Comment by nikolay-bushkov** [comment]
Probably... It is easier to check than to write some tests for new code.
