### ISSUE TITLE
Can't process train.csv file

### ISSUE THREAD

**Issue by AnnaTumanova** [deepmipt/DeepPavlov#1035]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4380             try:
-> 4381                 return libindex.get_value_box(s, key)
   4382             except IndexError:

pandas/_libs/index.pyx in pandas._libs.index.get_value_box()

pandas/_libs/index.pyx in pandas._libs.index.get_value_at()

pandas/_libs/util.pxd in pandas._libs.util.get_value_at()

pandas/_libs/util.pxd in pandas._libs.util.validate_indexer()

TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-172-a805fa13328b> in <module>
      2 
      3 dat = dataset_readers.basic_classification_reader.BasicClassificationDatasetReader()
----> 4 l=dat.read("C:\\Users\\Anna\\Desktop\\NLP", None, format = 'csv',class_sep=',')

~\Anaconda3\lib\site-packages\deeppavlov\dataset_readers\basic_classification_reader.py in read(self, data_path, url, format, class_sep, *args, **kwargs)
    103                     else:
    104                         # each sample is a tuple ("text", ["label", "label", ...])
--> 105                         data[data_type] = [(row[x], str(row[y]).split(class_sep)) for _, row in df.iterrows()]
    106             else:
    107                 log.warning("Cannot find {} file".format(file))

~\Anaconda3\lib\site-packages\deeppavlov\dataset_readers\basic_classification_reader.py in <listcomp>(.0)
    103                     else:
    104                         # each sample is a tuple ("text", ["label", "label", ...])
--> 105                         data[data_type] = [(row[x], str(row[y]).split(class_sep)) for _, row in df.iterrows()]
    106             else:
    107                 log.warning("Cannot find {} file".format(file))

~\Anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    866         key = com.apply_if_callable(key, self)
    867         try:
--> 868             result = self.index.get_value(self, key)
    869 
    870             if not is_scalar(result):

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4387                     raise InvalidIndexError(key)
   4388                 else:
-> 4389                     raise e1
   4390             except Exception:  # pragma: no cover
   4391                 raise e1

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_value(self, series, key)
   4373         try:
   4374             return self._engine.get_value(s, k,
-> 4375                                           tz=getattr(series.dtype, 'tz', None))
   4376         except KeyError as e1:
   4377             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'text'

from deeppavlov import train_model, configs

**Comment by dilyararimovna** [comment]
Hello, Anna!

I suppose you are trying to use DeepPavlov on your own data. For that you need to use some `dataset_reader`. So, as I can see, you are using `basic_classification_reader`. it requires several arguments:
```
"dataset_reader": {
    "class_name": "basic_classification_reader",
    "data_path": "{DOWNLOADS_PATH}/my_own_data_folder",  # this is a dataset folder
    "train": "train.csv",  # this is a name of train file which is in the dataset folder
    "valid": "valid.csv",
    "test": "test.csv",
    "x": "text",  # this is a name of the column of csv files containing Texts for classification
    "y": "label"  # this is a name of the column of csv files containing Labels for classification
  }
```

So, your `csv` file probably does not contain `text` column. Just change the configuration file a bit to make it compatible with your dataset.
