### ISSUE TITLE
How to train custom NER model for text paragraphs?

### ISSUE THREAD

**Issue by DLNSimha** [deepmipt/DeepPavlov#1036]
Getting errors related to token size if I pass a paragraph instead of a sentence.

I have increased the size of max_seq_length in the file bert_preprocessor.py. After that, i getting the below error.

InvalidArgumentError: assertion failed: [] [Condition x <= y did not hold element-wise:x (bert/embeddings/strided_slice_3:0) = ] [580] [y (bert/embeddings/assert_less_equal/y:0) = ] [512]
         [[{{node bert/embeddings/assert_less_equal/Assert/Assert}}]]

**Comment by mu-arkhipov** [comment]
Hi!
It seams that your input sequence has more than 512 subtokens. Unfortunately BERT based models does not support sequences longer than 512 because of trainable positional embeddings.

**Comment by polodealvarado** [comment]
Hi!

Could it be possible to add a sentence splitting method into the pipeline of the config file to solve it?

**Comment by mu-arkhipov** [comment]
Hi, 
It would be convenient to search and track if there will be a separate issue for this feature request. @polodealvarado please make one.

**Comment by polodealvarado** [comment]
Perfect, I'll do it.
