### ISSUE TITLE
Deeppavlov's site don't load

### ISSUE THREAD

**Issue by BetoFernandess** [deepmipt/DeepPavlov#1042]
Hello guys. The DeepPavlov's site (deeppavlov.ai) dont't load in my computer. What happen'd with the site?

**Comment by moryshka** [comment]
Hi, BetoFernandess
Please, use the link https://deeppavlov.ai for safety connection. 
If it also won't work, please send the screenshot of the site.

**Comment by BetoFernandess** [comment]
Still doen't work. 
![image](https://user-images.githubusercontent.com/23056234/66865282-4b946180-ef6d-11e9-9527-cfc74e11a5d2.png)
I'm using the work's computer.

**Comment by BetoFernandess** [comment]
Stil doesn't work:

![image](https://user-images.githubusercontent.com/23056234/66866278-594ae680-ef6f-11e9-8c2b-6d9a68a2d1cf.png)

I'm using enterprise's workspace.

**Comment by moryshka** [comment]
Unfortunately, this is most likely a problem on your network.  
Your provider is blocking this site by IP
