### ISSUE TITLE
how to save and load trained model

### ISSUE THREAD

**Issue by HFCristian** [deepmipt/DeepPavlov#1043]
I'm using it as follows
````
from deeppavlov import configs, train_model

model_config = read_json(configs.faq.tfidf_logreg_en_faq)
model_config["dataset_reader"]["data_path"] = "/content/faq.csv"
model_config["dataset_reader"]["data_url"] = None
faq = train_model(model_config)
````
I need to save this template to use again without training.
how to make?

**Comment by dilyararimovna** [comment]
Hi!
Could you, please, clarify what do you want to save: config file or model itself?
In the first case, you just need to save `model_config` using `json.dump` function.
In the second case, you are better to change `save_path` and `load_path` in all models (for all fitable and trainable models) to your custom paths. And then after `train_model` you can just do
```
faq.save()
```
And model will be saved in `save_path`.

**Comment by HFCristian** [comment]
it's the second case. And how to load the model?

**Comment by dilyararimovna** [comment]
Then you need to save your `model_config`, and next time just to do:
```
from deeppavlov import build_model

faq = build_model(model_config)
```
