### ISSUE TITLE
ModuleNotFoundError: No module named 'bert_dp'

### ISSUE THREAD

**Issue by luke4u** [deepmipt/DeepPavlov#1058]
Hey Guys, 

Trying to do a quick run on Bert-QA, but above error pops up. What I did is simple.
1) create a vir env in conda
2) install deeppavlov: pip install deeppavlov
3) install requests for the squad_bert: python -m deeppavlov install squad_bert

But this error keeps coming out. The thing is that after step 3, bert_dp has been installed! Can anyone give me advice? 

Thanks so much! Luke

--------------------------error msg below---------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-159e82c754ff> in <module>
----> 1 model = build_model(configs.squad.squad_bert, download=False)
      2 # model = build_model(configs.squad.squad)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\commands\infer.py in build_model(config, mode, load_trained, download, serialized)
     59             component_serialized = None
     60 
---> 61         component = from_params(component_config, mode=mode, serialized=component_serialized)
     62 
     63         if 'id' in component_config:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\params.py in from_params(params, mode, serialized, **kwargs)
     92         log.exception(e)
     93         raise e
---> 94     cls = get_model(cls_name)
     95 
     96     # find the submodels params recursively

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\registry.py in get_model(name)
     69             raise ConfigError("Model {} is not registered.".format(name))
     70         return cls_from_str(name)
---> 71     return cls_from_str(_REGISTRY[name])
     72 
     73 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\registry.py in cls_from_str(name)
     38                           .format(name))
     39 
---> 40     return getattr(importlib.import_module(module_name), cls_name)
     41 
     42 

~\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py in <module>
     18 
     19 import numpy as np
---> 20 from bert_dp.preprocessing import convert_examples_to_features, InputExample, InputFeatures
     21 from bert_dp.tokenization import FullTokenizer
     22 

ModuleNotFoundError: No module named 'bert_dp'

**Comment by yoptar** [comment]
Most likely `python` in `python -m deeppavlov install squad_bert` is not the same python that you run the model with.
In the code you can check
```
import sys
print(sys.executable)
```
and from terminal `python -c 'import sys; print(sys.executable)'`

**Comment by luke4u** [comment]
Thanks @yoptar. You are right. From the jupyter notebook, it returns 
'C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\python.exe'

But from the terminal, it returns
'C:\Users\kx764qe\AppData\Local\Continuum\anaconda3\envs\pavlov\python.exe'.

Jupyter notebook is calling the python in my vir env. 
But I run it within my virtual env:
'(pavlov) C:\Users\kx764qe\Desktop\deep_pavlov>jupyter notebook' 

Do you possibly know why? Thanks a lot.

**Comment by yoptar** [comment]
You shoud first install jupyter in the enviroment if you want to do it like that. Or you can [add a kernel of this environment](https://anbasile.github.io/programming/2017/06/25/jupyter-venv/).
```
(pavlov) $ pip install ipykernel
(pavlov) $ ipython kernel install --user --name=deppavlov
```
and then use it from your global jupyter.

**Comment by luke4u** [comment]
Thanks agian @yoptar . Really appreciate the help. 
I took the first one, it worked now.

**Comment by luke4u** [comment]
Thanks agian @yoptar . Really appreciate the help. 
I took the first one, it worked now.
