### ISSUE TITLE
understanding on different configs

### ISSUE THREAD

**Issue by luke4u** [deepmipt/DeepPavlov#1059]
Hey Guys,

Trying to get a better understanding on different configs. Taking multi_squad_noans.json, multi_squad_noans_infer.json, squad.json, squad_bert.json, squad_bert_infer.json, squad_bert_multilingual_freezed_emb.json as examples. 

1) they are all trained on SQuAD 1.1 dataset?
2) squad_bert.json is based on bert cased_L-12_H-768_A-12. what model squad.json is based on? 
3) what does _infter mean? 
4) what does _freezed_emb.json mean? 

Is there a link on official doc explaining the difference? 

Thanks a lot. Luke

**Comment by yurakuratov** [comment]
Hi!

Some of the models are described in doc page (in tables with results): http://docs.deeppavlov.ai/en/master/features/models/squad.html

- \*squad\* - models trained on SQuAD v1.1 dataset (En)
- squad_ru\* - models trained on SDSJ Task B dataset (Ru)
- squad_zh\* - models trained on DRCD dataset (Zh)
- \*bert\* - model is based on BERT (En)
- \*rubert\* - model is based on RuBERT (Ru)
- \*bert_multilingual\* - model is based on Multilingual BERT
- \*infer - models based on BERT that can be used for texts with more than 512 subtokens (BERT has limitation 512 tokens).
- Models with multi* prefix were trained to be used in multi-paragraph mode, when you feed several paragraphs to model and then select only one answer.

> 2. squad_bert.json is based on bert cased_L-12_H-768_A-12. what model squad.json is based on?

R-Net model is used If there is no bert in the name of config file.

> 4. what does _freezed_emb.json mean?

experimental version of model: subtokens embeddings were not changed during model training

**Comment by luke4u** [comment]
@yurakuratov . Thanks for explanation. Really helpful! 

One question: is *ru* trained on Russian? What is difference between squad_ru_bert.json and squad_ru_rubert.json?  For QA problem with many paragraphs as contexts, which config would you recommend to try? 

Thanks so much again! Luke

**Comment by yurakuratov** [comment]
yes, models with *ru* in name are trained for Russian language.

squad_ru_bert.json -- model is trained on SDSJ Task B with Multilingual BERT
squad_ru_rubert.json -- model is trained on SDSJ Task B with RuBERT

In case of several paragraphs I would recommend to try `squad_ru_rubert_infer.json` and `multi_squad_ru_retr_noans_rubert_infer.json`. You can feed multiple paragraphs as single text to *infer* models.

**Comment by luke4u** [comment]
Hi @yurakuratov , sorry for late response. 
My concern is if rubert is trained on Russian language, would that model applies well on English texts? 

Thanks again. Luke

**Comment by yurakuratov** [comment]
Models that were trained on Russian language are supposed to be used for Russian language.
If you need models for English, you can use models without **ru** in the name of config file.

**Comment by luke4u** [comment]
Thanks @yurakuratov .
