### ISSUE TITLE
Can any give some suggestion how to train a own dataset using NER pretrained model

### ISSUE THREAD

**Issue by vigneshgig** [deepmipt/DeepPavlov#1062]
Hi, Thanks for the great project.
I have some few question regarding custom training.

first question: In which format i have to prepare the training dataset.
-DOCSTART- -X- -X- O

EU NNP B-NP B-ORG
rejects VBZ B-VP O
German JJ B-NP B-MISC
call NN I-NP O
to TO B-VP O
boycott VB I-VP O
British JJ B-NP B-MISC
lamb NN I-NP O
. . O O

or

EU B-ORG
rejects O
the O
call O
of O
Germany B-LOC
to O
boycott O
lamb O
from O
Great B-LOC
Britain I-LOC
. O

China B-LOC
says O
time O
right O
for O
Taiwan B-LOC
talks O
. O

If I have to do like a first format means "How can I tag the pos and bio-tag schema for the training data.
second question:where should i change my current dataset (train.txt,test.txt,valid.txt) path in config file and where can i find the config file in my local.

third question: in which location the trained model is saved after training is finished and where i can change the hyperparameter(epochs,learning_rate etc.,)

Thanks

**Comment by yoptar** [comment]
Hi @vigneshgig,
1. Both options are acceptable: every line will be split by spaces and the first word is used as a token and the last — as a tag.
You can also take a look at the [ner_conll2003_pos](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_conll2003_pos.json) configuration file, it will use the second word of every line as a POS-tag, but you'll also have to provide POS-tags when inferring this model.
2. `data_path` argument for the `dataset_reader` in a config should be a path to the directory with `train.txt`, `valid.txt` and `test.txt` files. You can also omit the `dataset_name` parameter when using your own training data.
As for the config file location, you can run
    ```python3
    from deeppavlov import configs
    print(configs.ner.ner_ontonotes_bert)
    ```
    and get its path. You can copy the file anywhere and just use your path as a parameter for the `train_model` function
3. You can find (and modify) the save path in the `save_path` and `load_path` parameters in a configuration file. For example in the [ner_ontonotes_bert_mult](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json) the model will be saved to `~/.deeppavlov/models/ner_ontonotes_bert_mult`. You can change the `NER_PATH` variable in the `metadata` block.

**Comment by vigneshgig** [comment]
Hi @yoptar , thanks Now I got it, but can you explain why should we provide pos-tag when inferring the ner model as you mention above
You can also take a look at the ner_conll2003_pos configuration file, it will use the second word of every line as a POS-tag, but **you'll also have to provide POS-tags when inferring this model.**
Thanks

**Comment by yoptar** [comment]
The `ner_conll2003_pos` config is made for a case when you want to predict NER-tags based on tokens and their POS-tags. POS-tags do help, but you have to get them from somewhere. All the other configs, if I remember correctly, do not use them.
> is DOCSTART is compulsory

I do not think that it is.
