### ISSUE TITLE
fine tune bert

### ISSUE THREAD

**Issue by sonfiree** [deepmipt/DeepPavlov#1065]
Is there a tutorial on how to make fine tune bert for the Russian language on my data?

**Comment by yurakuratov** [comment]
Hi!

We don't have a tutorial on that. But you can follow this guide from BERT authors: https://github.com/google-research/bert#pre-training-with-bert
and use RuBERT vocabulary and RuBERT checkpoint as initialization.

https://github.com/google-research/bert repo does not supports multi-gpu training (only single GPU or TPUs). In case if you have multiple GPUs you can use our multi-gpu fork: https://github.com/deepmipt/bert/tree/feat/multi_gpu
