### ISSUE TITLE
QA: where to find tokenizer and pretrained QA model being called 

### ISSUE THREAD

**Issue by luke4u** [deepmipt/DeepPavlov#1066]
Hi Guys,

I am trying to understanding how this below code works, because this is an interface for QA system.

```
from deeppavlov import build_model, configs
model = build_model(configs.squad.squad, download=True) #core/commands/infer.py
model(['DeepPavlov is library for NLP and dialog systems.'], ['What is DeepPavlov?'])
```

If right, this function is to parse config file and read in as dict, download model data, import needed packages, create chainer object. I understand build_model() creates a Chainer object. But I am struggling to find where the real magic happens (take **multi_squad_noans_infer.json** for instance): 

--- tokenize the input and call for pretrained QA model and return output

Can anyone share some insights or points me a direction? This [article  ](https://medium.com/tensorflow/deeppavlov-an-open-source-library-for-end-to-end-dialog-systems-and-chatbots-31cf26849e37)is a good source, but cannot give me an answer. 

Thanks so much. Luke

**Comment by yoptar** [comment]
Hi @luke4u,
You can find the chainer logic in `chainer.pipe` of the config.
If we're looking at [multi_squad_noans_infer](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/squad/multi_squad_noans_infer.json):
- `squad_preprocessor` \(which is a registered name of [deeppavlov.models.preprocessors.squad_preprocessor.SquadPreprocessor](https://github.com/deepmipt/DeepPavlov/blob/0.6.1/deeppavlov/models/preprocessors/squad_preprocessor.py#L37)\) takes contexts and questions and returns sanitized contexts, contexts tokens, contexts chars, mappings between original character indexes and sanitized ones, sanitized questions, questions tokens, question chars and context tokens positions in the text
- `squad_ans_preprocessor`  \(which is a registered name of [deeppavlov.models.preprocessors.squad_preprocessor.SquadAnsPreprocessor](https://github.com/deepmipt/DeepPavlov/blob/0.6.1/deeppavlov/models/preprocessors/squad_preprocessor.py#L147)\) is only used for training
- `squad_vocab_embedder`  \(which is a registered name of [deeppavlov.models.preprocessors.squad_preprocessor.SquadVocabEmbedder](https://github.com/deepmipt/DeepPavlov/blob/0.6.1/deeppavlov/models/preprocessors/squad_preprocessor.py#L196)\) is there twice: one for context and question tokens and the other one — for chars
- `squad_model` \(which is a registered name of [deeppavlov.models.squad.squad.SquadModel](https://github.com/deepmipt/DeepPavlov/blob/0.6.1/deeppavlov/models/squad/squad.py#L31)\) is the model itself
- `squad_ans_postprocessor` \(which is a registered name of [deeppavlov.models.preprocessors.squad_preprocessor.SquadAnsPostprocessor](https://github.com/deepmipt/DeepPavlov/blob/0.6.1/deeppavlov/models/preprocessors/squad_preprocessor.py#L344)\) finds answers and their positions in original texts.

All of these components are built within  a Chainer object.
We have a [documentation on configuration files](http://docs.deeppavlov.ai/en/master/intro/configuration.html), it should help to understand how things work.

**Comment by luke4u** [comment]
Thanks a lot @yoptar . This is definitely very helpful!
