### ISSUE TITLE
Can kbqa support english version? Or, could it possible one detailed instruction written and everyone else can do it for their own native language

### ISSUE THREAD

**Issue by daqulazhang** [deepmipt/DeepPavlov#1072]
Can kbqa support english version? Or, could it possible one detailed instruction written and everyone else can do it for their own native language

**Comment by mu-arkhipov** [comment]
Hello,
At the moment KBQA supports only Russian language. English version is a current pull request. Training of such system is quite complex, there is no detailed instruction at the moment. Nevertheless, here is a high-level overview of how system was trained:
1) Linking of bAbI dataset to Wikidata (originally it is on Freebase)
2) Building NER dataset with BIO markup by finding entities in the questions using aliases
3) Training NER system (Bi-LSTM CRF tagger) and Relation Classification system (CNN question classifier)
4) Building index for Wikidata entries for fast entity search 
We also translated and used templates from [ZSRE dataset](http://nlp.cs.washington.edu/zeroshot/) which are actually cover a lot of typical questions.

**Comment by daqulazhang** [comment]
Hi, arkhipov,
Sorry if I got your name wrong, I am not quite familar with Russian:)
That sounds great about ZSRE, I am so willing to try that, is there some instructions like http://docs.deeppavlov.ai/en/master/features/models/kbqa.html
here can guide me how to use ZSRE in deeppavlov like we use wiki data so smoothly?
I checked kbqa mannul, seems not ZSRE mentioned there.

**Comment by dmitrijeuseew** [comment]
Hi, daqulazhang, ZRSE dataset is used the following way:
about 1000 question templates from ZRSE dataset with corresponding relations are written into a pickle file.
An input question to the model is compared with each of these templates. For example, the question
"What is the capital of Germany?" matches with the template "What is the capital of XXX?", the relation from Wikidata is P36 ("capital"), the entity substring is "Germany".
Such template matching is additional to machine learning components of KBQA.
