### ISSUE TITLE
bert_squad REST API - There was an error parsing the body

### ISSUE THREAD

**Issue by mabu-dev** [deepmipt/DeepPavlov#1073]
The REST endpoint doesn't accept requests on /probe and /model - I'm using python's requests

**/probe**
probe_req = requests.post("http://localhost:5000/probe")
probe_req.json()
Results: 
{'detail': [{'loc': ['body', 'item'],
   'msg': 'field required',
   'type': 'value_error.missing'}]}

**/model**
payload = [{'context_raw': ['Mabu is a data scietist'],
            'question_raw': ['Who is Mabu?']}]
predict = requests.post("http://localhost:5000/model", data=payload)
predict.json()
Results:
{'detail': 'There was an error parsing the body'}

**Comment by IgnatovFedor** [comment]
Hi @mabu-dev 
**/probe**
You have to send some payload in your POST-request to the service. For example adding an empty dictionary as payload should fix request:
```
probe_req = requests.post("http://localhost:5000/probe", json={})
probe_req.json()
```
Results: `['Test passed']`

**/model**
Listing a dictionary is redundant. 
```
payload = {'context_raw': ['Mabu is a data scietist'], 'question_raw': ['Who is Mabu?']}
predict = requests.post("http://localhost:5000/model", json=payload)
predict.json()
```
Results: `[['a data scietist', 8, 80782.3515625]]`

Note that passing `{'a': 'b'}` to post method as `data` argument will sent it in the request body as `a=b`. To send `payload` as model argument you shout either encode it first with `json.dumps` or pass payload as `json` argument.

**Comment by mabu-dev** [comment]
Works like a charm! Thank you very much!!
