### ISSUE TITLE
What parameters of RuBert training?

### ISSUE THREAD

**Issue by K-Mike** [deepmipt/DeepPavlov#1074]
Especially I interested in max_len
and what corpse did you use?

**Comment by yurakuratov** [comment]
Hi!

We trained model in two phases:
1. max_seq_len = 128
2. max_seq_len = 512, and train only positional embeddings

As training corpora we used Russian Wikipedia and News from Lenta.ru (total about ~6.5Gb).

You can find some details in our paper: https://arxiv.org/abs/1905.07213

**Comment by K-Mike** [comment]
Thank you Yuriy!

How much time did it take? How many GPUs did you use?

**Comment by yurakuratov** [comment]
We used single DGX-1 with 8 P-100 (16Gb).
Training took about one month. (4M steps for max_seq_len=128, 300k steps for 512).
