### ISSUE TITLE
FAQ new dataset

### ISSUE THREAD

**Issue by Elfreezy** [deepmipt/DeepPavlov#1080]
Здравствуйте, не могли бы вы уточнить?
Вопрос: тренируется ли **уже загруженная** модель?
Описание: В конфиге tfidf_autofaq заменяю data_path на путь с данными формата csv. После этого я могу построить и тренировать эту модель, однако после загрузки этой модели она остается **фиксированной**. Если в дальнейшем тренировать модель по тому же конфигу, но подгружать в агент именно ту модель, что загружена ранее, то и поведение остается старое.

Возможно ли, и если да, то как, изменять загруженную модель, при редактировании файла с информацией? 
Из ответов, которые нашел, был только способ удаления предыдущей модели. Почти уверен, что существуют альтернативы, но не могу найти

**Comment by Elfreezy** [comment]
Дополнительный вопрос.
Можно ли редактировать исходный код дефолт агента? Хотел получать текст введенный пользователем и сохранять в файл, если у ответа default_confidence меньше 0.5

**Comment by Elfreezy** [comment]
> 
> 
> Здравствуйте, не могли бы вы уточнить?
> Вопрос: тренируется ли **уже загруженная** модель?
> Описание: В конфиге tfidf_autofaq заменяю data_path на путь с данными формата csv. После этого я могу построить и тренировать эту модель, однако после загрузки этой модели она остается **фиксированной**. Если в дальнейшем тренировать модель по тому же конфигу, но подгружать в агент именно ту модель, что загружена ранее, то и поведение остается старое.
> 
> Возможно ли, и если да, то как, изменять загруженную модель, при редактировании файла с информацией?
> Из ответов, которые нашел, был только способ удаления предыдущей модели. Почти уверен, что существуют альтернативы, но не могу найти

**Comment by yoptar** [comment]
Здравствуйте, @Elfreezy!
> Вопрос: тренируется ли уже загруженная модель?
> Описание: В конфиге tfidf_autofaq заменяю data_path на путь с данными формата csv. После этого я могу построить и тренировать эту модель, однако после загрузки этой модели она остается фиксированной. Если в дальнейшем тренировать модель по тому же конфигу, но подгружать в агент именно ту модель, что загружена ранее, то и поведение остается старое.

Модель должна тренироваться, да. Возможно, используется опция загрузки? `download=True` из питона или `-d` из консоли. Тогда натренированная модель перетрётся моделью из конфигурации. Можно ещё из самого конфига загрузку претренированной модели убрать, чтобы наверняка. И даже поменять пути к самой модели.

> Можно ли редактировать исходный код дефолт агента?

Можно всё редактировать, конечно, мы для того и opensource :-)
Но в следующих релизах мы откажемся от агента в этом репозитории в пользу [DeepPavlov Agent](https://github.com/deepmipt/dp-agent)

**Comment by Elfreezy** [comment]
Спасибо, в принципе, вы ответили на интересующие вопросы, однако возникает новый. Будет ли функционировать старый агент и весь его функционал? Я правильно понимаю, что вы просто не будете его (старые агенты) дополнять, но пред. возможности использовать его останутся? 
Спасибо вам за вашу работу. Хотелось бы больше примеров использования того или иного функционала (нашел только 3-4 статьи)

**Comment by yoptar** [comment]
> Будет ли функционировать старый агент и весь его функционал?

Уже в ближайшем релизе он будет перенесён в другой модуль `deprecated`, и чтобы продолжать им пользовать, нужно будет провести некоторую работу.
В ветке [dev](https://github.com/deepmipt/DeepPavlov/tree/dev) видно, как это будет выглядеть.
Но всегда можно просто не обновляться, пока функционала хватает.

> Можно ли использовать нового агента уже?

Да, мы сами его используем. Ближе к новому году должна выйти новая версия, и там тоже можно писать в issues любые вопросы.
