### ISSUE TITLE
How to train my data on Bert ranking ?

### ISSUE THREAD

**Issue by dimwael** [deepmipt/DeepPavlov#1081]
Please correct me if I am wrong, instead TF_IDF we can use Bert for classification like for the insuranceQA V1 ? (configs.rankings.ranking_insurance_interact model )
If yes, how can we train it on csv file ?

**Comment by puleon** [comment]
You can do it in the same way as with other ranking models. Please, see the documentation `https://deeppavlov.readthedocs.io/en/master/features/models/neural_ranking.html#training-and-inference-on-your-own-data`. That is to train on your own csv file you need to provide train, dev, test files in the appropriate file format and use the `siamese_reader` component as a reader and the `siamese_iterator` as an iterator in your configuration file.
