### ISSUE TITLE
How to create my own TF-IDF matrix?

### ISSUE THREAD

**Issue by w95** [deepmipt/DeepPavlov#1082]
Hi there, I would like to create a custom train file based on en_ranker_tfidf_wiki.json, but I don't want to use the default Wikipedia vectors file. How can I create new vectors file, based on my own data?

**Comment by yoptar** [comment]
Hi @w95,
For that you can modify the `dataset_reader` block in your config:
```json
{
  "dataset_reader": {
    "class_name": "odqa_reader",
    "data_path": "~/path/to/documents/directory",
    "save_path": "~/path/to/resulting/sqlite.db",
    "dataset_format": "txt"
  },
  "dataset_iterator": {
    "class_name": "sqlite_iterator",
    "shuffle": false,
    "load_path": "~/path/to/resulting/sqlite.db"
  }
}
```
Where `~/path/to/documents/directory` is a directory that contains your text documents.

**Comment by w95** [comment]
@yoptar Thanks a lot for fast response, what about the .npz file ({MODELS_PATH}/odqa/enwiki_tfidf_matrix.npz), should I use the default one?

**Comment by yoptar** [comment]
> what about the .npz file ({MODELS_PATH}/odqa/enwiki_tfidf_matrix.npz), should I use the default one?

It should be overwritten, but I would change the location, just to be sure. You can also remove the `metadata.download` block from your config.

**Comment by w95** [comment]
Thank you!
