### ISSUE TITLE
Is there any way to build docker image for new trained NER model?

### ISSUE THREAD

**Issue by DLNSimha** [deepmipt/DeepPavlov#1085]
How to build a docker image for the newly trained NER model by DeepPavlov?

**Comment by IgnatovFedor** [comment]
Hi @DLNSimha,
DeepPavlov has Docker images to run models on [cpu](https://hub.docker.com/r/deeppavlov/base-cpu) and [gpu](https://hub.docker.com/r/deeppavlov/base-gpu). You could use this images for your tasks or build new images using Docker [documentation](https://docs.docker.com/engine/reference/builder/) and existing [DeepPavlov dockerfiles](https://github.com/deepmipt/stand_kubernetes_cluster/tree/master/utils/dp_base) as reference.
