### ISSUE TITLE
Телеграм бот

### ISSUE THREAD

**Issue by Elfreezy** [deepmipt/DeepPavlov#1088]
Из туториала создания простого бота не понял для чего нужны файлы validation/test (assistant-val.json and assistant-tst.json), если по шаблонам и тренировкам все ясно, то с этими у меня возникли вопросы. Как их заполнять в зависимости от задачи, что там происходит?

**Comment by yoptar** [comment]
Для оценки качества работы модели на данных, на которых она не училась. На validation оценивается качество периодически во время тренировки, а на test — только в конце. Если на validation качество начинает падать, то мы решаем, что модель переобучилась на тренировочных данных.
Там должны быть примерно такие же данные, как и в трейне, но которых в трейне нет.
