### ISSUE TITLE
Issue: Override ROOT_PATH

### ISSUE THREAD

**Issue by luke4u** [deepmipt/DeepPavlov#1089]
Hi Guys,

I try to override ROOT_PATH with a separate path. Got an error:
```
~\AppData\Local\Continuum\anaconda3\envs\deep_pavlov\lib\site-packages\deeppavlov\models\squad\squad.py in __init__(self, word_emb, char_emb, context_limit, question_limit, char_limit, train_char_emb, char_hidden_size, encoder_hidden_size, attention_hidden_size, keep_prob, min_learning_rate, noans_token, **kwargs)
     71         self.noans_token = noans_token
     72 
---> 73         self.word_emb_dim = self.init_word_emb.shape[1]
     74         self.char_emb_dim = self.init_char_emb.shape[1]
     75 

AttributeError: 'NoneType' object has no attribute 'shape'
```
**_What I did is_**: 
`"ROOT_PATH": "/C/Users/kx764qe/Desktop/deep_pavlov/deep_pavlov_model"`, In this folder, I have below:
![image](https://user-images.githubusercontent.com/45267576/70074119-08ac4d00-15f2-11ea-9e9b-e90655479b81.png)
_**I am using**_: **multi_squad_noans_infer.json**.  Can anyone give some insights on how to fix it? 

Thanks. Luke

**Comment by yoptar** [comment]
Hi @luke4u,
It's a Windows thing. You can replace it with `"C:/Users/kx764qe/Desktop/deep_pavlov/deep_pavlov_model"` or `"~/Desktop/deep_pavlov/deep_pavlov_model"` if you're running this as `kx764qe`

**Comment by luke4u** [comment]
Thanks @yoptar . problem solved.
