### ISSUE TITLE
NER fine-tuninng using pretrained using ner_ontonotes_bert_mult

### ISSUE THREAD

**Issue by igormis** [deepmipt/DeepPavlov#1097]
I am trying to use Bert for NER recognition of standard and some custom entities. For instance, I have the following entities:
`'financial_instrument', 'amount', 'percent', 'hashtag', 'exchange', 'number', 'sector', 'period', 'location', 'media_type', 'analyst', 'ticker', 'person', 'price_movement', 'rating_agency', 'product', 'amount_price_target', 'financial_topic', 'publication', 'company', 'event'`
and some of them I can map to the existing ones in BIO format, such as:
`EVENT, PERCENT, NUMBER, GPE, PERIOD, NORG`, etc.
However, some of my entities are new and cannot be mapped.
I was wondering if I can use the pretrained ner_ontonotes_bert_mult and just add my specific entities to fine-tune the model?
Is this possible and could you provide to me sample code?

Tnx

**Comment by yoptar** [comment]
Hi @igormis,
I think it might be better to merge your dataset with the OntoNotes one while renaming the entities in one or another. Then you can train the model from scratch on this merged data.

**Comment by igormis** [comment]
OK, got it and tnx. Could u provide a link of the dataset?

**Comment by yoptar** [comment]
> Could u provide a link of the dataset?

http://files.deeppavlov.ai/deeppavlov_data/ontonotes_ner.tar.gz

**Comment by igormis** [comment]
Tnx, And by combining the OntoNotes and mine dataset I will build a model that will be multilingual?

**Comment by igormis** [comment]
When I try to run the python code:
```
import json
from deeppavlov import configs, build_model, train_model

with configs.ner.ner_ontonotes_bert_mult.open(encoding='utf8') as f:
    ner_config = json.load(f)
print(ner_config)
ner_config['dataset_reader']['data_path'] = './data/'  # directory with train.txt, valid.txt and test.txt files
ner_config['metadata']['variables']['NER_PATH'] = './model/'
ner_config['metadata']['download'] = [ner_config['metadata']['download'][-1]]  # do not download the pretrained ontonotes model

ner_model = train_model(ner_config, download=True)
```
I get the following error:
`
requests.exceptions.ConnectionError: HTTPConnectionPool(host='files.deeppavlov.ai', port=80): Max retries exceeded with url: /deeppavlov_data/bert/multi_cased_L-12_H-768_A-12.zip.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9a4c25c18>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by yoptar** [comment]
There was a power outage in our data center, so the `files.deeppavlov.ai` server is down for now. If you have the BERT model downloaded, you can just remove the `download=True` argument.

**Comment by igormis** [comment]
OK, tnx.
I succeed to train the model and obtained the best model:
 - checkpoint
 - model.data-00000-of-00001
 - model.index
- model.data
and 
- tag.dict
How can I now load the model for inference?

**Comment by yoptar** [comment]
How can I now load the model for inference?
```python3
import json
from deeppavlov import configs, build_model

with configs.ner.ner_ontonotes_bert_mult.open(encoding='utf8') as f:
    ner_config = json.load(f)
ner_config['metadata']['variables']['NER_PATH'] = './model/'
ner_config['metadata']['download'] = [ner_config['metadata']['download'][-1]]  # do not download the pretrained ontonotes model

ner_model = build_model(ner_config)
```
You can also save your updated config to a file and just use it without further modifications: take the [base config](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json), replace [`NER_PATH` in `variables`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json#L104), remove [default ner model archive from downloads](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json#L112-L115) (or replace it with your own) and then just run `ner_model = build_model('path/to/your/config.json)`

**Comment by ferrygun** [comment]
how long does it take to train with CPU ?

I am getting this message while training, but I am not sure how to interpret it correctly. Can you advise.

```
{"train": {"eval_examples_count": 16, "metrics": {"ner_f1": 8.6957, "ner_token_f1": 14.0351}, "time_spent": "2:18:49", "epochs_done": 0, "batches_seen": 140, "train_examples_seen": 2240, "head_learning_rate": 0.009999999776482582, "bert_learning_rate": 1.9999999552965164e-05, "loss": 6.453477513790131}}
2020-04-09 18:12:52.406 DEBUG in 'deeppavlov.metrics.fmeasure'['fmeasure'] at line 394: processed 163118 tokens with 11068 phrases; found: 4514 phrases; correct: 0.

precision:  10.59%; recall:  4.32%; FB1:  6.14

        CARDINAL: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        DATE: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        EVENT: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        FAC: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        GPE: precision:  8.99%; recall:  13.05%; F1:  10.65 3293

        LANGUAGE: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        LAW: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        LOC: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        MONEY: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        NORP: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        ORDINAL: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        ORG: precision:  6.40%; recall:  2.41%; F1:  3.51 656

        PERCENT: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        PERSON: precision:  24.78%; recall:  6.93%; F1:  10.83 565

        PRODUCT: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        QUANTITY: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        TIME: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        WORK_OF_ART: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        nancial_instrument: precision:  0.00%; recall:  0.00%; F1:  0.00 0


2020-04-09 18:12:52.636 INFO in 'deeppavlov.core.trainers.nn_trainer'['nn_trainer'] at line 211: Did not improve on the ner_f1 of 32.2876
{"valid": {"eval_examples_count": 9604, "metrics": {"ner_f1": 6.1353, "ner_token_f1": 13.2213}, "time_spent": "2:36:09", "epochs_done": 0, "batches_seen": 140, "train_examples_seen": 2240, "impatience": 7, "patience_limit": 100}}
2020-04-09 18:15:16.823 DEBUG in 'deeppavlov.metrics.fmeasure'['fmeasure'] at line 394: processed 180 tokens with 6 phrases; found: 5 phrases; correct: 0.

precision:  20.00%; recall:  16.67%; FB1:  18.18

        CARDINAL: precision:  0.00%; recall:  0.00%; F1:  0.00 0

        GPE: precision:  0.00%; recall:  0.00%; F1:  0.00 1

        ORG: precision:  50.00%; recall:  50.00%; F1:  50.00 2

        PERSON: precision:  0.00%; recall:  0.00%; F1:  0.00 2


{"train": {"eval_examples_count": 16, "metrics": {"ner_f1": 18.1818, "ner_token_f1": 33.3333}, "time_spent": "2:38:33", "epochs_done": 0, "batches_seen": 160, "train_examples_seen": 2560, "head_learning_rate": 0.009999999776482582, "bert_learning_rate": 1.9999999552965164e-05, "loss": 4.355190372467041}} 
```

**Comment by ferrygun** [comment]
Also, when preparing the custom entity, do I need to use the BIO format? Or I can just insert my custom entity like:

stlf    financial_instrument

Or

stlf B_FIN

Where stlf is my new word and financial_instrument and B_FIN is the custom entity.

**Comment by xirect** [comment]
Anybody has an idea over how the ner_ontonotes_bert_mult model is licensed?

**Comment by yoptar** [comment]
@ferrygun, we didn't really test the training time on CPU. For me personally the answer is “Too long”.
I think that the model itself will work properly with custom format but the `ner_f1` metric will most certainly break. We will release an update in a few days that will expand the `ner_f1` metric for IOB, BILOU and IOBES formats as well.

**Comment by yoptar** [comment]
@xirect, we license our code and models under the [Apache License 2.0](https://github.com/deepmipt/DeepPavlov/blob/master/LICENSE)

**Comment by yoptar** [comment]
Closing the issue as all the questions have been answered.

**Comment by xirect** [comment]
@yoptar Is there any documentation on how the models were trained on the ontoNotes set?

**Comment by yoptar** [comment]
@xirect, we do have a [documentation for the NER models](http://docs.deeppavlov.ai/en/master/features/models/ner.html) with links on configs that were used for training and can be used for inference. If you want to know more about the exact architecture you'll have to take a look at the [source code](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/bert/bert_sequence_tagger.py#L460-L475)

**Comment by muhammadahmad671** [comment]
/root/.deeppavlov/downloads/bert_models/multi_cased_L-12_H-768_A-12/vocab.txt; No such file or directory
 
 i am getting this error while loading me own trained model
 i have not set download=True as following
 
import json
from deeppavlov import configs, build_model

with configs.ner.ner_ontonotes_bert_mult.open(encoding='utf8') as f:
    ner_config = json.load(f)
ner_config['metadata']['variables']['NER_PATH'] = '/content/ner_ontonotes_bert_mult'
ner_config['metadata']['download'] = [ner_config['metadata']['download'][-1]]  # do not download the pretrained ontonotes model

ner_model = build_model(ner_config)
