### ISSUE TITLE
NER output different results

### ISSUE THREAD

**Issue by IzzyHibbert** [deepmipt/DeepPavlov#1098]
After a successful installation of the Docker container with ner_ontonotes,
I tried to run the example of the docs area :

"_Elon Musk launched his cherry Tesla roadster to the Mars orbit_"

with the response body  :
`
[
  [
    [
      "Elon",
      "Musk",
      "launched",
      "his",
      "cherry",
      "Tesla",
      "roadster",
      "to",
      "the",
      "Mars",
      "orbit"
    ],
    [
      "B-ORG",
      "I-ORG",
      "O",
      "O",
      "O",
      "B-PRODUCT",
      "O",
      "O",
      "O",
      "B-LOC",
      "O"
    ]
  ]
]
`
While if I process the same sentence in the online demo [https://demo.deeppavlov.ai/#/en/ner](url) I see it coming with the correct result, Elon Musk correctly detected as **PERSON** and not **ORG**.

Any idea why this bad result here compare to the correct one on the demo ?

**Comment by yoptar** [comment]
Hi @IzzyHibbert,
In the demo we use the [`ner_ontonotes_bert_mult`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json) model, it's the one that gives [the best score](http://docs.deeppavlov.ai/en/master/features/models/ner.html) on the OntoNotes dataset.

**Comment by IzzyHibbert** [comment]
> 
> 
> Hi @IzzyHibbert,
> In the demo we use the [`ner_ontonotes_bert_mult`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes_bert_mult.json) model, it's the one that gives [the best score](http://docs.deeppavlov.ai/en/master/features/models/ner.html) on the OntoNotes dataset.

I suspected it. 
Thanks a lot and keep up the extremely good work.
