### ISSUE TITLE
Issue with Docker container CPU version

### ISSUE THREAD

**Issue by IzzyHibbert** [deepmipt/DeepPavlov#1099]
Hi guys.

I created a ticket #1098 for which I was suggested to use the **ner_ontonotes_bert_mult** model (while my container had a ner_ontonotes).

After the suggestion I removed the container and went to a new fresh installation.
Same Win 10 machine with Docker Desktop (2.1.0.5). This time I just have used the suggested model, so the input was :

`docker run -e CONFIG=ner_ontonotes_bert_mult -p 5555:5000 -v ~/my_deeppavlov_components:/root/.deeppavlov -v ~/my_deeppavlov_envs:/venv deeppavlov/base-cpu`
 
This time I noticed that the installation process did not end with something like :
```
2019-12-12 15:43:42 Started server process [63]
2019-12-12 15:43:42 Waiting for application startup.
```
But anyway I gave a try.
And immediately founded our that the URL `http://127.0.0.1:5555` was KO, rather sistematically returning an error 
`No connection could be made because the target machine actively refused it 127.0.0.1:5555`
Never ever worked in my configuration. Despite the various attepts to re-install everything (Docker included). Also I installed NGINX and made sure it worked. Yest it did worked. So no issues with IP, ports, and similar.
What I also made was doing a new installation of this deeppavlov container in port 32768, which was the port where NGINX was running a second before. No way. Did not work wven like that. Same error message.

I also noticed that the container was in status `Exited (137)` pretty much every time. I made an increase in the RAM assigned and was not solving this.

After loosing all the hope, I made a choice and tried to move back to the same container that worked, which I created with 
`docker run -e CONFIG=ner_ontonotes -p 5555:5000 -v ~/my_deeppavlov_components:/root/.deeppavlov -v ~/my_deeppavlov_envs:/venv deeppavlov/base-cpu`
and voilà, this one confirmed to work properly..

The bottomline, is that the same attempt with just the installation of a container with a different model **ner_ontonotes_bert_mult** (the suggested one) did not work.

How do you see it ? After all the attempts type I made, I can tell that seems something related to the `CONFIG=ner_ontonotes_bert_mult` instead of `CONFIG=ner_ontonotes` in my container. Which does not make sense at all to me.

Any idea ? Any hint is highly appreciated.
Any other live installation of that container with `CONFIG=ner_ontonotes_bert_mult`  that works ?

Thanks

**Comment by litinsky** [comment]
Hi, IzzyHibbert! Is seems, that you you used same virtualenv volume mapping `-v ~/my_deeppavlov_envs:/venv deeppavlov/base-cpu` both `ner_ontonotes` and `ner_ontonotes_bert_mult`. Try using another virtualenv for `ner_ontonotes_bert_mult`.

**Comment by IzzyHibbert** [comment]
Hi litinsky,
Thanks for your answer.
Actually the two containers never existed simultaneously on the machine.

As soon as I received the help telling me to move to `ner_ontonotes_bert_mult` I deleted the previous container that used `ner_ontonotes` with command `docker container rm` and manually cleaned (removed) all the content of both
`~/my_deeppavlov_components`
and
`~/my_deeppavlov_envs`

So if you suspected that the conatiner with `ner_ontonotes_bert_mult` was in conflict with the previous one, I believe that with my manual moves I made sure all was well cleaned, while only one container was installed.

Correct me if I am wrong.

**Comment by IzzyHibbert** [comment]
Hi guys.

I am bringing back the issue as after several attempts I suspect the issue is somehow originated with the model, as `ner_ontonotes_bert_mult` is the only one difference when trying to create this container.
Also @litinsky I followed your hint and anyway tried to create this one in a different virtualenv. Even with that, no success.

I believe the issue could impact multiple users to come.
All the details of the last installation steps  were saved and shared here :
[https://pastebin.com/FSdJkrXP](url)

**Comment by IgnatovFedor** [comment]
Hi @IzzyHibbert 
Could you tell the amount of free RAM on your PC before running the containers? `ner_ontonotes_bert_mult` is bigger than `ner_ontonotes` and container could be killed due to the lack of free RAM.
Also, could you try to run container with `ner_ontonotes_bert_mult` without volume mapping, i.e.
`docker run -e CONFIG=ner_ontonotes_bert_mult -p 5555:5000 -v ~/my_deeppavlov_components:/root/.deeppavlov deeppavlov/base-cpu`?

**Comment by IzzyHibbert** [comment]
Hi @IgnatovFedor thanks for the hint.
Yours was a good point.

In all the process of creating the container (with `ner_ontonotes_bert_mult`) my system had an average of > **6Gb free RAM**.
(my Docker engine is set at 4096)
In this last attempt I made, I turned off any process not requested, making sure the RAM was enough: still KO.

Copy of the result is here: [https://pastebin.com/dth1XJg8](url)

that said, I even tried not to map the volume, as suggested. still the same issue.
Also, the container status is always immediately an : 
`Exited (137)`

**Comment by IgnatovFedor** [comment]
@IzzyHibbert 
I built an image with installed all necessary requirements installed and downloaded necessary files for `ner_ontonotes_bert_mult`. Please download archived image from [here](files.deeppavlov.ai/containers/ner_ontonotes_bert_mult.tar), unpack it with `docker load -i <path to image tar file>` and run `ner_ontonotes_bert_mult` model with `docker run -p 5555:5000 deeppavlov/ner_ontonotes_bert_mult:0.7.1` and write whether it worked.

**Comment by IzzyHibbert** [comment]
@IgnatovFedor Thanks ! Unfortunately the provided link is a 404 not found :-(

**Comment by IgnatovFedor** [comment]
@IgnatovFedor Sorry, use this link `http://files.deeppavlov.ai/containers/ner_ontonotes_bert_mult.tar`.

**Comment by IzzyHibbert** [comment]
Hi @IgnatovFedor 
First thanks for all the support and dedicated time. Highly appreciated. I hope this issue can come to an end as I expect other people trying to use it on a win docker machine.

I followed the steps with the image you shared and it ends with the same bad result I experienced when creating my own one.

This means that instead of the final message `Started server process [63]` which I see when using the `ner_ontonotes` the process with `ner_ontonotes_bert_mult` ends with 

```
2019-12-23 16:13:40.451220: W tensorflow/core/framework/allocator.cc:107] Allocation of 367248384 exceeds 10% of system memory.
2019-12-23 16:13:43.011689: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Killed
```
which means it doesn't end correctly.


Some info : 
- Even in this last attempts of installing the given image I had an average of 6 Gb RAM available in the laptop ;
- There are _no error messages visible_ in all the steps. I made a double check also in the pastebin I shared ;
- I am suspecting that as the image you shared was working on your machine, it must be something with resources/settings I have configured.
- I had two cpu for Docker, have added 2 more for a total of 4 now.

What amount of free RAM do you have ?

**Comment by IzzyHibbert** [comment]
Hi @IgnatovFedor 
I have good news. You pointed me to the right direction. I hope this can help others in the future ..

The issue is related to the RAM that is used by the Docker engine.
For `ner_ontonotes` I made it with **2 Gb ram**, but `ner_ontonotes_bert_mult` requires **6 Gb Ram** in the Docker engine in order to make it.

I close the ticket.
Again thanks a lot for the support.

**Comment by IgnatovFedor** [comment]
@IzzyHibbert, you welcome. Thank you very much for describing the solution, I'm sure it will help others.
