### ISSUE TITLE
multi_squad_noans_infer: output empty answer for no-answer text

### ISSUE THREAD

**Issue by luke4u** [deepmipt/DeepPavlov#1104]
Hi Guys,

For config (multi_squad_noans_infer), I wonder how the model determines if there is no answer in a text? and if we can reset the probability (if there is such a parameter)? Can anyone explain how squad_noans works?

In the model file, [here ](https://github.com/deepmipt/DeepPavlov/blob/a95149294bc7fa30baaa15c629adad4c1cba264e/deeppavlov/models/squad/squad.py#L306): but not sure how it work.

As pointed out here (https://github.com/HKUST-KnowComp/R-Net/issues/48), 

> R-net uses boundary model presented in "Machine Comprehension Using Match-LSTM and Answer Pointer". It will give an answer whether the true answer exists or not.

  So back to the question ...

Thanks so much. 
Luke

**Comment by yurakuratov** [comment]
Hi!

R-Net model finds an answer by predicting `answer_start` and `answer_end` positions with Pointer Networks. We add special `no_answer` token to the beginning of a text (actually, we add this token only before Pointer Network layer) and model should predict this token if question doesn't have an answer in a given text. 
SQuAD v1.1 does not have training examples without an answer, so we added such examples to the training set. Some details on how we build training set with examples without an answer are given here: http://docs.deeppavlov.ai/en/master/features/models/squad.html#squad-with-contexts-without-correct-answers

**Comment by luke4u** [comment]
Hi @yoptar , thanks and good to know this, though I think this didn't get to the point on 
> how the model determines if there is no answer in a text?

probably it is about Pointer network. Can you share insights on it or point me to the line of the code on how no answer is determined?

**Comment by yurakuratov** [comment]
Maybe I was not so clear on answering this:
> how the model determines if there is no answer in a text?

Pointer Network is an output layer of R-Net, the task of Pointer Network is to find two positions in text: `answer_start` and `answer_end`. `no_answer` is used as usual token and is appended to every text here: https://github.com/deepmipt/DeepPavlov/blob/a95149294bc7fa30baaa15c629adad4c1cba264e/deeppavlov/models/squad/squad.py#L191-L196

Probability of an answer is computed as 1 - P(no_answer is start token) * P(no_answer is end token), `no_answer` token index is 0:
https://github.com/deepmipt/DeepPavlov/blob/a95149294bc7fa30baaa15c629adad4c1cba264e/deeppavlov/models/squad/squad.py#L209-L210
Similar way of doing this is described in this paper (Section 3.3): https://arxiv.org/abs/1710.10723
