### ISSUE TITLE
method download_decompress downloads non-existing files

### ISSUE THREAD

**Issue by acriptis** [deepmipt/DeepPavlov#1109]
I've used method download_decompress to load the file from remote storage. It seems that if I provide [broken URL](http://files.deeppavlov.ai/spelling_crrectors/elmo_weights_ckpt3.tar.gz) the method downloads content without check of file validity and tries to unpack it (although it is not archieve) and silently continues on fail. 

I think expected behavior is to raise exception for missed file on broken URL and wrong archive formats.

**Comment by yoptar** [comment]
We need to check a status code in `simple_download()`. It's weird that we do not do that already.
