### ISSUE TITLE
При определении настроения текста выдает много классов и медленно работает

### ISSUE THREAD

**Issue by marsel171** [deepmipt/DeepPavlov#1110]
model = build_model(configs.classifiers.rusentiment_convers_bert, download=True,load_trained=True)

text = "Назван лучший российский сервелат"

model(text)

получаю следующее:

['neutral',
 'neutral',
 'skip',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'skip',
 'neutral',
 'skip',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'skip',
 'neutral',
 'neutral',
 'neutral',
 'skip',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'skip']

**Comment by yoptar** [comment]
Попробуйте запустить `model([text])`.
Модель работает с батчами и восприняла строку как список символов.

**Comment by marsel171** [comment]
сработало! благодарю!

**Comment by ice1x** [comment]
сервелат - сила
