### ISSUE TITLE
No requirements found in config

### ISSUE THREAD

**Issue by Elfreezy** [deepmipt/DeepPavlov#1114]
Попытался скачать faq/tfidf_autofaq, выдает ошибку вида:
WARNING in 'deeppavlov.utils.pip_wrapper.pip_wrapper'['pip_wrapper'] at line 46: No requirements found in config

Посмотрел файл pip_wrapper обнаружил обращение вида:
requirements_files = config.get('metadata', {}).get('requirements', [])
Если metadata я в конфиге вижу, то о requirements слышу впервые.

Установленные модули:
1. deeppavlov
2. tensorflow-gpu==1.14.0
3. email-validator

В остальных конфигах данные параметр присутствует, однако в tfidf_logreg_autofaq, tfidf_autofaq
его нет

**Comment by yoptar** [comment]
Это параметр нужен, если у конфига есть дополнительные зависимости, не учтённых в зависимостях самого пакета `deeppavlov`. У этих конфигов таких зависимостей нет.
Это `Warning`, а не ошибка, падать ничего не должно.

**Comment by Elfreezy** [comment]
После этого предупреждения, в командной строке ничего не происходит, как при установке других когфигов, а при попытке построить модель ( или в той же командной строке команда interact ) c download=True происходит:
"raise RuntimeError(f'It looks like the server does not support resuming '
RuntimeError: It looks like the server does not support resuming downloads."

Это никак не связано?  Спасибо за ответ
![изображение](https://user-images.githubusercontent.com/56732709/72210685-41ccbc80-34d0-11ea-95ab-1c1b1238ffd1.png)

**Comment by yoptar** [comment]
А, `install` ничего и не должен делать для этого конфига, потому что дополнительных зависимостей нет.
А вот ошибка загрузки — это что-то странное. Можно увидеть лог с этой ошибкой целиком?

**Comment by Elfreezy** [comment]
![изображение](https://user-images.githubusercontent.com/56732709/72255883-ed812400-3618-11ea-9d5b-2441ac6de78a.png)
[](url)
[requirements.txt](https://github.com/deepmipt/DeepPavlov/files/4053477/requirements.txt)

**Comment by yoptar** [comment]
Это что-то странное. Файл скачался целиком, но временный файл докачки не был переименован в конечное имя. Теперь вместо последних 0 байт сервер отдаёт какие-то 190, из-за этого всё падает.
Можно переименовать `C:\Users\blood\.deeppavlov\models\vectorizer\tfidf_vectorizer_ruwiki.pkl.part` в `C:\Users\blood\.deeppavlov\models\vectorizer\tfidf_vectorizer_ruwiki.pkl`, тогда ошибка должна уйти. Или просто удалить `C:\Users\blood\.deeppavlov\models\vectorizer\tfidf_vectorizer_ruwiki.pkl.part`, чтобы он скачался заново.

**Comment by Elfreezy** [comment]
У меня нет там этого файла)
![изображение](https://user-images.githubusercontent.com/56732709/72260644-5d48dc00-3624-11ea-95ad-ddfdcd09478f.png)

**Comment by yoptar** [comment]
Путь не тот.

**Comment by Elfreezy** [comment]
![изображение](https://user-images.githubusercontent.com/56732709/72261433-db59b280-3625-11ea-8587-54e49115e60e.png)
К сожалению, при команде interact с параметром -d опять ничего не выходит, хотя на этот раз файл скачан нужный

**Comment by yoptar** [comment]
Та же проблема с файлом `C:\Users\blood\.deeppavlov\models\faq\tfidf_cos_sim_classifier.pkl.part`

**Comment by Elfreezy** [comment]
Спасибо большое, удалил в папке faq и vectorizer все файлы, после чего все хорошо установилось.
