### ISSUE TITLE
Question Answering on local machine only possible with tensorflow GPU (geforce graphics card)?

### ISSUE THREAD

**Issue by JonasNothnagel** [deepmipt/DeepPavlov#1116]
Is there a way to locally run the QA model on my local machine without installing tensorflow-gpu? I do not have a geforce graphics card and thus it seems impossible for me to use tensorflow with GPU support.

**Comment by yurakuratov** [comment]
Hi!

Yes you can! Just install cpu-only version of tensorflow: `pip install tensorflow==1.14.0`
