### ISSUE TITLE
What are the steps for creating another language support (eg: Korean)?

### ISSUE THREAD

**Issue by Eugen2525** [deepmipt/DeepPavlov#1117]
Hi, 

I am considering creating language support for the Korean language, and I am interested in what are the requirements, steps I need to take?

Could you please elaborate on the steps and also on the feasibility of doing so?

Thanks!

**Comment by yoptar** [comment]
Hi @Eugen2525,
There are at least two problems when creating solutions for established tasks on new languages: **datasets** and **tokenization**.
What tasks are you interested in?
We do have two multi-language models you can take a look at: https://demo.deeppavlov.ai/#/mu/textqa

**Comment by Eugen2525** [comment]
Dear @yoptar 
Thanks for a prompt reply, I wanted to create chat bot just like the default one provided which runs on the Cambridge restaurant dataset.

So, I am interested what steps should I take to make a chatbot for Korean? I know for sure I need a dataset like the Cambridge restaurant dataset for the training of the bot, but what are some other things needed to be done?

Could you please elaborate...

**Comment by yoptar** [comment]
We do have two tutorials for that: [basic](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_tutorial.ipynb) and [extended](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_extended_tutorial.ipynb). Almost everything in those should work for Korean.
But the basic config uses embeddings for English, so you can try and replace that.

**Comment by gasyoun** [comment]
> basic config uses embeddings for English

Non with Russian? What's the quickest way to build a VK and FB bot?

**Comment by Eugen2525** [comment]
I am not sure if you mean if there is a Russian language support (which I saw there is), but for Korean, I just translated datasets and it worked. 

For the quick prototyping you can select any dataset and just try and see with the mentioned approach. This is what I did at least
