### ISSUE TITLE
Changing start_message in sever_config.json does not change message in Telegram bot

### ISSUE THREAD

**Issue by JonasNothnagel** [deepmipt/DeepPavlov#1118]
I built the telegram bot as described in the tutorials. It works fine and gives me context driven inferences to my questions. However, changing the "start_message" and "help_message" entries in the server_config.json file does not change anything in the bot. How can I edit my telegram bot accordingly? Thank you!

**Comment by IgnatovFedor** [comment]
Hi @JonasNothnagel 
I just checked this feature and it worked fine. Could you describe all the steps you've taken? Did you save `server_config.json` and restart DeepPavlov after changing the messages?

**Comment by JonasNothnagel** [comment]
Hi!

I simply run this python script on an anaconda virtual environment in which I installed `deeppavlov` and the required packages. 
`
from deeppavlov.utils.telegram import interact_model_by_telegram
from deeppavlov import configs

interact_model_by_telegram(configs.squad.squad, token='xxxxxxxxx_my_token_xxxxxxxxx' )
`
I saved the changed `sever_config.json` and restarted my whole python environment. It seems like the function does not make use of my locally stored files. Even if I delete the whole `server_config.json` file it runs with the default messages on telegram. 

Just as an additional information, I had permission errors when installing `deeppavlov` and used the --user tag.

**Comment by IgnatovFedor** [comment]
@JonasNothnagel 
Please, check full path to settings directory. You can do this by running `python -m deeppavlov.settings` (see [docs](http://docs.deeppavlov.ai/en/master/integrations/settings.html#settings-files-access-and-management) for more details). Do changes in `server_config.json` from this directory affect bot?
