### ISSUE TITLE
FileNotFoundError - No such file or directory: 'deeppavlov/configs/ner/ner_ontonotes.json'

### ISSUE THREAD

**Issue by pearly-ang** [deepmipt/DeepPavlov#1120]
<img width="1016" alt="Screen Shot 2020-01-22 at 5 14 26 PM" src="https://user-images.githubusercontent.com/43221298/72880899-bad2dc00-3d3a-11ea-80ee-6d4be0369368.png">

I am unable to load the pre-trained model on Onto Notes 5. Would appreciate any good suggestions. Thanks!

**Comment by yoptar** [comment]
Hi @pearly-ang,
You can build the pretrained OntoNotes model like so:
```python3
from deeppavlov import build_model, configs

ner_model = build_model(configs.ner.ner_ontonotes, download=True)
ner_model(['Computer Sciences Corp . , El Segundo , Calif . , said it is close to making final an agreement to buy Cleveland Consulting Associates'])
```

Here `configs.ner.ner_ontonotes` contains the configuration path.
There is also a couple of better models based on BERT: `ner_ontonotes_bert` and `ner_ontonotes_bert_mult`, you can find out more about them in our [documentation](http://docs.deeppavlov.ai/en/master/features/models/ner.html).

**Comment by pearly-ang** [comment]
Thanks so much for your help @yoptar! I tried what you suggested, but it's been returning an Attribute Error with tensorflow despite my trying the stable version and the updated tf 2.0 versions on my virtual machine. Would you have any experience with this?

![Screenshot_2020-02-12 spaCy - Jupyter Notebook](https://user-images.githubusercontent.com/43221298/74351972-cd4cac80-4df2-11ea-8bd3-b74894108751.png)
![Screenshot_2020-02-12 spaCy - Jupyter Notebook(1)](https://user-images.githubusercontent.com/43221298/74351981-d178ca00-4df2-11ea-9abe-df0a318a6cb9.png)

**Comment by yoptar** [comment]
Sorry but our models do not support tf-2 at this moment.
You can run
```bash
python -m deeppavlov install ner_ontonotes
```
from your environment to install everything required to run the `ner_ontonotes` config.

**Comment by pearly-ang** [comment]
Understood, thanks for your help @yoptar!
