### ISSUE TITLE
building go-bot in russian

### ISSUE THREAD

**Issue by Grossmend** [deepmipt/DeepPavlov#1122]
Good day!

I want to build a go-bot using DeepPavlov in russian language (on example of this [notebook](https://colab.research.google.com/github/deepmipt/DeepPavlov/blob/master/examples/gobot_extended_tutorial.ipynb)).
I created dataset by DSTC2 format. Now i want add NER training in go bot config pipline. Because my dataset includes **_names_** and **_phones_**. All possible variants i **can't** include in slot_vals.json

It is possible to implement on DeepPavlov?

**Comment by oserikov** [comment]
Hey! What exactly is the purpose of the NER in the pipeline? It seems like one could just pipe the input text through the NER before the model to feed the GO-bot with marked up text.
