### ISSUE TITLE
Can't figure out how to use this for general chatbot

### ISSUE THREAD

**Issue by memologyserver** [deepmipt/DeepPavlov#1125]
Hi, I am interested in developing a general purpose chatbot that you can do two things. Have normal conversations with and ask for specific things like cheapest resturant. Having looked at this i'm struggling to work out how i can use this for this purpose

Any help would be appreciated

**Comment by oserikov** [comment]
Hey! I think that the most straightforward solution (sort of baseline) is to run chitchat and GO-bot in parallel choosing between their responses on-the-run.
