### ISSUE TITLE
No way to read 'test.csv' without labels

### ISSUE THREAD

**Issue by DrMatters** [deepmipt/DeepPavlov#1126]
Hello!
I'm trying to read train.csv and test.csv files with this call:
`
dataset = BasicClassificationDatasetReader()
`
`
dataset.read('/data/', train='train.csv', test='test.csv', x='text', y='target')
`
That finishes with an error, because 'test.csv' has no 'target'. How to read dataset without labels to make a predictions on it?

**Comment by yoptar** [comment]
Hi @DrMatters,
DatasetReaders are created for models training and evaluation.
To make predictions you can read your data in a python list \(or two lists if the model expects two arguments\) and just pass it to the model:
```
from deeppavlov import build_model, configs

model = build_model(configs.classifiers.intents_snips, download=True)
data = [
    'Show me the forecast for my upcoming weekend',
    'Find me the I, Robot television show',
    'Can I get some Russian cuisine at a restaurant with Shari and I?'
]

predictions = model.batched_call(data, batch_size=32)
```

**Comment by DrMatters** [comment]
Seems fine
