### ISSUE TITLE
Confidence and start/stop index in NER

### ISSUE THREAD

**Issue by Grossmend** [deepmipt/DeepPavlov#1127]
Good day!

It is possible return from NER model **confidence** and (or) **start/stop** position entities?
By default model return `["x_tokens", "y_pred"]`

**Comment by yoptar** [comment]
Hi @Grossmend,
1. It is possible to return probabilities for NER models based on BERT: you can set the `return_probas` option to `true` in the configuration, remove the last `tag_vocab` component from the pipeline and rename `y_pred_ind` to `y_pred` in `bert_sequence_tagger`’s `out` field.
2. There is no way at this moment to return `start/stop` positions as the model works with tokenized text. You can however tokenize your inputs beforehand remembering start and stop positions for every token and then match those with the model outputs.

**Comment by Grossmend** [comment]
Thanks!
