### ISSUE TITLE
Link for Russian FAQ dataset is broken

### ISSUE THREAD

**Issue by bespaloff** [deepmipt/DeepPavlov#1128]
Link for the dataset in documentation to train FAQ bot in Russian is broken:
Origin in docs: https://github.com/deepmipt/DeepPavlov/blob/master/docs/features/skills/faq.rst
Broken Link: http://www.ftl.name/page/989

As well as following links for files: 
http://files.deeppavlov.ai/faq/school/faq_tfidf_cos_model.pkl

**Comment by yoptar** [comment]
Hi @bespaloff,
Thank you for finding this.
I've created a pull request with a fix, it will be merged before the next release.

**Comment by gasyoun** [comment]
Seems there are a lot of broken links. I would recommend to use http://home.snafu.de/tilman/xenulink.html
