### ISSUE TITLE
What are supported list of languages in Multi-lang model

### ISSUE THREAD

**Issue by helloworldkr** [deepmipt/DeepPavlov#1129]
Hi guys,
I could not find anywhere the list of languages that are supported by your Multi-lang QnA model.

**Comment by yoptar** [comment]
Hi @helloworldkr,
It is based on the multilingual BERT model so theoretically the languages list is [the same](https://github.com/google-research/bert/blob/master/multilingual.md#list-of-languages).

**Comment by helloworldkr** [comment]
@yoptar  thanks
