### ISSUE TITLE
Utility to convert BILOU NER Output

### ISSUE THREAD

**Issue by srijiths** [deepmipt/DeepPavlov#1132]
Hi All, 

Is there any utility available to convert NER BILOU output to proper entities? 
Thanks, 
Srijith

**Comment by yoptar** [comment]
Hi @srijiths,

We don't have one but I feel like it's simple enough to write.
You can just replace `'U-'` with '`B-'` and `'L-'` with `'I-'` for every tag.

**Comment by srijiths** [comment]
I have created a utility. Thank You
