### ISSUE TITLE
Unable to load pre-trained model

### ISSUE THREAD

**Issue by MaheshChandrra** [deepmipt/DeepPavlov#1133]
Hi 

I'm trying to use a pre-trained model for NER,and once the model got downloaded,
I'm getting the below issue.

```
from deeppavlov import configs, build_model

ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)

2020-02-18 17:45:34.88 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.preprocessors.bert_preprocessor.BertNerPreprocessor'>
Traceback (most recent call last):
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 119, in __init__
    do_lower_case=do_lower_case)
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py", line 165, in __init__
    self.vocab = load_vocab(vocab_file)
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py", line 127, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 178, in readline
    self._preread_check()
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\mchandra\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the file specified.
; No such file or directory
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-5-f2cfbde6d24a> in <module>
      1 from deeppavlov import configs, build_model
      2 
----> 3 ner_model = build_model(configs.ner.ner_ontonotes_bert, download=False)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\commands\infer.py in build_model(config, mode, load_trained, download, serialized)
     59             component_serialized = None
     60 
---> 61         component = from_params(component_config, mode=mode, serialized=component_serialized)
     62 
     63         if 'id' in component_config:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\params.py in from_params(params, mode, serialized, **kwargs)
    104                 kwargs['mode'] = mode
    105 
--> 106             component = obj(**dict(config_params, **kwargs))
    107             try:
    108                 _refs[config_params['id']] = component

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py in __init__(self, vocab_file, do_lower_case, max_seq_length, max_subword_length, token_masking_prob, provide_subword_tags, subword_mask_mode, **kwargs)
    117         vocab_file = str(expand_path(vocab_file))
    118         self.tokenizer = FullTokenizer(vocab_file=vocab_file,
--> 119                                        do_lower_case=do_lower_case)
    120         self.token_masking_prob = token_masking_prob
    121 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py in __init__(self, vocab_file, do_lower_case)
    163 
    164   def __init__(self, vocab_file, do_lower_case=True):
--> 165     self.vocab = load_vocab(vocab_file)
    166     self.inv_vocab = {v: k for k, v in self.vocab.items()}
    167     self.basic_tokenizer = BasicTokenizer(do_lower_case=do_lower_case)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py in load_vocab(vocab_file)
    125   with tf.gfile.GFile(vocab_file, "r") as reader:
    126     while True:
--> 127       token = convert_to_unicode(reader.readline())
    128       if not token:
    129         break

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py in readline(self)
    176   def readline(self):
    177     r"""Reads the next line from the file. Leaves the '\n' at the end."""
--> 178     self._preread_check()
    179     return self._prepare_value(self._read_buf.ReadLineAsString())
    180 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     82                                            "File isn't open for reading")
     83       self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
---> 84           compat.as_bytes(self.__name), 1024 * 512)
     85 
     86   def _prewrite_check(self):

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\mchandra\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the file specified.
; No such file or directory
```

Can you please let me the way of fixing this, I used **ner_ontonotes** as well but its working fine,have the problem with bert models.

Thanks in advance.

**Comment by yoptar** [comment]
Hi @MaheshChandrra,

This error says that the `C:\Users\mchandra\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt` file is not found.
Are you sure that everything was downloaded? There is no info on that in shown logs.

**Comment by MaheshChandrra** [comment]
Hi @yoptar , Thanks for the quick response,sorry log got swapped:

Below is the log once I downloaded the ner_ontonotes_bert module:
`
from deeppavlov import configs, build_model

ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)


2020-02-18 19:09:08.808 INFO in 'deeppavlov.download'['download'] at line 117: Skipped http://files.deeppavlov.ai/deeppavlov_data/ner_ontonotes_bert_v1.tar.gz download because of matching hashes
---------------------------------------------------------------------------
ConnectionResetError                      Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    671                 headers=headers,
--> 672                 chunked=chunked,
    673             )

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    420                     # Otherwise it looks like a bug in the code.
--> 421                     six.raise_from(e, None)
    422         except (SocketTimeout, BaseSSLError, SocketError) as e:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\packages\six.py in raise_from(value, from_value)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    415                 try:
--> 416                     httplib_response = conn.getresponse()
    417                 except BaseException as e:

~\AppData\Local\Continuum\anaconda3\lib\http\client.py in getresponse(self)
   1335             try:
-> 1336                 response.begin()
   1337             except ConnectionError:

~\AppData\Local\Continuum\anaconda3\lib\http\client.py in begin(self)
    305         while True:
--> 306             version, status, reason = self._read_status()
    307             if status != CONTINUE:

~\AppData\Local\Continuum\anaconda3\lib\http\client.py in _read_status(self)
    266     def _read_status(self):
--> 267         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    268         if len(line) > _MAXLINE:

~\AppData\Local\Continuum\anaconda3\lib\socket.py in readinto(self, b)
    588             try:
--> 589                 return self._sock.recv_into(b)
    590             except timeout:

ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    719             retries = retries.increment(
--> 720                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    721             )

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    399             if read is False or not self._is_method_retryable(method):
--> 400                 raise six.reraise(type(error), error, _stacktrace)
    401             elif read is not None:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\packages\six.py in reraise(tp, value, tb)
    733             if value.__traceback__ is not tb:
--> 734                 raise value.with_traceback(tb)
    735             raise value

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    671                 headers=headers,
--> 672                 chunked=chunked,
    673             )

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    420                     # Otherwise it looks like a bug in the code.
--> 421                     six.raise_from(e, None)
    422         except (SocketTimeout, BaseSSLError, SocketError) as e:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\packages\six.py in raise_from(value, from_value)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    415                 try:
--> 416                     httplib_response = conn.getresponse()
    417                 except BaseException as e:

~\AppData\Local\Continuum\anaconda3\lib\http\client.py in getresponse(self)
   1335             try:
-> 1336                 response.begin()
   1337             except ConnectionError:

~\AppData\Local\Continuum\anaconda3\lib\http\client.py in begin(self)
    305         while True:
--> 306             version, status, reason = self._read_status()
    307             if status != CONTINUE:

~\AppData\Local\Continuum\anaconda3\lib\http\client.py in _read_status(self)
    266     def _read_status(self):
--> 267         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    268         if len(line) > _MAXLINE:

~\AppData\Local\Continuum\anaconda3\lib\socket.py in readinto(self, b)
    588             try:
--> 589                 return self._sock.recv_into(b)
    590             except timeout:

ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-6-978aa0321948> in <module>
      1 from deeppavlov import configs, build_model
      2 
----> 3 ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\commands\infer.py in build_model(config, mode, load_trained, download, serialized)
     38 
     39     if download:
---> 40         deep_download(config)
     41 
     42     import_packages(config.get('metadata', {}).get('imports', []))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\download.py in deep_download(config)
    145         if not isinstance(config, dict):
    146             url = set_query_parameter(url, 'config', Path(config).stem)
--> 147         download_resource(url, dest_paths)
    148 
    149 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\download.py in download_resource(url, dest_paths)
    118     elif any(ext in url for ext in ('.tar.gz', '.gz', '.zip')):
    119         download_path = dest_paths[0].parent
--> 120         download_decompress(url, download_path, dest_paths)
    121     else:
    122         file_name = url.split('/')[-1].split('?')[0]

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\data\utils.py in download_decompress(url, download_path, extract_paths)
    231     else:
    232         arch_file_path = download_path / file_name
--> 233         simple_download(url, arch_file_path)
    234         extracted_path = extract_paths.pop()
    235 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\data\utils.py in simple_download(url, destination)
     75 
     76     headers = {'dp-token': _get_download_token()}
---> 77     r = requests.get(url, stream=True, headers=headers)
     78     total_length = int(r.headers.get('content-length', 0))
     79 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py in get(url, params, **kwargs)
     73 
     74     kwargs.setdefault('allow_redirects', True)
---> 75     return request('get', url, params=params, **kwargs)
     76 
     77 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py in request(method, url, **kwargs)
     58     # cases, and look like a memory leak in others.
     59     with sessions.Session() as session:
---> 60         return session.request(method=method, url=url, **kwargs)
     61 
     62 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 
    535         return resp

~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 
    648         # Total elapsed time of the request (approximately)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    496 
    497         except (ProtocolError, socket.error) as err:
--> 498             raise ConnectionError(err, request=request)
    499 
    500         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**and below is the log when I've kept download=False as the module is already downloaded:**

`
from deeppavlov import configs, build_model

ner_model = build_model(configs.ner.ner_ontonotes_bert, download=False)


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mchandra\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mchandra\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\mchandra\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\mchandra\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
WARNING:tensorflow:From C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2020-02-18 19:08:51.41 ERROR in 'deeppavlov.core.common.params'['params'] at line 112: Exception in <class 'deeppavlov.models.preprocessors.bert_preprocessor.BertNerPreprocessor'>
Traceback (most recent call last):
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\params.py", line 106, in from_params
    component = obj(**dict(config_params, **kwargs))
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py", line 119, in __init__
    do_lower_case=do_lower_case)
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py", line 165, in __init__
    self.vocab = load_vocab(vocab_file)
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py", line 127, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 178, in readline
    self._preread_check()
  File "C:\Users\mchandra\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\mchandra\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the file specified.
; No such file or directory
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-5-f2cfbde6d24a> in <module>
      1 from deeppavlov import configs, build_model
      2 
----> 3 ner_model = build_model(configs.ner.ner_ontonotes_bert, download=False)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\commands\infer.py in build_model(config, mode, load_trained, download, serialized)
     59             component_serialized = None
     60 
---> 61         component = from_params(component_config, mode=mode, serialized=component_serialized)
     62 
     63         if 'id' in component_config:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\core\common\params.py in from_params(params, mode, serialized, **kwargs)
    104                 kwargs['mode'] = mode
    105 
--> 106             component = obj(**dict(config_params, **kwargs))
    107             try:
    108                 _refs[config_params['id']] = component

~\AppData\Local\Continuum\anaconda3\lib\site-packages\deeppavlov\models\preprocessors\bert_preprocessor.py in __init__(self, vocab_file, do_lower_case, max_seq_length, max_subword_length, token_masking_prob, provide_subword_tags, subword_mask_mode, **kwargs)
    117         vocab_file = str(expand_path(vocab_file))
    118         self.tokenizer = FullTokenizer(vocab_file=vocab_file,
--> 119                                        do_lower_case=do_lower_case)
    120         self.token_masking_prob = token_masking_prob
    121 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py in __init__(self, vocab_file, do_lower_case)
    163 
    164   def __init__(self, vocab_file, do_lower_case=True):
--> 165     self.vocab = load_vocab(vocab_file)
    166     self.inv_vocab = {v: k for k, v in self.vocab.items()}
    167     self.basic_tokenizer = BasicTokenizer(do_lower_case=do_lower_case)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\bert_dp\tokenization.py in load_vocab(vocab_file)
    125   with tf.gfile.GFile(vocab_file, "r") as reader:
    126     while True:
--> 127       token = convert_to_unicode(reader.readline())
    128       if not token:
    129         break

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py in readline(self)
    176   def readline(self):
    177     r"""Reads the next line from the file. Leaves the '\n' at the end."""
--> 178     self._preread_check()
    179     return self._prepare_value(self._read_buf.ReadLineAsString())
    180 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py in _preread_check(self)
     82                                            "File isn't open for reading")
     83       self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
---> 84           compat.as_bytes(self.__name), 1024 * 512)
     85 
     86   def _prewrite_check(self):

NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\mchandra\.deeppavlov\downloads\bert_models\cased_L-12_H-768_A-12\vocab.txt : The system cannot find the file specified.
; No such file or directory


``

Please do the needful.

**Comment by yoptar** [comment]
Not everything is downloaded. For some reason the `BERT` model is not.
You can try and download it yourself: http://files.deeppavlov.ai/deeppavlov_data/bert/cased_L-12_H-768_A-12.zip
And then extract the directory in `C:\Users\mchandra\.deeppavlov\downloads\bert_models`

**Comment by MaheshChandrra** [comment]
Sure Thanks,it worked!

**Comment by RAVANv2** [comment]
> Not everything is downloaded. For some reason the `BERT` model is not.
> You can try and download it yourself: http://files.deeppavlov.ai/deeppavlov_data/bert/cased_L-12_H-768_A-12.zip
> And then extract the directory in `C:\Users\mchandra\.deeppavlov\downloads\bert_models`

**Comment by RAVANv2** [comment]
@yoptar after downloading this file it shows me 
this error:
2020-05-26 20:20:06.220 INFO in 'deeppavlov.download'['download'] at line 116: Skipped http://files.deeppavlov.ai/deeppavlov_data/ner_ontonotes_bert_v1.tar.gz download because of matching hashes
2020-05-26 20:20:07.468 INFO in 'deeppavlov.download'['download'] at line 116: Skipped http://files.deeppavlov.ai/deeppavlov_data/bert/cased_L-12_H-768_A-12.zip download because of matching hashes

**Comment by yoptar** [comment]
Hi @RAVANv2,
This is not an error message. It shows that you already have the required files and that their hashes match those of requested files on the server.
