### ISSUE TITLE
Text QA (Q: Юбилей скоро? A: двадцать девять)

### ISSUE THREAD

**Issue by gasyoun** [deepmipt/DeepPavlov#1136]
На [вопрос](https://demo.deeppavlov.ai/#/mu/textqa) "Юбилей скоро?" заведомо чепуху отвечает.

```
A: двадцать девять

Q: Юбилей скоро?
```

**Comment by gasyoun** [comment]
```
A: юбилей

Q: Где?
```


```
A: ракетный окислитель

Q: Что я сделал?
```

```
A: двадцать девять

Q: Девять чего?
```

Я бы ожидал лет в ответ.

**Comment by gasyoun** [comment]
@yurakuratov понятно ли что мне непонятно? 
Ответы совершенно мимо. И это простейшие вопросы.

**Comment by gasyoun** [comment]
Странно, что нет реакции на замечания со стороны. 
Выглядит весьма подозрительно. Хотя бы - да, знаем.

**Comment by yurakuratov** [comment]
Эта TextQA модель была обучена на датасете SDSJ Task B (SberSQuAD), который и определяет на что способна модель. Качество модели ~85 F-1, что тоже говорит о неидеальной работе.

В датасете вопросы задаются в более полной форме, чем просто `где?`, `девять чего?`.
Чтобы понять на какие вопросы система способна отвечать вы можете посмотреть на обучающие данные: http://files.deeppavlov.ai/datasets/multi_squad_ru_retr_clean.tar.gz
