### ISSUE TITLE
Plans to trained bigger BERT/RoBERTa/T5 models for Russian language?

### ISSUE THREAD

**Issue by avostryakov** [deepmipt/DeepPavlov#1139]
Hello! 

Do you have any plans for training larger transformers models, something from the last architectures (Reformer specifically) or BERT?

Or maybe you have plans in the opposite direction: to train TinyBERT with https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/TinyBERT ?

**Comment by yurakuratov** [comment]
Hi!

I can't say any specific plans on what is going to be released, but we are interested in training larger and more recent architectures for Russian language. I expect that to the end of this year or sooner we will release new models.

We also have ongoing work on models distillation but I can't name any time frames.

**Comment by avostryakov** [comment]
Thanks, Yura!
