### ISSUE TITLE
English NER Demo vs github version 

### ISSUE THREAD

**Issue by farmeh** [deepmipt/DeepPavlov#1140]
Hi,
I tried ner_ontonotes_bert model from http://docs.deeppavlov.ai/en/master/features/models/ner.html.
And followed the instructions.
ner_model([mysentence]) works.

But unfortunately, I am not getting the same tags for the same sentence, as nice as I get from the demo page: https://demo.deeppavlov.ai/#/en/ner
Many tags are missing, or incorrect.

Could someone tell me what the problem is?
Thank you!

**Comment by yoptar** [comment]
Hi @farmeh,
On the demo we actually have the `ner_ontonotes_bert_mult` model as it shows better results for English as well.

**Comment by farmeh** [comment]
Thank you,I tried it and I noticed it gives the same results!
