### ISSUE TITLE
Multiprocessing with DeepPavlov - shared memory

### ISSUE THREAD

**Issue by mpjuhasz** [deepmipt/DeepPavlov#1142]
I’m running the pretrained DeepPavlov NER model in parallel on separate cpus with multiprocessing, and want to avoid each instance loading the whole model into memory. Is there any way to only load the model in once?

**Comment by muzaluisa** [comment]
Hey, interested in the same question! What are the ways for CPU speed-up that we can use.

**Comment by username1618** [comment]
I've got the same question.
