### ISSUE TITLE
Tensorflow warnings

### ISSUE THREAD

**Issue by grayskripko** [deepmipt/DeepPavlov#1143]
Tons of warnings arise of two types:

WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000217AD0119E8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x00000217AD0119E8>>: AssertionError: Bad argument number for Name: 3, expecting 4

and

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])

**Comment by luke4u** [comment]
Got similar issue with the warning. 
Wonder if possible to disable the Tensorflow warning? Tried to reset the log level in `log_config.json`, but did't work out.

**Comment by yoptar** [comment]
Hi,

You can run 
```python3
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
```
in your code to suppress warnings and INFO messages from TensorFlow.

**Comment by grayskripko** [comment]
thanks @yoptar, I found the solution a month ago. The thing is that most of your users won't find this and important messages will be hidden in tons of non-relevant garbage info messages. Why don't create an argument for most important CLI commands (build_model, train_model, ...) log_level and adjust deeppavlov, keras, tf, pytorch, (...) and others

**Comment by grayskripko** [comment]
on the other side, a lot of tf warnings are good to solve on the deeppavlov side

**Comment by IgnatovFedor** [comment]
Tensorflow will be removed from the library in the 1.0.0. Reducing the number of the warning is in progress.
