### ISSUE TITLE
extra space in the ner output

### ISSUE THREAD

**Issue by muzaluisa** [deepmipt/DeepPavlov#1145]
Hi,
While running DEMO NER on the example:
"We have achieved 90 percent of our target of a 2.0 percent reduction in the fuel consumption of our coaches over 18 tons GVW for the period 2005–2020 and 100 percent of the same target for city buses over 18 tons GVW"
I am getting a result with "2 . 0 percent", in other words extra spaces are added that were not there before, can you fix that issue in the implementation or may be there is a way to fix it with the existing methods you provide?

**Comment by yoptar** [comment]
Hi @muzaluisa,

Sorry for getting back to you late.
The model predicts tags for tokens but it does not track tokens positions in the original text.
You can tokenize your texts beforehand, remember tokens positions and pass lists of tokens to the model.

**Comment by muzaluisa** [comment]
Hey, thank you for the answer, I ended up reconstruction using regular expressions :)

```
                try:
                    pattern = ' ?'.join(list(phrase.replace(' ', ''))) # get the list of characters without spaces, allow one space between each character
                    pattern = re.escape(pattern)
                    res = re.findall(pattern, sentence)
                except Exception as e:
                    print('ERROR:', e, 'Pattern:', pattern, sentence, ':', sentence)
                    continue
```

**Comment by innovative-roh** [comment]
@yoptar 
I used the Full tokenizer for bert with vocab file  cased_L-12_H-768_A-12/Vocab.txt but the NER output tokens and the tokens obtained  are a bit different.
