### ISSUE TITLE
bert_as_summarizer:  _get_nsp_predictions score is non-informative 

### ISSUE THREAD

**Issue by vcjob** [deepmipt/DeepPavlov#1146]
Hello everyone!

I try to use _deeppavlov.models.bert.bert_as_summarizer.BertAsSummarizer_ for NSP task.
In order to do so, I did:

```
from deeppavlov.models import bert
nsp = bert.bert_as_summarizer.BertAsSummarizer('/root/.deeppavlov/downloads/bert_models/rubert_cased_L-12_H-768_A-12_v2/bert_config.json',
                                              '/root/.deeppavlov/downloads/bert_models/rubert_cased_L-12_H-768_A-12_v2/bert_model.ckpt',
                                              '/root/.deeppavlov/downloads/bert_models/rubert_cased_L-12_H-768_A-12_v2/vocab.txt',
                                              100)

```
The results I get when do:
`nsp._get_nsp_predictions([sent1], [sent2])` 
are strange. Take a look, please!
```
nsp._get_nsp_predictions(['Ветер дул в окно.'], ['Лягушка выпила воды из ручья.'])
output: array([0.4839714], dtype=float32)
nsp._get_nsp_predictions(['Ветер дул в окно.'], ['Как говоришь его зовут?'])
output: array([0.48752904], dtype=float32)

```
Do I do something wrong?
Please, help me to figure it out!

btw, I tried before to use the following strategy: compute embedding with the first sentence, compute embedding with the first sentence followed by the second one, then I compare the distance between embeddings. If the distance differs quite a lot, I supposed the sentences are not in the sequence order. Is this approach not correct?

Thank you!

**Comment by yurakuratov** [comment]
Hi!

Thank you for reporting!
We need to investigate further on that problem.

You use this model correctly, but predictions do not look like expected ones. Did you experienced the same problem with other BERT models?
