### ISSUE TITLE
A bug or a feature of a Russian ner?

### ISSUE THREAD

**Issue by kudep** [deepmipt/DeepPavlov#1154]
For a configs.ner.ner_rus_bert configuration
```
# %%

from deeppavlov import configs, build_model

# %%

ner_model = build_model(configs.ner.ner_rus_bert, download=True)
]
```
I got this outputs of a model
```
# %%

ner_model(["Ivan is better"])


...
[[['Ivan', 'is', 'better']], [['B-PER', 'O', 'O']]]
```
and next
```
...
[[['Bob', 'Ross', 'lived', 'in', 'Florida']],
 [['B-PER', 'I-PER', 'O', 'O', 'B-LOC']]]

...
[[['Привет', 'друг']], [['O', 'O']]]

...
[[['Я', 'встал', 'и', 'пошел']], [['O', 'O', 'O', 'O']]]


...
[[['Иван', 'красавчик']], [['O', 'O']]]


```
so, it isn't working for rus and working for eng. It's amazing.

**Comment by kudep** [comment]
It is work when i was splitting by spaces input
```
ner_model(["Петрович", "Дарина"]) 
```
...
[[['Петрович'], ['Дарина']], [['B-PER'], ['B-PER']]]

...
[[['Петрович'], ['он']], [['B-PER'], ['O']]]
```

**Comment by yoptar** [comment]
The model was trained on full and proper sentences, so it would work fine on `'Иван — красавчик'` but no on `'Ivan better'`.
