### ISSUE TITLE
Error running the Classification Tutorial in Google Colab

### ISSUE THREAD

**Issue by mukundanma** [deepmipt/DeepPavlov#1157]
I am getting the following error when running the classification tutorial in Google Colab in the step "Infering on validation data we get probability distribution on given data" under the section "KerasClassificationModel on GloVe embeddings in python"

https://colab.research.google.com/github/deepmipt/DeepPavlov/blob/master/examples/classification_tutorial.ipynb

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-56-88374151ec2d> in <module>()
----> 1 y_valid_pred = cls(embedder(tokenizer(str_lower(x_valid))))

12 frames
/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py in _as_graph_element_locked(self, obj, allow_tensor, allow_operation)
   3684       # Actually obj is just the object it's referring to.
   3685       if obj.graph is not self:
-> 3686         raise ValueError("Tensor %s is not an element of this graph." % obj)
   3687       return obj
   3688     elif isinstance(obj, Operation) and allow_operation:

ValueError: Tensor Tensor("activation_4/Sigmoid:0", shape=(?, 7), dtype=float32) is not an element of this graph.

I am a newbie to DeepPavlov. Apologize my ignorance. Appreciate your response.

**Comment by dilyararimovna** [comment]
Hello!
Thank you for reporting this bug. We've already catched that but didn't fix yet.
You may change the line
```
y_valid_pred = cls(embedder(tokenizer(str_lower(x_valid))))
```
to the line
```
y_valid_pred = cls.__call__(embedder(tokenizer(str_lower(x_valid))))
```
