### ISSUE TITLE
Dont load previous model in bert_classifier

### ISSUE THREAD

**Issue by grayskripko** [deepmipt/DeepPavlov#1160]
I found that on each run my model shows better results. It was suspicious. I realized it uses the same trained model. I tried to remove "load_path" from config file in "train" section and it raised an exception File "....\Anaconda3\lib\site-packages\deeppavlov\models\bert\bert_classifier.py", line 98, in __init__
    and not tf.train.checkpoint_exists(str(self.load_path.resolve())):
AttributeError: 'NoneType' object has no attribute 'resolve'
What is good way to train a fresh model everytime and not to delete files manually before each training?

**Comment by dilyararimovna** [comment]
Hello!

It's better not to remove `load_path` but to remove pre-trained model which is located in load path location.
Our current ideology assumes we always try to load model if it's located `load_path`.

**Comment by grayskripko** [comment]
is there an argument of `train()` for this?

**Comment by dilyararimovna** [comment]
Currently, we don't have this parameter.

**Comment by dilyararimovna** [comment]
You may also just set `load_path` to some not existing folder.

**Comment by grayskripko** [comment]
thanks @yoptar
