### ISSUE TITLE
Import deeppavlov in notebook problem

### ISSUE THREAD

**Issue by anoukbnd** [deepmipt/DeepPavlov#1163]
Hi everyone,

I have created a virtuel environment and installed in it deeppavlov
aio-pika==6.4.1
aiormq==3.2.1
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.1.1
cryptography==2.8
Cython==0.29.14
DAWG-Python==0.7.2
deeppavlov==0.8.0
docopt==0.6.2
fastapi==0.47.1
fuzzywuzzy==0.17.0
h11==0.9.0
h5py==2.10.0
idna==2.8
joblib==0.14.1
multidict==4.7.5
nltk==3.4.5
numpy==1.18.0
overrides==2.7.0
pamqp==2.3.0
pandas==0.25.3
pycparser==2.20
pydantic==1.3
pymorphy2==0.8
pymorphy2-dicts==2.4.393442.3710985
pymorphy2-dicts-ru==2.4.404381.4453942
pyOpenSSL==19.1.0
pyTelegramBotAPI==3.6.7
python-dateutil==2.8.1
pytz==2019.3
requests==2.22.0
rusenttokenize==0.0.5
scikit-learn==0.21.2
scipy==1.4.1
six==1.14.0
starlette==0.12.9
tqdm==4.41.1
urllib3==1.25.8
uvicorn==0.11.1
websockets==8.1
yarl==1.4.2

Then I have launched a jupyter notebook in that virtual environment, but I can't import deeppavlov in it.

I have tried :
```
import sys
!{sys.executable} -m pip install --user deeppavlov
```
But then I have this error : 
ERROR: wrangle 0.6.7 has requirement scipy==1.2, but you'll have scipy 1.4.1 which is incompatible.
  WARNING: The script tqdm.exe is installed in 'C:\Users\ABA19328\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script uvicorn.exe is installed in 'C:\Users\ABA19328\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts cygdb.exe, cython.exe and cythonize.exe are installed in 'C:\Users\ABA19328\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

What can I do to import it in my notebook ?
Thanks

**Comment by IgnatovFedor** [comment]
Hi, @anoukbnd 
I apologize for long absence of any answer. I could not reproduce this error. Could you please describe how you started the notebook and send results of `!pip freeze` command execution?
