### ISSUE TITLE
Bert tokenisation limit of 512

### ISSUE THREAD

**Issue by anoukbnd** [deepmipt/DeepPavlov#1165]
Hi everyone,

I am trying to extract named entity in different languages using configs.ner.ner_ontonotes_bert_mult as a model but I am stuck with the bert tokenisation of 512 tokens.

I have to filter with a NLTK tokenizer but I still have the problem for sequences that have less than 512 tokens with the NLTK tokenizer calculation.
What is the bert tokenizer used in this mult ner model ? I would like to use to split my data correctly.

Thanks

**Comment by yurakuratov** [comment]
Hi!

BERT-based models use WordPiece tokenization, not a tokenization on words like it does NLTK tokenizer.

Here is an example of how to check actual length in subtokens:
```python
from bert_dp.tokenization import FullTokenizer
tokenizer = FullTokenizer(vocab_file='PATH_TO/vocab.txt', do_lower_case=False)
tokenizer.tokenize('Heyyyyy how are you.')
> ['Hey', '##yy', '##yy', 'how', 'are', 'you', '.']
```
