### ISSUE TITLE
Дообучение модели ner_rus_bert. Проблема с длиной входной последовательности в данных

### ISSUE THREAD

**Issue by AntipatternCorp** [deepmipt/DeepPavlov#1166]
Здравствуйте, я хочу дообучить модель ner_rus_bert на своих данных, а не обучить с нуля. Для этого вызываю обучения без правок самой конфигурации ner_rus_bert.json. В ~/.deeppavlov/downloads/total_rus положил размеченные файлы train.txt, test.txt, valid.txt объемом в 147к, 19к и 20к строк соответственно. Предложения разделены пустой строкой, предложения длиннее 50 слов разделены на части пустыми строками, знаки препинания при разметке рассматривались как отдельные токены.
При вызове:
`ner_model = train_model(configs.ner.ner_rus_bert, download=False)`

Получаю:

> Runtime Error: input sequence after bert tokenization shouldn't exceed 512 tokens.

Подскажите, пожалуйста, в чём может быть проблема? В размеченных данных длинных предложений нет.

**Comment by AntipatternCorp** [comment]
Похоже проблема была в большой разреженности данных. Между тэгированными сущностями были большие куски незначащего текста. Я переразметил данные для обучения и попробовал дообучить на небольшом куске в 8к слов. Отработало без ошибок. Привожу ниже ссылку на файлы с текущей разметкой на примере новостной страницы.
https://dropmefiles.com/kZHyp

**Comment by username1618** [comment]
Насколько я понял, ошибка возникает в модуле bert_preprocessor.py на этапе токенизации. Некоторые предложения после проведения BPE-токенизации превышают лимит в 512 токенов.
