### ISSUE TITLE
get both NER confidence and tags

### ISSUE THREAD

**Issue by danie08** [deepmipt/DeepPavlov#1168]
Good morning,

I am quite new with using DeepPavlov. I am using the model ner_ontonotes_bert_mult and I need to get **both** named entities confidence score and their ner tag.

In order to get the confidence scores, I followed this issue https://github.com/deepmipt/DeepPavlov/issues/1127.

Here is an example of what I get.

[[['Billy', 'goes', 'to', 'London', '.']], array([[[4.63200547e-03, 3.96298783e-05, 9.93227184e-01, 1.35380775e-04,
         1.19723982e-05, 3.45377717e-04, 7.19909964e-04, 4.73044965e-05,
         3.95460665e-05, 1.68470688e-05, 6.78724155e-06, 2.42228343e-05,
         5.22621485e-06, 5.16213186e-06, 2.00176393e-04, 2.59094418e-06,
         9.02667125e-06, 2.42573378e-06, 1.03035827e-05, 1.62995493e-05,
         4.55893360e-06, 1.47988767e-05, 1.67417293e-05, 4.54163637e-06,
         4.31066546e-05, 2.22109054e-04, 1.62923534e-05, 6.43290768e-05,
         1.27500225e-05, 1.16676310e-05, 3.33146272e-05, 3.94602102e-05,
         1.34320953e-06, 2.73407665e-07, 1.65085057e-05, 4.37715386e-07,
         3.46819888e-07],
        [9.98991787e-01, 5.04238669e-05, 7.25901482e-05, 6.77923481e-06,
         1.83096010e-04, 2.46839918e-05, 2.78051466e-05, 9.05577836e-05,
         4.33492351e-05, 3.32144032e-06, 1.52910161e-05, 1.12833422e-05,
         1.47117908e-05, 2.58828504e-06, 1.60394862e-04, 2.04118242e-05,
         4.06110848e-06, 2.31282252e-06, 5.61653687e-05, 1.01547369e-06,
         8.01751376e-05, 7.01585577e-06, 7.98722067e-06, 2.14762567e-05,
         3.06174443e-05, 6.13409702e-06, 7.64426773e-07, 4.11873079e-05,
         1.57549857e-06, 5.35763775e-06, 1.13041233e-06, 1.05683885e-05,
         2.46561217e-06, 2.13046974e-07, 5.33064394e-07, 1.80490517e-07,
         7.88342263e-08],
        [9.98495221e-01, 9.37192817e-05, 8.45555041e-05, 1.10676856e-05,
         2.37328204e-04, 4.49083782e-05, 4.73405962e-05, 1.12615104e-04,
         5.20517169e-05, 4.61343780e-06, 2.22581566e-05, 1.78215269e-05,
         1.75777204e-05, 3.27747239e-06, 2.89861928e-04, 2.94838355e-05,
         5.55565748e-06, 2.88227830e-06, 1.03362428e-04, 1.89081948e-06,
         1.12321759e-04, 1.35988485e-05, 1.52996454e-05, 2.75350030e-05,
         3.18790226e-05, 1.02671029e-05, 1.54516522e-06, 7.49917235e-05,
         2.67208839e-06, 6.87334068e-06, 1.78912342e-06, 1.80686802e-05,
         3.89746947e-06, 3.19762421e-07, 1.02859440e-06, 2.92813269e-07,
         1.25266155e-07],
        [8.47491377e-04, 4.36725747e-03, 2.25299736e-03, 9.32394505e-01,
         3.67192551e-04, 4.38850001e-03, 9.38139856e-04, 4.22404555e-04,
         2.83661211e-04, 9.74120339e-04, 3.85050371e-04, 1.65012106e-02,
         8.42199137e-04, 1.51958942e-04, 2.06684833e-03, 2.53509090e-04,
         9.30820534e-04, 8.43221860e-05, 2.43433146e-03, 6.49685506e-03,
         4.82923148e-04, 4.14968608e-03, 6.00215420e-03, 7.65926612e-04,
         2.57420237e-04, 4.44916775e-04, 2.44243653e-03, 5.10011846e-03,
         6.93351496e-04, 3.15110316e-04, 8.72670062e-05, 5.05973352e-04,
         3.10938951e-04, 1.03070226e-04, 2.51112273e-04, 5.88057737e-04,
         1.16155941e-04],
        [9.99448359e-01, 2.18682435e-05, 7.16410068e-05, 6.51546816e-06,
         5.17829903e-05, 3.99655582e-05, 9.99741405e-06, 8.34220191e-05,
         4.64651821e-05, 2.66088523e-06, 5.36417701e-06, 5.13857685e-06,
         8.99422776e-06, 1.81156440e-06, 4.99818743e-05, 1.39911381e-05,
         3.61078855e-06, 1.61039088e-06, 1.94981021e-05, 9.60510306e-07,
         3.02198205e-05, 3.20725053e-06, 3.54652934e-06, 1.17129548e-05,
         2.14316988e-05, 5.25522501e-06, 9.22581535e-07, 1.53147321e-05,
         1.58982380e-06, 3.77368042e-06, 1.19498441e-06, 5.77305082e-06,
         1.37755842e-06, 1.66102140e-07, 7.46686965e-07, 1.01334592e-07,
         4.98796560e-08]]], dtype=float32)]

How can I get named entities tags from this?

Thanks in advance

**Comment by yoptar** [comment]
Hi @danie08,

You can get tags by running `dict(model['tag_vocab'])` if `model` is the variable name of your model. It will return a dictionary with tag names as keys and their indexes in resulting probabilities lists as values.

**Comment by danie08** [comment]
Thank you so much! :D

**Comment by danie08** [comment]
Hi @yoptar 
starting from the probabilities lists, how can I determine the right tag for each token?
I was assuming it was an argmax, but maybe I was going wrong. 

For example, given this sentence "tonight at 7:56 PM ET", what I obtained is the following: 

[[['tonight', 'at', '7', ':', '56', 'PM', 'ET']], array([[[1.63543143e-03, 9.96820199e-06, 1.78842602e-04, 1.85967328e-05,
         1.78099417e-05, 3.80352540e-05, 1.57919530e-05, 1.32198431e-04,
         7.87259924e-05, 7.21344259e-06, 1.53685542e-05, 9.05004890e-06,
         1.74918205e-05, 1.91379895e-05, 2.26408465e-05, 1.24618809e-05,
         2.43787563e-05, 1.03718467e-05, 1.05706340e-05, 2.82249694e-05,
         1.39975129e-03, 8.55145845e-06, 2.30801998e-05, 6.02477849e-05,
         9.95207965e-01, 6.26708497e-05, 4.17556730e-05, 2.77076506e-05,
         4.33662644e-05, 6.88260363e-04, 5.10401842e-05, 2.20654110e-05,
         1.68241404e-05, 6.10518964e-06, 2.15794389e-05, 1.28948923e-05,
         3.76125172e-06],
        [9.86744702e-01, 3.09826981e-04, 1.08850875e-03, 8.38169581e-05,
         5.96281257e-04, 3.49598209e-04, 2.53523700e-04, 1.14374026e-03,
         6.38564059e-04, 3.20436448e-05, 1.39155934e-04, 8.05537129e-05,
         1.58643961e-04, 4.73556793e-05, 9.40731203e-04, 1.44768303e-04,
         5.43576389e-05, 3.79088233e-05, 3.15132202e-04, 2.28375520e-05,
         1.58766261e-03, 8.74634206e-05, 7.46468722e-05, 2.77578307e-04,
         3.56729608e-03, 1.99152506e-04, 2.77351119e-05, 3.64156469e-04,
         6.82647224e-05, 2.51586986e-04, 4.59448529e-05, 1.94452514e-04,
         3.25508045e-05, 7.55884321e-06, 2.17205161e-05, 7.45896932e-06,
         2.72413808e-06],
        [2.25036172e-03, 1.05760548e-04, 3.43198568e-04, 1.06821040e-04,
         2.33332175e-04, 2.07258970e-04, 1.19529548e-04, 9.92248300e-04,
         9.16383520e-04, 3.98416778e-05, 2.34967185e-04, 1.20077391e-04,
         3.13471450e-04, 1.74726723e-04, 2.34926629e-04, 2.39448695e-04,
         3.61896178e-04, 1.80689342e-04, 1.32410903e-04, 1.47697850e-04,
         1.84580684e-02, 1.31688677e-04, 1.98857248e-04, 6.70700800e-04,
         9.66880083e-01, 3.30344803e-04, 3.93270719e-04, 3.88257526e-04,
         4.18778218e-04, 3.06904246e-03, 3.01061460e-04, 2.81881046e-04,
         3.48588539e-04, 1.00343146e-04, 1.49086976e-04, 3.42631829e-04,
         8.23245427e-05],
        [8.38728845e-02, 9.18215979e-03, 7.21930806e-03, 3.02870665e-03,
         1.67564172e-02, 4.10433626e-03, 8.73984210e-03, 9.19415802e-03,
         1.21864555e-02, 1.05597975e-03, 1.17851887e-02, 9.95693915e-03,
         3.11599486e-02, 1.78912887e-03, 1.93017814e-02, 8.70462134e-03,
         4.35255747e-03, 5.42650931e-03, 9.31751356e-03, 1.40491698e-03,
         3.15933943e-01, 8.85599479e-03, 7.35662598e-03, 3.70673202e-02,
         2.80978113e-01, 4.02963487e-03, 3.59686487e-03, 2.59066410e-02,
         3.76161211e-03, 1.72072835e-02, 2.66005984e-03, 1.08532868e-02,
         1.08241122e-02, 1.41862687e-03, 3.09671089e-03, 6.23249635e-03,
         1.68143644e-03],
        [6.70295581e-02, 8.75810254e-03, 8.20575282e-03, 4.06107632e-03,
         1.23554822e-02, 6.49106037e-03, 8.42060335e-03, 1.31184030e-02,
         2.05714386e-02, 1.42105646e-03, 1.11985449e-02, 9.34873614e-03,
         1.56622268e-02, 2.94393161e-03, 1.29894400e-02, 1.04307057e-02,
         7.55108753e-03, 5.33165643e-03, 7.94164278e-03, 2.63834698e-03,
         2.03533888e-01, 1.05030555e-02, 1.27084553e-02, 3.35541144e-02,
         3.86360407e-01, 5.56138018e-03, 7.45608192e-03, 2.53897179e-02,
         5.97441243e-03, 2.70361062e-02, 4.72999131e-03, 1.17830765e-02,
         1.34913931e-02, 1.98593573e-03, 3.10597965e-03, 8.34909733e-03,
         2.00803299e-03],
        [1.27673661e-02, 2.67291418e-03, 1.80009066e-03, 8.04805779e-04,
         5.12094144e-03, 9.11579293e-04, 2.17298302e-03, 3.13126436e-03,
         3.82886408e-03, 3.89471796e-04, 4.67337202e-03, 2.46173842e-03,
         1.04690846e-02, 1.09119853e-03, 4.93753795e-03, 1.56989926e-03,
         1.51982554e-03, 1.08036038e-03, 3.81222577e-03, 5.20780857e-04,
         4.30593640e-01, 2.82003870e-03, 2.59846542e-03, 3.45753618e-02,
         4.20109242e-01, 1.65211351e-03, 1.89103687e-03, 6.69109821e-03,
         2.06603250e-03, 1.63119119e-02, 8.51659570e-04, 3.47254123e-03,
         4.12023626e-03, 5.93516568e-04, 1.36578607e-03, 3.65797454e-03,
         8.93101504e-04],
        [1.39687970e-01, 4.73172916e-03, 2.10670233e-02, 4.38894005e-03,
         3.47801531e-03, 1.68933962e-02, 2.57931417e-03, 1.42191229e-02,
         5.05011948e-03, 1.13185344e-03, 2.04183720e-03, 1.20955822e-03,
         2.17212038e-03, 1.07902649e-03, 1.11598605e-02, 7.09155574e-04,
         1.34561746e-03, 7.90474936e-04, 4.81618149e-03, 5.38069475e-03,
         6.97211325e-02, 2.22855830e-03, 3.46798636e-03, 4.47074138e-03,
         6.02136433e-01, 2.09812839e-02, 5.76783298e-03, 5.80309145e-03,
         1.43826827e-02, 8.24773498e-03, 4.51515103e-03, 6.38775853e-03,
         1.15121843e-03, 6.24716049e-04, 4.61739348e-03, 1.15363358e-03,
         4.10581968e-04]]], dtype=float32)]

Starting from this, by using argmax, I obtained the following:

[['tonight', 'at', '7', ':', '56', 'PM', 'ET']
[('B-TIME', 0.99520797), ('O', 0.9867447), ('B-TIME', 0.9668801), ('I-TIME', 0.31593394), ('B-TIME', 0.3863604), ('I-TIME', 0.43059364), ('B-TIME', 0.60213643)]]

'7', ':', '56', 'PM', 'ET', though, belong to the same named entity. 

So what I would expect is that '7' has tag 'B-TIME' and  ':', '56', 'PM', 'ET' have tag 'I-TIME'.

Could you suggest me how should I solve this problem?

**Comment by yoptar** [comment]
ok, so looking at [the inference code](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/bert/bert_sequence_tagger.py#L621-L628) I can see that if we want to return probabilities the `use_crf` parameter is basically ignored.
I don't know a lot about CRF and Viterbi scores but my guess is that they can get the most probable set of tags for the full sentence but not a list of probabilities for every token as if it's independent.
So these probabilities are not conditional, they do not take in account what tags are chosen for other tokens.
