### ISSUE TITLE
Error in gobot_tutorial!

### ISSUE THREAD

**Issue by paulagd** [deepmipt/DeepPavlov#1169]
Hi, I am trying to run gobot_tutorial [jupyter noteebok](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_tutorial.ipynb) and I get a strange error when trying to interact with the bot. In the training I did not have any problems but when I try to run the 2nd cell of "Interact with the bot", which is "
bot(['good evening, bot'])", I get the following error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-21-b94b39027f45> in <module>
> ----> 1 bot(['good evening, bot'])
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py in __call__(self, *args)
>     205 
>     206     def __call__(self, *args):
> --> 207         return self._compute(*args, param_names=self.in_x, pipe=self.pipe, targets=self.out_params)
>     208 
>     209     @staticmethod
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py in _compute(***failed resolving arguments***)
>     228                 res = component.__call__(**dict(zip(in_keys, x)))
>     229             else:
> --> 230                 res = component.__call__(*x)
>     231             if len(out_params) == 1:
>     232                 mem[out_params[0]] = res
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py in _wrapped(*args, **kwargs)
>      26     def _wrapped(*args, **kwargs):
>      27         with graph.as_default():
> ---> 28             return func(*args, **kwargs)
>      29 
>      30     return _wrapped
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/models/go_bot/network.py in __call__(self, batch, user_ids)
>     471 
>     472                 _, predicted_act_id, tracker.network_state = \
> --> 473                     self._infer(tokens, tracker=tracker)
>     474 
>     475                 tracker.update_previous_action(predicted_act_id)
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py in _wrapped(*args, **kwargs)
>      26     def _wrapped(*args, **kwargs):
>      27         with graph.as_default():
> ---> 28             return func(*args, **kwargs)
>      29 
>      30     return _wrapped
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/models/go_bot/network.py in _infer(self, tokens, tracker)
>     425                               [[action_mask]], [[tracker.network_state[0]]],
>     426                               [[tracker.network_state[1]]],
> --> 427                               prob=True)
>     428         return probs, np.argmax(probs), (state_c, state_h)
>     429 
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/core/models/tf_backend.py in _wrapped(*args, **kwargs)
>      26     def _wrapped(*args, **kwargs):
>      27         with graph.as_default():
> ---> 28             return func(*args, **kwargs)
>      29 
>      30     return _wrapped
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/deeppavlov/models/go_bot/network.py in network_call(self, features, emb_context, key, action_mask, states_c, states_h, prob)
>     516         probs, prediction, state = \
>     517             self.sess.run([self._probs, self._prediction, self._state],
> --> 518                           feed_dict=feed_dict)
>     519 
>     520         if prob:
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
>     948     try:
>     949       result = self._run(None, fetches, feed_dict, options_ptr,
> --> 950                          run_metadata_ptr)
>     951       if run_metadata:
>     952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> ~/Workspace/virtualenvs/research/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
>    1147                              'which has shape %r' %
>    1148                              (np_val.shape, subfeed_t.name,
> -> 1149                               str(subfeed_t.get_shape())))
>    1150           if not self.graph.is_feedable(subfeed_t):
>    1151             raise ValueError('Tensor %s may not be fed.' % subfeed_t)
> 
> ValueError: Cannot feed value of shape (1, 1, 112) for Tensor 'features:0', which has shape '(?, ?, 129)'

Could anyone help me, please?

I would appreciate it so much!

Thanks,

**Comment by Ablat** [comment]
Exact same problem here. With the new release, I noticed some things are changed. My previous working code for simple gobot, now getting the same error. Judging by the error, this seems to be caused by some changes in 'network.py' file, possibly something to do with the new trackers' split implementation. For the time being, try downgrading to previous version.

**Comment by oserikov** [comment]
Hey! 

Thanks for rising an issue: we are working on go bot refactoring, debugging and improvement right now and such a feedback is extremely helpful. 
The updated version is work-in-progress though and I think that for now some hacks are the best way to deal with bugs in the released version.

I suggest you to simulate the batched dialogue inference by wrapping the replics onto the batch of single dialogue of length 1 (the batch of dialogues is the list of lists of dicts usually). 

So the bot call will look like this:
```python
>>> bot([[{"text": "the weather is clooudy and gloooomy"}]])
[['Then you should cycle!']]
```
