### ISSUE TITLE
Question Answering Model for SQuAD - Use of specific huggingface BERT model

### ISSUE THREAD

**Issue by newuni** [deepmipt/DeepPavlov#1171]
Could you provide a sample of config for Question Answering Model for SQuAD, like this https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/squad/squad_bert_multilingual_freezed_emb.json, but using a specific huggingface model like https://huggingface.co/mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es?

Thanks in advance.

**Comment by yurakuratov** [comment]
Hi!
To use models from HuggingFace in DeepPavlov BERT-SQuAD models you will have to convert them into TensorFlow format (with `.ckpt` files, `bert_config.json` and `vocab.txt`). HuggingFace has [script to convert weights](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_bert_pytorch_checkpoint_to_original_tf.py), but you will have to build `bert_config.json` and `vocab.txt` by yourself.
After that, you can just update paths to converted model in configuration file.
