### ISSUE TITLE
Script or tutorial to create training dataset with DSTC2 format

### ISSUE THREAD

**Issue by patelmiteshn** [deepmipt/DeepPavlov#1175]
Hi there, Thanks for the open source library. I've got the library installed and working. I specifically ran to the gobot_extended_tutorial.ipynb and got it to train on 50 samples using the DSTC2 dataset. 

The question I have is, I am looking to train the gobot on a customized scheduling query dataset that I have. To that end I am trying to see if there are any scripts that I can use/modify to convert the .csv files dataset into DSTC2 format dataset so that I can plug it directly into the gobot_extended_tutorial.ipynb for training.. 

thanks for your help.

**Comment by oserikov** [comment]
Hey!

We’re working on the GO bot to make it easier to use on various datasets right now. 
It’s now work-in-progress though so the best option indeed is to convert your data to follow the dstc2 layout.

Here is hiw I did this to convert the dstc8 data to dstc2: [github.com/oserikov/dstc8_dstc2_converter](https://github.com/oserikov/dstc8_dstc2_converter)

**Comment by patelmiteshn** [comment]
Hi There, 

Thanks a lot for your response and the pointer to some examples to convert dstc8 data to dstc2 format. I'll try to use that as a reference point.
