### ISSUE TITLE
Named Entity Recognition task with my own tags.

### ISSUE THREAD

**Issue by ostreech1997** [deepmipt/DeepPavlov#1176]
Hi, I'm intrested in NER task. In documentation, I see predefind 18 tags from PERSON to CARDINAL. However, my task isn't solved by this tags. Is there any possibility to add new tags? 
I want the following: use your DeepPavlov library, but with my own tags. And if it's possible, how many examples(sentences) I need?
P.S. I use this documentation link: http://docs.deeppavlov.ai/en/master/features/models/ner.html

**Comment by theanhle** [comment]
Hi, all you need is to (1) prepare your dataset in the CoNLL2003 format (refer to the link you mentioned above), then (2) create a config file to define the model with your own hyperparameters. You should collect as many samples as possible. It's hard to say how many is enough. For instance, the CoNLL2003 dataset consists of about 15000, 3500, 3600 samples for training, validation, and test, respectively. Anyway, just try to create a dataset, build a model, train on it, and see how it works.

**Comment by ostreech1997** [comment]
Ok, I got it!
Thanks a lot!
