### ISSUE TITLE
Sentence BERT models incompletable with original library

### ISSUE THREAD

**Issue by Serbernari** [deepmipt/DeepPavlov#1180]
Is there some way to use Sentence RuBERT with sentence-transformers (https://github.com/UKPLab/sentence-transformers) library? Current models seems missing file modules.json

**Comment by yoptar** [comment]
Hi @Serbernari,

Sorry but we currently don't have any plans for adapting our models for the `sentence-transformers` library.

**Comment by Serbernari** [comment]
Ok, it seems to work if i:
1) download sentence-transformers multilingial model
2) unpack it and in folder 0_DistilBERT place pytorch_model.bin from Sentence RuBERT
3) place bert_config.json in 0_DistilBERT from Sentence RuBERT WITH, not INSTEAD of config.json 

Still not sure how, but it seems to work. At least i got vectors for my texts)
