### ISSUE TITLE
No way to disable default reading

### ISSUE THREAD

**Issue by atsanda** [deepmipt/DeepPavlov#1195]
There is a situation when I have 'test.csv' in data path, but I don't want it to be read by dataset_reader.
I could pass `test=None` in kwargs then, but it fails, because string is expected. So, I have to dream up some name which does not exist to gain this behaviour.

https://github.com/deepmipt/DeepPavlov/blob/5f862b012715cc6dff8599ddb80880d9173df231/deeppavlov/dataset_readers/basic_classification_reader.py#L76

**Comment by yoptar** [comment]
Hi @atsanda,
Thank you for bringing this up.
We will discuss this internally, but I'm not sure if we want to add this option to the reader, as it would add more clutter to the code and there are simple enough workarounds.
You can rename your `test.csv` to `_test.csv` or `test_no_labels.csv` as it would reflect why the model should not be evaluated on that data.
