### ISSUE TITLE
In gobot model ..how should we display the intent of a particular dialog

### ISSUE THREAD

**Issue by VenetiaTA** [deepmipt/DeepPavlov#1196]
![image](https://user-images.githubusercontent.com/55089078/80783489-9dae7480-8b97-11ea-93f8-42c452610a44.png)
I want to display the intent of "hi what can i help you with"

**Comment by oserikov** [comment]
There is no such a feature in go_bot right now though I'm working on the ability to configure responses format right now. The PR is #1173 , it's WIP.
