### ISSUE TITLE
Can someone help me how can I implement 3rd party API calls in custom defined actions? Like get weather details or location with google API.

### ISSUE THREAD

**Issue by Ahzam-Lathiya** [deepmipt/DeepPavlov#1198]

**Comment by IgnatovFedor** [comment]
Hi, @Ahzam-Lathiya 
Do you mean the integration of 3rd party API calls to DeepPavlov pipeline?

**Comment by Ahzam-Lathiya** [comment]
I mean can there be a way to use 3rd party APIs? 
Just like some actions query database via an API , I want to know is there a way I can use 3rd party APIs in my actions.
Thanks.

**Comment by Ahzam-Lathiya** [comment]
@IgnatovFedor  Do you know how 3rd party APIs can be integrated?

**Comment by IgnatovFedor** [comment]
@Ahzam-Lathiya, I still can’t quite understand what you need. Could you please give a more concrete example of how it should look? What actions do you mean?

**Comment by Ahzam-Lathiya** [comment]
@IgnatovFedor  When the go-bot is provided with information in slots it runs an API to query a database. (I'm talking about the restaurant example). That is defined in it's actions to query databases on given information. I'm asking that can I add an action in my own bot that would query some 3rd party API like weather, news etc instead of querying a database.

**Comment by IgnatovFedor** [comment]
@Ahzam-Lathiya, to add your custom action you should write your own class inherited from [Component](docs.deeppavlov.ai/en/master/apiref/core/models.html#deeppavlov.core.models.component.Component), [register](http://docs.deeppavlov.ai/en/master/devguides/registry.html) new model in library and new component to [configuration](http://docs.deeppavlov.ai/en/master/intro/configuration.html) file.

**Comment by Ahzam-Lathiya** [comment]
@IgnatovFedor  Thank you for replying me. Can you please elaborate a little more that how can I call a 3rd party API as my custom action?
