### ISSUE TITLE
Very trivial error: "No module named 'deeppavlov.skills.pattern_matching_skills'

### ISSUE THREAD

**Issue by sgladkoff** [deepmipt/DeepPavlov#1202]
Hi,

I am trying to follow Tutorial1, 'Hello bot', and have done the following locally:

I have create venv, ran:

pip install deeppavlov

then I am trying to import 

from deeppavlov.skills.pattern_matching_skill import PatternMatchingSkill

And the system tells me:

ModuleNotFoundError: No module named 'deeppavlov.skills.pattern_matching_skill'

I am pretty sue it's something really trivial but I can't move from there.

Can you help me, please?

**Comment by nchirr** [comment]
same problem here. do not see any references to deeppavlov.skills in http://docs.deeppavlov.ai/en either.

**Comment by yoptar** [comment]
Hi,

[This](http://docs.deeppavlov.ai/en/0.4.0/intro/hello_bot.html) is an obsolete tutorial.
To have it running you can install an older DeepPavlov version:
```bash
pip install deeppavlov==0.4.0
```

We've moved away from this interface of skills and agents and are making a separate [Agent](https://github.com/deepmipt/dp-agent) entity with connectors to arbitrary skills.

**Comment by sgladkoff** [comment]
Nagesh, I managed to overcome this by looking into the deprecated section of code of Deeppavlov.

**Comment by AsbjornOlling** [comment]
> Hi,
> 
> [This](http://docs.deeppavlov.ai/en/0.4.0/intro/hello_bot.html) is an obsolete tutorial.
> To have it running you can install an older DeepPavlov version:
> 
> ```shell
> pip install deeppavlov==0.4.0
> ```
> 
> We've moved away from this interface of skills and agents and are making a separate [Agent](https://github.com/deepmipt/dp-agent) entity with connectors to arbitrary skills.

I suggest that you remove the tutorial from [this page](https://github.com/deepmipt/dp_notebooks)

It's not very welcoming to newcomers like me, that the very first tutorial in the "For beginners: Tutorials" section is totally broken. :(
