### ISSUE TITLE
 AttributeError: module 'transformers' has no attribute 'BertModel'

### ISSUE THREAD

**Issue by fr-judson** [deepmipt/DeepPavlov#1208]
im just importing this module using this code:

```
from deeppavlov.models.embedders.transformers_embedder import TransformersBertEmbedder
```
i got the error 

AttributeError                            Traceback (most recent call last)
<ipython-input-84-06c2cf24cfb1> in <module>
----> 1 from deeppavlov.models.embedders.transformers_embedder import TransformersBertEmbedder

//anaconda3/lib/python3.7/site-packages/deeppavlov/models/embedders/transformers_embedder.py in <module>
     24 
     25 @register('transformers_bert_embedder')
---> 26 class TransformersBertEmbedder(Serializable):
     27     """Transformers-based BERT model for embeddings tokens, subtokens and sentences
     28 

//anaconda3/lib/python3.7/site-packages/deeppavlov/models/embedders/transformers_embedder.py in TransformersBertEmbedder()
     33 
     34     """
---> 35     model: transformers.BertModel
     36     dim: int
     37 

AttributeError: module 'transformers' has no attribute 'BertModel'

**Comment by yoptar** [comment]
Hi @fr-judson,

Do you have pytorch installed?
