### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by mananeau** [deepmipt/DeepPavlov#1211]
Hi all, thanks for your open-source contributions :)

I'm planning to use [one of your models](https://huggingface.co/DeepPavlov/bert-base-cased-conversational) and am wondering how I should cite it. Could you provide me with a reference?

Thanks a lot in advance.

**Comment by yoptar** [comment]
Hi @mananeau,

We don't have a specific paper for this model, but you can reference our paper on the DeepPavlov library: https://www.aclweb.org/anthology/P18-4021/

**Comment by mananeau** [comment]
Sounds good, thanks for your reply!
