### ISSUE TITLE
Warnings in basic_clasf_reader for valid and test files

### ISSUE THREAD

**Issue by grayskripko** [deepmipt/DeepPavlov#1218]
An absence of valid-test files shouldn't be a reason for [warnings](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_readers/basic_classification_reader.py#L109)
because this is expected behavior when I pass only test.csv file and split data in data-iterator
It can be a `log.info` but even better, it should be exposed outside with explicit arguments

**Comment by dilyararimovna** [comment]
Hello!
Dataset reader does not have an access to the dataset iterator parameters. Therefore, it doesn't know that you want to split train set into train and valid, but still it does know that you will need validation set for training. So, it logs warning to notify that you do not have validation set.

**Comment by grayskripko** [comment]
I agree the reader is responsible for reading. In the code of the basic_clas_reader, there is an assumption that all 3 files should be presented. If users intentionally use a train file only they can't avoid nonsense warnings.

**Comment by grayskripko** [comment]
my whole feeling of your great package is so that there are tons of weakly adjusted logs when you train or build a model. Any truly important warning has high chances to be lost there. When I set the logging level to warning I expect to get true warnings. For the moment, I'm able to do this only changing the deeppavlov code.

**Comment by yoptar** [comment]
Hi @grayskripko,
We believe that this scenario warrants a warning, but you're right that one should be able to explicitly skip a data type, so I've added #1224.
With it you should be able to add `"valid": null` to the reader config and not get this warning.
