### ISSUE TITLE
GoBot breaks when calling Tensorflow

### ISSUE THREAD

**Issue by sgladkoff** [deepmipt/DeepPavlov#1220]
The GoBot example from tutrorial says at runtime:

2020-05-12 08:01:47.577 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 101: [saving vocabulary to /home/sgladkoff/Documents/MyWork/assistant_bot/word.dict]
WARNING:tensorflow:From /home/sgladkoff/Documents/MyWork/env/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py:37: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /home/sgladkoff/Documents/MyWork/env/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py:222: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/sgladkoff/Documents/MyWork/env/lib/python3.7/site-packages/deeppavlov/core/models/tf_model.py:222: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

It looks like code in deeppavlov/core/models/tf_model.py does not correspond to current state of Tensorflow... Or am I doing smth wrong?

**Comment by yoptar** [comment]
Hi @sgladkoff,

This is an expected behavior, there are no errors.
We do have plans on updating properly but no timeframe yet, as there is a lot of work involved.
