### ISSUE TITLE
Train using GPU, predict using CPU

### ISSUE THREAD

**Issue by ostreech1997** [deepmipt/DeepPavlov#1222]
Hi everyone!
I'm new in deep learning, so sorry I ask a lot of questions.  I opened this issue: https://github.com/deepmipt/DeepPavlov/issues/1212 and now I can use GPU to train BERT models. I'm building chatbot system and for this reason I have to load 4 trained models: intent classification, two ner models, and bert embedder. But I have several problems with it:
1) I want to train models one by one, but after first training, training process is still exist (nvidia-smi shows this). I trained 3 models this way: train model, then restart Jupyter's kernel (this clear training process from GPU) and then train another models the same way. But it is not flexible solution. I want to use .py file where all models will be trained. (when I use .py file also this problem)
2) Loading trained models using GPU to Jupyter Notebook make Jupyter's kernel dead. I try to load them using .py file, also have error. I think, that may be not enough memory, but It's strange. When I use CPU to train, there is no problem with memory, I can load all this models and use them. May be good way is to train model using GPU, and then make predictions using CPU, is it possible?

I feel that smth wrong with memory usage of GPU, but lack of experience in deep learning doesn't afford me to solve this by myself. 
(p.s. возможно будет эффективней общаться на русском:) )

**Comment by yoptar** [comment]
Привет, @ostreech1997!

Можно по-русски, если так удобнее.

TensorFlow и pytorch не освобождают память, которую заняли, пока не завершится процесс, память всегда будет показываться занятой в nvidia-smi, тут мы ничего не можем сделать, к сожалению.
Другое дело, что можно в рамках фреймворка освободить память, которую смогут переиспользовать другие модели на том же фреймворке. Для TensorFlow-моделей мы написали метод `model.destroy()`, который это делает, а в pytorch это должно происходить автоматически.

Есть вариант запускать обучение в отдельном процессе в рамках одного блокнота как-то так:
```python3
from concurrent.futures import ProcessPoolExecutor

from deeppavlov import train_model

with ProcessPoolExecutor(max_workers=1) as executor:
    executor.submit(train_model, 'ner_ontonotes_bert_mult', download=True)
```
Тогда память освободится сразу по завершении обучения.

**Comment by ostreech1997** [comment]
Привет @yoptar! Спасибо за ответ) 
У меня следующая схема работы: я переобучаю модели с помощью .py файла вида:
from deeppavlov import configs, train_model
```
# Обучение классификатора интентов 
config1 = configs.classification.rusentiment_bert
... # Указываем путь к данным для обучения
model = train_model(config1, dowload=False)
# Обучение ner1 
config2 = configs.classification.ner_rus_bert
... # Указываем путь к данным для обучения
model = train_model(config2, dowload=False)
# Обучение ner2
config3 = configs.classification.rusentiment_bert
... # Указываем путь к данным для обучения
model = train_model(config3, dowload=False)
```
То есть мне нужно после каждого обучения дописывать model.destroy() ? Типа так:
```
# Обучение классификатора интентов 
config1 = configs.classification.rusentiment_bert
... # Указываем путь к данным для обучения
model = train_model(config1, dowload=False)
model.destroy() # Освобождаем память для обучения других моделей
```
Или может быть создать main.py, который будет вызывать три других .py файла обучения: intent.py, ner1.py, ner2.py, обучающие модели по отдельности? Или все равно память будет резервироваться за main.py и после окончания выполенения intent.py она не освободится?
И как последний вариант, который я понял из твоего ответа сделать так:
```
from concurrent.futures import ProcessPoolExecutor
from deeppavlov import train_model
# Обучение intent
with ProcessPoolExecutor(max_workers=1) as executor:
    executor.submit(train_model, config1, download=False)
# Обучение ner1
with ProcessPoolExecutor(max_workers=1) as executor:
    executor.submit(train_model, config2, download=False)
# Обучение ner2
with ProcessPoolExecutor(max_workers=1) as executor:
    executor.submit(train_model, config3, download=False)
```

Также не понял про прогнозирование. Я хочу на Flask создать сервис чат-бота, поэтому мне нужно, чтобы модели были подгружены в памяти  и обрабатывали приходящие сообщения пользователей в режиме онлайн, но то ли памяти не хватает все модели держать, то ли еще  какая проблема, но при загрузке всех моделей  .py файл падает в ошибку. Такой проблемы не было при использовании CPU.  Может быть можно каким-то способом обучать на GPU, а прогнозировать на CPU?

Пример подгрузки моделей:
```
with configs.classifiers.rusentiment_bert.open(encoding='utf8') as f:
    config_classifier = json.load(f)
config_classifier['metadata']['variables']['MODEL_PATH'] = '/base/.deeppavlov/models/classification_task/classification_intent/'

clf_intent = build_model(config_classifier, download=False)



# NER модель для БО 
with configs.ner.ner_rus_bert.open(encoding='utf8') as f:
    ner_config = json.load(f)
ner_config['metadata']['variables']['NER_PATH'] = '/base/.deeppavlov/models/ner_task/rubert_bo/'

ner_bo = build_model(ner_config, download=False)


# NER модель для транзакций
with configs.ner.ner_rus_bert.open(encoding='utf8') as f:
    ner_config = json.load(f)
ner_config['metadata']['variables']['NER_PATH'] = '/base/.deeppavlov/models/ner_task/rubert_transaction/'

ner_transaction = build_model(ner_config, download=False)
```

**Comment by ostreech1997** [comment]
Thanks for help here, I continue discussion on Deeppavlov's forum
