### ISSUE TITLE
Preprocessing for BERT base cased conversational

### ISSUE THREAD

**Issue by manueltonneau** [deepmipt/DeepPavlov#1229]
Hi all,

Thanks for your cool contributions :)

I am currently using [this model](https://huggingface.co/DeepPavlov/bert-base-cased-conversational) for tweet classification and was wondering whether you did any data preprocessing before pre-training on social media data (e.g. tweets). I didn't find this information on the model card so that's why I'm asking here :)

**Comment by mananeau** [comment]
Actually, my question can be divided into two:
- did you clean the raw tweets?
- did you split the tweets in different sentences?

Thanks a lot in advance :)

**Comment by dilyararimovna** [comment]
Hello!
- we didn't clean raw tweets, we have kept hashtags, account names, smiles, etc. For training BERT, we just tokenized texts.
- We didn't parsed threads of twits, so yes, we have taken twits and divided them to sentences (several sentences of one twit is one sample).

**Comment by mananeau** [comment]
Hi @dilyararimovna, thank you for you reply :)

> we didn't clean raw tweets, we have kept hashtags, account names, smiles, etc. For training BERT, we just tokenized texts.

Thanks, that is clear.

>We didn't parsed threads of twits, so yes, we have taken twits and divided them to sentences (several sentences of one twit is one sample).

This is not clear to me. You say you divided tweets in sentences, I get that. But you then say that several sentences of one tweet (that is the whole tweet I guess) is one sample? In that case, you have one tweet per line in your txt file and not one sentence? What am I missing?

Thanks a lot in advance for your help :)

**Comment by dilyararimovna** [comment]
To train BERT on task of predicting next sentence, you need to have a sequence of sentences as one sample in the dataset. 

When you training downstream tasks like classification, that's normal to classify text consisting of several sentences as one sample.

**Comment by manueltonneau** [comment]
Understood, thank you :)
