### ISSUE TITLE
Memory issues with bert_ner_ontonotes_mult

### ISSUE THREAD

**Issue by TsvetanRangelov** [deepmipt/DeepPavlov#1237]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
0.10
**Python version**:
3.7.6

**Operating system** (ubuntu linux, windows, ...):
 Mojave

**Issue**:
After loading the model for production purposes, the memory occupied is 3 times larger than expected.

**Content or a name of a configuration file**:
```

```

**Command that led to error**:
```
import os
import psutil
from deeppavlov import build_model, configs
tagger = build_model(configs.ner.ner_ontonotes_bert_mult)
process = psutil.Process(os.getpid())
process.memory_info()

```

**Error (including full traceback)**:
```

```

**Comment by yurakuratov** [comment]
Hi!
I tried to run these code and got following output for CPU-only:
```
pmem(rss=6818693120, vms=25823158272, shared=533868544, text=2342912, lib=0, data=6957596672, dirty=0)
```
with GPU:
```
pmem(rss=6840561664, vms=25890275328, shared=537337856, text=2342912, lib=0, data=6975823872, dirty=0)
```

What is your output of this command? How did you calculate that it is 3 times more than expected? What is the expected value?

**Comment by TsvetanRangelov** [comment]
Hello, thank you for your response. I ran this several times and get values around 5 000 000 000 similar to this:
pmem(rss=5709262848, vms=14938374144, pfaults=6714897, pageins=20091)
pmem(rss=5053218816, vms=10306125824, pfaults=2975375, pageins=3475)
but I expected the model to be 1.4GB in memory as stated in:
http://docs.deeppavlov.ai/en/master/features/models/ner.html
I hope I am not a misunderstanding. I was aiming for multiple workers parallelizing these objects so the memory usage caught me off guard.

**Comment by yurakuratov** [comment]
`Model Size` in this table means HDD usage, not RAM.

**Comment by TsvetanRangelov** [comment]
Oh ok, I misunderstood then. Closing this in that case
