### ISSUE TITLE
Provide an example of go-bot integration with DB systems other than SQLite

### ISSUE THREAD

**Issue by oserikov** [deepmipt/DeepPavlov#1238]
The go-bot is able ([example](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_extended_tutorial.ipynb)) to query an API to get the data. The data is usually stored in DB. In our example the SQlite database is used. 

There are other DBMS used in production environments and examples of integration with these are needed. 

**The contribution could be one of these**: 
* update existing tutorials with alternative DBMS usage examples
* provide the completely new case (e.g. from you real-world experience) as the tutorial

**Comment by Eugen2525** [comment]
Hi, I can try to do one for postgresql for the starter.

**Comment by oserikov** [comment]
Sounds cool! I suggest to use the [gobot-extended tutorial](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_extended_tutorial.ipynb) as the backbone for the postgresql tutorial to provide the minimalistic yet expressive demo, what do you think about?

**Comment by Eugen2525** [comment]
Thanks, I have tried to use the format to create a tutorial kind of explanation for the earlier issue/feature request. You can see it in the pull request btw, but the problem is it is a bit behind the current refactoring in the codebase.
I will come up with a tutorial hopefully soon. stay tuned!
