### ISSUE TITLE
Provide an extensive example of API usage in go-bot

### ISSUE THREAD

**Issue by oserikov** [deepmipt/DeepPavlov#1239]
The go-bot is able ([example](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_extended_tutorial.ipynb)) to query an API to get the data. It allows to perform the dialog relying onto some explicit knowledge.

In the provided example the bot queries the database to perform some read operations. Operations of other classes (e.g. update) seem to be possible but we have no examples of such cases.

**The contribution could follow these steps**: 
* discover the purpose of update- queries in goal-oriented datasets
* find the dataset with such api calls or generate an artificial one
* provide an example of the go-bot trained on this dataset and using this data

**Comment by 0pride** [comment]
Hello,
If I understand correctly, 
this dataset should be added instead of DSTC-2 (or after working with it)  in this notebook?
