### ISSUE TITLE
Implement various output modules for go-bot

### ISSUE THREAD

**Issue by oserikov** [deepmipt/DeepPavlov#1240]
The go-bot defaults to template-based response generation (i.e. the model learns to respond with relevant templates) though both non-templated and non-natural-language (e.g. #1196 verbose intermediate calculations logs) output features seem relevant.

There has been done some refactoring to allow such extensions of the go-bot (yet some ideas are to be finished).

To implement some additional output modules **the contribution could implement the [NLG module interface](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/go_bot/nlg/nlg_manager_interface.py).** The contribution could require the further refactor of the main go-bot codebase, do not hesitate to start a discussion on such a case.

**Comment by Eugen2525** [comment]
Hi, can I assign this issue to me or how does it work? 
Basically, I want to contribute on this...

**Comment by 0pride** [comment]
Hello, @oserikov 
I'd like to do that. 
Could you point a couple of steps to start from?

**Comment by Arnab1181412** [comment]
Sir can I work on this issue?
