### ISSUE TITLE
Не детерминированная работа ner_few_shot_ru

### ISSUE THREAD

**Issue by lyangas** [deepmipt/DeepPavlov#1244]
DeepPavlov version:
0.10.0
Python:
3.7.4

Operating system:
Ubuntu 18.04.4

config:
configs.ner.ner_few_shot_ru

использую ner_few_shot_ru для решения задачи именованных сущностей. вывожу итоговый имбеддинг слов и оказалось что имбеддинг разный при каждом запуске классификации токенов. не нашел нигде способа детерминировать работу модели (как я понял, ELMO), это возможно?

прикрепляю пример
<img width="611" alt="image" src="https://user-images.githubusercontent.com/44424726/84239703-25888680-ab27-11ea-8280-2716a610e5b0.png">

**Comment by mu-arkhipov** [comment]
Might be related to this issue https://github.com/allenai/allennlp/issues/2516, mentioned here https://opendatascience.slack.com/archives/C04N3UMSL/p1592085494240700?thread_ts=1591772554.130900&cid=C04N3UMSL

**Comment by kudep** [comment]
Детерминировать представление (embeddings) ELMo для определенного предложения можно, если обнулять стейты lstm-ов после каждого шага (step), в архитектуре ELMo предусмотено так, что модель сама умеет (после train) обнулять стейты lstm-ов по спец. токену, но делает это не идеально из-за этого появляется отклонения. Обнулять стейты можно дописав обнуление после каждого предложения стейтов lstm, либо грубо, но быстро через `tf.global_variables_initializer()`.

Но в целом, если нет задачи полного совпадения представлений, то можно ожидать, что расстояния между представлениями разных и одинаковых предложений отличаются на порядок. 

Для примера, возьмем два предложения `это каталог` и `это потолок`. Получим для каждого по 30-ть представлений
```python
sess.run(tf.global_variables_initializer())
embeddings = []
for i in range(30):
    embeddings += [sess.run(elmo([sentece], signature="default", as_dict=True)["elmo"])]
```
 и посчитаем cosine для всех пар (`with_self_cosines` - дистанции косайна для пар представлений от одного и того же предложения, `with_other_cosines` -  дистанции косайна для пар представлений от разных предложений):
```python
[
    with_self_cosines.min(),
    with_self_cosines.max(),
    with_self_cosines.mean(),
    with_self_cosines.std(),
    with_self_cosines.shape,
], [
    with_other_cosines.min(),
    with_other_cosines.max(),
    with_other_cosines.mean(),
    with_other_cosines.std(),
    with_other_cosines.shape,
]
```
получим:

```python
([
  1.1920928955078125e-07,
  0.016765058040618896,
  0.002283974875152381,
  0.004698426563357737,
  (442,)
 ],
 [
  0.33362287282943726,
  0.35768985748291016,
  0.3538326478059454,
  0.0010225684507660566,
  (867,)
 ]
)
```
