### ISSUE TITLE
Paraphrase detection - BadZipFile

### ISSUE THREAD

**Issue by alissiawells** [deepmipt/DeepPavlov#1250]
My module, based on deeppavlov, runs on my machine. However, it does not work on a remote sever with Ubuntu 18.04 because of BadZipFile. What problem can be in a paraphrazer.zip, mentioned in the traceback (in a screenshot)?
I use deeppavlov of 0.8.0 version with small modifications: github.com/alissiawells/deeppavlov (treshold instead of model’s verdict in the output)

![33300DFF-121D-4F37-A8ED-39093D74934E](https://user-images.githubusercontent.com/35057128/84739865-0c635800-afb5-11ea-8188-6a080f43bcb5.jpeg)
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**Comment by IgnatovFedor** [comment]
Hi @alissiawells,
I apologize for the very late reply, but could you clarify the specific commit you are using? I am puzzled that 2.69k is downloaded instead of 1.16M size of `paraphrizer.zip` size.
