### ISSUE TITLE
ODQA on Wikipedia example doesn't work

### ISSUE THREAD

**Issue by zjohn77** [deepmipt/DeepPavlov#1265]
Getting the error below when I try to follow the Quick Start from: http://docs.deeppavlov.ai/en/master/features/skills/odqa.html

My environment is: DeepPavlov 0.11.0, python 3.7.7, MacOS 10.15.5

FileNotFoundError                         Traceback (most recent call last)
~/my_pav.py in <module>
      2 from deeppavlov.core.commands.infer import build_model
      3 
----> 4 odqa = build_model(configs.odqa.en_odqa_infer_wiki, load_trained=True)
      5 
      6 result = odqa(['What is the name of Darth Vader\'s son?'])

~/opt/miniconda3/lib/python3.7/site-packages/deeppavlov/core/commands/infer.py in build_model(config, mode, load_trained, download, serialized)
     60             component_serialized = None
     61 
---> 62         component = from_params(component_config, mode=mode, serialized=component_serialized)
     63 
     64         if 'id' in component_config:

~/opt/miniconda3/lib/python3.7/site-packages/deeppavlov/core/common/params.py in from_params(params, mode, serialized, **kwargs)
     79         _refs.clear()
     80         config = parse_config(expand_path(config_params['config_path']))
---> 81         model = build_model(config, serialized=serialized)
     82         _refs.clear()
     83         _refs.update(refs)

~/opt/miniconda3/lib/python3.7/site-packages/deeppavlov/core/commands/infer.py in build_model(config, mode, load_trained, download, serialized)
     60             component_serialized = None
     61 
---> 62         component = from_params(component_config, mode=mode, serialized=component_serialized)
     63 
     64         if 'id' in component_config:

~/opt/miniconda3/lib/python3.7/site-packages/deeppavlov/core/common/params.py in from_params(params, mode, serialized, **kwargs)
    104                 kwargs['mode'] = mode
    105 
--> 106             component = obj(**dict(config_params, **kwargs))
    107             try:
    108                 _refs[config_params['id']] = component

~/opt/miniconda3/lib/python3.7/site-packages/deeppavlov/models/vectorizers/hashing_tfidf_vectorizer.py in __init__(self, tokenizer, hash_size, doc_index, save_path, load_path, **kwargs)
     78 
     79         if kwargs.get('mode', 'infer') == 'infer':
---> 80             self.tfidf_matrix, opts = self.load()
     81             self.ngram_range = opts['ngram_range']
     82             self.hash_size = opts['hash_size']

~/opt/miniconda3/lib/python3.7/site-packages/deeppavlov/models/vectorizers/hashing_tfidf_vectorizer.py in load(self)
    260         """
    261         if not self.load_path.exists():
--> 262             raise FileNotFoundError("HashingTfIdfVectorizer path doesn't exist!")
    263 
    264         logger.info("Loading tfidf matrix from {}".format(self.load_path))

FileNotFoundError: HashingTfIdfVectorizer path doesn't exist!

**Comment by mosvlad** [comment]
Same error on **configs.odqa.ru_odqa_infer_wiki**

**Comment by IgnatovFedor** [comment]
Hi @zjohn77 and @mosvlad,

There is an error in documentation: `load_trained=True` argument in `build_model` should be replaced with `download=True`.
