### ISSUE TITLE
KBQA model for simple question answering in Russian not working

### ISSUE THREAD

**Issue by mosvlad** [deepmipt/DeepPavlov#1266]
Code :

    from deeppavlov import configs, build_model

    kbqa_model = build_model(configs.kbqa.kbqa_rus, download=True)
    kbqa_model(['Когда родился Пушкин?'])

fails with :

    kbqa_model = build_model(configs.kbqa.kbqa_cq_rus, download=True)
    AttributeError: 'Struct' object has no attribute 'kbqa_cq_rus'

**DeepPavlov version** : 0.10.0

**Python version**:   3.6.9

**Operating system** : Ubuntu 18.04

**Comment by dmitrijeuseew** [comment]
KBQA model for simple question answering was replaced with beta version of KBQA model for complex question answering in the latest release of DeepPavlov. New config is in the folder configs/kbqa/kbqa_cq_rus.json

**Comment by IgnatovFedor** [comment]
Hi @mosvlad,

`configs.kbqa.kbqa_cq_rus` was added in 0.11.0
