### ISSUE TITLE
Вывод top_n ответов в odqa

### ISSUE THREAD

**Issue by mapryl** [deepmipt/DeepPavlov#1280]
На данный момент не реализован вывод top_n ответов odqa (непосредственно в logit_ranker.py это отмечено комментарием TODO). 
Для своих нужд мы это реализовали и хотели бы законтрибьютить, если это возможно :)

**Comment by IgnatovFedor** [comment]
Добрый день, @mapryl
С радостью добавили бы этот функционал в библиотеку. Вы не могли бы сделать PR?
