### ISSUE TITLE
Use TFLMSV to solve OOM Error.

### ISSUE THREAD

**Issue by inksong** [deepmipt/DeepPavlov#1305]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
Considering that the current version of deeppavlov does not support multiple GPU training, we will often encounter OOM errors (insufficient GPU memory), can we integrate this solution? By IBM -> tensorflow-large-model-support aka tflmsv1
```

**How can we solve it?**:
```
Simply merge this feature. Not very troublesome.
https://github.com/IBM/tensorflow-large-model-support/tree/tflmsv1
```

**Are there other issues that block this solution?**:
```
Nope
```

**Comment by vaskonov** [comment]
Nowadays, DeepPavlov does support multi GPU training with PyTorch.
