### ISSUE TITLE
multi-threading in NER model ?

### ISSUE THREAD

**Issue by cattoni** [deepmipt/DeepPavlov#1315]
Sorry for the naive question, I am a newbie of DeepPavlov.

Is a NER model built with build_model multi-threaded (e.g. build_model(configs.ner.ner_ontonotes_bert_mult) ) or is there any parameter/arg to set to have multi-threading?

Thanks for your kind support!

**Comment by moryshka** [comment]
Hi @cattoni 
Please, ask this question in [our forum ](https://forum.deeppavlov.ai). 
Use issues only to enhance library components or error reports.
Thank you!
