### ISSUE TITLE
Loading Bert Different Models

### ISSUE THREAD

**Issue by Harish202** [deepmipt/DeepPavlov#1319]
Hi, First of all thank you for the great repo. My issue is loading uncased bert model for ner_conll2003_bert for ner task.. I have modified the config accordingly.

  "metadata": {
    "variables": {
      "ROOT_PATH": "~/.deeppavlov",
      "DOWNLOADS_PATH": "{ROOT_PATH}/downloads",
      "MODELS_PATH": "{ROOT_PATH}/models",
      "BERT_PATH": "{DOWNLOADS_PATH}/bert_models/uncased_L-12_H-768_A-12",
      "NER_PATH": "{MODELS_PATH}/ner_conll2003_bert"
    },
    "requirements": [
      "{DEEPPAVLOV_PATH}/requirements/tf.txt",
      "{DEEPPAVLOV_PATH}/requirements/bert_dp.txt"
    ],
    "download": [
      {
        "url": "http://files.deeppavlov.ai/deeppavlov_data/ner_conll2003_bert_v1.tar.gz",
        "subdir": "{MODELS_PATH}"
      },
      {
        "url": "http://files.deeppavlov.ai/deeppavlov_data/bert/uncased_L-12_H-768_A-12.zip",
        "subdir": "{DOWNLOADS_PATH}/bert_models"
      }
    ]
  }
}

But looks like architecture is not matching with the saved uncased model. It throws dimension mismatch error.

ner_model = build_model("ner_conll2003_bert.json", download=True)

InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [30522,768] rhs shape= [28996,768]
	 [[node save/Assign_2 (defined at /home/harish/anaconda3/envs/pytorch2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Can you please let me know if I need to change any other attribute in config file?

**Comment by mu-arkhipov** [comment]
Hi,
It seems that the part below loads the fine-tuned cased BERT. Just remove it, than either remove already downloaded files from `MODELS_PATH` or change `load_path` in `"bert_sequence_tagger"` part of the config.
```{
"url": "http://files.deeppavlov.ai/deeppavlov_data/ner_conll2003_bert_v1.tar.gz",
"subdir": "{MODELS_PATH}"
},
```

**Comment by Harish202** [comment]
Thank you for quick response. I have done changes as you mentioned. Now the model is able to build but when I am trying to do NER it is throwing bellow error:

Config:

  "metadata": {
    "variables": {
      "ROOT_PATH": "~/.deeppavlov",
      "DOWNLOADS_PATH": "{ROOT_PATH}/downloads",
      "MODELS_PATH": "{ROOT_PATH}/models",
      "BERT_PATH": "{DOWNLOADS_PATH}/bert_models/uncased_L-12_H-768_A-12",
      "NER_PATH": "{MODELS_PATH}/ner_conll2003_bert"
    },
    "requirements": [
      "{DEEPPAVLOV_PATH}/requirements/tf.txt",
      "{DEEPPAVLOV_PATH}/requirements/bert_dp.txt"
    ],
    "download": [
      {
        "url": "http://files.deeppavlov.ai/deeppavlov_data/bert/uncased_L-12_H-768_A-12.zip",
        "subdir": "{DOWNLOADS_PATH}/bert_models"
      }
    ]
  }

Code 
ner_model = build_model("/mnt/d/Harish/code_u/text/deeppavlov/ner_conll2003_bert.json", download=True)
ner_model(['Bob Ross lived in Florida']) #this is the line throwing the error.

Error is as below
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda3/envs/pytorch2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

~/anaconda3/envs/pytorch2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
-> 1350                                       target_list, run_metadata)
   1351 

~/anaconda3/envs/pytorch2/lib/python3.6/site-packages/tensorflow_core/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1442                                             fetch_list, target_list,
-> 1443                                             run_metadata)
   1444 

InvalidArgumentError: Requested more than 0 entries, but params is empty.  Params shape: [1,7,0]
	 [[{{node ner_1/GatherNd}}]]


Please let me know if I am missing something. Appreciate your help

**Comment by mu-arkhipov** [comment]
This error is due to empty tag dictionary, which in turn is due to untrained model. Use `model = train_model(<config_path>, download=True)` command to train it.

**Comment by mu-arkhipov** [comment]
I close this issue treating it as solved. Feel free to open it again in case of questions.
