### ISSUE TITLE
Query prediction in KBQA

### ISSUE THREAD

**Issue by SnigdhaBiswas** [deepmipt/DeepPavlov#1320]
Hi,

I want to train the model on my own dataset for query prediction. Is there a way that can be done?

Also, from where can I get the query templates of the existing 8 labels and add new templates to it?

**Comment by Sharathmk99** [comment]
@SnigdhaBiswas Did you figure out how to use your own dataset?

**Comment by dmitrijeuseew** [comment]
The example of the dataset can be downloaded from https://github.com/deepmipt/DeepPavlov/blob/eddb44542b43eb0aeacf954a0d98710a3ef3b0ed/deeppavlov/configs/classifiers/query_pr.json#L104
The file with SPARQL templates is https://github.com/deepmipt/DeepPavlov/blob/eddb44542b43eb0aeacf954a0d98710a3ef3b0ed/deeppavlov/configs/kbqa/kbqa_cq.json#L171
