### ISSUE TITLE
DeepPavlov installed from wrong branch in RASA config tutorial

### ISSUE THREAD

**Issue by oserikov** [deepmipt/DeepPavlov#1322]
see `!pip install git+https://github.com/deepmipt/DeepPavlov.git@feature/gobot-md-yaml-config
` [here](https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_md_yaml_configs_tutorial.ipynb)

**Comment by arya2910** [comment]
@oserikov  i dont understand whats exactly the issue is??...i have executed each line written https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_md_yaml_configs_tutorial.ipynb .
everything is working nicely
