### ISSUE TITLE
Bad requirement file

### ISSUE THREAD

**Issue by duongkstn** [deepmipt/DeepPavlov#1324]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):

**Python version**: 3.7.6

**Operating system** (ubuntu linux, windows, ...): ubuntu linux

**Issue**:
The `requirments.txt` should be written for compatible with multiple versions of packages.
For instance,  condition `numpy>=1.18.0` is preferred by software developers instead of strictly declaring `numpy==1.18.0`.
At first, developers like me feel very inconvenient.
Rgds,

**Comment by IgnatovFedor** [comment]
Hi, @duongkstn
We prefer `==` in requirements to `>=` because of possible errors when a new version of dependencies is released. What errors can be caused by using double equals?
