### ISSUE TITLE
pymorphy2 0.9.1 is released

### ISSUE THREAD

**Issue by kuraga** [deepmipt/DeepPavlov#1329]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:

Current `pymorphy2` requirement [is obsolete](https://github.com/deepmipt/DeepPavlov/blob/0.12.1/requirements.txt#L11) in DeepPavlov.
`pymorphy2 0.9.1` [was released](https://github.com/kmike/pymorphy2/releases/tag/0.9.1).
See also: https://github.com/kmike/pymorphy2/issues/125, https://github.com/kmike/pymorphy2/issues/133.

**How can we solve it?**:
```
pymorphy2==0.9.1
````

**Comment by IgnatovFedor** [comment]
Requirement is replaced with pymorphy2<=0.9.1 in 1.0.0rc1
