### ISSUE TITLE
Improve config file documentation

### ISSUE THREAD

**Issue by polodealvarado** [deepmipt/DeepPavlov#1334]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
It is quite difficult to understand the config file when you want to build your own.

```

**How can we solve it?**:
```
Add more documentation.

```

**Are there other issues that block this solution?**:
```

```

**Comment by rushilpatra** [comment]
hey @polodealvarado!  Can I work on this?

**Comment by polodealvarado** [comment]
> hey @polodealvarado! Can I work on this?

Sure, no problem.

**Comment by nastyachizhikova** [comment]
Hi @polodealvarado!
Pease check the following page in DeepPavlov's documentation: https://docs.deeppavlov.ai/en/master/intro/configuration.html
