### ISSUE TITLE
404 in the docs

### ISSUE THREAD

**Issue by oserikov** [deepmipt/DeepPavlov#1338]
Our docs contain 404 links for nemo tutorials [here](http://docs.deeppavlov.ai/en/master/features/models/nemo.html) below in the model training section

**Comment by HassanRahim26** [comment]
Hey, @oserikov 
I am **interested** in working on this issue. Can you please guide me about how to proceed with solving this?

**Comment by oserikov** [comment]
Hey! Well,
`Speech recognition` and `Speech Synthesis` links 
in the models training sections lead nowhere. 

I think this can be fixed somewhere [here](https://github.com/deepmipt/DeepPavlov/blob/b66179e584d3eb6da73c5731ba7b732dab7e94bd/docs/features/models/nemo.rst)! 
To check if docs are built properly, run `make html` from inside the docs folder of the project.

Thanks for your interest! Feel free to reference me if you have questions
