### ISSUE TITLE
unable to load trained model on custom dataset

### ISSUE THREAD

**Issue by Bharat9280** [deepmipt/DeepPavlov#1343]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):

**Python version**:

**Operating system** (ubuntu linux, windows, ...):

**Issue**:

**Content or a name of a configuration file**:
```
import json
from deeppavlov import configs, build_model, train_model

with configs.classifiers.insults_kaggle_bert.open(encoding='utf8') as f:
    ner_config = json.load(f)
ner_config['chainer']['pipe'][3]['save_path']='/home/bharat/ensemble_bert_model/mymodel.dict'
ner_config['chainer']['pipe'][3]['load_path']='/home/bharat/ensemble_bert_model/mymodel.dict'




a=build_model(ner_config,load_trained=True)
![Screenshot from 2020-11-16 14-26-24](https://user-images.githubusercontent.com/25278928/99232929-90e22d00-2818-11eb-8ea3-8b5169fb5566.png)

```

**Command that led to error**:
```
build_model(config,load_trained=True)
```

**Error (including full traceback)**:
```
instead of loading pretrained model from specified checkpoint its  loading from deppalov bert cgeck point .kindly help
```

**Comment by yurakuratov** [comment]
Hi!

It looks like `tf.train.checkpoint_exists(load_path)` returns `False` in your case, could you check it? The possible reason is that checkpoint is saved in format that is not supported by `tf.train.checkpoint_exists`.

**Comment by andreybondarb** [comment]
It seems like you didnt change anything in your config inplace. Try this one:

with open(configs.classifiers.insults_kaggle_bert, 'r+') as f:
    ner_config = json.load(f)
    ner_config['chainer']['pipe'][3]['save_path']='/home/bharat/ensemble_bert_model/mymodel.dict'
    ner_config['chainer']['pipe'][3]['load_path']='/home/bharat/ensemble_bert_model/mymodel.dict'
    
    f.seek(0) 
    json.dump(ner_config, f)
    f.truncate()

**Comment by SAYAKGHANTA** [comment]
You can try this :
```
import json
from deeppavlov import configs, build_model

with configs.ner.ner_ontonotes_bert_mult.open(encoding='utf8') as f:
    ner_config = json.load(f)
ner_config['metadata']['variables']['NER_PATH'] = '~/model_path/'

ner_model=build_model(ner_config,load_trained=True)
```
