### ISSUE TITLE
Error while trying to get the probablities of the predicted entities using ontonotes_bert ner model

### ISSUE THREAD

**Issue by ravishpankar** [deepmipt/DeepPavlov#1353]
Deeppavlov version: 0.12.1
Python version: 3.7.7
"return_probas"set to true in ner_ontonotes_bert config json
Command: python -m deeppavlov interact F:\miniconda3\envs\ute_query_params_service\Lib\site-packages\deeppavlov\configs\ner\ner_ontonotes_bert.js
Command string: London is in England.
**Full Traceback:**
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\tokenization.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

2020-11-30 21:37:31.122 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 115: [loading vocabulary from C:\Users\User\.deeppavlov\models\ner_ontonotes_bert\tag.dict]
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:37: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:222: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:222: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:193: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:236: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:314: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\modeling.py:178: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\modeling.py:418: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\modeling.py:499: The name tf.assert_less_equal is deprecated. Please use tf.compat.v1.assert_less_equal instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\modeling.py:366: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\modeling.py:680: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\tensorflow_core\python\layers\core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\bert_dp\modeling.py:283: The name tf.erf is deprecated. Please use tf.math.erf instead.

WARNING:tensorflow:Variable *= will be deprecated. Use `var.assign(var * other)` if you want assignment to the variable value or `x = x * y` if you want a new python Tensor object.
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:75: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\tensorflow_core\contrib\crf\python\ops\crf.py:213: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:234: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:131: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:131: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:94: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\tensorflow_core\python\training\moving_averages.py:433: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:671: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:244: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\models\bert\bert_sequence_tagger.py:249: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2020-11-30 21:40:57.982 INFO in 'deeppavlov.core.models.tf_model'['tf_model'] at line 51: [loading model from C:\Users\User\.deeppavlov\models\ner_ontonotes_bert\model]
WARNING:tensorflow:From f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\models\tf_model.py:54: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

x::London is in England.
Traceback (most recent call last):
  File "f:\miniconda3\envs\ute_query_params_service\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\miniconda3\envs\ute_query_params_service\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\__main__.py", line 4, in <module>
    main()
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\deep.py", line 89, in main
    interact_model(pipeline_config_path)
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\commands\infer.py", line 89, in interact_model
    pred = model(*args)
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\common\chainer.py", line 207, in __call__
    return self._compute(*args, param_names=self.in_x, pipe=self.pipe, targets=self.out_params)
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\common\chainer.py", line 230, in _compute
    res = component.__call__(*x)
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 92, in __call__
    looked_up_batch = [self(sample, is_top=False) for sample in batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 92, in <listcomp>
    looked_up_batch = [self(sample, is_top=False) for sample in batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 92, in __call__
    looked_up_batch = [self(sample, is_top=False) for sample in batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 92, in <listcomp>
    looked_up_batch = [self(sample, is_top=False) for sample in batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 92, in __call__
    looked_up_batch = [self(sample, is_top=False) for sample in batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 92, in <listcomp>
    looked_up_batch = [self(sample, is_top=False) for sample in batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 94, in __call__
    return self[batch]
  File "f:\miniconda3\envs\ute_query_params_service\lib\site-packages\deeppavlov\core\data\simple_vocab.py", line 161, in __getitem__
    raise NotImplementedError("not implemented for type `{}`".format(type(key)))
NotImplementedError: not implemented for type `<class 'numpy.float32'>`

I would like to get the probablities of predicted entities. Is return_probas is the way to go? Please help.
Thanks in advance.
- Ravishankar

**Comment by yurakuratov** [comment]
Hi!

You also need to remove [the last component](https://github.com/deepmipt/DeepPavlov/blob/c10b079b972493220c82a643d47d718d5358c7f4/deeppavlov/configs/ner/ner_ontonotes_bert.json#L61-L65) from pipe, which converts label indices to actual labels.
```json
{
        "ref": "tag_vocab",
        "in": ["y_pred_ind"],
        "out": ["y_pred"]
}
```
and change [chainer out section](https://github.com/deepmipt/DeepPavlov/blob/c10b079b972493220c82a643d47d718d5358c7f4/deeppavlov/configs/ner/ner_ontonotes_bert.json#L67) `"out": ["x_tokens", "y_pred"]` -> `"out": ["x_tokens", "y_pred_ind"]`
As result, model will return tokens and labels probabilities for each token. Order of labels probabilities is the same as in labels vocabulary: https://github.com/deepmipt/DeepPavlov/blob/c10b079b972493220c82a643d47d718d5358c7f4/deeppavlov/configs/ner/ner_ontonotes_bert.json#L30

**Comment by ravishpankar** [comment]
@yurakuratov, Hi! Thank you for answering. It helps. I would like to get the labels and probabilities in one go. The model is loaded in a python microservice and I can't change the config everytime for label and probabilities. 
This is offtopic but I would like to talk to you about how to improve my ner task over whatsapp. I'm not able to do a specific task in spacy and I need your advice. Could you send me your whatsapp no? Please...

**Comment by ravishpankar** [comment]
@yurakuratov, one more request. Is it possible to annotate using span start and span end of an entity in a sentence instead of bio tagging? I'm going to train this model with additional dataset.

**Comment by yurakuratov** [comment]
Hi!

>  I would like to get the labels and probabilities in one go. The model is loaded in a python microservice and I can't change the config everytime for label and probabilities.

You could create a custom configuration file which will could return `x_tokens`,  `y_pred` and `y_pred_ind`. Add `proba2labels` component ([example](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/classifiers/glue/glue_rte_cased_bert_torch.json#L62-L66)) to get `y_pred` from `y_pred_ind`.

> This is offtopic but I would like to talk to you about how to improve my ner task

You are welcome to ask a question on forum https://forum.deeppavlov.ai/ .

> Is it possible to annotate using span start and span end of an entity in a sentence instead of bio tagging?

It will require additional component in the pipeline which will convert BIO tags to spans. We don't have such component in the library, but it would be great if you could contribute it.

**Comment by ravishpankar** [comment]
@yurakuratov, Thank you. Ok. This doubt may be silly; do I need two models to be loaded for two configs (one for labels and the other for probabilities)? Models are huge btw. I don't want two models to be loaded in my python microservice. If I build the model with two configs, will there be two copies of the model?

**Comment by yurakuratov** [comment]
There is no need in two models running to get and labels and probabilities, just modify original config as was mentioned in previous comment.

And yes, if you build two models with two configs there will be two copies running and use double resources.

**Comment by ravishpankar** [comment]
@yurakuratov, Thank you. I understand. Is it possible to train the ner ontonotes bert model incrementally? The idea is I will use the model to predict for some sentences and I will annotate its predictions along with the entities missed(required by me which are deeppavlov predefined entitytypes) and train the model only with those sentences on top of pretrained model.

**Comment by ravishpankar** [comment]
@yurakuratov , if I train incrementally like I said before, how can I distribute the model to some clients?

**Comment by yurakuratov** [comment]
@ravishpankar Sorry for the delay.

> Is it possible to train the ner ontonotes bert model incrementally? The idea is I will use the model to predict for some sentences and I will annotate its predictions along with the entities missed(required by me which are deeppavlov predefined entitytypes) and train the model only with those sentences on top of pretrained model.

Yes, it could be done, but maybe just extending training dataset with new examples will work better. If you will have only few sentences to train on model can overfit easily.

> how can I distribute the model to some clients?

You can change the link to trained model in configuration file (section download) to newer model and distribute new configuration files. Another way, if it works to you, just replace download url with your own and periodically update file (but you will need models to re-download weights). DeepPavlov also supports s3 urls.

**Comment by ravishpankar** [comment]
@yurakuratov , Where will I get the training data set in bio format for ontonotes bert ner model? Are there anymore additional files like weights file required? How long will it take to train the model with the base dataset and additional sentences which will be few thousands utmost? I'm using a i5 dual processor, windows 10 os system with 8GB RAM. Is there anyway to terminate the training in between? I will running the training in a python web app thread and i should be able to kill it may be after the current epoch.

**Comment by ravishpankar** [comment]
@yurakuratov, Thank you for your answers to my questions before the last bunch.

**Comment by yurakuratov** [comment]
> Where will I get the training data set in bio format for ontonotes bert ner model? 

Training dataset will be downloaded automatically to https://github.com/deepmipt/DeepPavlov/blob/f9af2fa3f9f425e715aae647b57637406fc7145e/deeppavlov/configs/ner/ner_ontonotes_bert.json#L4 folder if you will start training (`python -m deeppavlov train ...`) or evaluating (`python -m deeppavlov evaluate ...`) the model.
Another way is to download the data manually from https://github.com/deepmipt/DeepPavlov/blob/b66179e584d3eb6da73c5731ba7b732dab7e94bd/deeppavlov/dataset_readers/conll2003_reader.py#L36
and extend it with your data.

> Are there anymore additional files like weights file required?

All model files (pre-trained weights for ) could be downloaded with `python -m deeppavlov download config_name` or from python with `model = build_model(config_name, download=True)`

> How long will it take to train the model with the base dataset and additional sentences which will be few thousands utmost? I'm using a i5 dual processor, windows 10 os system with 8GB RAM.
Sorry, but I am not aware of training time estimates for running on CPU. 8GB RAM could be a problem.

> Is there anyway to terminate the training in between? I will running the training in a python web app thread and i should be able to kill it may be after the current epoch.

As any process it could be terminated, it is not something that is specific to DP library. During the training process the current best model based on metrics will be saved. Also, you can modify maximum number of training epochs and validation patience value (number of epochs without metrics improving).

**Comment by ravishpankar** [comment]
@yurakuratov, thank you very much for your answers.  Please tell me how long will training take on a GPU? What do you mean by overfit just in case I train incrementally?

**Comment by ravishpankar** [comment]
@yurakuratov, my config.json file looks different. I will attach the file here and you may make the necessary changes and upload it here with description of the changes. Of course, this is for getting the entity tokens and probabilities. Please help.
This is my ner_ontonotes_bert config.json:
{
  "dataset_reader": {
    "class_name": "conll2003_reader",
    "data_path": "{DOWNLOADS_PATH}/ontonotes/",
    "dataset_name": "ontonotes",
    "provide_pos": false
  },
  "dataset_iterator": {
    "class_name": "data_learning_iterator"
  },
  "chainer": {
    "in": ["x"],
    "in_y": ["y"],
    "pipe": [
      {
        "class_name": "bert_ner_preprocessor",
        "vocab_file": "{BERT_PATH}/vocab.txt",
        "do_lower_case": false,
        "max_seq_length": 512,
        "max_subword_length": 15,
        "token_masking_prob": 0.0,
        "in": ["x"],
        "out": ["x_tokens", "x_subword_tokens", "x_subword_tok_ids", "startofword_markers", "attention_mask"]
      },
      {
        "id": "tag_vocab",
        "class_name": "simple_vocab",
        "unk_token": ["O"],
        "pad_with_zeros": true,
        "save_path": "{NER_PATH}/tag.dict",
        "load_path": "{NER_PATH}/tag.dict",
        "fit_on": ["y"],
        "in": ["y"],
        "out": ["y_ind"]
      },
      {
        "class_name": "bert_sequence_tagger",
        "n_tags": "#tag_vocab.len",
        "keep_prob": 0.1,
        "bert_config_file": "{BERT_PATH}/bert_config.json",
        "pretrained_bert": "{BERT_PATH}/bert_model.ckpt",
        "attention_probs_keep_prob": 0.5,
        "use_crf": true,
        "return_probas": true,
        "ema_decay": 0.9,
        "encoder_layer_ids": [-1],
        "weight_decay_rate": 1e-6,
        "learning_rate": 1e-2,
        "bert_learning_rate": 2e-5,
        "min_learning_rate": 1e-7,
        "learning_rate_drop_patience": 30,
        "learning_rate_drop_div": 2,
        "load_before_drop": false,
        "clip_norm": 1.0,
        "save_path": "{NER_PATH}/model",
        "load_path": "{NER_PATH}/model",
        "in": ["x_subword_tok_ids", "attention_mask", "startofword_markers"],
        "in_y": ["y_ind"],
        "out": ["y_pred_ind"]
      },
      {
        "ref": "tag_vocab",
        "in": ["y_pred_ind"],
        "out": ["y_pred"]
      }
    ],
    "out": ["x_tokens", "y_pred"]
  },
  "train": {
    "epochs": 30,
    "batch_size": 16,
    "metrics": [
      {
        "name": "ner_f1",
        "inputs": ["y", "y_pred"]
      },
      {
        "name": "ner_token_f1",
        "inputs": ["y", "y_pred"]
      }
    ],
    "validation_patience": 100,
    "val_every_n_batches": 40,

    "log_every_n_batches": 40,
    "tensorboard_log_dir": "{NER_PATH}/logs",
    "show_examples": false,
    "pytest_max_batches": 2,
    "pytest_batch_size": 8,
    "evaluation_targets": ["valid", "test"],
    "class_name": "nn_trainer"
  },
  "metadata": {
    "variables": {
      "ROOT_PATH": "~/.deeppavlov",
      "DOWNLOADS_PATH": "{ROOT_PATH}/downloads",
      "MODELS_PATH": "{ROOT_PATH}/models",
      "BERT_PATH": "{DOWNLOADS_PATH}/bert_models/cased_L-12_H-768_A-12",
      "NER_PATH": "{MODELS_PATH}/ner_ontonotes_bert"
    },
    "requirements": [
      "{DEEPPAVLOV_PATH}/requirements/tf.txt",
      "{DEEPPAVLOV_PATH}/requirements/bert_dp.txt"
    ],
    "download": [

      {
        "url": "http://files.deeppavlov.ai/deeppavlov_data/ner_ontonotes_bert_v1.tar.gz",
        "subdir": "{MODELS_PATH}"
      },
      {
        "url": "http://files.deeppavlov.ai/deeppavlov_data/bert/cased_L-12_H-768_A-12.zip",
        "subdir": "{DOWNLOADS_PATH}/bert_models"
      }
    ]
  }
}

**Comment by ravishpankar** [comment]
@yurakuratov, please help

**Comment by danielkornev** [comment]
> @yurakuratov, thank you very much for your answers. Please tell me how long will training take on a GPU? What do you mean by overfit just in case I train incrementally?

Hi and thank you very much for your interest in the aforementioned NER model from the DP Library. As the GPUs that we and our customers like you use usually differ (e.g., model, amount of memory, etc.), it is advised to measure the performance on your own hardware to get the best picture.

**Comment by ravishpankar** [comment]
@danielkornev, thank you for your answer. What is the minimum ram required? Also, please make changes to the config file pasted in the third comment above. The aim is to get the entity tokens and probabilities. Please see the comment.

**Comment by danielkornev** [comment]
BERT models eat approximately 4GB of GPU RAM.

**Comment by ravishpankar** [comment]
@danielkornev, thank you. Please make the changes to the nerontonotes Bert config json changes and paste it in your comment. The reason is the config file is quite different from the file where the changes are suggested by @yurakuratov. I'm using deeppavlov 0.12.1.

**Comment by ravishpankar** [comment]
@danielkornev , I can get the labels and probabilities. I'm getting an error while training the trained model after extending the train.txt dataset with my sample. Thanks a lot Daniel and Yura. It was really instructive and helpful. You may want to close this one.
