### ISSUE TITLE
Tensorflow 2.4.0 support

### ISSUE THREAD

**Issue by rupamojha** [deepmipt/DeepPavlov#1359]
**What problem are we trying to solve?**:
```
Deeppavlov currently supports tensorflow version 1.15.2 for running various models. 
The code which is built using these models shows security vulnerabilities in whitesource (https://www.whitesourcesoftware.com/) scans. These vulnerabilities are due to outdated version of tensorflow.

```

**How can we solve it?**:
```
We can have support for latest tensorflow version 2.4.0 which has patches for all the security vulnerabilities found in older versions.
```

**Are there other issues that block this solution?**:
```
No.
```

**Comment by danielkornev** [comment]
Hi! Idea is great, and it is on our list. However, given the wide number of available models, we plan to re-factor the library based on the model's popularity, and then we'll work on migration to 2.0. :) 

If you want to contribute let us know!

**Comment by IgnatovFedor** [comment]
All tensorflow-based models will be removed/replaces with pytorch-based ones in 1.0.0. [1.0.0rc0](https://github.com/deepmipt/DeepPavlov/releases/tag/1.0.0rc0) is already available.
