### ISSUE TITLE
Review analytics and prepare list of all models that we want to support or deprecate

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1367]
Moved to internal Trello

**Comment by moryshka** [comment]
@yurakuratov summarization ( bert_as_summarizer,bert_as_summarizer_with_init) - del
@oserikov Seq2seq_go_bot (bot_kvret, bot_kvret_train) - del

**Comment by yurakuratov** [comment]
remove summarization PR:
https://github.com/deepmipt/DeepPavlov/pull/1391

**Comment by danielkornev** [comment]
https://github.com/deepmipt/DeepPavlov/issues/1380

**Comment by danielkornev** [comment]
no news for this week - we wait for updates in the Tool
