### ISSUE TITLE
File Share: Versioning for Models

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1371]
# Problems
* We don't know what each particular file is for (because of lack of naming conventions & controlled versioning)
* Lack of access control

# Requirements
* files should be controlled by versions 
* file names should conform to naming conventions
* access control should be enforced
* S3 API support

# Proposed Solutions
### Pros
* simple and familiar
* no additional costs for learning, deploying, and supporting custom solution
* S3 API Support
* Version control

### Cons
*TBD?

### Pros
* Version control
* S3 API support
* If we will use MLFlow, DVC etc., we can use this solution as backend easily
### Cons
* additional costs for learning, deploying, and supporting this solution
* ?

# Tasks
* [ ] Ask Yuri Shkandybin's opinion - @IgnatovFedor 
* [ ] Look up for more solutions

**Comment by yurakuratov** [comment]
https://min.io/

**Comment by oserikov** [comment]
there also exists openstack swift: https://wiki.openstack.org/wiki/Swift

**Comment by danielkornev** [comment]
awaiting comments from @jurashka

**Comment by danielkornev** [comment]
we need a system for URL redirects w/ ability to count download links

**Comment by danielkornev** [comment]
create doc w/ all requirements & define design decisions

**Comment by danielkornev** [comment]
Spec is done, see link in Slack.
