### ISSUE TITLE
Error when initializing FileWriter (deprecated usage)

### ISSUE THREAD

**Issue by ayeffkay** [deepmipt/DeepPavlov#1383]
Please, update these lines for train and validation FileWriter (or make it compatible with tf 2):
https://github.com/deepmipt/DeepPavlov/blob/b66179e584d3eb6da73c5731ba7b732dab7e94bd/deeppavlov/core/trainers/nn_trainer.py#L150
This gives: `AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'`.
Possible fix:

```
self.tb_train_writer = self._tf.summary.create_file_writer(str(self.tensorboard_log_dir / 'train_log'))
self.tb_valid_writer = self._tf.summary.create_file_writer(str(self.tensorboard_log_dir / 'valid_log'))
```

And
https://github.com/deepmipt/DeepPavlov/blob/b66179e584d3eb6da73c5731ba7b732dab7e94bd/deeppavlov/core/trainers/nn_trainer.py#L178
produces `AttributeError: module 'tensorflow' has no attribute 'Summary'`

**Comment by IgnatovFedor** [comment]
Replaced with `torch.utils.tensorboard.SummaryWriter` in #1572
