### ISSUE TITLE
Support RASA 2.0 format for nlu.md & extend with Intent Catcher

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1395]
Moved to internal Trello

**Comment by danielkornev** [comment]
# Action Items
* [ ] Create environment with RASA 2.0
* [ ] Use RASA 2.0-only examples to form domain.yml and nlu.yml, as well as stories.yml (read the docs)
* [ ] Build chatbot
* [ ] Observe its behavior (including but not limited to their regex-based **intent** implementation)
* [ ] Build own reader for RASA 2.0 format
* [ ] Ensure that own Intent Classifier provides similar (or better) results for vanilla format
* [ ] Add support for Intent Catcher extensions to RASA 2.0 **nlu.yml** format in our data reader
* [ ] Ensure that Intent Catcher can build intent classifier based on extended RASA 2.0 **nlu.yml** format

**Comment by Edith-panda** [comment]
hii @danielkornev I want to work on this issue can you tell me from where to begin with and how to proceed with same.

**Comment by danielkornev** [comment]
Adding @danchern97 @oserikov - to discuss

**Comment by danielkornev** [comment]
Waiting for PR
