### ISSUE TITLE
pip install DeepPavlov showing error on python 3.9.1  

### ISSUE THREAD

**Issue by 123456asdf** [deepmipt/DeepPavlov#1400]
ERROR: Command errored out with exit status 1:
   command: 'f:\tpl\pythonprojects\ner\env\scripts\python.exe' 'f:\tpl\pythonprojects\ner\env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\umar.safeer\AppData\Local\Temp\pip-build-env-mog_5bg7\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.4.0'
       cwd: None
  Complete output (331 lines):
  Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
  Collecting wheel
    Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Collecting setuptools
    Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
  Collecting Cython>=0.29.13
    Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3.zip (6.4 MB)
  Collecting pybind11>=2.4.0
    Using cached pybind11-2.6.2-py2.py3-none-any.whl (191 kB)
  Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.
  Installing collected packages: wheel, setuptools, Cython, numpy, pybind11
      Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'f:\tpl\pythonprojects\ner\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\umar.safeer\\AppData\\Local\\Temp\\pip-install-65zebcyc\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\umar.safeer\\AppData\\Local\\Temp\\pip-install-65zebcyc\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\umar.safeer\AppData\Local\Temp\pip-record-iqq9xlw3\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\umar.safeer\AppData\Local\Temp\pip-build-env-mog_5bg7\overlay' --compile --install-headers 'C:\Users\umar.safeer\AppData\Local\Temp\pip-build-env-mog_5bg7\overlay\include\site\python3.9\numpy'
           cwd: C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\
      Complete output (302 lines):
      Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)

      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      blis_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blis not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      openblas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_3_10_blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\system_info.py:690: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        self.calc_info()
      blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\system_info.py:690: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      blas_src_info:
        NOT AVAILABLE

      C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\system_info.py:690: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE

      'svnversion' is not recognized as an internal or external command,
      operable program or batch file.
      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      openblas_lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      openblas_clapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas,lapack not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      flame_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries flame not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in f:\tpl\pythonprojects\ner\env\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack not found in ['f:\\tpl\\pythonprojects\\ner\\env\\lib', 'C:\\']
        NOT AVAILABLE

      C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
        NOT AVAILABLE

      C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win-amd64-3.9
      creating build\src.win-amd64-3.9\numpy
      creating build\src.win-amd64-3.9\numpy\distutils
      building library "npymath" sources
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Inumpy\core\src\common -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -If:\tpl\pythonprojects\ner\env\include -IC:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\include -IC:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include /Tc_configtest.c /Fo_configtest.obj
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\lib\x64 _configtest.obj /OUT:_configtest.exe
      LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
      failure.
      removing: _configtest.c _configtest.obj _configtest.obj.d
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\setup.py", line 443, in <module>
          setup_package()
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\setup.py", line 435, in setup_package
          setup(**metadata)
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\core.py", line 171, in setup
          return old_setup(**new_attr)
        File "f:\tpl\pythonprojects\ner\env\lib\site-packages\setuptools\__init__.py", line 165, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\install.py", line 62, in run
          r = self.setuptools_run()
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\install.py", line 36, in setuptools_run
          return distutils_install.run(self)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\command\install.py", line 546, in run
          self.run_command('build')
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\build.py", line 47, in run
          old_build.run(self)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\umar.safeer\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\build_src.py", line 142, in run
          self.build_sources()
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\build_src.py", line 153, in build_sources
          self.build_library_sources(*libname_info)
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\build_src.py", line 286, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
        File "C:\Users\umar.safeer\AppData\Local\Temp\pip-install-65zebcyc\numpy\numpy\distutils\command\build_src.py", line 369, in generate_sources
          source = func(extension, build_dir)
        File "numpy\core\setup.py", line 669, in get_mathlib_info
          raise RuntimeError("Broken toolchain: cannot link a simple C program")
      RuntimeError: Broken toolchain: cannot link a simple C program
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'f:\tpl\pythonprojects\ner\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\umar.safeer\\AppData\\Local\\Temp\\pip-install-65zebcyc\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\umar.safeer\\AppData\\Local\\Temp\\pip-install-65zebcyc\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\umar.safeer\AppData\Local\Temp\pip-record-iqq9xlw3\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\umar.safeer\AppData\Local\Temp\pip-build-env-mog_5bg7\overlay' --compile --install-headers 'C:\Users\umar.safeer\AppData\Local\Temp\pip-build-env-mog_5bg7\overlay\include\site\python3.9\numpy' Check the logs for full command output.
  WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
  You should consider upgrading via the 'f:\tpl\pythonprojects\ner\env\scripts\python.exe -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'f:\tpl\pythonprojects\ner\env\scripts\python.exe' 'f:\tpl\pythonprojects\ner\env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\umar.safeer\AppData\Local\Temp\pip-build-env-mog_5bg7\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'pybind11>=2.4.0' Check the logs for full command output.

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):

**Python version*3.9.1*:

**Operating system** (windows, ...):

**Issue**:

**Content or a name of a configuration file**:
```

```

**Command that led to error**:
```

```

**Error (including full traceback)**:
```

```

**UPDATE**
Moved to internal Trello

**Comment by danielkornev** [comment]
We currently only support Python 3.6.

**Comment by arya2910** [comment]
@danielkornev  i have python 3.8  but i have installed it properly.
if there any issue with python 3.8.

**Comment by arya2910** [comment]
@123456asdf  first set your environment variable and check your python in working properly or not in cmd then again do the follow the step to install deeppavlov in anaconda prompt.

**Comment by danielkornev** [comment]
We don't currently support Python versions other than 3.5 and 3.6 for the time being.

**Comment by arya2910** [comment]
so should i install python3.6 if it is properly installed.

**Comment by danielkornev** [comment]
You just should make sure that python 3.6 is exposed to DeepPavlov by default. Or, you can use docker iamge instead

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Edith-panda** [comment]
Hii 
![IMG_20210314_125928](https://user-images.githubusercontent.com/73990998/111060734-3191e200-84c5-11eb-8b49-0236791ecc85.jpg)


@danielkornev and @arya2910 in installation guide it is written over their that they support python 3.6 and 3.7  , python 3.5 is not supported 

 So by default it doesn't support python 3.9.1 also

**Comment by Edith-panda** [comment]
And so @123456asdf  it's not a bug it's prerequisite thing for installation.

**Comment by arya2910** [comment]
@Edith-panda i figured that out and installed all the prerequisite.and now its working nicely...thanks for ur reply:)
