### ISSUE TITLE
Add support for Actions in Go-Bot

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1409]
Moved to internal Trello

**Comment by danielkornev** [comment]
@oserikov : formulate task for prospective GSoC students, alongside with your existing work

**Comment by rashmiprabhat567** [comment]
Hey @danielkornev @oserikov , I've gone through the GO-bot pipeline research paper and found it interesting to work with. I want to contribute to this issue but i'm unable to understand the base here. How should I incorporate this? Kindly guide me with it.
