### ISSUE TITLE
Try to combine Dataverse with our CEPH

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1413]
Moved to internal Trello

**Comment by rashmiprabhat567** [comment]
Hey @danielkornev , would you give a little description of this issue. I think I would contribute to this as it is somewhat related to my tech stack. Thanks!


> _No description provided._

**Comment by danielkornev** [comment]
Hi! This is an internal issue. There is a nice GUI for organizing work with ML Models called Dataverse, and we want to evaluate its effectiveness when combined with CEPH where we store our models.
