### ISSUE TITLE
Location NER Tagging

### ISSUE THREAD

**Issue by shamil-kadavan** [deepmipt/DeepPavlov#1426]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
I am new to deeppavalov framework, can we have an ner which can identify cities and states instead of just location. I mean having custom tags for entities
```

**How can we solve it?**:
```

```

**Are there other issues that block this solution?**:
```

```

**Comment by vaskonov** [comment]
@shamil-kadavan you can always get the specific location type by using vocabularies of cities and states.
