### ISSUE TITLE
 Multi class emotion classification for text in russian 

### ISSUE THREAD

**Issue by MuhammedTech** [deepmipt/DeepPavlov#1430]
Как использовать BERT Classifier для multi class классификаций текста? У меня есть свой датасет, нужно тренировать модель на этом датасете.
Пример Input:
Я сегодня чувствую себя не очень хорошо
Output:
Sadness

Классов должно быть 5 или 6

Знаю что есть rusentiment_bert.json. Это как я понимаю pretrained и здесь только Positive neutral negative speech skip, а мне надо чтобы были эмоций типа (радость, печаль итп)

Мне получается нужно быть изменить конфиг rusentiment_bert.json? Если да – то как и что надо изменить для настройки данной модели? 
Прошу помочь c гайденсом как работает весь процесс.

**Comment by moryshka** [comment]
Добрый день!

Напишите свой вопрос у нас на форуме, пожалуйста: https://forum.deeppavlov.ai.
