### ISSUE TITLE
Entity Linking

### ISSUE THREAD

**Issue by rider8581** [deepmipt/DeepPavlov#1445]
https://github.com/deepmipt/DeepPavlov/blob/master/docs/features/models/entity_linking.rst

I was reading this and got how to run entity linking.

But could you give me more detailed description of output meaning?

python -m deeppavlov interact entity_linking_eng -d
>>> The city stands on the River Thames in the south-east of England, at the head of its 50-mile (80 km) estuary leading to the North Sea.
>>> (['the river thames', 'the north sea', 'england'], [[4, 5, 6], [30, 31, 32], [13]], ['Q19686', 'Q1693', 'Q21'])

What does this output mean?

**Comment by IgnatovFedor** [comment]
Hi, @rider8581 
Firs list is detected entities substrings, second - detected entities positions, third is detected entities ids in wikidata (https://www.wikidata.org/wiki/Q19686 for `the river thames` etc)
