### ISSUE TITLE
Support of the Transformers>=4.0.0 version library

### ISSUE THREAD

**Issue by Piteryo** [deepmipt/DeepPavlov#1454]
**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
latest
**Python version**:
3.6
**Operating system** (ubuntu linux, windows, ...):
ubuntu
**Issue**:
Starting from version 4.0.0 the interface of Transformers library was changed and a dictionary is returned as model output. That is why issue #1355 cannot be fixed by changing PyTorch version. It can be fixed as easy as adding an additional argument `return_dict=False` to model call at [this](https://github.com/deepmipt/DeepPavlov/blob/6c8f8924628f40eab3ce6301916dc6fbd38869f0/deeppavlov/models/embedders/transformers_embedder.py#L73) line. But it breaks the support of the previous Transformers library version.

Please add the version check for this library or something like this because this issue is the only one that stops from using the latest Transformers library versions.

**Comment by danielkornev** [comment]
In plans for v0.16 ) We hope to ship in mid-July

**Comment by IgnatovFedor** [comment]
Newer transformers are available in the latest release 0.17.2 and in the pre-release 1.0.0rc0.
