### ISSUE TITLE
Any plan to upgrade tf to 2x?

### ISSUE THREAD

**Issue by jeffzhengye** [deepmipt/DeepPavlov#1457]
as the title said.

**Comment by danielkornev** [comment]
No, our plan is to migrate to PyTorch

**Comment by novotnej** [comment]
Is the plan in motion? We are using DeepPavlov for a project, and it is currently seriously breaking our dependencies with numpy==1.18 and tf 1.15 - we need to maintain two environments with different versions, which is a disaster waiting to happen...

**Comment by danielkornev** [comment]
Hi! Our plan is to migrate from TF 1.x to PyTorch, and abandon TF 1.x entirely. We plan to bring the majority of updates to our models in our upcoming releases, 0.16 (July 2021) and 0.17 (August/September 2021), respectively.

Thanks!

**Comment by IgnatovFedor** [comment]
Hi, @novotnej 
[1.0.0rc0](https://github.com/deepmipt/DeepPavlov/releases/tag/1.0.0rc0) pre-release with more free requirements is already available.
