### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by alyferryhalo** [deepmipt/DeepPavlov#1470]
**DeepPavlov version**: 0.15.0

**Python version**: 3.6 (Google Colaboratory)

**Operating system**: Ubuntu Linux 20.04 / Google Colaboratory

**Issue**: IndexError: index 0 is out of bounds for axis 0 with size 0

**Command that led to error**:
```
from deeppavlov import configs, build_model
ner_model = build_model(configs.ner.ner_ontonotes_bert_mult, download=True)
for d in data:
  ner_model([d])
```

The `data` is python list of strings that was created from one pandas dataframe column. It contains Russian text.

**Error (including full traceback)**:
```
IndexError                                Traceback (most recent call last)

<ipython-input-13-5235083b55ae> in <module>()
      1 for i in new_big_list:
----> 2   ner_model([i])

6 frames

/usr/local/lib/python3.7/dist-packages/tensorflow_core/contrib/crf/python/ops/crf.py in viterbi_decode(score, transition_params)
    406   trellis = np.zeros_like(score)
    407   backpointers = np.zeros_like(score, dtype=np.int32)
--> 408   trellis[0] = score[0]
    409 
    410   for t in range(1, score.shape[0]):

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by Ihab-Asaad** [comment]
I ran the following in colab:
!pip install DeepPavlov==0.15.0
!python -m deeppavlov install ner_ontonotes_bert_mult

from deeppavlov import configs, build_model
data = ['Привет','Добро пожаловать в Россию','МФТИ']
ner_model = build_model(configs.ner.ner_ontonotes_bert_mult, download=True)
for d in data:
  print(ner_model([d]))
print(ner_model(data))

output:
[[['Привет']], [['O']]]
[[['Добро', 'пожаловать', 'в', 'Россию']], [['O', 'O', 'O', 'B-GPE']]]
[[['МФТИ']], [['B-ORG']]]
[[['Привет'], ['Добро', 'пожаловать', 'в', 'Россию'], ['МФТИ']], [['O'], ['O', 'O', 'O', 'B-GPE'], ['B-ORG']]]

Maybe there's a problem with your data.
