### ISSUE TITLE
Performance issue in the definition of CudnnGRU, deeppavlov/models/squad/utils.py(P1)

### ISSUE THREAD

**Issue by DLPerf** [deepmipt/DeepPavlov#1476]
Hello, I found a performance issue in the difinition of `CudnnGRU`, deeppavlov/models/squad/utils.py, [tf.expand_dims](https://github.com/deepmipt/DeepPavlov/blob/d60649aaf26e0fc5f5c9850a76c41701410ec77c/deeppavlov/models/squad/utils.py#L33) will be called repeately during the program execution, resulting in reduced efficiency. So I think `init_bw ` should be created before the loop.

The same issue exists in [here](https://github.com/deepmipt/DeepPavlov/blob/d60649aaf26e0fc5f5c9850a76c41701410ec77c/deeppavlov/models/squad/utils.py#L84).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
@IgnatovFedor Hi, friend, could you deal with the issue asap?

**Comment by IgnatovFedor** [comment]
Last TF components were removed in #1574. After 1.0.0 release only pytorch-based NN models will remain in the library.
