### ISSUE TITLE
How to show more results? QA

### ISSUE THREAD

**Issue by decadance-dance** [deepmipt/DeepPavlov#1482]
I use 
`model = build_model(configs.squad.squad_ru_rubert_infer, load_trained=True)`
and for any context and question, I get only one top 1 result.
`model(["A beautiful evening blue house stood on the mountain."], ["what was the house like?"])`
`[['ening blue house st'], [14], [2.080101490020752]]`
I need to get more results.

**Comment by dmitrijeuseew** [comment]
Current version of Reading Comprehension model does not have an option to get several outputs.
ODQA model https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/odqa/ru_odqa_infer_wiki_rubert.json has an option to get several candidate passages for a questions and several candidate answers in these passages.
