### ISSUE TITLE
Add support for Sequence Labeling & Q&A from original article for KBQA migration to PyTorch

### ISSUE THREAD

**Issue by danielkornev** [deepmipt/DeepPavlov#1486]
Moved to internal Trello

**Comment by imsiddhant07** [comment]
Hi @danielkornev @dimakarp1996 the issue seems quite interesting, was wondering if dimakarp is still working on this. If not would like to take it up :)

**Comment by danielkornev** [comment]
Hi Siddhant,

Thanks for reaching out!

@***@***.******@***.***> are you or @vasily (via Google ***@***.***> still on it?

Best,
Daniel

**Comment by dimakarp1996** [comment]
Sequence labeling for PAL-BERT is supported in the branch pal-bert+ner, there is a PR on this issue. Q&A is also implemented in pal-bert+ner+qa, but not tested yet.
