### ISSUE TITLE
 ModuleNotFoundError: No module named 'deeppavlov.skills.pattern_matching_skill'

### ISSUE THREAD

**Issue by sandeeppandey456** [deepmipt/DeepPavlov#1496]
I have done a fresh installation of Deeppavlov in a new conda environment having Tensorflow 1.15.2.

I am trying to run the "hello_bot" tutorial program in spyder . However, it throws this error on the first line itself

`from deeppavlov.skills.pattern_matching_skill import PatternMatchingSkill`

Please help

**Comment by Sachit71** [comment]
try doing this 
`pip install deeppavlov==0.4.0`
the tutorial has become obsolete after the newer versions

**Comment by IgnatovFedor** [comment]
`pattern_matching_skill` was removed in 0.7.0.
