### ISSUE TITLE
Проблема с анализом тональности текста

### ISSUE THREAD

**Issue by Tulpa00** [deepmipt/DeepPavlov#1514]
Версия 0.17.2
Google Colab

Нашла на форуме код для анализа тональности текста
```
!pip install deeppavlov
!python -m deeppavlov install rusentiment_elmo_twitter_cnn

from deeppavlov import build_model

model = build_model('rusentiment_elmo_twitter_cnn', download=True)

model(['Мне фильм показался скучным и затянутым.'])
```
Пару месяцев назад всё работала исправно, сегодня пришлось вернуться к проекту, но он начал выдавать ошибку

`AttributeError: module 'tensorflow' has no attribute 'ConfigProto'`

Я не очень опытна в этом, не могли бы вы мне помочь?

**Comment by dimakarp1996** [comment]
@Tulpa00 Баг не воспроизводится.
https://colab.research.google.com/drive/1GjUCmJNZkw6BsHOaR8TuyPUnFSiFhYCY?usp=sharing
