### ISSUE TITLE
Use tensorflow instead of tensorflow-gpu

### ISSUE THREAD

**Issue by sld** [deepmipt/DeepPavlov#153]
Version 0.0.1 has tensorflow in requirements.txt.
0.0.3 now uses tensorflow-gpu.

It is common use case to write and test model in laptop without GPU and then deploy it to server with GPU. 
So it will be great to support both CPU and GPU modes in the DeepPavlov lib.

`python setup.py develop` outputs
```
Searching for tensorflow-gpu==1.4.0
Reading https://pypi.python.org/simple/tensorflow-gpu/
No local packages or working download links found for tensorflow-gpu==1.4.0
error: Could not find suitable distribution for Requirement.parse('tensorflow-gpu==1.4.0')
```

pip 9.0.3
Python 3.6.1

**Comment by seliverstov** [comment]
We added tensorflow-gpu to requirements because the SQuAD model does not work on the CPU.
We will consider your notes about using DP on laptops and maybe return CPU version of TF and add additional notes for SQuAD model to README

**Comment by seliverstov** [comment]
We decided to switch back to CPU version of Tensorflow as default installation option and add check GPU availability for models like SQuAD. Thank you for your comment.
