### ISSUE TITLE
Squad BERT model not handling multiple requests with gunicorn

### ISSUE THREAD

**Issue by raghavsuriya** [deepmipt/DeepPavlov#1538]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

Please enter all the information below, otherwise your issue may be closed without a warning. 

**DeepPavlov version** (you can look it up by running `pip show deeppavlov`):
0.14.0

**Python version**:
3.7.7

**Operating system** (ubuntu linux, windows, ...):
red hat linux 

**Issue**:
I am running the ODQA model of deeppavlov in production with flask. Whenever we have a request coming in , the request is blocked and is run as a single thread when using squad_torch_bert. For example the request waits for the previous request to complete the BERT squad reader and then it gets processed. I am not sure if I am missing anything or is there any production flag I am missing to include. 

**Content or a name of a configuration file**:
```
squad_torch_bert.json
```

**Command that led to error**:
```
I build the model at the bootstrap time using 
 self.model = build_model(config=model_config_path, download=False)
And then at the inference time I do this: 
reader_output = self.model(context_list, query_list)
```

**Error (including full traceback)**:
```

```

**Comment by vaskonov** [comment]
@raghavsuriya Thank you very much for your issue, currently `riseapi` process requests in a single thread mode. Maybe we will support multi thread mode in future.
