### ISSUE TITLE
Is there any way to achieve mult-lingual intent classification

### ISSUE THREAD

**Issue by SAIVENKATARAJU** [deepmipt/DeepPavlov#1542]
Want to contribute to DeepPavlov? Please read the [contributing guideline](http://docs.deeppavlov.ai/en/master/devguides/contribution_guide.html) first.

**What problem are we trying to solve?**:
```
I am new to this repo. I am trying to solve the multi-lingual intent classifications for one of my chatbots. is there any way to achieve the same?
```

**Comment by vaskonov** [comment]
Hey @SAIVENKATARAJU ,

Could you describe your task in more details? Do you have specific intent dataset in mind?
We have a bunch of configs for text classification, for example, you can use `insults_kaggle_bert_torch`.
Define `TRANSFORMER` variable as `bert-base-multilingual-cased` and train the model with your intent dataset.

**Comment by vaskonov** [comment]
@SAIVENKATARAJU I see, do you use some specific intent dataset, what set of intents you are interested in?
