### ISSUE TITLE
Ошибка обучения модели в навыке Frequently Asked Questions (FAQ)

### ISSUE THREAD

**Issue by HeavyPunk** [deepmipt/DeepPavlov#1551]
**DeepPavlov version** : deeppavlov 0.17.2

**Python version**: Python 3.7.4

**Operating system** Ubuntu linux

**Issue**: 
Привет! Воспользовался инструкцией по быстрому старту в навыке [вот](http://docs.deeppavlov.ai/en/master/features/skills/faq.html).
Установил python 3.7.4 в виртуальное окружение, установил в нём deeppavlov версии 0.17.2 и запустил следующий код:
```
from deeppavlov import build_model, configs

faq = build_model(configs.faq.tfidf_logreg_en_faq, download=True)

result = faq(['What is your open hours?'])
print(result)
```
Получаю следующий вывод:
```
INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 203: Loading model sklearn.feature_extraction.text:TfidfVectorizer from /home/blackpoint/.deeppavlov/models/faq/mipt/en_mipt_faq_v4/tfidf.pkl
INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 210: Model sklearn.feature_extraction.textTfidfVectorizer loaded  with parameters
WARNING in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 216: Fitting of loaded model can not be continued. Model can be fitted from scratch.If one needs to continue fitting, please, look at `warm_start` parameter
INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 115: [loading vocabulary from /home/user/.deeppavlov/models/faq/mipt/en_mipt_faq_v4/en_mipt_answers.dict]
INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 203: Loading model sklearn.linear_model:LogisticRegression from /home/blackpoint/.deeppavlov/models/faq/mipt/en_mipt_faq_v4/logreg.pkl
INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 210: Model sklearn.linear_model.logisticLogisticRegression loaded  with parameters
WARNING in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 216: Fitting of loaded model can not be continued. Model can be fitted from scratch.If one needs to continue fitting, please, look at `warm_start` parameter
[['A program taught in Russian will cost you 250,000 rubles per year. The fees on English-taught programs are higher, at 400,000 rubles per year.'], [[0.012554319580681459, 0.05530520048179519, 0.15909443059072864, 0.01647692304580628, 0.19257728490480125, 0.04304321554817387, 0.0927372005467117, 0.26208660444861587, 0.0859539299878814, 0.010506932996152626, 0.050110662122245936, 0.008866932711861935, 0.010686363034543999]]]
```

Попробовал запустить навык в вашем контейнере [deeppavlov/jupyter](https://hub.docker.com/r/deeppavlov/jupyter)

В контейнере хотел запустить код из ноутбука DeepPavlov/examples/yandex_faq_ru.ipynb, но на этапе
```
from deeppavlov.contrib.skills.similarity_matching_skill import SimilarityMatchingSkill

faq = SimilarityMatchingSkill(data_path = 'http://files.deeppavlov.ai/faq/dataset.csv',
                              x_col_name = 'Question', 
                              y_col_name = 'Answer',
                              save_load_path = './model',
                              config_type = 'tfidf_autofaq',
                              train = True)
```

Получил ту же ошибку при попытке обучения
```
2022-04-11 17:51:00.301 INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 202: Loading model sklearn.feature_extraction.text:TfidfVectorizer from /base/DeepPavlov/examples/model/vectorizer/tfidf_vectorizer_ruwiki.pkl
2022-04-11 17:51:02.635 INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 209: Model sklearn.feature_extraction.textTfidfVectorizer loaded  with parameters
2022-04-11 17:51:02.636 WARNING in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 215: Fitting of loaded model can not be continued. Model can be fitted from scratch.If one needs to continue fitting, please, look at `warm_start` parameter
2022-04-11 17:51:02.651 INFO in 'deeppavlov.models.sklearn.sklearn_component'['sklearn_component'] at line 108: Fitting model sklearn.feature_extraction.textTfidfVectorizer

```

Помогите разобраться баг ли это или я что-то делаю не так)

**Comment by alexunderch** [comment]
Здравствуйте!

Тот код, который Вы пытаетесь запустить, немного устарел в связи с усовершенствованием библиотеки, а именно не поддерживается продолжение обучения уже `pretrained`-модели.

У данной проблемы существует следующее решение: Вы можете удалить `pretrained`-модели и запустить обучение заново (см. подробнее [community forum](https://forum.deeppavlov.ai/t/fitting-of-loaded-faq-model-can-not-be-continued/277)). Однако, при Вашем желании, Вы можете конкретезировать решаемую задачу, и мы постараемся Вам предложить решение, более подходящее со стороны последних релизов библиотеки.

Sincerely,
Alexander.

**Comment by HeavyPunk** [comment]
Спасибо!)
Моя задача такова:
Есть у меня csv-файл с таблицей из столбцов Question Answer, хочу натренировать модель на этом файле (в файле есть вопросы как на русском, так и на английском языках)
При этом, файл будет периодически меняться и хочется перетеренировывать модель на новых данных
Как сейчас deeppavlov решает такой кейс?

**Comment by alexunderch** [comment]
Здравствуйте!

Спасибо за подробную постановку вопроса. `DeepPavlov` хорошо подходит для решение Вашей задачи, попробуйте воспользоваться данными ресурсами:
1. [intent recognition and question answering with DeepPavlov](https://medium.com/deeppavlov/simple-intent-recognition-and-question-answering-with-deeppavlov-c54ccf5339a9)
2. [text classification using DeepPavlov](https://medium.com/deeppavlov/text-classification-using-deeppavlov-library-with-pytorch-and-transformers-f14db5528821)
3. Вы всегда вольны изменять под себя существующие конфигурации, явно запуская
```
python -m deeppavlov train path/to/your/config.json
```

Удачи в дальнейшем использовании.
Sincerely,
Alex
