### ISSUE TITLE
Cant control the number of val and log epochs

### ISSUE THREAD

**Issue by oserikov** [deepmipt/DeepPavlov#1559]
I'm using the pypi version of deeppavlov in google colab without GPU.

When trying to run the `ner_few_shot_ru_simulate` experiment, scary message appears in logs. Am I unable to set the number of val and log epochs indeed?

```python3
from deeppavlov import configs, train_model
ner_model = train_model(configs.ner.ner_few_shot_ru_simulate, download=True)
```

`2022-04-30 07:59:50.502 INFO in 'deeppavlov.core.trainers.fit_trainer'['fit_trainer'] at line 68: FitTrainer got additional init parameters ['epochs', 'validation_patience', 'val_every_n_epochs', 'log_every_n_epochs'] that will be ignored:`

**Comment by IgnatovFedor** [comment]
`fit_trainer` doesn't support val and log epoch indeed. These parameters are supported by `nn_trainer` and `torch_trainer`.
