### ISSUE TITLE
How to write the component without cloning and patching the whole DeepPavlov repo?

### ISSUE THREAD

**Issue by sld** [deepmipt/DeepPavlov#159]
Hi!

I'd like to write my own component in my private project. 

It seems like I should clone the repo then patch it:
1. By writing write my own dataset readers, iterators,... and putting them into DeepPavlov folder.
2. Then I should put necessary imports into https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/__init__.py.
3. In the end I should write my config.json and run `python -m deeppavlov...`

Can I write separate component independently without patching source code of DeepPavlov?

**Comment by seliverstov** [comment]
The only reason we write the imports in the `__init__` file is to ensure that all standard components are registered through the decorator @register. 
```python
@register('ner')
class NER(TFModel):
```
It is not necessary to put your component import in this `__init__` file, you only need to ensure that the appropriate decorator is called before the component is used through it code name in pipeline.

**Comment by sld** [comment]
I am running next command:
`python -m deeppavlov.deep interact deeppavlov/configs/custom_config_component.json`

How can I register custom component's dataset readers, iterators, model without putting to `__init__.py` of DeepPavlov repo?

It seems that I should write my own fork of deeppavlov.deep interact module.

**Comment by seliverstov** [comment]
`deeppavlov.deep interact` module is pretty simple. You can write two line of code to interact with your model directly in your own python script:
```python
from deeppavlov.core.commands.infer import interact_model
interact_model(pipeline_config_path)
```
or train your model:
```python
from deeppavlov.core.commands.train import train_model_from_config
train_model_from_config(pipeline_config_path)
```

**Comment by sshivaji** [comment]
This should be in the FAQ as its a very common need!
