### ISSUE TITLE
go_bot_all pretrained model not found

### ISSUE THREAD

**Issue by mlearning** [deepmipt/DeepPavlov#169]
Hi,

I was trying to test the go_bot full model with the following command:

      python3 deep.py interact configs/go_bot/gobot_dstc2_all.json

And noticed that the **download/go_bot_all**  directory is empty (PS: I've executed "python3 -m deeppavlov.download -all" and see all other existing model files).  

As a result, the GoalOrientedBotNetwork.\__init\__ method couldn't find the "**go_bot_all/model**" as specified in the **gobot_dstc2_all.json** config file. 

Could you please upload the pretrained full model?

Thanks

**Comment by vikmary** [comment]
Hi @mlearning!

We haven't planned to upload pretrained models for all provided configs (cause it takes time to support them).

`python3 -m deeppavlov.download -all` provides all the necessary data for model training:
```bash
python3 deep.py train configs/go_bot/gobot_dstc2_all.json
```
and takes 1-3 hours on a single 1080ti graphic card.

(As you probably noticed, you can still interact with pretrained model from [`configs/go_bot/gobot_dstc2.json`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/go_bot/gobot_dstc2.json))
