### ISSUE TITLE
Go_bot return #name

### ISSUE THREAD

**Issue by fjfo** [deepmipt/DeepPavlov#193]
I interact to go_bot in config: configs/go_bot/gobot_dstc2.json
but it alway return some kind of: #name, #addrs,...
like this:
`x::i want some food
['i want some food']
>> I am sorry but there is no **#food** restaurant that matches your request.
x::i want sea food 
['i want sea food']
>> What part of town do you have in mind?
x::north
['north']
>> Would you like something in the cheap, moderate, or expensive price range?
x::cheap
['cheap']
>> **#name** is a nice place in the north of town serving tasty seafood food.
x::ok thank
['ok thank']
>> You are welcome!
x::exit`

How can I make bot returning the suggested information instead of #name or #food?

Thanks.

**Comment by vikmary** [comment]
Hi, @fjfo 
We will support such configuration via configs in the next release.
For now you can modify [deeppavlov/skills/go_bot/bot.py](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/skills/go_bot/bot.py) in `reset()` method setting `db_result` with desired values.
For example,
```python
self.db_result = {
    "addr": "Sobina Square, 1/4",
    "area": "north",
    "food": "russian",
    "phone": "+7(965)173-37-33",
    "postcode": "141700",
    "pricerange": "cheap"
}
```

**Comment by fjfo** [comment]
got it,
Thank @vikmary

**Comment by fjfo** [comment]
hi @vikmary ,
Is that the same issue in seq2seq_go_bot?
I interact with seq2seq_go_bot and get something like:

"**home_poi_type** at **home_address** is **home_distance** away."

Thank,

**Comment by anyuhang01** [comment]
Is there any way not to hard code the db_result? I would expect the bot sends out requests with parameters such as food type and location and gets responses from external db, and then db_result will be updated. Really appreciate it if similar workflow is possible.

**Comment by vikmary** [comment]
@fjfo Yes, the same issue with database not being present during interaction occurs. seq2seq_go_bot is now in active development, and the fix will also be added, but in later releases (when architecture and configs stabilize).

**Comment by vikmary** [comment]
@anyuhang01 Such feature is currently not available out of the box. 
You can modify `_infer()` in [`deeppavlov/skills/go_bot/bot.py`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/skills/go_bot/bot.py) so that `db_result` variable is set to any value (to result of mongo database request, for example), then it will be used to encode context and generate response during interaction.

**Comment by Jertol** [comment]
@vikmary Would you have any visibility on when database querying will be integrated into go_bot? Thanks!

**Comment by vikmary** [comment]
@Jertol It will be in [the nearest 0.0.4 release](https://github.com/deepmipt/DeepPavlov/releases/tag/untagged-eb9ac70bb41e3a069f91).
