### ISSUE TITLE
Where is the Neural Model for Intent Classification defined?

### ISSUE THREAD

**Issue by mfxss** [deepmipt/DeepPavlov#200]
I tried to read your code, but still can not find it. It's so hard.

**Comment by vikmary** [comment]
@mfxss [deeppavlov/models/classifiers/intents/intent_model.py](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/models/classifiers/intents/intent_model.py)

**Comment by mfxss** [comment]
@vikmary I noticed that file. But when I am training in this way"python deep.py train configs/intents/intents_snips.json", it seems that this file is never used. So how it works?

**Comment by yoptar** [comment]
@mfxss notice the `"name": "intent_model"` block in the config and `@register('intent_model')` in the class file. Imports are done in https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/__init__.py
