### ISSUE TITLE
intent classifier example for Russian language

### ISSUE THREAD

**Issue by Mega4alik** [deepmipt/DeepPavlov#213]
Hi, 
I could not find any examples for Russian language 

If you could add one for intent classification problem, that would be a great help

thank you

**Comment by dilyararimovna** [comment]
Hello! 
Sorry for delay. Now we have add sentiment model in Russian language for Twitter mokoron dataset (http://study.mokoron.com/) that is also classification task.
Feel free to ask questions about it.
