### ISSUE TITLE
Is Mac OSX supported?

### ISSUE THREAD

**Issue by pboz** [deepmipt/DeepPavlov#214]
Hi,

I know the readme says only Linux is supported, but since OSX is a Unix based operating system, it's unclear to me if it should be supported as well.

Thanks,

Patrick

**Comment by Mega4alik** [comment]
Yes, I was able to run it on OSX python3

**Comment by pboz** [comment]
I was able to get it running, but not with GPU, so the answer module wasn't available

**Comment by vnikk** [comment]
> Yes, I was able to run it on OSX python3

Did you have to solve any issues along the installation?
