### ISSUE TITLE
Database connection failing with Telegram API

### ISSUE THREAD

**Issue by Jertol** [deepmipt/DeepPavlov#250]
Hi,

When using pre-trained `gobot_dstc2_best.json` with `interactbot`, I receive the following error:

> `sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4321387392 and this is thread id 123145327210496`

However, it does work using `interact`. Would you know what is the problem with the Telegram API?

Thanks!

**Comment by vikmary** [comment]
fixed https://github.com/deepmipt/DeepPavlov/commit/d8ff727b523c12da68e0a499ccea55f72b6fa669
