### ISSUE TITLE
How seq2seq_go_bot model was created?

### ISSUE THREAD

**Issue by tomferreira** [deepmipt/DeepPavlov#281]
Hi,

This is a very promising project, but I'm having troubles in understand how the models was created, e.g. seq2seq_go_bot?

What train/test/validation data was used?
How the model was built?

Thanks!

**Comment by vikmary** [comment]
Hi, thanks for the feedback.

Concerning `seq2seq_go_bot`: the documentation is still not finished, and the model is being actively improved. (Within a month a much better model is being released.)

Train/valid/test data is used from [here](https://nlp.stanford.edu/blog/a-new-multi-turn-multi-domain-task-oriented-dialogue-dataset/). It contains dialogues from three distinct domains:  calendar scheduling, weather information retrieval, and point-of-interest navigation.

The model is a simplified version of [model from the same guys](https://arxiv.org/abs/1705.05414).

Please wait till we update the details of implementation.

**Comment by tomferreira** [comment]
Thanks!
