### ISSUE TITLE
Problem with fastText

### ISSUE THREAD

**Issue by Sneg42** [deepmipt/DeepPavlov#283]
i have issue when start "python -m deeppavlov interactbot deeppavlov/configs/intents/intents_snips.json -d -t 597656151:AAGF3C9T8U8T7iyEIY8_u1t_u9Qv1_LQKUo"
AttributeError: module 'fastText' has no attribute 'load_model'
i use Windows 10, anaconda

**Comment by Sneg42** [comment]
WSL help me with all problem

**Comment by vikmary** [comment]
Have you solved the issue?

We don't officially support Windows and don't test DeepPavlov on it.

**Comment by Sneg42** [comment]
Yes, i use Window System fo Linux and set deeppavlov from zero.

**Comment by OVolkova** [comment]
I have the same problem with Ubuntu 18.04, no anaconda

**Comment by Sneg42** [comment]
@OVolkova try this:
$ git clone https://github.com/facebookresearch/fastText.git
$ cd fastText
$ pip install

**Comment by yoptar** [comment]
Should be resolved as of #326. Deeppavlov itself no longer requires fastText, requirements for specific configs can be installed with `python -m deeppavlov install <path to config>`

**Comment by nwpuIT** [comment]
when use pip install git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22  
using import fastText
or pip install fasttext
using import fasttext

**Comment by nwpuIT** [comment]
> @OVolkova try this:
> $ git clone https://github.com/facebookresearch/fastText.git
> $ cd fastText
> $ pip install

another method using directly : pip install git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22

**Comment by KhondokerIslam** [comment]
Neither `load` or `load_model` attribute available in fastText. Using google colab with `fasttext==0.9.2`. Hoping for a quick fix.

**Comment by goodguyerik** [comment]
Same here, 
AttributeError: module 'fastText' has no attribute 'load_model'
