### ISSUE TITLE
Data to train NER for dstc2

### ISSUE THREAD

**Issue by Jertol** [deepmipt/DeepPavlov#296]
Hi,

I am working with go_bot, and I cannot find the data used to train ner_dstc2. According to the [documentation](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/ner/README.md), I am supposed to find three files (`train.txt`, `valid.txt`, and `test.txt`) containing tagged user sentences. Where could I find them?

Thanks!

**Comment by mu-arkhipov** [comment]
These files are constructed on the go from the data produced by [deeppavlov.dataset_readers.dstc2_reader](https://github.com/deepmipt/DeepPavlov/blob/1da5fd31adb15f3b94c965368ad3b1d78c2b7981/deeppavlov/dataset_readers/dstc2_reader.py#L33) using [deeppavlov/dataset_iterators/dstc2_ner_iterator](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_iterators/dstc2_ner_iterator.py).
However you can download those files from [here](lnsigo.mipt.ru/export/datasets/dstc2_ner.tar.gz)

**Comment by mu-arkhipov** [comment]
The data for NER training were constructed partially automatically and partially by manually collected paraphrases. Please, have a look at the [code](https://github.com/deepmipt/DeepPavlov/blob/1da5fd31adb15f3b94c965368ad3b1d78c2b7981/deeppavlov/dataset_iterators/dstc2_ner_iterator.py#L77). This coder relies on the following dictionary:
lnsigo.mipt.ru/export/datasets/dstc_slot_vals.json

**Comment by vikmary** [comment]
Hi, @Jertol
I was the one responsible for transforming the original DSTC2 to the final format from deeppavlov.
I wrote a script to do it, but, unfortunately, i don't have it now, so you should transform the data by yourself.
