### ISSUE TITLE
Попробуйте

### ISSUE THREAD

**Issue by MacJieHokNSU** [deepmipt/DeepPavlov#30]
Вместо наложения маски на результат, добавить при обучении в функцию ошибки расстояние между вектором с маской и без.

**Comment by vikmary** [comment]
Есть ли пример, где добавление такой составляющей в функцию ошибки, дало прирост качества?

**Comment by MacJieHokNSU** [comment]
Примера сейчас нет, но я пробовал эту модель, и основная проблема была в том, что сама маска в обучении не участвует (почти, если не ошибаюсь, там влияние маски учитывается через предыдущее действие). 
Протестируйте. Самому интересно. Должно давать эффект.
Расстояние (косинусное, например), между выходным вектором и его вариантом, умноженным на маску. Лучше с понижающим параметром (a=0.01, например). Добавить к ошибке в качестве регуляризации.

**Comment by vikmary** [comment]
Да, в текущей реализации маска учитывается через предыдущее действие; при инфере форсится домножением.
Идея интересная, подумаем над тем, чтобы реализовать
Если оформите в виде pull-request, потесчу и рассмотрю мёрж
