### ISSUE TITLE
Please tell me about the training model

### ISSUE THREAD

**Issue by s-kun** [deepmipt/DeepPavlov#310]
Hello!
An error occurred when running Train on DSTC - 2 written in Neural Model for Classification.

python deep.py train configs / intents / intents_ dstc2.json

   File "deep.py", line 46
     def find_config (pipeline_config_path: str):
                                         ^
SyntaxError: invalid syntax

I do not know the cause, could you tell me

**Comment by yoptar** [comment]
Hi!
Looks like you're trying to run it with python2, but DeppPavlov only supports python3.6
