### ISSUE TITLE
setup.py develop

### ISSUE THREAD

**Issue by Tony2h** [deepmipt/DeepPavlov#316]
I created my env with conda, py3.6.
When I run "python setup.py develop", after all the requirements are satisfied, this happens:

running develop
running egg_info
creating deeppavlov.egg-info
error: could not create 'deeppavlov.egg-info': Permission denied

how can i solve this problem?

**Comment by Tony2h** [comment]
I didn't git in my env. I clone DeepPavlov before i create the env. Is that the reason?

**Comment by yoptar** [comment]
Can you provide the whole output? Somewhere in the message there should be more on what permissions are missing.

**Comment by Tony2h** [comment]
I run 'python setup.py develop', and there are many raw begin with 'requirement already satisfied....'
then I get this four output and below them there is another ...@...$.

I delete the DeepPavlov and git clone it again in my env. And run 'python setup.py develop' successfully. There is no problem right now. THX.
