### ISSUE TITLE
tensorflow 1.8

### ISSUE THREAD

**Issue by Tony2h** [deepmipt/DeepPavlov#320]
I want to quick install and it begin to catch tensorflow==1.8.0. But the speed is too low to finish. It always stop during the download.
can I download tensorflow 1.8 first and then install the pre-trained models?
And do i need to download cuda 9? If I want to use my GPU, which edition of cudnn should I use?
I know that before the recent update I should use cudnn 6.0. What about now?

**Comment by yoptar** [comment]
If you're using the latest (0.0.6) version of deeppavlov, you can install `tensorflow-gpu==1.8.0` beforehand, yes. You will also need cuda 9.0 installed. We tested our models on cudnn 7.
