### ISSUE TITLE
hello_bot 

### ISSUE THREAD

**Issue by rachhitgarg** [deepmipt/DeepPavlov#331]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3bf7b8b89fc3> in <module>()
----> 1 from deeppavlov.skills.pattern_matching_skill import PatternMatchingSkill

ModuleNotFoundError: No module named 'deeppavlov'

**Comment by yoptar** [comment]
Hi!
Did you install deeppavlov before running the notebook? And did you run it from the same environment that deeppavlov was installed to?

**Comment by martian-coder** [comment]
Run 
`
from deeppavlov.deprecated.skills.pattern_matching_skill import PatternMatchingSkill
`
