### ISSUE TITLE
Unified embeddings for all components

### ISSUE THREAD

**Issue by bond005** [deepmipt/DeepPavlov#333]
At the present each component (NER, classification component and others) uses its own embeddings for words. For example, `dstc2_fastText_model.bin` is used for intent classification, `glove.6B.100d.txt` is used for named entity recognition, etc. It is inconveniently in terms of architecture and memory utilization. I think that unified word embeddings must be used for all models and components processing texts in a one language.

**Comment by yoptar** [comment]
We're probably not going to do that.
Existing configurations are built to get the best result we could for separate tasks.
