### ISSUE TITLE
No load path is set for GoalOrientedBot!

### ISSUE THREAD

**Issue by luosmart** [deepmipt/DeepPavlov#336]
I run goal-oriented bot with console interface and my command is 
```
python -m deeppavlov interact deeppavlov/configs/go_bot/gobot_dstc2.json -d
```
2018-07-24 11:13:27.417 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 56: No load path is set for GoalOrientedBot!

tensorflow===1.14.0

**Comment by vikmary** [comment]
That's allright. `GoalOrientedBot` doesn't have any savable weights, only `GoalOrientedBotNetwork` does.

**Comment by vikmary** [comment]
To delete the WARNING I'll move "load_path" from `GoalOrientedBotNetwork` to `GoalOrientedBot`.
You can track hotfix/load-path-to-GoalOrientedBot branch for that.

**Comment by luosmart** [comment]
@vikmary Thanks.

**Comment by vikmary** [comment]
Resolved in https://github.com/deepmipt/DeepPavlov/pull/449.
