### ISSUE TITLE
"deeppavlov" module doesn't install on conda environment anymore

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#342]
Steps to reproduce:

0. Checkout to `dev` branch.

1. Create a new conda environment:
```
conda create -n deeppavlov python==3.6
```
2. Activate env:
```
source activate deeppavlov
```
3. Run deeppavlov installation:
```
python setup.py
```
Here the expected behavior is that `deeppavlov` will be installed as a package.
4. Check installed packages:
```
conda list
```
As a result, no module `deeppavlov` exists.

**Comment by yoptar** [comment]
`python setup.py install` or `python setup.py develop` maybe?
