### ISSUE TITLE
does it support english and chinese?

### ISSUE THREAD

**Issue by loveJasmine** [deepmipt/DeepPavlov#343]

**Comment by xxllp** [comment]
@DeepPavlov ，does you have the example ?

**Comment by 15950552800** [comment]
How to use Chinese?

**Comment by yoptar** [comment]
Hi @15950552800,
Are there any specific tasks that you want to use DeepPavlov for? You can take a look at [a demo for our multilingual question answering model](https://demo.ipavlov.ai/#/mu/textqa), it should support Chinese.
