### ISSUE TITLE
May I ask a simple question

### ISSUE THREAD

**Issue by SakurasouID** [deepmipt/DeepPavlov#347]
I meet the statement like "def train_evaluate_model_from_config(config: [str, Path, dict], to_train=True, to_validate=True) -> None" for the first time. Could you please tell me what "config: [str, Path, dict]" and "-> None" mean?

**Comment by yoptar** [comment]
It means that `config` argument is expected to be one of `str`, `pathlib.Path` or `dict` and that this function returns nothing.
You can read more on this in https://www.python.org/dev/peps/pep-0483/
