### ISSUE TITLE
Deeppavlov_chitchat tutorial also needs tf.estimator examples

### ISSUE THREAD

**Issue by tgchoi** [deepmipt/DeepPavlov#351]
While I'm reading deeppavlov tutorial jupyter notebook, I guess there's no tensorflow model implementation with tf.estimator. 
I want to tackle this issue and wish I could contribute on this code with tf.estimator if the contributors allow.

**Comment by DeepPavlov** [comment]
Hi @tgchoi ! Thank you for your interest in our library. It would be very nice to have tf.estimator example in our repo.  We will be happy to have your contribution in our library. Looking forward for your pull request!
