### ISSUE TITLE
Directory for downloaded resources

### ISSUE THREAD

**Issue by ismaslov** [deepmipt/DeepPavlov#363]
При использовании функции
`from deeppavlov.download import deep_download` 
загружаемые файлы попадают в директорию относительно текущего местоположения файла **download.py**.

Хотелось бы отвязаться от местоположения **download.py** и более гибко настраивать путь для скачиваемых ресурсов, чтобы скачиваемые ресурсы не попадали в директорию с библиотеками окружения питона.

**Comment by yoptar** [comment]
Решено в #371
