### ISSUE TITLE
deeppavlov_root param

### ISSUE THREAD

**Issue by ismaslov** [deepmipt/DeepPavlov#364]
Подскажите пожалуйста назначение параметра **deeppavlov_root**, определяется он несколько странным образом:
```
    try:
        deeppavlov_root = Path(config['deeppavlov_root'])
    except KeyError:
        deeppavlov_root = Path(__file__, "..", "..", "..", "..", "download").resolve()
```
Я вынужден выставлять его в "./" чтобы файл (в моём случае Vocab) сохранялся в директории _моего_ проекта. Насколько это опасно? Почему там упоминается download?

**Comment by yoptar** [comment]
Это базовый путь для относительных путей в конфиге. По умолчанию выставляется папкой `download` в корне репозитория. Можно в корне конфига добавить параметр `"deeppavlov_root"`, чтобы его переопределить.

**Comment by ismaslov** [comment]
спасибо за пояснения, тогда так и поступим :)
