### ISSUE TITLE
Packages required for these tutorials can not be installed successfully

### ISSUE THREAD

**Issue by JiahangOK** [deepmipt/DeepPavlov#370]
When I did as  00 in the tutorials,I excuted ‘python -m deeppavlov install gobot_dstc2’，it has errors:
`Collecting fastText==0.8.22 from git+https://github.com/facebookresearch/fastText.git@25d0bb04bf43d8b674fe9ae5722ef65a0856f5d6#egg=fastText==0.8.22
  Cloning https://github.com/facebookresearch/fastText.git (to revision 25d0bb04bf43d8b674fe9ae5722ef65a0856f5d6) to /tmp/pip-install-l3u7pzt8/fastText
Requirement already satisfied: pybind11>=2.2 in /home/jiahang/env/lib/python3.6/site-packages (from fastText==0.8.22) (2.2.3)
Requirement already satisfied: setuptools>=0.7.0 in /home/jiahang/env/lib/python3.6/site-packages (from fastText==0.8.22) (40.0.0)
Requirement already satisfied: numpy in /home/jiahang/env/lib/python3.6/site-packages (from fastText==0.8.22) (1.14.5)
Building wheels for collected packages: fastText
  Running setup.py bdist_wheel for fastText ... error
  Complete output from command /home/jiahang/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l3u7pzt8/fastText/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-7rjckfyq --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/fastText
  copying python/fastText/__init__.py -> build/lib.linux-x86_64-3.6/fastText
  copying python/fastText/FastText.py -> build/lib.linux-x86_64-3.6/fastText
  creating build/lib.linux-x86_64-3.6/fastText/util
  copying python/fastText/util/__init__.py -> build/lib.linux-x86_64-3.6/fastText/util
  copying python/fastText/util/util.py -> build/lib.linux-x86_64-3.6/fastText/util
  creating build/lib.linux-x86_64-3.6/fastText/tests
  copying python/fastText/tests/test_script.py -> build/lib.linux-x86_64-3.6/fastText/tests
  copying python/fastText/tests/__init__.py -> build/lib.linux-x86_64-3.6/fastText/tests
  copying python/fastText/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fastText/tests
  running build_ext
  creating tmp
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/jiahang/env/include/python3.6m -c /tmp/tmpblq367da.cpp -o tmp/tmpblq367da.o -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/jiahang/env/include/python3.6m -c /tmp/tmpn30ssec_.cpp -o tmp/tmpn30ssec_.o -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  building 'fasttext_pybind' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/python
  creating build/temp.linux-x86_64-3.6/python/fastText
  creating build/temp.linux-x86_64-3.6/python/fastText/pybind
  creating build/temp.linux-x86_64-3.6/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/jiahang/env/include/site/python3.6 -I/home/jiahang/env/include/site/python3.6 -Isrc -I/usr/include/python3.6m -I/home/jiahang/env/include/python3.6m -c python/fastText/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-3.6/python/fastText/pybind/fasttext_pybind.o -DVERSION_INFO="0.8.22" -std=c++14 -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  In file included from /home/jiahang/env/include/site/python3.6/pybind11/pytypes.h:12:0,
                   from /home/jiahang/env/include/site/python3.6/pybind11/cast.h:13,
                   from /home/jiahang/env/include/site/python3.6/pybind11/attr.h:13,
                   from /home/jiahang/env/include/site/python3.6/pybind11/pybind11.h:43,
                   from python/fastText/pybind/fasttext_pybind.cc:13:
  /home/jiahang/env/include/site/python3.6/pybind11/detail/common.h:111:20: fatal error: Python.h: 没有那个文件或目录
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fastText
  Running setup.py clean for fastText
Failed to build fastText
Installing collected packages: fastText
  Running setup.py install for fastText ... error
    Complete output from command /home/jiahang/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l3u7pzt8/fastText/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2o8ia0j_/install-record.txt --single-version-externally-managed --compile --install-headers /home/jiahang/env/include/site/python3.6/fastText:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/__init__.py -> build/lib.linux-x86_64-3.6/fastText
    copying python/fastText/FastText.py -> build/lib.linux-x86_64-3.6/fastText
    creating build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/__init__.py -> build/lib.linux-x86_64-3.6/fastText/util
    copying python/fastText/util/util.py -> build/lib.linux-x86_64-3.6/fastText/util
    creating build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_script.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/__init__.py -> build/lib.linux-x86_64-3.6/fastText/tests
    copying python/fastText/tests/test_configurations.py -> build/lib.linux-x86_64-3.6/fastText/tests
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/jiahang/env/include/python3.6m -c /tmp/tmpj67wo_si.cpp -o tmp/tmpj67wo_si.o -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/jiahang/env/include/python3.6m -c /tmp/tmpy35jox2p.cpp -o tmp/tmpy35jox2p.o -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    building 'fasttext_pybind' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/python
    creating build/temp.linux-x86_64-3.6/python/fastText
    creating build/temp.linux-x86_64-3.6/python/fastText/pybind
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/jiahang/env/include/site/python3.6 -I/home/jiahang/env/include/site/python3.6 -Isrc -I/usr/include/python3.6m -I/home/jiahang/env/include/python3.6m -c python/fastText/pybind/fasttext_pybind.cc -o build/temp.linux-x86_64-3.6/python/fastText/pybind/fasttext_pybind.o -DVERSION_INFO="0.8.22" -std=c++14 -fvisibility=hidden
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/jiahang/env/include/site/python3.6/pybind11/pytypes.h:12:0,
                     from /home/jiahang/env/include/site/python3.6/pybind11/cast.h:13,
                     from /home/jiahang/env/include/site/python3.6/pybind11/attr.h:13,
                     from /home/jiahang/env/include/site/python3.6/pybind11/pybind11.h:43,
                     from python/fastText/pybind/fasttext_pybind.cc:13:
    /home/jiahang/env/include/site/python3.6/pybind11/detail/common.h:111:20: fatal error: Python.h: 没有那个文件或目录
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/jiahang/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-l3u7pzt8/fastText/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2o8ia0j_/install-record.txt --single-version-externally-managed --compile --install-headers /home/jiahang/env/include/site/python3.6/fastText" failed with error code 1 in /tmp/pip-install-l3u7pzt8/fastText/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiahang/DeepPavlov/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/jiahang/DeepPavlov/deeppavlov/deep.py", line 81, in main
    install_from_config(pipeline_config_path)
  File "/home/jiahang/DeepPavlov/utils/pip_wrapper/pip_wrapper.py", line 47, in install_from_config
    install(r)
  File "/home/jiahang/DeepPavlov/utils/pip_wrapper/pip_wrapper.py", line 25, in install
    env=os.environ.copy())
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/jiahang/env/bin/python', '-m', 'pip', 'install', 'git+https://github.com/facebookresearch/fastText.git@25d0bb04bf43d8b674fe9ae5722ef65a0856f5d6#egg=fastText==0.8.22']' returned non-zero exit status 1.
`
Why？I did totally as the tutorial,please help..

**Comment by yoptar** [comment]
Hi!
What operating system do you have? And what version?

You could try and install a `python3-dev` package and then recreate the virtual environment and try again.

**Comment by SummerTrainingBJTU** [comment]
@yoptar thanks, I use the vmware. And it's system is Ubuntu LTS 16.04. I have tried 'sudo apt install python3-dev' , but it still has the problem.

**Comment by yoptar** [comment]
Did it install anything? Did you create the new virtualenv after installing python3-dev?

**Comment by SummerTrainingBJTU** [comment]
@yoptar yes,after I installed the python3-dev,I create the vitual environment again.

**Comment by yoptar** [comment]
ok, so looks like Ubuntu 16.04 does not support python3.6 properly and the only info on this that i found is this issue https://github.com/davisking/dlib/issues/1269#issuecomment-409057108

**Comment by SummerTrainingBJTU** [comment]
@yoptar Thank you very much！

**Comment by JiahangOK** [comment]
@yoptar hi，may I ask which linux version do you use？I want to change my linux system

**Comment by yoptar** [comment]
I'm using Ubuntu 18.04
