### ISSUE TITLE
what is "assert" mean?

### ISSUE THREAD

**Issue by JiahangOK** [deepmipt/DeepPavlov#372]
In tutorial 01, there is a paragraph as follow:
'''
dataset = dataset_reader.read('data/')
assert len(dataset) == 3, 'The dataset must be a dict with three fields: train, test, and valid'
assert len(set(dataset) & {'train', 'test', 'valid'}) == 3, 'The dataset keys must be exactly train, test, and valid'
assert isinstance(dataset['train'][0][0][0], str) and isinstance(dataset['train'][0][0][1], str), 'Both tokens and tags must be strings'
assert len(dataset['train']) == 14041, 'there must be exactly 14041 samples in train'
assert len(dataset['valid']) == 3250, 'there must be exactly 3250 samples in train'
assert len(dataset['test']) == 3453, 'there must be exactly 3453 samples in test'
'''
What are these 'assert'-started lines meaning? Are they the parts of the program？

**Comment by JiahangOK** [comment]
Why I have such error？
‘’‘
>>> class NerDatasetReader:
...   def read(self,data_path):
...     data_parts = ['train','valid','test']
...     extention = '.txt'
...     dataset = {}
...     for data_part in data_parts:
...       file_path = Path(data_path) / Path(data_path + extension)
...       dataset[data_part] = self.read_file(str(file_path))
...     return dataset
... 
>>> dataset_reader = NerDatasetReader()
>>> assert len(dataset) == 3, 'The dataset must be a dict with three fields: train, test, and valid'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dataset' is not defined
‘’’

**Comment by yoptar** [comment]
```python
assert len(dataset) == 3, 'The dataset must be a dict with three fields: train, test, and valid'
```
roughly translates to
```python
if not len(dataset) == 3:
    raise AssertionError('The dataset must be a dict with three fields: train, test, and valid')
```  
   
   
This error is there because you are referencing the `dataset` variable in the `assert` statement, but it is not defined.
