### ISSUE TITLE
Can't reassign default values in __call__()

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#373]
Hi! It looks like there is `mean` argument in [elmo_embedder](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/embedders/elmo_embedder.py)  `__call__()` that can't be reassigned in a config according to dp architecture. Please, pass `mean` as a parameter to `__init__()`.

**Comment by kudep** [comment]
Hi! Please wait for the approve and the update #379 .

**Comment by my-master** [comment]
Closing, since #379 merged.
