### ISSUE TITLE
ConfigError: 'Model dstc2_v2_reader is not registered.'

### ISSUE THREAD

**Issue by JiahangOK** [deepmipt/DeepPavlov#385]
from deeppavlov.core.commands.train import train_evaluate_model_from_config

train_evaluate_model_from_config("gobot/vocab_config.json")
After I execute this code ,it have error:
=============================================
---------------------------------------------------------------------------
ConfigError                               Traceback (most recent call last)
<ipython-input-35-52fc4be2d2df> in <module>()
      1 from deeppavlov.core.commands.train import train_evaluate_model_from_config
      2 
----> 3 train_evaluate_model_from_config("gobot/vocab_config.json")

~/DeepPavlov/deeppavlov/core/commands/train.py in train_evaluate_model_from_config(config, to_train, to_validate)
    133                 raise e
    134         else:
--> 135             reader = get_model(reader_config.pop('name'))()
    136         data_path = reader_config.pop('data_path', '')
    137         if isinstance(data_path, list):

~/DeepPavlov/deeppavlov/core/common/registry.py in get_model(name)
     63 def get_model(name: str) -> type:
     64     if name not in _REGISTRY:
---> 65         raise ConfigError("Model {} is not registered.".format(name))
     66     return cls_from_str(_REGISTRY[name])
     67 

ConfigError: 'Model dstc2_v2_reader is not registered.'
========================
I did as the tutorial03 compeletely,why?help..

**Comment by vikmary** [comment]
@JiahangOK, thanks for finding a bug. Will be fixed in the next release.
You can change all mentions of `dstc2_v2_reader` to `dstc2_reader`, and `DSTC2Version2DatasetReader` to `DSTC2DatasetReader`, it should work then.

**Comment by JiahangOK** [comment]
@vikmary thank you very much

**Comment by vikmary** [comment]
Fixed in https://github.com/deepmipt/DeepPavlov/pull/391. Released in [0.0.7](https://github.com/deepmipt/DeepPavlov/releases/tag/0.0.7).
