### ISSUE TITLE
DSTC2Version2DatasetReader missed

### ISSUE THREAD

**Issue by JiahangOK** [deepmipt/DeepPavlov#388]
There is no DSTC2Version2DatasetReader in deeppavlov.dataset_readers.dstc2_reader ....

**Comment by vikmary** [comment]
Linked to issue https://github.com/deepmipt/DeepPavlov/issues/385

**Comment by vikmary** [comment]
Fixed in https://github.com/deepmipt/DeepPavlov/pull/391. Released in [0.0.7](https://github.com/deepmipt/DeepPavlov/releases/tag/0.0.7).

**Comment by vikmary** [comment]
`DSTC2Version2DatasetReader` is now renamed to `DSTC2DatasetReader`.
