### ISSUE TITLE
seq2seq gobot kvret_kb intent not replacing correctly

### ISSUE THREAD

**Issue by MuruganR96** [deepmipt/DeepPavlov#408]
-->Will there be any fee which will be charged for this replacement health care card? 
>> you will receive the new in_the_event_of_non_receipt_of_the_new_card_by_25th,_i_apply_for_a_new_health_care_card_,_renewal_health_care_card_event by 25th of the month in which the old card is getting expired.

actual intent(you will receive the new in the event of non receipt of the new card by 25th, i apply for a new health care card,renewal health care card event by 25th of the month in which the old card is getting expired.)

why that underscore made in the inbetween gab. 

why not replacing  kvret_kb.json id's (i.e  in_the_event_of_non_receipt_of_the_new_card_by_25th , _i_apply_for_a_new_health_care_card_, _renewal_health_care_card_event.)

thank you for advance.

**Comment by vikmary** [comment]
The tokens with underscores correspond to items from your database. For example, `i_apply_for_a_new_health_care_card,_renewal_health_care_card_event` corresponds to some item with the following format:
```json
{
    "<item's_main_key>": "i apply for a new health care card, renewal health care card",
    "event": "<event_value>"
}
```

`Seq2seq_go_bot` model in `master` branch is very simple. The `i_apply_for_a_new_health_care_card,_renewal_health_care_card_event` should be substituted to `<event_value>` for proper response generation.

You should consider using `seq2seq_go_bot` from https://github.com/deepmipt/DeepPavlov/pull/382, as the model there is far more advanced (BLEU score 3x higher).

**Comment by MuruganR96** [comment]
https://github.com/deepmipt/DeepPavlov/pull/382#issue-209186276

Mam in this notes,where and how to see new release seq2seq_gobot_v2.tar.gz model with BLEU=13.2. and documentation.
https://github.com/deepmipt/DeepPavlov/issues/408#issue-354995078

Mam, in my trained data not depends on database(The tokens with underscores correspond to items from your database). then how to overcome this issue. 

mam i am just only replace my new utterance in that train set. is it not relevant to own seq2seq model . that is the reason only it shows this kind of structure.

but i gave correct question bot given almost acquired reply answer. then i change that question different way it shows this kind of structure.

if i use your new release(seq2seq_gobot_v2.tar.gz model with BLEU=13.2), is it resloved? 

thank you for advance

**Comment by vikmary** [comment]
Try the latest 0.0.7 release for model that handles items from database (words with underscores).
