### ISSUE TITLE
training custom data for slot filling

### ISSUE THREAD

**Issue by kishore0905** [deepmipt/DeepPavlov#423]
I would like to train the slot filling for my own custom data and i read the documentation and it is not clear.So anyone tell me how to train them.And my data is to small.

**Comment by kishore0905** [comment]
i trained with slotfill_dstc2_raw.json and showing show some good results but i need to remove some noise  in slotfill_dstc2.json they done like that but how to own data to it to get the more accurate results..

**Comment by mu-arkhipov** [comment]
We will add detailed description to the documentation in days to come (to the dev branch). The SlotFilling system itself is not trainable. It uses the results of the Named Entity Recognition (NER) module, which is a trainable part of the pipeline. The NER module provides tags for the SlotFilling component. SlotFilling component than uses the tokens and tags to perform fuzzy search in the existing vocabulary. The vocabulary is defined in the `slot_vals.json` file. A simple example with description is provided below:
```
{
    "food": {
        "caribbean": [
            "carraibean",
            "carribean",
            "caribbean"
        ],
        "kosher": [
            "kosher"
        ]
    },
    "pricerange": {
        "moderate": [
            "moderately",
            "medium",
            "moderat",
            "moderately",
            "derately",
            "modreately",
            "moderate"
        ],
        "expensive": [
            "high priced",
            "expensive"
        ],
        "cheap": [
            "cheap"
        ],
        "dontcare": [
            "any price",
            "i dont care about the price",
            "i dont care about price",
            "any range is fine",
            "any range",
            "dontcare"
        ]
    }
}
```
This is an example of the `slot_vals.json` file. It contains the vocabulary (like a python `dict`) of the all **types** of the slots. In this case `food` and `pricerange`. For each type of the slots there is a collection of the possible slot values in the **normal form** (a nested `dict`). For instance, for `pricerange` there are four possible slot values: `moderate`, `expensive`, `cheap`, `dontcare`.  Finally, for each slot value there is a list of all possible paraphrases. For example, for `expensive` slot value there are two paraphrases: `high priced` and `expensive`. Notice that the name of the normalized slot value must be provided in the paraphrases list.

**Comment by mu-arkhipov** [comment]
Do you change `slotfill_dstc2/dstc_slot_vals.json`?

**Comment by kishore0905** [comment]
yes i changed but its again downloading and replacing the older file value during training.

**Comment by kishore0905** [comment]
for training the slot filling with ner(dstc2) should i need to change the dstc2 data also.

**Comment by mnsrmov** [comment]
Inorder to stop the constant downloading just remove the download section from the json file. You have misunderstood the concept of slot filling. In general and in very layman like terms, slot filling is just an additional operation on named entity recognition. You train the model using named entity recognition train module and then perform slot filling on the results. No other training is required. Why is that? Named entity recognition provides you with the tagged named entities in the utterances, while slot filling tells an actuator what are the important tags and/or positions. The actuator uses the info of both sections to provide you with the words in the important tags. Thus, filling the slot which is designated by the tag and/or the position of the tag with the word.
