### ISSUE TITLE
Настройка прокси для телебота

### ISSUE THREAD

**Issue by ismaslov** [deepmipt/DeepPavlov#426]
в режиме запуска модели **interactbot** необходима возможность передать в библиотеку telebot адрес прокси. Например вот так:
`
python -m deeppavlov interactbot config.json -t <token> -p <proxy>
`

**Comment by IgnatovFedor** [comment]
Закрываем в связи с [разблокировкой](https://rkn.gov.ru/news/rsoc/news73050.htm) Телеграмма

**Comment by IgnatovFedor** [comment]
[Телеграм убран из библиотеки](https://github.com/deepmipt/DeepPavlov/pull/1548)
