### ISSUE TITLE
telegram-бот. конфигурация models_info

### ISSUE THREAD

**Issue by ismaslov** [deepmipt/DeepPavlov#427]
сейчас при подключении агента к телеграму сообщения _start_message_ и _help_message_ беруться из конфигурации **models_info.json**, которая лежит в библиотеке и которую соответственно, очень желательно не править.
Необходима возможность скормить свою конфигурацию библиотеке. Например так:
`
 python -m deeppavlov interactbot config.json -t <token> --telegram-config tg_config.json
`

**Comment by litinsky** [comment]
ismaslov, добрый день! `models_info.json` править теперь можно. Мы добавили функционал по управлению настройками DeepPavlov, в том числе и сброс настроек на дефолтные. Подробнее ознакомиться можно [тут](http://docs.deeppavlov.ai/en/latest/devguides/settings.html). На данный момент это доступно в dev, в ближайшем релизе окажется в master.
