### ISSUE TITLE
No load path is set for Seq2Seq

### ISSUE THREAD

**Issue by mOeztuerk** [deepmipt/DeepPavlov#428]
`WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 56: No load path is set for Seq2SeqGoalOrientedBot!
x_text::hello
>> what city
x_text::test
>> error long
x_text::when is my tennis activity
>> your tennis activity tennis_activity_date tennis_activity_date on tennis_activity_date at tennis_activity_time.
x_text::ok good day
>> you are welcome. end_of_dialogue
x_text::wil it be rainy today
>> what day and time should i add the reminder for
x_text::thank you car
>> you're welcome! end_of_dialogue
x_text::where is the nearest gas station
>> the 76 is 76 76_distance away.
x_text::how far is chevron
>> navigation set and we should be able to
x_text::os is there traffic
>> there is currently civic_center_garage_traffic_info on the route to
`

I geht this for following command: 
`python -m deeppavlov interact configs/seq2seq_go_bot/bot_kvret_infer.json -d
`

can someone please tell me why I get responses like "what city" for hello etc.? 
And how can i set for example the tennis activity to Friday or something else?

**Comment by vikmary** [comment]
Hi! Firstly, you're using not the latest version of the model. In the [0.0.7 release](https://github.com/deepmipt/DeepPavlov/releases/tag/0.0.7) the `seq2seq_go_bot` model was improved.

The `WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 56: No load path is set for Seq2SeqGoalOrientedBot!` warning is not crucial. If you're interested to know has model been initialized from scratch or loaded from disk, you should monitor logging messages like this: `[loading Seq2SeqGoBotNetwork from scratch]` or `[loading Seq2SeqGoBotNetwork from saved]`.

The model is based on sequence-to-sequence architecture that doesn't always respond with  syntactically valid language phrases. Thus "what city" is a valid response. One possible way for improvement is to provide more data.

You can set activities via dialog index (in the 0.0.7 release). In the interaction mode the model will ask you 'x_text' and also 'dialog_id'. If you input a dialog id from train, valid or test dataset, it will take it's database items from it. See examples here http://docs.deeppavlov.ai/en/master/skills/seq2seq_go_bot.html .

**Comment by mOeztuerk** [comment]
@vikmary thanks!
I tried
`python -m deeppavlov interact configs/seq2seq_go_bot/bot_kvret_infer.json -d
`
with the 0.0.7 release and got a "MemoryError: std::bad_alloc"

**Comment by vikmary** [comment]
`seq2seq_go_bot` requires quite lots of RAM -- about 9Gb.

**Comment by mOeztuerk** [comment]
thanks! that was my problem.

u mean "you can set activities via dialog index..."
so do you mean i have to put de 'dialog_id' manually for every x_text input?

i dont get the point in using dialog-Id manually, especially when i have to set it myself ever time i put a input in x_text

**Comment by vikmary** [comment]
You can leave dialog_id empty, and the model will still work.

The difference is when you set the dialog index, then the corresponding database items will be used to generate responses.

**Comment by vikmary** [comment]
Resolved in https://github.com/deepmipt/DeepPavlov/pull/449.
