### ISSUE TITLE
question regarding noise in sentence utterance

### ISSUE THREAD

**Issue by kkpriyankacoding** [deepmipt/DeepPavlov#429]
how do you removed noise form long text and recognising intent

**Comment by mu-arkhipov** [comment]
What kind of noise are you referring to? We have some preprocessing parts in our pipelines such as https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/preprocessors/sanitizer.py. This `Component` removes diacritical marks and replace all digits with 1.
