### ISSUE TITLE
TFModel.get_train_op() method doesn't allow passing any optimizer parameters other than "learning_rate"

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#442]
I believe that a simple (but important) enhancement can be done to `TFModel.get_train_op()` method. Currently, it allows passing only "learning_rate" parameter to optimizer options. Thus, if I want to use, say, `tf.train.MomentumOptimizer` with `momentum=0.9`, I have to duplicate `TFModel.get_train_op()` code into my code in order to do that. I think, we can create something like `optimizer_options` arg to pass **all** optimizer parameters.

**Comment by mu-arkhipov** [comment]
May be something like:
```
def get_train_op(self, learning_rate, **kwargs):
    optimizer = tf.train.AdamOptimizer(learnign_rate, **kwargs)
```

**Comment by my-master** [comment]
It can be like this, but also we should decide how we do call these `**kwargs` inside networks' classes. 
As I see from DeepPavlov's code , `get_train_op()` is called inside network classes in `_build_graph()` or other networks' methods with similar semantics. So we should pass the optimizer parameters inside `__int__()` method of networks classes and we should have a name for this parameter (which can't be `**kwargs` at the `__init__()` level, because other things go to `__init__'s`  `**kwargs`). I suggest we have something like `dict: optimizer_options` parameter which can be passed like `**kwargs` or `optimizer_options` to `get_train_op()`.
However, I see one disadvantage of this approach: we will have to edit all json configs to change `learning_rate: ...` to `optimizer_options: {'learning_rate: ...'}`.

**Comment by IgnatovFedor** [comment]
TF removed from the library. TorchModels allows to set any optimizer parameters.
