### ISSUE TITLE
The deeppavlov docker says in tutorials is unavailable

### ISSUE THREAD

**Issue by woolh** [deepmipt/DeepPavlov#445]
Hi, I'm beginer  of tf learner and have encountered a problem when I try to do according the tutorials.
Here is the tutorials page:
https://github.com/deepmipt/DeepPavlov/blob/master/examples/tutorials/00_deeppavlov_intro.ipynb

When I try to follow the tutorials and run docker pull altinsky/convai:deeppavlov, it tells me the docker is not found.
So I go to docker hub and only find one docker under this user altinsky, so I try to run that docker, but the result is disaccord with  the tutorials.

Who can help me how to go on?

**Comment by litinsky** [comment]
Hi, Woolh! Recently we have finished with updating our [Docker Hub repository](https://hub.docker.com/u/deeppavlov/). Now you are welcomed to explore DeepPavlov with [Jupyter Docker image](https://hub.docker.com/r/deeppavlov/jupyter/) or interact prebuilt configs via REST API. All images will be updated along with further DeepPavlov releases.
