### ISSUE TITLE
Morphotagger crashes in the multi-threaded mode

### ISSUE THREAD

**Issue by litinsky** [deepmipt/DeepPavlov#457]
When rising morphotagger skill in a multithreaded app (for example with `riseapi` and `app.run(host=host, port=port, threaded=True)` in `server.py`), error occurres during inference:

```
ValueError: Tensor Tensor("p/Reshape_1:0", shape=(?, ?, 711), dtype=float32) is not an element of this graph.
```

**Comment by yoptar** [comment]
Can be solved by inheriting a morphotagger class from `KerasModel`
