### ISSUE TITLE
Implicit tokenization in MorphoTagger pipelines

### ISSUE THREAD

**Issue by yoptar** [deepmipt/DeepPavlov#464]
Tokenization should be removed from the LowerCasePreprocessor https://github.com/deepmipt/DeepPavlov/blob/e91ff6c3eafbd49b6f09499d2e1b4b5675b513bb/deeppavlov/models/preprocessors/capitalization.py#L125-L126
and the WordIndexVectorizer https://github.com/deepmipt/DeepPavlov/blob/e91ff6c3eafbd49b6f09499d2e1b4b5675b513bb/deeppavlov/models/vectorizers/word_vectorizer.py#L49-L50
and made explicit.
affects #463

**Comment by AlexeySorokin** [comment]
Fixed in #507
