### ISSUE TITLE
Do not store downloaded files in <>/site-packages/download

### ISSUE THREAD

**Issue by vikmary** [deepmipt/DeepPavlov#468]
Seems like `<>/site-packages/download` is not the best place for downloaded models.
`<>/site-packages/deeppavlov/download` or `~/download` might be a better decision.

Also `<>/site-packages/utils` is not the best place for utils specific to deeppavlov library.

**Comment by yoptar** [comment]
relies on #112

**Comment by yoptar** [comment]
Done in #574 
moved to `~/.deeppavlov/`
