### ISSUE TITLE
How to verify the Precision, Recall and F1-Measure of the model

### ISSUE THREAD

**Issue by KevinChen1994** [deepmipt/DeepPavlov#480]
First of all, thanks for your work!
I'm using deeppavlov.models.classifiers.logreg_classifier and cos_sim_classifier. After I trained my models, I only saw those models can work, but I can't know the Precision of those models. So is there has some method to let me know the Precision, Recall and F1-Measure of my models?
Thanks!

**Comment by vikmary** [comment]
In every config file you can modify `train.metrics` section: for example, add new metrics. They all be calculated in the evaluation phase of training. For implemented metrics see https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/metrics
For example, there is F1-measure for classification tasks. You can implement your own metric taking it as an example:
https://github.com/deepmipt/DeepPavlov/blob/d643000f0a5bb4c220a28899d727e12e195000e0/deeppavlov/metrics/fmeasure_classification.py#L25
