### ISSUE TITLE
REST API changes types of returning values.

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#482]
When a `Component` is called via REST API, all tuples in returning data are converted into lists, which may lead to errors when this data is passed further in a pipeline config. Thus, the same component returns different types when called via REST API or called as usual. I will add issue details / steps to reproduce later.

**Comment by yoptar** [comment]
Objects are serialized as json, so there is not a lot of things that we could do about it.

**Comment by my-master** [comment]
It's possible to add an object hook for tuples in custom `JSONEncoder` and `JSONDecoder`. It will take some time to encode-decode, so the question is how much is computational overhead.

**Comment by yoptar** [comment]
We're probably not going to implement this.
