### ISSUE TITLE
How to train my own dstc format file(go_bot)?

### ISSUE THREAD

**Issue by jx1100370217** [deepmipt/DeepPavlov#484]
How to train my own dstc format file(go_bot)?It didn't work with my own data.

**Comment by vikmary** [comment]
Please provide your config file, example of your data sample and command you use to train go_bot

**Comment by jx1100370217** [comment]
{"speaker": 2, "text": "Hello, welcome to the Cambridge restaurant system. You can ask for restaurants by area, price range or food type. How may I help you?", "dialog_acts": [{"act": "welcomemsg", "slots": []}]}
{"speaker": 1, "text": "Hunan cuisine", "goals": {"food": "Hunan cuisine"}, "dialog_acts": [{"slots": [["food", "Hunan cuisine"]], "act": "inform"}]}
{"speaker": 2, "text": "What part of town do you have in mind?", "dialog_acts": [{"act": "request_area", "slots": []}]}
{"speaker": 1, "text": "in the south", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [["area", "south"]], "act": "inform"}]}
{"speaker": 2, "text": "api_call area=\"south\" food=\"Hunan cuisine\" pricerange=\"dontcare\"", "dialog_acts": [{"act": "api_call", "slots": [["food", "Hunan cuisine"], ["area", "south"
      ]]}], "db_result": {"food": "Hunan cuisine", "area": "south", "addr": "Nanshan Avenue Comprehensive Building, Nanshan District (Guimiao Intersection)", "phone": "0755-26642666", "pricerange": "expensive", "postcode": "518000", "name": "Farmhouse"}}
{"speaker": 2, "text": "Farmhouse is a nice place in the south of town serving tasty Hunan cuisine food.", "dialog_acts": [{"act": "inform_area+inform_food+offer_name", "slots": [["name"
      , "Farmhouse"], ["food", "Hunan cuisine"], ["area", "south"]]}]}
{"speaker": 1, "text": "what is the address", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [["slot", "addr"]], "act": "request"}]}
{"speaker": 2, "text": "Sure, Farmhouse is on Nanshan Avenue Comprehensive Building, Nanshan District (Guimiao Intersection).", "dialog_acts": [{"act": "inform_addr+offer_name", "slots":
       [["name", "Farmhouse"], ["addr", "Nanshan Avenue Comprehensive Building, Nanshan District (Guimiao Intersection)"]]}]}
{"speaker": 1, "text": "what is the phone number", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [["slot", "phone"]], "act": "request"}]}
{"speaker": 2, "text": "The phone number of Farmhouse is 0755-26642666.", "dialog_acts": [{"act": "inform_phone+offer_name", "slots": [["name", "Farmhouse"], ["phone", "0755-26642666"]]}
      ]}
{"speaker": 1, "text": "thank you good bye", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [], "act": "thankyou"}, {"slots": [], "act": "bye"}]}
{"speaker": 2, "text": "You are welcome!", "dialog_acts": [{"act": "bye", "slots": []}]}

 {"speaker": 2, "text": "Hello, welcome to the Cambridge restaurant system. You can ask for restaurants by area, price range or food type. How may I help you?", "dialog_acts": [{"act": 
"welcomemsg", "slots": []}]}
{"speaker": 1, "text": "Hunan cuisine", "goals": {"food": "Hunan cuisine"}, "dialog_acts": [{"slots": [["food", "Hunan cuisine"]], "act": "inform"}]}
{"speaker": 2, "text": "What part of town do you have in mind?", "dialog_acts": [{"act": "request_area", "slots": []}]}
{"speaker": 1, "text": "in the south", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [["area", "south"]], "act": "inform"}]}
{"speaker": 2, "text": "api_call area=\"south\" food=\"Hunan cuisine\" pricerange=\"dontcare\"", "dialog_acts": [{"act": "api_call", "slots": [["food", "Hunan cuisine"], ["area", "south"
      ]]}], "db_result": {"food": "Hunan cuisine", "area": "south", "addr": "3rd Floor, Zhongnan Haibin Hotel, No. 18 Nanxin Road, Nanshan District", "phone": "26088736-2212", "pricerange": 
"moderate", "postcode": "518000", "name": "Donghai Restaurant"}}
{"speaker": 2, "text": "Donghai Restaurant is a nice place in the south of town serving tasty Hunan cuisine food.", "dialog_acts": [{"act": "inform_area+inform_food+offer_name", "slots":
       [["name", "Donghai Restaurant"], ["food", "Hunan cuisine"], ["area", "south"]]}]}
{"speaker": 1, "text": "what is the address", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [["slot", "addr"]], "act": "request"}]}
{"speaker": 2, "text": "Sure, Donghai Restaurant is on 3rd Floor, Zhongnan Haibin Hotel, No. 18 Nanxin Road, Nanshan District.", "dialog_acts": [{"act": "inform_addr+offer_name", "slots"
      : [["name", "Donghai Restaurant"], ["addr", "3rd Floor, Zhongnan Haibin Hotel, No. 18 Nanxin Road, Nanshan District"]]}]}
{"speaker": 1, "text": "what is the phone number", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [["slot", "phone"]], "act": "request"}]}
{"speaker": 2, "text": "The phone number of Donghai Restaurant is 26088736-2212.", "dialog_acts": [{"act": "inform_phone+offer_name", "slots": [["name", "Donghai Restaurant"], ["phone",
      "26088736-2212"]]}]}
{"speaker": 1, "text": "thank you good bye", "goals": {"food": "Hunan cuisine", "area": "south"}, "dialog_acts": [{"slots": [], "act": "thankyou"}, {"slots": [], "act": "bye"}]}
{"speaker": 2, "text": "You are welcome!", "dialog_acts": [{"act": "bye", "slots": []}]}


I want to add the above content to dstc-trn.jsonlist, how can I make the changes take effect?

**Comment by vikmary** [comment]
1. Change every `load_path` and `save_path` parameter present in your config file to something new (otherwise during training model will try to load itself from old dstc2 model files).
2. Replace `dstc2-trn.jsonlist` with your new data file (The path to `dstc2-trn.jsonlist` should be `DEEPPAVLOV_ROOT/../download/dstc2/dstc2-trn.jsonlist`.
3. Run training of go_bot `python3 -m deeppavlov train go_bot`

**Comment by jx1100370217** [comment]
Thank you very much!

**Comment by skbalahere** [comment]
Training intents_dstc2_bert takes lot of time and resource, is there any way i can reduce the time. I think i am wrong some where.

**Comment by vikmary** [comment]
@skbalahere intents_dstc2_bert is a large model, for smaller model take intents_dstc2.
