### ISSUE TITLE
An implicit requirement

### ISSUE THREAD

**Issue by avidale** [deepmipt/DeepPavlov#491]
deeppavlov.core.commands.infer.build_model_from_config doesn't work without gensim and tensorflow (trying to run goo.gl/V2gfxn tutorial on windows)

**Comment by vikmary** [comment]
Tensorflow has cpu-version `tensorflow` and gpu-compatible version `tensorflow-gpu`.
You should choose yourself and install any of them BEFORE installing deeppavlov.

`gensim` is not required by all deeppavlov models, and is not installed by default. Before using any model you should firstly install it's requirements by `python -m deeppavlov install path/to/config`. Maybe that was in your case?
