### ISSUE TITLE
Metrics inputs and outputs

### ISSUE THREAD

**Issue by dilyararimovna** [deepmipt/DeepPavlov#493]
It will be very useful to have an opportunity to assign in config which data elements of chainer to give as "true" and "predict" inputs for every metric (separately for each). By default, leave as previously was. 
For example:
```
{
  "metrics": [
      "accuracy",
      {
        "metric": "roc_auc",
        "true": "y_true_onehot",
        "predict": "probas"
      }
    ]
}
```

Thank you in advance!

**Comment by yoptar** [comment]
Resolved with #517 
http://docs.deeppavlov.ai/en/latest/intro/config_description.html#metrics
