### ISSUE TITLE
how to add words char-composition to ner_dstc2

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#508]
Hi!
I've trained ner_dstc2 component on my data (russian dialogs).
But it performs more or less good only if user's answers have more then one word in response.
As I see this caused by that the ner is based only on words and there is now char-composition accounting.

I found that ner_rus (based on Conll2003) uses char embeddings.

Is it the right way to stack char-analysing components in the same way and to use its ner model component?

**Comment by mu-arkhipov** [comment]
You can just use the `ner_rus` config or copy the char level parts from it to train the components from scratch. If you want to use pretrained parts of the `ner_rus` the easiest way would be just to pass the predictions from the pretrained network to the new network. However, the `ner_rus` is trained on the news data which is almost long context.

**Comment by vitalyuf** [comment]
Hi!
When i trained ner_rus I found that the directory **download\total_rus** (where ner_rus takes data from) contanined train.txt, test.txt, valid.txt **in english**.
So when I use yours prebuilt model it gives more or less right tags for russian texts.
But if I use the model trained using ner_rus it gives **'o'-tags** for every token in any russian text.
