### ISSUE TITLE
Can anyone update the OntoNotes NER document?

### ISSUE THREAD

**Issue by ljch2018** [deepmipt/DeepPavlov#514]
![image](https://user-images.githubusercontent.com/22562546/46726597-45f8a180-ccb1-11e8-9d16-92a68608d1e7.png)

when I use this code from document, I mean the follow error.
```
>>> from deeppavlov.core.commands.train import train_model_from_config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'train_model_from_config'
``

**Comment by mu-arkhipov** [comment]
Fixes are already in the dev branch. They will be released in in days to come.

**Comment by mu-arkhipov** [comment]
You can use dev branch to resolve the issue.

**Comment by ljch2018** [comment]
Thank you @mu-arkhipov
