### ISSUE TITLE
Python 3.7.0 support

### ISSUE THREAD

**Issue by ololobus** [deepmipt/DeepPavlov#520]
DeepPavlov has scikit-learn version fixed to v0.19.1, but its c-extensions build fails on python 3.7.0 (at least on macOS), please see [scikit-learn issue](https://github.com/scikit-learn/scikit-learn/issues/11320).

This issue has been fixed in scikit-learn v0.19.2 release, so you have to up at least minor version to enable python 3.7.0 support.

I can try python 3.7.0 compatibility of other packages and prepare a pull-request, if you want.

**Comment by seliverstov** [comment]
Hi, Alexey!
Thanks, It will be great!

**Comment by ololobus** [comment]
Here it is https://github.com/deepmipt/DeepPavlov/pull/521

**Comment by yoptar** [comment]
Waiting on https://github.com/tensorflow/tensorflow/issues/20517

**Comment by lcswillems** [comment]
The issue you are waiting on is now closed. Tensorflow 1.13.1 now supports Python 3.7. Could you update your dependencies?

I would like to use Spacy with your package but I can't currently because of dependencies.

**Comment by yoptar** [comment]
Resolved in #950
