### ISSUE TITLE
ModuleNotFoundError inside deep.py 

### ISSUE THREAD

**Issue by rikhuijzer** [deepmipt/DeepPavlov#525]
While using deeppavlov 0.0.8 package I get the following error when importing find_config from deeppavlov.deep:
```
File "<removed>", line 16, in <module>
    from deeppavlov.deep import find_config'

File "<removed>/venv/lib/python3.6/site-packages/deeppavlov/deep.py", line 26, in <module>
    from utils.telegram_utils.telegram_ui import interact_model_by_telegram

ModuleNotFoundError: No module named 'utils.telegram_utils'; 'utils' is not a package
```
The import seems fine in the Github repository at tag 0.0.8 so I'm wondering what problem occurs here. It seems that it is an DeepPavlov issue. But of course please let me know if I'm doing anything wrong here :)

**Comment by yoptar** [comment]
Hi!
Have you installed the package or are you just working with code from github?
You can install it in development mode with `pip3 install -e .` from the repository root directory.

**Comment by yoptar** [comment]
So I just
1. created and activated a new virtual environment
1. `pip install deeppavlov`
1. `python -c 'from utils.telegram_utils.telegram_ui import interact_model_by_telegram; from deeppavlov.deep import find_config'`

and got no errors. 
Do you have a way to reproduce your exception?

**Comment by rikhuijzer** [comment]
Found it. Trivial problem. The package `utils` and `deeppavlov` are both top-level imports. I had one source file called `utils.py` causing the `utils` package to be overridden. Had to rename my `utils.py` and completely restart the project. Only removing virtual environment was not enough.

Thanks for your help!
