### ISSUE TITLE
How to restore shape of words after Automatic Spelling Correction?

### ISSUE THREAD

**Issue by takiholadi** [deepmipt/DeepPavlov#529]
It returns lowercased text after corrections.
Tried two configs: Brill Moore top 4 + lm, and Damerau Levenshtein 1 + lm.

**Comment by yoptar** [comment]
Hi
You could add a component that remembers casing after tokenization and another one that restores it or extends candidates list with it before a language model.
We never had a need for it nor data to check if it will work better or worse, so we didn't do it ourselves yet.
