### ISSUE TITLE
ValueError in Intent Classification if running from script

### ISSUE THREAD

**Issue by takiholadi** [deepmipt/DeepPavlov#542]
```
import json
from deeppavlov.core.commands.infer import build_model_from_config
NER_CONFIG_PATH = 'sentiment_twitter_preproc.json'
config = json.load(open(NER_CONFIG_PATH, mode='rt'))
new_model = build_model_from_config(config)
new_model(['привет!))'])
```
gives me

> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-11-dda7dd7e22e9> in <module>
> ----> 1 new_model(['привет!))'])
> 
> ~/projects/intent-classification/env/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py in __call__(self, *args, **kwargs)
>     104 
>     105     def __call__(self, *args, **kwargs):
> --> 106         return self._predict(*args, **kwargs)
>     107 
>     108     def _predict(self, x, y=None, to_return=None):
> 
> ~/projects/intent-classification/env/lib/python3.6/site-packages/deeppavlov/core/common/chainer.py in _predict(***failed resolving arguments***)
>     139                 res = component(**dict(zip(in_keys, x)))
>     140             else:
> --> 141                 res = component(*x)
>     142             if len(out_params) == 1:
>     143                 mem[out_params[0]] = res
> 
> ~/projects/intent-classification/env/lib/python3.6/site-packages/deeppavlov/models/classifiers/keras_classification_model.py in __call__(self, data, *args)
>     223         preds = np.array(self.infer_on_batch(data), dtype="float64")
>     224 
> --> 225         labels = proba2labels(preds, confident_threshold=self.opt['confident_threshold'], classes=self.classes)
>     226         return labels, [dict(zip(self.classes, preds[i])) for i in range(preds.shape[0])]
>     227 
> 
> ~/projects/intent-classification/env/lib/python3.6/site-packages/deeppavlov/models/classifiers/utils.py in proba2labels(proba, confident_threshold, classes)
>      70             y.append(np.array(classes)[to_add].tolist())
>      71         else:
> ---> 72             y.append(np.array([np.array(classes)[np.argmax(sample)]]).tolist())
>      73 
>      74     return y
> 
> ~/projects/intent-classification/env/lib/python3.6/site-packages/numpy/core/fromnumeric.py in argmax(a, axis, out)
>    1002 
>    1003     """
> -> 1004     return _wrapfunc(a, 'argmax', axis=axis, out=out)
>    1005 
>    1006 
> 
> ~/projects/intent-classification/env/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
>      50 def _wrapfunc(obj, method, *args, **kwds):
>      51     try:
> ---> 52         return getattr(obj, method)(*args, **kwds)
>      53 
>      54     # An AttributeError occurs if the object does not have
> 
> ValueError: attempt to get argmax of an empty sequence
> 

Though all is OK if running from command line as
`$ python -m deeppavlov interact ../sentiment_twitter_preproc.json`

What I am doing wrong?

**Comment by dilyararimovna** [comment]
Hello!
I've tried to reproduce your error but didn't faced this problem. 
Do you use master branch of DeepPavlov?
Could you, please, check whether you run code in the same environment?
Also, please, try to download pre-trained models again.

**Comment by dilyararimovna** [comment]
Hello!
I've tried to reproduce this error but didn't fase it.
Do you use master branch of deeppavov?
Could you, please, try to download pre-trained models again and run scripts?
Also you can check whether you use the same environment to run code?

**Comment by dilyararimovna** [comment]
Whatever you want. 
I think git-version can be better if you are developing something (you can use another branches of DeepPavlov, you can create your own mirror of the repo to develop and control versions with git) while pip version is ok if your are only using models on your own data.
