### ISSUE TITLE
Why Levenshtein Corrector make strange inserts inplace of punctuation marks?

### ISSUE THREAD

**Issue by takiholadi** [deepmipt/DeepPavlov#543]
```
from deeppavlov.deep import find_config, deep_download
from deeppavlov.core.commands.infer import build_model_from_config
config = find_config('levenshtein_corrector_ru')
deep_download(config)
model = build_model_from_config(config)
print(model(['Сегодня.']))
print(model(['в 3 . Сегодня.']))
```
Gives me
> ['сегодня в']
> ['в 3 и сегодня и']

There are strange "." --> "в" and "." --> "и" inserts.

**Comment by yoptar** [comment]
Punctuation marks are not in the list of words, so substitutions are made. #545 should fix that.

**Comment by yoptar** [comment]
Resolved in the [latest release](https://github.com/deepmipt/DeepPavlov/releases/tag/0.0.9)
