### ISSUE TITLE
DeepPavlov NER problem 

### ISSUE THREAD

**Issue by pjmal** [deepmipt/DeepPavlov#548]
I'm trying to run the example of training a NER model and using it for prediction, as described on page
http://docs.deeppavlov.ai/en/master/components/ner.html#train-and-use-the-model
I'm using the CoNLL2003 data, embeddings file glove.6B.100d.txt and config file ner_conll2003.json, I've just changed the path names, and use a smaller value for "epochs", otherwise the config file is unchanged. However, when running build_model_from_config(config), I get the following errors (only the main parts are shown below). Any ideas what could be wrong and how to fix that?

...
/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
...

2018-10-19 12:28:21.772 ERROR in 'deeppavlov.core.common.params'['params'] at line 110: Exception in <class 'deeppavlov.models.ner.network.NerNetwork'>
Traceback (most recent call last):
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [0,32] rhs shape= [86,32]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@Variable"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Variable, save/RestoreV2/_33)]]

...
During handling of the above exception, another exception occurred:

  File "/opt/DL/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1759, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.

**Comment by mu-arkhipov** [comment]
It seems that something is not loaded `(shape= [0,32] rhs shape= [86,32])`. Can you provide config and list of the contents of the load folders.

**Comment by pjmal** [comment]
Thanks, I actually found a little bug in the config file, which explained this, so problem solved. But, another question came to my mind about the coNLL2003 data you use:
In the original CoNLL2003 data they used I-beginning to tag also the start of the named entity (B only if there are 2 entities following each other). However, in the data you provide, you use B-beginning always for the start of a named entity. Did you use the original CoNLL2003 tags, and change them to the B-tagging format yourself? And is that conversion included also somewhere as a part of the deeppavlov packet?

**Comment by mu-arkhipov** [comment]
BIO tagging scheme is provided with CoNLL2003, however, there might be some versions

**Comment by shivambatra76** [comment]
> Thanks, I actually found a little bug in the config file, which explained this, so problem solved. But, another question came to my mind about the coNLL2003 data you use:
> In the original CoNLL2003 data they used I-beginning to tag also the start of the named entity (B only if there are 2 entities following each other). However, in the data you provide, you use B-beginning always for the start of a named entity. Did you use the original CoNLL2003 tags, and change them to the B-tagging format yourself? And is that conversion included also somewhere as a part of the deeppavlov packet?

I am facing the same issue with the shapes. Can you help me out with the bug in the config file.
