### ISSUE TITLE
Seq2Seq Chatbot Data Example

### ISSUE THREAD

**Issue by mulki214** [deepmipt/DeepPavlov#559]
Hi Im new with deep learning things here, i like to train my own data using seq2seq model but curently i have qna file using .csv format, could you plese tell me how can i use this data? Thanks in advance.

**Comment by vikmary** [comment]
There is a sequence-to-sequence model called `seq2seq_go_bot`, but it requires existence of some database items in your task (for example, you discuss some appointments in your schedule with a bot). For now it doesn't work without the items. You can look at a data example in the documentation http://docs.deeppavlov.ai/en/master/skills/seq2seq_go_bot.html

Deeppavlov doesn't have a general purpose sequence-to-sequence model.
