### ISSUE TITLE
Вопрос относительно spelling_correction

### ISSUE THREAD

**Issue by drunkinlove** [deepmipt/DeepPavlov#562]
Можете уточнить, пожалуйста, как используется статистическая языковая модель при отборе кандидатов на исправление в компонентах spelling_correction?

**Comment by yoptar** [comment]
https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/spelling_correction/electors/kenlm_elector.py
Beam search токенов из кандидатов внутри предложения. Ищем максимальную сумму логарифмических вероятностей  от языковой модели и модели ошибок

**Comment by drunkinlove** [comment]
Вероятность от языковой модели -- это вероятность появления предложения, содержащего кандидата, согласно модели, да?

**Comment by yoptar** [comment]
Не совсем, это вероятность появления предложения, начинающегося с одного из лучших кандидатов первого токена и продолжающегося вплоть до рассматриваемого. Для «мама мыла раму» это
```
p("мама"|[]) * p("мыла"|["мама"]) * p("раму"|["мама", "мыла"])
```
Когда рассмотрены кандидаты для всех токенов, ещё прибавляется вероятность конца предложения после такой последовательности.

**Comment by drunkinlove** [comment]
> начинающегося с одного из лучших кандидатов первого токена

С одного из "ближайших" "эталонных" кандидатов согласно levenshtein_corrector или brillmoore, так?

> и продолжающегося вплоть до рассматриваемого.

Токена, (вероятно) подлежащего исправлению в исходном документе?

**Comment by drunkinlove** [comment]
Понятно, спасибо. 
А как словарь задействован в алгоритме? Поскольку ошибочные слова исправляются не только на словарные.

**Comment by yoptar** [comment]
Модель ошибок должна выдавать кандидатов только из словаря (или исходное слово)
