### ISSUE TITLE
[debug] Print [in],[out] param in chainer

### ISSUE THREAD

**Issue by fjfo** [deepmipt/DeepPavlov#572]
hi 
I want to debug each pipe in chainer like:
`"pipe": [
      {
        "id": "classes_vocab",
        "name": "default_vocab",
        "fit_on": ["y"],
        "level": "token",
        "save_path": "xxx.dict",
        "load_path": "xxx.dict"
      },
      {
        "in": "x",
        "out": "x_tok",
        "id": "my_tokenizer",
        "name": "my_tokenizer",
        "tokenizer": "my_tokenizer"
      },.....`

How to print out [in], [out] in each Pipe to make sure everything correct?
I dont want to edit __call__ in each Component to do that.
Any ideas? mode debug or something?

**Comment by yoptar** [comment]
You can set a breakpoint here:
https://github.com/deepmipt/DeepPavlov/blob/03d0f3fc12fbe4b7bf01216e194f6450254fe768/deeppavlov/core/common/chainer.py#L164
You'll see what component is called and with what arguments
