### ISSUE TITLE
NameError: name 'TfIdfVectorizer' is not defined

### ISSUE THREAD

**Issue by lql0716** [deepmipt/DeepPavlov#576]
vectorizer = TfIdfVectorizer(mode='train')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'TfIdfVectorizer' is not defined

**Comment by dilyararimovna** [comment]
Hello!
Now `TfidfVectorizer` is not presented in the library as a separate component. You can use SklearnComponent (registered as `sklearn_component`), see documentation [here](https://deeppavlov.readthedocs.io/en/latest/components/data_processors.html) and examples of usage [here](https://github.com/deepmipt/DeepPavlov/blob/dev/examples/tutorials/05_deeppavlov_classification.ipynb)

**Comment by ravi7893** [comment]
NameError: name 'TfidfVectorizer' is not defined

same error please any solution
