### ISSUE TITLE
AttributeError: 'DefaultVocabulary' object has no attribute 'len'

### ISSUE THREAD

**Issue by fjfo** [deepmipt/DeepPavlov#577]
Hi 
I'm training with my custom dataset but it always returns Error:

> File "/deeppavlov/core/common/params.py", line 41, in _resolve
>     val = eval('.'.join(attributes))
>   File "<string>", line 1, in <module>
> AttributeError: 'DefaultVocabulary' object has no attribute 'len'

What is that mean?

**Comment by yoptar** [comment]
Looks like in your configuration you are using something like `"vocab_len": "#word_vocab.len"` where `word_vocab` is a `default_vocab`. You can use `simple_vocab` instead
