### ISSUE TITLE
Logger configuration should be available for users inside pipeline configs at least as a label

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#585]
Currently, everything needed for the correct pipeline usage is outlined into configs `"metadata"` except logger. Logger lives as a separate config in `utils/settings/log_config.json` and there is no way to configure separate logging for each config. This leads to the necessity to write custom logging code for each experiment. It would be great to have an ability either to have  `log_config.json` structured in the same way as `server_config.json` with a separate label assigned to each config or to be able to configure logging in the main pipeline configs.

**Comment by yoptar** [comment]
Was created when the old logging system was implemented, so it is now obsolete.
