### ISSUE TITLE
Вопрос насчёт обучения моделей для компонента QA

### ISSUE THREAD

**Issue by drunkinlove** [deepmipt/DeepPavlov#588]
Добрый день!

Прошу уточнить, каким способом можно указать собственный dataset (json?/tar.gz?) для обучения модели. 
 Насколько я понимаю, `squad_dataset_reader` загружает и делит dataset на train/dev наборы, если значение `"dataset"` в config-файле соответствует одному из 'SQuAD', 'SberSQuAD' или 'MultiSQuAD'.

Также хотел бы узнать, как указать модель для обучения. Это поля `
        "save_path": "multi_squad_model_noans/model",
        "load_path": "multi_squad_model_noans/model"`? Можно ли обучить модель с нуля?

Последний вопрос: есть ли ограничения на размер контекста, а также размер входных данных при обучении?

Спасибо!

**Comment by drunkinlove** [comment]
Благодарю за ответ!

Можно узнать подробнее про модель и датасет MultiSQuAD? Насколько я понимаю, это случай, когда для каждого вопроса есть несколько контекстов (обязательно ли 11?), и не во всех из них содержится ответ на вопрос. Модель проверяет наличие ответа в каждом из контекстов? 
И как был сформирован датасет -- похоже, для каждой пары вопрос-контекст были выбраны другие параграфы из той же викистатьи, и отранжированы по tf-idf?

**Comment by yurakuratov** [comment]
> И как был сформирован датасет -- похоже, для каждой пары вопрос-контекст из SQuAD 1.1 были выбраны другие параграфы из той же викистатьи, и отранжированы по tf-idf?

Да, верно, датасет был составлен именно таким образом.

> Модель проверяет наличие ответа в каждом из контекстов, или MultiSquadIterator передаёт только один контекст на каждый вопрос?

[MultiSquadIterator](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_iterators/squad_iterator.py#L72) каждую эпоху для каждого вопроса случайным образом решает брать контекст с ответом на вопрос или без ответа. Причем вероятность выбора конкретного контекста без ответа пропорциональна его tf-idf скору.

>  (обязательно ли 11?)

Не обязательно, мы брали 1 контекст из SQuAD 1.1 и топ 10  контекстов по tf-idf из викистатьи.

> Наконец, на чём тестировалась эта модель и модели Simple and Effective Multi-Paragraph Reading Comprehension, DrQA для получения оценок, приведённых в документации?

Брался вопрос и статья википедии, в которой есть ответ на данный вопрос. Викистатья разбивалась на параграфы и в каждом из них искался ответ. Затем выбирали ответ с максимальным скором P(has_ans | C, Q) и считали стандартные метрики для SQuAD: EM, F-1.

Использовалась модель R-Net, которая могла в качестве позиции начала и конца ответа выбрать специальный NO_ANS токен. P(has_ans | C, Q) = 1 - P(NO_ANS | C, Q)

**Comment by drunkinlove** [comment]
Спасибо.

Возник ещё небольшой батч вопросов. Я правильно понимаю, что по команде train обучается только сама модель squad, а squad_vocab_embedder использует готовые word vectors? Какую роль в таком случае играет параметры save_path и fit_on?

`        "class_name": "squad_vocab_embedder",`
`...`
`       "save_path": "{MODELS_PATH}/squad_model_ru/emb/vocab_embedder.pckl",`
`       "load_path": "{MODELS_PATH}/squad_model_ru/emb/vocab_embedder.pckl",`
`...`
`        "fit_on": ["context_tokens", "question_tokens"],`
`        "in": ["context_tokens", "question_tokens"],`
`        "out": ["context_tokens_idxs", "question_tokens_idxs"]`

Также в chainer'e присутствует как token-level embedder, так и char-level embedder. Зачем нужны оба? Наконец, какой принцип используется для char-level embedder'a?

**Comment by yurakuratov** [comment]
При вызове команды `train` `squad_vocab_embedder` собирает матрицу эмбеддингов для всех слов из обучающего набора данных. Эта же процедура производится и для символов.

Token- и char-lvl embedder используются в моделью, чтобы представить каждое слово двумя способами: взять готовый вектор из token-lvl матрицы эмбеддингов и закодировать слово с помощью BiGRU, как последовательность символов. Такой способ помогает решить проблему out-of-vocabulary слов. Для любого слова мы сможем построить вектор на основе векторов символов.

**Comment by drunkinlove** [comment]
Т.е. ни один из эмбеддеров не обучается; и если для слова существует token-lvl эмбеддинг, то сопоставляется он, а если нет, то генерируется char-lvl эмбеддинг с помощью Bi-rNN?

**Comment by yurakuratov** [comment]
> Т.е. ни один из эмбеддеров не обучается; и если для слова существует token-lvl эмбеддинг, то сопоставляется он, а если нет, то генерируется char-lvl эмбеддинг с помощью Bi-rNN?

В сети векторное представление слова строится как конкатенация token-lvl вектора и вектора, полученного с помощью BiGRU. token-lvl вектора не обучаются, но char-lvl обучаются вместе со всей моделью.

**Comment by drunkinlove** [comment]
Спасибо за ответ.
