### ISSUE TITLE
ModuleNotFoundError: No module named 'deeppavlov.models.ner.evaluation'

### ISSUE THREAD

**Issue by LuisQ95** [deepmipt/DeepPavlov#602]
Hello, i need help, this import is not recognize.

from deeppavlov.models.ner.evaluation import precision_recall_f1
Traceback (most recent call last):

  File "<ipython-input-12-af55e76b7ff9>", line 1, in <module>
    from deeppavlov.models.ner.evaluation import precision_recall_f1

ModuleNotFoundError: No module named 'deeppavlov.models.ner.evaluation'

**Comment by mu-arkhipov** [comment]
Hello!

What config are you using? The tests are fine, everything is working. However the `precision_recall_f1` function was moved from `deeppavlov.models.ner.evaluation` to `deeppavlov.metrics.fmeasure`. You can you try to checkout the fresh version of `master` branch.

**Comment by LuisQ95** [comment]
Thank you.
