### ISSUE TITLE
Issue Regarding unrelated answer extracted from context_raw

### ISSUE THREAD

**Issue by csrujan** [deepmipt/DeepPavlov#606]
i am able to set the code. When i am giving unrelated question_raw from the given context_raw , i am getting some answer , can this be rectified , instead can i get unrelated question or NOT RELATED in the answer field , can you give information regarding this , please let me know

**Comment by yurakuratov** [comment]
Hi!

Can you specify which model do you try to use?

**Comment by csrujan** [comment]
> Hi!
> 
> Can you specify which model do you try to use?

i am using interact and squad.json , if that is what you are asking

**Comment by yurakuratov** [comment]
`squad.json` model will always output some answer from context.
You can use `multi_squad_noans.json` model. This model outputs empty string if there is no answer in context (question is not related) and a score (value of how model is confident that there is answer in context).

**Comment by csrujan** [comment]
> `squad.json` model will always output some answer from context.
> You can use `multi_squad_noans.json` model. This model outputs empty string if there is no answer in context (question is not related) and a score (value of how model is confident that there is answer in context).

I used multi_squad_noans.json and when i have run this model below are the values i entered and got back

context_raw::my name is srujan
question_raw::what is my name?
>> ('', -1, 0.07074844837188721)

some help needed regarding this as you can see that i gave related question , but got back an empty string

**Comment by csrujan** [comment]
Is there a way to get for both small and larger contexts , if yes please guide me.

**Comment by csrujan** [comment]
> Is there a way to get results for both small and larger contexts , if yes please guide me.

please provide the solution steps for this issue , Could you please provide me the link or names of the algorithms used for this project

**Comment by yurakuratov** [comment]
> > Is there a way to get results for both small and larger contexts , if yes please guide me.
> 
> please provide the solution steps for this issue , Could you please provide me the link or names of the algorithms used for this project

If you have context-question-answer triplets with short contexts you can add them to dataset, which we used to train `multi_squad_noans` model. Link to dataset can be found here: [SquadDatasetReader](http://docs.deeppavlov.ai/en/master/_modules/deeppavlov/dataset_readers/squad_dataset_reader.html#SquadDatasetReader).

If you don't have such data then you can augment original dataset by randomly cuting some contexts to shorter lengths.

**Comment by yoptar** [comment]
Closing this issue as it's been inactive.

**Comment by jayachandra2128** [comment]
When i run "python -m deeppavlov train deeppavlov/configs/squad/multi_squad_nouns.json" it is getting stuck and running through ages at line "Loading saved tokens vocab from */vocab_embedder.pckl" and finally server getting killed. Im even using GPU's. Have you faced such issue while training multi_squad_noans model. Can you please guide me on how to train multi_squad_noans model.
