### ISSUE TITLE
ImportError: cannot import name 'build_model'

### ISSUE THREAD

**Issue by LuisQ95** [deepmipt/DeepPavlov#610]
Hi, I have a problem with this import,

from deeppavlov import build_model, configs.

Does not detect build_model package, help.

**Comment by seliverstov** [comment]
Hi,
Try to upgrade to 0.1.0 version (just have released).

**Comment by LuisQ95** [comment]
I still have the same problem. 

![error1](https://user-images.githubusercontent.com/40223102/49028396-4b7e4e00-f170-11e8-8e69-5c44dda46ac0.PNG)

![error2](https://user-images.githubusercontent.com/40223102/49028400-4d481180-f170-11e8-9a28-e2574de3b37b.PNG)

**Comment by seliverstov** [comment]
I can't reproduce your error. My actions are:
* create new env: `virtualenv -p python3 env`
* activate it: './env/bin/activate'
* `pip install deeppavlov jupyter`
*  `jupyter notebook`
And then successfuly run code:
```
from deeppavlov import configs, build_model

ner_model = build_model(configs.ner.ner_ontonotes, download=True)
ner_model(['Computer Sciences Corp. is close to making final an agreement to buy Cleveland Consulting Associates'])
```

**Comment by seliverstov** [comment]
Also, try to run `!pip freeze` in your notebook and check that `deeppavlov==0.1.0`

**Comment by LuisQ95** [comment]
I don't found those package build_model or train_model

![error3](https://user-images.githubusercontent.com/40223102/49029856-c006bc00-f173-11e8-9de3-b9f1f6108a62.PNG)

![error4](https://user-images.githubusercontent.com/40223102/49029937-f5aba500-f173-11e8-852f-083744ac43cd.PNG)

**Comment by seliverstov** [comment]
https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/__init__.py

**Comment by SahithiParsi** [comment]
@LuisQ95 is it resolved? i am facing the same error. @seliverstov could you help.

![image](https://user-images.githubusercontent.com/16195067/80368044-bb36c200-88a9-11ea-8cde-304d6f5a552e.png)
