### ISSUE TITLE
script for creating the ontonotes dataset

### ISSUE THREAD

**Issue by pjmal** [deepmipt/DeepPavlov#629]
I would like to test deeppavlov NER with the other two languages of the OntoNotes dataset. You only provide the English data as a single file ontonotes_senna.pckl. However, I didn't find any mention in your documents or scripts how you created this file from the original raw Ontonotes data, containing all 3 languages. Is that script available somewhere, so that I could easily extract also the Chinese or Arabic datasets in the correct format for Deeppavlov?

**Comment by mu-arkhipov** [comment]
Hello!

You can find the script for parsing OntoNotes here: https://gist.github.com/mu-arkhipov/e06c70259aa6420de15469786cf5b018
Note: it treats each sentence as separate training example.

**Comment by pjmal** [comment]
Hi, thanks, but that script doesn't seem to match at least the raw Ontonotes data I have (v.5.0), where the raw files with NER tags are in a hierarchy like 
ontonotes-release-5.0/data/files/data/english/annotations/bn/cnn/00/cnn_0035.name
and contain the tags in this format:
<ENAMEX TYPE="DATE">today</ENAMEX>
Is your script taking as input some other type of files than cnn_0035.name?
So, I'm looking for a script which would read eg. all tagged files under the english (or chinese) main directory, and then create the train, test and valid text files or the pickled dict file as your ontonotes_senna.pckl

Another question, when training a model, in addition to printing out just the total F1 I would also like to output F1 score separately for each tag, similarly to your example on page
http://docs.deeppavlov.ai/en/latest/components/ner.html#ontonotes-ner
I'm using a default config file similar to your
https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_ontonotes.json
What would I need to change to print also the separate F1 scores for each tag?

**Comment by mu-arkhipov** [comment]
Not quite sure about the `.name' files. There is no files with such extension in my version of the dataset.

**Comment by pjmal** [comment]
Ok, you apparently have a premade dataset of just the English data, not the original raw data with 3 languages.
