### ISSUE TITLE
Unexpected loss shown during `deep.py train`

### ISSUE THREAD

**Issue by vikmary** [deepmipt/DeepPavlov#64]
`python deep.py train config.json`
first trains model, then loads it from disk and calculates valid and test scores.
In case when `load_path` and `save_path` differ, final test score will be calculated for model from `load_path`, which creates quite a confusion.

**Comment by yoptar** [comment]
In current version before evaluating the model, its `save_path` block in config is written over its `load_path`. But model in go_bot configs itself does not have save and load path, they are in its children, so config parser does not know, what to do.
We can try and do the paths thing deeper in the model's config tree, but i'm not sure that it's the right way.

**Comment by seliverstov** [comment]
Fixed in 0.0.2
