### ISSUE TITLE
Attribute error in COLAB 04_deeppavlov_chitchat.ipynb

### ISSUE THREAD

**Issue by taneta** [deepmipt/DeepPavlov#650]
Colab import error in the cell: 

`tf.reset_default_graph()`
`vocab_size = 100`
`hidden_dim = 100`
`inputs = tf.cast(tf.random_uniform(shape=[32, 10]) * vocab_size, tf.int32) # bs x seq_len`
`mask = tf.cast(tf.random_uniform(shape=[32, 10]) * 2, tf.int32) # bs x seq_len`
`inputs_len = tf.reduce_sum(mask, axis=1)`
`embedding_matrix = tf.random_uniform(shape=[vocab_size, hidden_dim])`

`encoder(inputs, inputs_len, embedding_matrix, hidden_dim)` 

Result:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-d0aed5ba09b6> in <module>()
      7 embedding_matrix = tf.random_uniform(shape=[vocab_size, hidden_dim])
      8 
----> 9 encoder(inputs, inputs_len, embedding_matrix, hidden_dim)

<ipython-input-21-ec2c86052107> in encoder(inputs, inputs_len, embedding_matrix, cell_size, keep_prob)
     12         encoder_cell = tf.nn.rnn_cell.GRUCell(
     13                             num_units=cell_size,
---> 14                             kernel_initializer=tf.contrib.layers.xavier_initializer(),
     15                             name='encoder_cell')
     16 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py in __getattr__(self, item)
     51 
     52   def __getattr__(self, item):
---> 53     module = self._load()
     54     return getattr(module, item)
     55 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/lazy_loader.py in _load(self)
     40   def _load(self):
     41     # Import the target module and insert it into the parent's namespace
---> 42     module = importlib.import_module(self.__name__)
     43     self._parent_module_globals[self._local_name] = module
     44 

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/__init__.py in <module>()
     47 from tensorflow.contrib import deprecated
     48 from tensorflow.contrib import distribute
---> 49 from tensorflow.contrib import distributions
     50 from tensorflow.contrib import estimator
     51 from tensorflow.contrib import factorization

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/distributions/__init__.py in <module>()
     36 from tensorflow.contrib.distributions.python.ops.distribution_util import softplus_inverse
     37 from tensorflow.contrib.distributions.python.ops.distribution_util import tridiag
---> 38 from tensorflow.contrib.distributions.python.ops.estimator import *
     39 from tensorflow.contrib.distributions.python.ops.geometric import *
     40 from tensorflow.contrib.distributions.python.ops.half_normal import *

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/distributions/python/ops/estimator.py in <module>()
     19 from __future__ import print_function
     20 
---> 21 from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
     22 from tensorflow.contrib.learn.python.learn.estimators.head import _RegressionHead
     23 from tensorflow.python.framework import ops

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/__init__.py in <module>()
     94 
     95 # pylint: disable=wildcard-import
---> 96 from tensorflow.contrib.learn.python.learn import *
     97 # pylint: enable=wildcard-import
     98 

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/__init__.py in <module>()
     26 
     27 # pylint: disable=wildcard-import
---> 28 from tensorflow.contrib.learn.python.learn import *
     29 # pylint: enable=wildcard-import

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py in <module>()
     28 from tensorflow.contrib.learn.python.learn import basic_session_run_hooks
     29 from tensorflow.contrib.learn.python.learn import datasets
---> 30 from tensorflow.contrib.learn.python.learn import estimators
     31 from tensorflow.contrib.learn.python.learn import graph_actions
     32 from tensorflow.contrib.learn.python.learn import learn_io as io

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py in <module>()
    300 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
    301 from tensorflow.contrib.learn.python.learn.estimators.constants import ProblemType
--> 302 from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
    303 from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNEstimator
    304 from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNRegressor

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py in <module>()
     33 from tensorflow.contrib.layers.python.layers import optimizers
     34 from tensorflow.contrib.learn.python.learn import metric_spec
---> 35 from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
     36 from tensorflow.contrib.learn.python.learn.estimators import estimator
     37 from tensorflow.contrib.learn.python.learn.estimators import head as head_lib

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py in <module>()
     34 from tensorflow.contrib.layers.python.layers import optimizers
     35 from tensorflow.contrib.learn.python.learn import metric_spec
---> 36 from tensorflow.contrib.learn.python.learn.estimators import estimator
     37 from tensorflow.contrib.learn.python.learn.estimators import head as head_lib
     38 from tensorflow.contrib.learn.python.learn.estimators import model_fn

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py in <module>()
     50 from tensorflow.contrib.learn.python.learn.estimators import tensor_signature
     51 from tensorflow.contrib.learn.python.learn.estimators._sklearn import NotFittedError
---> 52 from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
     53 from tensorflow.contrib.learn.python.learn.utils import export
     54 from tensorflow.contrib.learn.python.learn.utils import saved_model_export_utils

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py in <module>()
     24 from __future__ import print_function
     25 
---> 26 from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
     27 from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_labels
     28 from tensorflow.contrib.learn.python.learn.learn_io.dask_io import HAS_DASK

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py in <module>()
     31 try:
     32   # pylint: disable=g-import-not-at-top
---> 33   import dask.dataframe as dd
     34   allowed_classes = (dd.Series, dd.DataFrame)
     35   HAS_DASK = True

/usr/local/lib/python3.6/dist-packages/dask/dataframe/__init__.py in <module>()
      2 
      3 try:
----> 4     from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      5                        repartition, to_datetime, to_timedelta)
      6     from .groupby import Aggregation

/usr/local/lib/python3.6/dist-packages/dask/dataframe/core.py in <module>()
     33 from ..delayed import delayed, Delayed, to_task_dask
     34 
---> 35 from . import methods
     36 from .accessor import DatetimeAccessor, StringAccessor
     37 from .categorical import CategoricalAccessor, categorize

/usr/local/lib/python3.6/dist-packages/dask/dataframe/methods.py in <module>()
      8 from toolz import partition
      9 
---> 10 from .utils import PANDAS_VERSION
     11 from ..utils import Dispatch
     12 if PANDAS_VERSION >= '0.20.0':

/usr/local/lib/python3.6/dist-packages/dask/dataframe/utils.py in <module>()
     11 import numpy as np
     12 import pandas as pd
---> 13 import pandas.util.testing as tm
     14 from pandas.api.types import is_categorical_dtype, is_scalar
     15 try:

AttributeError: module 'pandas.util' has no attribute 'testing'

**Comment by vikmary** [comment]
Ran the same cell in COLAB and couldn't reproduce the error. Seems like some package import issue. Try to reload colab url and run on a different machine.
