### ISSUE TITLE
building stateless models (to serve as shared resource for memory usage optimizing)

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#653]
Hi!
I've built a skill 'phonebook', based on dstc2 gobot.

Such a gobot has a "tracker" subcomponent.
It means that if I use build_model(...json) then the model is being loaded into the memory and keeps state of the dialog.

So as I can see if **several** users started their **dialogs** with the same model I have to **load several models** (one model for each dialog).
But this is a problem because each model needs **a lot of memory** (possibly because of loading large embeding models).

Is there a ready-to-use way to **avoid abundant memory consumption**?
For example can I easily transform dstc2.json component excluding "tracker" subcomponent and track dialog states somewhere out of the gobot (for example at appropriate skill wrapper)?
How to do so?
Or If there an easier way to reduce memory usage?

**Comment by vikmary** [comment]
Hi @vitalyuf,
Thanks for the feedback, we're aware of the single user support issue of `go_bot` and will try to faster fix it.

The hot fix you can make is the following:
1. Every attribute in `deeppavlov.models.go_bot.bot:GoalOrientedBot.reset_state` is user-specific. So all attributes should be in the input of the whole pipeline and `deeppavlov.models.go_bot.bot:GoalOrientedBot.r__call__` method. `__call__` should also return updates version of the attributes (the final `GoalOrientedBot` object shouldn't save any state).
For that to work you should modify python code of bot.py and config too.
2. The best way is to create a new pipeline variable "state", which contains all the user-specific values.

In the end you can start a REST API server that expects the whole state of a user and can make predictions for multiple users. (Though you would have to store the state of all users yourself.)

3.  Optionaly if your pipeline input consists of three variables: `response`, `history` and `state`, it can be then interpreted as a "Skill". And there is a specifial class `Agent` that will store the states for all users for you. For a statefull agent example:

```python
from deeppavlov.agents.default_agent.default_agent import DefaultAgent         
from deeppavlov.agents.processors.highest_confidence_selector import HighestConfidenceSelector

from deeppavlov import build_model, configs

skill = build_model('/path/to/your/config', download=True) # is already a skill, not just a model
agent = DefaultAgent([skill], skills_selector=HighestConfidenceSelector())

agent(['hello, i want some cheap food'])
```

**Comment by vitalyuf** [comment]
thank you!
Please, tell me how to desribe a pipeline variable in configuration file?

**Comment by vitalyuf** [comment]
Thank you!
All worked well!
