### ISSUE TITLE
Continue training a model

### ISSUE THREAD

**Issue by tuyoisaza** [deepmipt/DeepPavlov#658]
Hi!
How do you continue training a model.
Lets say not the keras way by model.fit() but the deeppavlov way...

Im thinking that there might be something like train_evaluate_model_from_config(config=config, epoch=100) or something?
Thanks!

**Comment by yoptar** [comment]
Hi!

You can use `train_evaluate_model_from_config(config=config, start_epoch_num=100)`, but it will only affect logging and a corresponding field in a report for event handlers in your model
