### ISSUE TITLE
Make ROOT_PATH, MODELS_PATH and DOWNLOADS_PATH environment variables

### ISSUE THREAD

**Issue by Guitaricet** [deepmipt/DeepPavlov#665]
All config files I've seen so far have the following variables:
```
"ROOT_PATH": "~/.deeppavlov",
"DOWNLOADS_PATH": "{ROOT_PATH}/downloads",
"MODELS_PATH": "{ROOT_PATH}/models"
```
Should we make them environment variables?
This would be better for the following reasons:
1. No need to define the same variables across all configs
1. No need to redefine variables for your system. For example, I do not store source code and downloads/models at same place (cause of their huge size), so I need to change configs for me and change them _back_ to make PR (that is kind of ridiculous). If these variables were in the environment, I'd have to change them only one time - after deeppavlov installation.
1. Make configs working directory independent (no '~/'-paths)

**Comment by nikolay-bushkov** [comment]
If someone implements this, change variable names to something specific like "DEEPPAVLOV_ROOT_PATH" in order to avoid name clashes.

**Comment by yoptar** [comment]
Proposed solution: environment variable `DP_VARIABLE_NAME` should be interpreted as `VARIABLE_NAME` variable in configs

**Comment by seliverstov** [comment]
Another solution: use syntax like ENV:VARIABLE_NAME in configs to reference any env variable
