### ISSUE TITLE
Install & First Tutorial

### ISSUE THREAD

**Issue by RyPoints** [deepmipt/DeepPavlov#671]
I am going through the install of deeppavlov and the first tutorial.

I created a fresh EC2 for install and also attempted this on my local machine and saw the same issues.

**Step 1.**  Installed Python 3.6.
**Step 2.** Successfully installed DeepPavlov via pip.
**Step 3.** Implement the pattern matching tutorial on the README and here: https://github.com/deepmipt/DeepPavlov/blob/master/examples/tutorials/00_deeppavlov_intro.ipynb

When I run the code I see:

```
Traceback (most recent call last):
  File "deeppavlov.py", line 6, in <module>
    from deeppavlov.skills.pattern_matching_skill import PatternMatchingSkill
  File "/home/ec2-user/deeppavlov.py", line 6, in <module>
    from deeppavlov.skills.pattern_matching_skill import PatternMatchingSkill
ModuleNotFoundError: No module named 'deeppavlov.skills'; 'deeppavlov' is not a package
```

If I download the repository and put the .py in the root directory and run the code again, it functions as expected though.  I'm also not using a virtualenv, if that matters, and I haven't downloaded any of the preexisting models or created a config file.

Any idea what's needed to get this first tutorial functioning?

**Comment by Snedashkovsky** [comment]
I have the error after installing on Ubuntu 18.04 without using a virtualenv  
(```sudo -H pip3 install deeppavlov```):
```ImportError: cannot import name ‘HighestConfidenceSelector’```
Python version is 3.6.7

**Comment by yoptar** [comment]
Hi, @RyPoints!
Looks like the problem is in a naming conflict: your script is named `deepavlov.py`, so when you try to `import deeppavlov` python looks in this file first.

**Comment by yoptar** [comment]
@Snedashkovsky, if you're still having trouble, please open a new issue with a little bit more information, like the error stacktrace and what code you're trying to run.

**Comment by aakash086** [comment]
Though the issue is closed without resolution hence allow me to write the resolution which is to use :
"from deeppavlov.agents.processors.highest_confidence_selector import HighestConfidenceSelector" it should work.
Thanks
