### ISSUE TITLE
Spelling correction not working properly

### ISSUE THREAD

**Issue by Aswarthadk** [deepmipt/DeepPavlov#679]
All the modules and files are imported by using below commands .

_**import sys
from deeppavlov import build_model, configs
CONFIG_PATH = configs.spelling_correction.brillmoore_kartaslov_ru
model = build_model(CONFIG_PATH, download=True)*_*

Checking the model as below. 
'g' is the parameter I have passed to the model .it is giving output as same word every time.

> **g='perimeteri'   
> model([g])[0]**

output after running above code is " perimeteri"

> g='parti'
> model([g])[0]

output after running above code is " parti"

Could you please check am I doing in a right way or not?

**Comment by yoptar** [comment]
Hi! [brillmoore_kartaslov_ru](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/spelling_correction/brillmoore_kartaslov_ru.json) is a config for russian language in cyrillic. If you want to correct english text, you can use the [brillmoore_wikitypos_en](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/spelling_correction/brillmoore_wikitypos_en.json) configuration file.
You can also take [https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/spelling_correction/levenshtein_corrector_ru.json](levenshtein_corrector_ru) as a base and give it your own list of all acceptable words and a [kenlm](https://github.com/kpu/kenlm) language model file

**Comment by Aswarthadk** [comment]
Thank you
