### ISSUE TITLE
DSTC2 Intent output seems to have no labels

### ISSUE THREAD

**Issue by Weilin37** [deepmipt/DeepPavlov#680]
I am having issue getting the correct output for intent classification using dstc2 big

I am following this documentation: https://github.com/deepmipt/DeepPavlov/blob/master/docs/components/classifiers.rst#id53

My code is the following:
```
import os
from deeppavlov import build_model, configs

os.environ["KERAS_BACKEND"] = "tensorflow"

CONFIG_PATH =  configs.classifiers.intents_dstc2_big
model = build_model(CONFIG_PATH, download=True)
print(model(["Hello"]))
```
I am expecting an output like this format:
```
"goals": {"pricerange": "cheap"},
"db_result": null,
"dialog-acts": [{"slots": [["pricerange", "cheap"]], "act": "inform"}]}
```

However, I am getting just an array of numbers like this:
```
[[0.004440320190042257, 0.0035526982974261045, 0.003814868861809373, 0.004386670421808958, 0.0026496422942727804, 0.004122086800634861, 0.004859328735619783, 0.005762884858995676, 0.006169301923364401, 0.9743947386741638, 0.005218957085162401, 0.004720163065940142, 0.006856555584818125, 0.0047727120108902454, 0.008368589915335178, 0.011183635331690311, 0.007578883320093155, 0.005414197687059641, 0.008248056285083294, 0.005105976946651936, 0.005934832151979208, 0.005890967790037394, 0.005130860488861799, 0.005532102193683386, 0.005490032024681568, 0.0046647703275084496, 0.004590084310621023, 0.004707065410912037]]
```

Any help would be appreciated!

**Comment by Weilin37** [comment]
Thank you. I have one more quick question. I changed my code to the following:

```
import os
from deeppavlov import build_model, configs
from deeppavlov.core.common.file import read_json

os.environ["KERAS_BACKEND"] = "tensorflow"

CONFIG_PATH =  configs.classifiers.intents_dstc2_big
model_config = read_json(CONFIG_PATH)
model_config['chainer']['out'] =  ['y_pred_labels']

model = build_model(model_config, download=True)
print(model(["thank you good bye"]))
print(model(["Hello"]))

```

The output of "thank you good bye" matches the documentation.
However, the output of "Hello" is "Unknown", when it should be labeled as greeting. Am I doing something wrong here?

**Comment by Weilin37** [comment]
Thanks a lot for your help. 

Do you have any idea why "hello" outputs blank?

**Comment by dilyararimovna** [comment]
It's just not very confident in this class (as you can see probability of belonging to `hello` class is equal to 0.32). 
You can try to vary `confident_threshold` to obtain more accurate model.

**Comment by Weilin37** [comment]
Thanks! It seems like I'm getting the current output now.
