### ISSUE TITLE
Как в autofaq лучше реализовать проверку на сколько выбранный класс подходит входящему условию?

### ISSUE THREAD

**Issue by trembolon58** [deepmipt/DeepPavlov#682]
В примере по ссылке ниже не работат скилл fallback, так как скилл faq возвращет вероятность отнесения к однму из классов и сумма вероятностей равна единице. Тоесть если во входящем сообщении есть слово, которое присутствует только в одном варианте faq, вернется единица, хотя данный ответ неверный.
[Новогодний скилл для Яндекс.Алиса с помощью DeepPavlov](https://github.com/deepmipt/DeepPavlov/blob/ae7ee6254976516078b424329d7ef171be0d1550/examples/tutorials/yandex_faq.ipynb)

Как в autofaq лучше реализовать проверку на сколько выбранный класс подходит входящему условию?

**Comment by vaskonov** [comment]
Скилл fallback сработает в том случае, если все другие скиллы в агенте получили вероятность меньше 0.5. Кажется, что в данном случае надо поработать на точностью autoFAQ, и тут есть несколько вариантов. 
1) Попробовать применить другую модель autoFAQ.
2) Добавить примеры в тренировочную выборку.
Если в Вашей задаче есть много коротких команд - попробуйте autoFAQ на векторном представлении слов.

**Comment by trembolon58** [comment]
Я решил эту проблему использованием определения перефразирования, установив верный ответ начиная с вероятности выше 89%, а дальше выбираю наиболее вероятный ответ.
