### ISSUE TITLE
ConfigError: 'Model char_vocab is not registered.' in the new deeppavlov version

### ISSUE THREAD

**Issue by pjmal** [deepmipt/DeepPavlov#684]
I had a working Ontonotes NER system, but now after updating deeppavlov to the newest version, and changing from build_model_from_config(config) to build_model(config) and making the documented changes to the config file (based on the example ner_ontonotes.json) I get the following error:
ConfigError: 'Model char_vocab is not registered.'

This is the part in the config file which worked in an earlier version (name replaced with class_name):
      {
        "in": ["x_char"],
        "id": "char_vocab",
        "class_name": "char_vocab",
        "pad_with_zeros": true,
        "fit_on": ["x_char"],
        "save_path": "/path/char.dict",
        "load_path": "/path/char.dict",
        "out": ["x_char_ind"]
      },

I don't see any obvious reason why that wouldn't be registered, especially as the other simple_vocab from same script works (these are just before the char_voab-part in the config file):
      {
        "in": ["y"],
        "id": "tag_vocab",
        "class_name": "simple_vocab",
        "pad_with_zeros": true,
        "fit_on": ["y"],
        "save_path": "/path/tag.dict",
        "load_path": "/path/tag.dict",
        "out": ["y_ind"]
      },
      {
        "in": ["x_tokens"],
        "class_name": "char_splitter",
        "out": ["x_char"]
      },
Any ideas what could be wrong and how to fix that?

**Comment by mu-arkhipov** [comment]
Hello!
The `simple_vocab` now support both character and token level. So, you need to just replace the `char_vocab` with `simple_vocab`, it should work fine.
