### ISSUE TITLE
question: Формат данных для tf-idf ранкера

### ISSUE THREAD

**Issue by drunkinlove** [deepmipt/DeepPavlov#690]
Хочу обучить tf-idf ранкер на большом количестве текстов, поэтому посчитал целесообразным сразу поместить их в SQLite-базу. Подскажите, пожалуйста, какие параметры следует указать для dataset_reader в [конфиг-файле](https://github.com/deepmipt/DeepPavlov/blob/0.1.5.1/deeppavlov/configs/doc_retrieval/ru_ranker_tfidf_wiki.json), чтобы использовать эту базу для обучения ранкера, минуя фазу её автоматического составления?

**Comment by my-master** [comment]
Чтобы обучить на уже готовой SQLite БД, нужно рядом с файлом БД положить файлик `<DB_name.db>.done`. Например, если файл c SQLite БД называется `ruwiki.db`, то положить рядом файл `ruwiki.db.done`.  В этом случае этап создания БД будет игнорироваться.

Но нужно проследить, чтобы SQLite имела нужные названия колонок. Тексты статей должны лежать в поле `text`, а id документов - в поле `id`. В дефолтной БД из DeepPavlov используются названия статей вики в качестве `id`, но можно использовать и что-то другое, например, просто номера текстов.

**Comment by drunkinlove** [comment]
Благодарю за ответ.
