### ISSUE TITLE
Принцип работы tf-idf ранкера

### ISSUE THREAD

**Issue by drunkinlove** [deepmipt/DeepPavlov#694]
Добрый день!

Правильно ли я понимаю принцип работы tf-idf ранкера: для каждой биграммы в запросе вычисляется td-idf оценка по каждому документу, затем эти оценки суммируются по биграммам (а точнее -- bi-gram bins), и ранкер выбирает несколько документов с наибольшей суммой?

**Comment by my-master** [comment]
Добрый день,

Если точнее, то так. Для каждого запроса считается tf-idf вектор размерностью  `1 x N`, где `N` - количество термов (мы считаем как юниграмы, так и биграмы) по тому же принципу, по которому он считается для документов. Затем этот вектор умножается (dot) на имеющуюся tf-idf матрицу всех документов. Размерность матрицы документов  `N x M`, где `N` - количество термов, а `M` - количество документов в БД. В результате умножения мы получаем вектор размерностью `1 X M`, из которого уже вычисляем нужные документы по индексам максимальных значений вектора.

**Comment by drunkinlove** [comment]
Спасибо!

А на каком этапе происходит хеширование?

**Comment by my-master** [comment]
Хеширование происходит каждый раз при вызове `HashingTfidfVectorizer`. На этапе тренировки документы хешируются сразу после токенизации и разбивки на n-грамы. На этапе инференса хешируются только n-грамы входящего вопроса.
