### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by tower-app** [deepmipt/DeepPavlov#707]
**Seems to me that** `python3.6 -m deeppavlov download deeppavlov/configs/squad/squad.json` **results in script failure due to connection time out:**

> 2019-02-07 08:32:17.499 DEBUG in 'urllib3.connectionpool'['connectionpool'] at line 205: Starting new HTTP connection (1): files.deeppavlov.ai:80
> Traceback (most recent call last):
>   File "/root/env/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw)
>   File "/root/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
>     raise err
>   File "/root/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
>     sock.connect(sa)
> TimeoutError: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/root/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.6/http/client.py", line 1239, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.6/http/client.py", line 964, in send
>     self.connect()
>   File "/root/env/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
>     conn = self._new_conn()
>   File "/root/env/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1f1946c18>: Failed to establish a new connection: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/root/env/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
>     timeout=timeout
>   File "/root/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/root/env/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='files.deeppavlov.ai', port=80): Max retries exceeded with url: /embeddings/ft_native_300_ru_wiki_lenta_nltk_word_tokenize-char.vec.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1f1946c18>: Failed to establish a new connection: [Errno 110] Connection timed out',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/env/lib/python3.6/site-packages/deeppavlov/__main__.py", line 3, in <module>
>     main()
>   File "/root/env/lib/python3.6/site-packages/deeppavlov/deep.py", line 77, in main
>     deep_download(pipeline_config_path)
>   File "/root/env/lib/python3.6/site-packages/deeppavlov/download.py", line 143, in deep_download
>     download_resource(url, dest_paths)
>   File "/root/env/lib/python3.6/site-packages/deeppavlov/download.py", line 114, in download_resource
>     if check_md5(url, dest_paths):
>   File "/root/env/lib/python3.6/site-packages/deeppavlov/download.py", line 79, in check_md5
>     r = requests.get(url + '.md5')
>   File "/root/env/lib/python3.6/site-packages/requests/api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "/root/env/lib/python3.6/site-packages/requests/api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/root/env/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/root/env/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
>     r = adapter.send(request, **kwargs)
>   File "/root/env/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='files.deeppavlov.ai', port=80): Max retries exceeded with url: /embeddings/ft_native_300_ru_wiki_lenta_nltk_word_tokenize-char.vec.md5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1f1946c18>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by litinsky** [comment]
Issue could not be reproduced neither by DeepPavlov team, nor by other DP users. We consider that this issue cause is inside user's network.  Issue closed.
