### ISSUE TITLE
Rename `utils` module to something else

### ISSUE THREAD

**Issue by mu-arkhipov** [deepmipt/DeepPavlov#708]
At the moment all utils are located in the `utils` directory in the root of the repository. So, after installation of `deeppavlov` using pip the import from this module will look like:
`from utils.alice import start_alice_server`
At the same time import from the library looks like:
`from deeppavlov import build_model, configs`
So, it is not obvious that the utils module belongs to the deeppavlov repository.
May be it should be renamed to something like: `deeppavlov_utils`

**Comment by yoptar** [comment]
It should be mostly moved to the `deeppavlov` module divided into multiple modules. The `utils.prepare` module should not be installed at all, for example.

**Comment by yoptar** [comment]
Fixed in #744
