### ISSUE TITLE
i have a requirement to retrieve data from tables by giving a value as an input (input and its value that already exists in table) , but the table structure is not always the same its generic , Please provide helpful information

### ISSUE THREAD

**Issue by csrujan** [deepmipt/DeepPavlov#709]
We don't know the structure of the table but we need to be able to retrieve data from table that is generic , what i mean by generic is we will not know the structure of the table , it might be in any structure, will deeppavlov framework help me for this prblm , if not please help me with a solution that helps to TRAIN the model so that if i give an input like feature of a product (ex: like ram for iphone 6) i need to get the value of the ram that is present in table but table may be or may not be like this [http://media.gizmodo.co.uk/wp-content/uploads/2016/03/iphone-se-table1.png](url)

**Comment by mu-arkhipov** [comment]
Unfortunately our library do not support working with tables. However, there are some interesting works devoted to this problem. Please have a look at the following works:
https://arxiv.org/pdf/1706.02427.pdf
https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43806.pdf
