### ISSUE TITLE
how to remove loaded model from RAM?

### ISSUE THREAD

**Issue by glebmikha** [deepmipt/DeepPavlov#713]
Is there a way to clear memory after certain model is loaded? I'm using rusentiment elmo classifier. I've tried:

1) tf.keras.backend.clear_session() 
2) del model and then gc.collect()
3) model = None and gc.collect()
Nothing worked out.

Is there a best practice for removing loaded model from memory with all its embedding, etc?

**Comment by yoptar** [comment]
Hi!
You can try and call the `model.destroy()` method. It will not clear everything, but the embedding should be removed from memory after that.

**Comment by glebmikha** [comment]
I've tried destroy() with my model and it does destroy model, but memory stays untouched. Literary same RAM usage before and after destroy. What do you thing?

**Comment by yoptar** [comment]
Are we talking about RAM on a video card? And are you running your model in jupyter or as a script?

**Comment by yoptar** [comment]
@kudep, please look into elmo embedder's RAM usage and if we can clear anything in `.destroy()` there

**Comment by glebmikha** [comment]
> Are we talking about RAM on a video card? And are you running your model in jupyter or as a script?

I'm running on cpu in jupyter and using only regular ram. I also plan to use it as a script (in flask)

**Comment by yoptar** [comment]
Should be fixed by #745
