### ISSUE TITLE
Error installing deeppavlov on google cloud engine

### ISSUE THREAD

**Issue by MNCTTY** [deepmipt/DeepPavlov#728]
Hi
I faced some issue, installing deeppavlov module via !pip in jupyter notebook on google cloud computer engine

> error: Command "g++ -pthread -B /opt/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/opt/anaconda3/include/python3.7m -c sklearn/cluster/_dbscan_inner.cpp -o build/temp.linux-x86_64-3.7/sklearn/cluster/_dbscan_inner.o -MMD -MF build/temp.linux-x86_64-3.7/sklearn/cluster/_dbscan_inner.o.d" failed with exit status 1
>     
>     ----------------------------------------
>   Rolling back uninstall of scikit-learn
> Command "/opt/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bk0y8avp/scikit-learn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6f9o_h8v/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-bk0y8avp/scikit-learn/

But in Google Colab it has been installed very well.
How to be?

**Comment by yoptar** [comment]
Hi there!

Python3.7 is not yet supported. For now DeepPavlov only works on Python3.6.

**Comment by MNCTTY** [comment]
ok, thank you!
