### ISSUE TITLE
[bug] I saw a small typo

### ISSUE THREAD

**Issue by exelents** [deepmipt/DeepPavlov#729]
Hello, guys.

https://github.com/deepmipt/DeepPavlov/blob/66c676cc8db4994c8ddf8fc9bcd619bebd990245/deeppavlov/models/seq2seq_go_bot/bot.py#L86

In this file you have written 'target_vocab_soze', but it seems it should look like "target_vocab_size"
I don't want to make a pull request for this nonsense, just fix it yourself.

**Comment by exelents** [comment]
https://github.com/deepmipt/DeepPavlov/blob/66c676cc8db4994c8ddf8fc9bcd619bebd990245/deeppavlov/configs/seq2seq_go_bot/bot_kvret_train.json#L101
https://github.com/deepmipt/DeepPavlov/blob/66c676cc8db4994c8ddf8fc9bcd619bebd990245/deeppavlov/configs/seq2seq_go_bot/bot_kvret_train.json#L102

Two defines in json, I still have not run this code, but this config may have some troubles with parsing double-defined parameter.
Same situation with prod config for s2s gobot:

https://github.com/deepmipt/DeepPavlov/blob/66c676cc8db4994c8ddf8fc9bcd619bebd990245/deeppavlov/configs/seq2seq_go_bot/bot_kvret.json#L81
https://github.com/deepmipt/DeepPavlov/blob/66c676cc8db4994c8ddf8fc9bcd619bebd990245/deeppavlov/configs/seq2seq_go_bot/bot_kvret.json#L82

**Comment by vikmary** [comment]
https://github.com/deepmipt/DeepPavlov/pull/733

**Comment by exelents** [comment]
Thank you.
