### ISSUE TITLE
Move to tensorflow>=2.0.0

### ISSUE THREAD

**Issue by yoptar** [deepmipt/DeepPavlov#732]
We'll have to remove all `tf.contrib` usage and move from `bert_db` to `transformers` everywhere.

**Comment by Barracuda72** [comment]
To me this seems to be a major problem, as TensorFlow 1.x doesn't support Python 3.8+, and not going to:

https://github.com/tensorflow/tensorflow/issues/39768

So Py3.8 users (running Ubuntu 20.04, e.g.) can't use most (if any at all) of DeepPavlov models. 
(And it's better to be straight dead than to mix different Python versions on one machine.)

**Comment by andreabrduque** [comment]
Are there any updates on this issue?

**Comment by IgnatovFedor** [comment]
Tensorflow components will be removed in 1.0.0. In [1.0.0rc0](https://github.com/deepmipt/DeepPavlov/releases/tag/1.0.0rc0) all pytorch-based models support python 3.6-3.9.
