### ISSUE TITLE
NerNetwork issue

### ISSUE THREAD

**Issue by K-Mike** [deepmipt/DeepPavlov#740]
I think there should be `embedding_layer` calling, otherwise it'll be error when `token_emb_mat=None`.

https://github.com/deepmipt/DeepPavlov/blob/c5f481dea90ab06ea3def935987b3313d2e97b75/deeppavlov/models/ner/network.py#L177

**Comment by mu-arkhipov** [comment]
Hello,
As you can see, there are two cases: 
1) you have a pre-trained embedding matrix
2) you have no embedding matrix and train it from scratch
In the first case you use embeddings coming from the external embedder module. So, in this case you need not `embedding_lookup`.

**Comment by K-Mike** [comment]
Thanks, I solve it for myself, but maybe it'll be usefull for future work.

**Comment by mu-arkhipov** [comment]
If you have any error tracebacks coming from your code, feel free to post it here
