### ISSUE TITLE
error while training with database_dstc2.json

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#788]
Hi!
An error hapens when I fill sqlite dabase by launching comand
 "**python -m deeppavlov train database_dstc2.json**".
Could you help?

> 2019-04-04 12:29:44.588 INFO in 'deeppavlov.dataset_readers.dstc2_reader'['dstc2_reader'] at line 113: [loading dialogs from /home/yvi/.deeppavlov/downloads/dstc2/dstc2-trn.jsonlist]
> 2019-04-04 12:29:44.766 INFO in 'deeppavlov.dataset_readers.dstc2_reader'['dstc2_reader'] at line 113: [loading dialogs from /home/yvi/.deeppavlov/downloads/dstc2/dstc2-val.jsonlist]
> 2019-04-04 12:29:44.905 INFO in 'deeppavlov.dataset_readers.dstc2_reader'['dstc2_reader'] at line 113: [loading dialogs from /home/yvi/.deeppavlov/downloads/dstc2/dstc2-tst.jsonlist]
> 2019-04-04 12:29:45.75 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 51: No load path is set for Sqlite3Database!
> 2019-04-04 12:29:45.76 INFO in 'deeppavlov.core.data.sqlite_database'['sqlite_database'] at line 63: Loading database from /home/yvi/.deeppavlov/downloads/dstc2/resto.sqlite.
> 2019-04-04 12:29:45.107 INFO in 'deeppavlov.core.data.sqlite_database'['sqlite_database'] at line 63: Loading database from /home/yvi/.deeppavlov/downloads/dstc2/resto.sqlite.
> 2019-04-04 12:29:45.108 INFO in 'deeppavlov.core.commands.train'['train'] at line 236: Testing the best saved model
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/yvi/projects/DP_agent/DeepPavlov/deeppavlov/__main__.py", line 3, in <module>
>     main()
>   File "/home/yvi/projects/DP_agent/DeepPavlov/deeppavlov/deep.py", line 86, in main
>     start_epoch_num=start_epoch_num)
>   File "/home/yvi/projects/DP_agent/DeepPavlov/deeppavlov/core/commands/train.py", line 242, in train_evaluate_model_from_config
>     show_examples=train_config['show_examples'])
>   File "/home/yvi/projects/DP_agent/DeepPavlov/deeppavlov/core/commands/train.py", line 287, in _test_model
>     metrics = [(m.name, m.fn(*[outputs[i] for i in m.inputs])) for m in metrics_functions]
>   File "/home/yvi/projects/DP_agent/DeepPavlov/deeppavlov/core/commands/train.py", line 287, in <listcomp>
>     metrics = [(m.name, m.fn(*[outputs[i] for i in m.inputs])) for m in metrics_functions]
> **TypeError: accuracy() missing 2 required positional arguments: 'y_true' and 'y_predicted'**

As result sqlite-dabase is filled with data from **trn-file**. But Data from **val** and **tst** files are absent.

**Comment by vikmary** [comment]
Hi @vitalyuf !

Which version of `deeppavlov` do you use? Can't reproduce the error on the latest 0.2.0 release.

It is true that database is only updated with items present in `trn` file. It is expected behavior, cause model isn't designed to use any data from `val` or `tst` files.
If you want to construct database from all data, the easiest way seems to be to concatenate `trn`, `val` and `tst` files into one `trn` (do not forget to revert it back before training neural network model).

**Comment by vitalyuf** [comment]
I tired to repeoduce on v 0.2.0.
There is no error.
