### ISSUE TITLE
Answers broken 

### ISSUE THREAD

**Issue by alexriabtsev** [deepmipt/DeepPavlov#789]
![8B8F17A2-8380-4321-953A-072248E91FA9](https://user-images.githubusercontent.com/8425396/55565971-7cb0f100-5703-11e9-9533-626ca030b8b0.png)

**Comment by yoptar** [comment]
Hi @alexriabtsev,
Thank you for this issue.
We've actually updated both model and example questions for it in the [demo](https://demo.deeppavlov.ai/#/ru/odqa) some time ago, but no one remembered to answer you here, sorry about that.

**Comment by alexriabtsev** [comment]
где находится Эр-Рифа так и не знает ;)
