### ISSUE TITLE
Training & prediction with lowercased data

### ISSUE THREAD

**Issue by AnnaShaleva** [deepmipt/DeepPavlov#790]
As a part of chainer configuration pipline for NER you use module which performs lowercasing. Also you mentioned that at training stage the corpora were lemmatized and lowercased.

My question is whether it is possible to get NER prediction for lowercased string using one of your pre-trained models, e.g. 
`ner_model(['bob ross lived in florida'])`
`>>> [[['bob', 'ross', 'lived', 'in', 'florida']], [['B-PERSON', 'I-PERSON', 'O', 'O', 'B-GPE']]]`

Thanks for considering my question

**Comment by mu-arkhipov** [comment]
To do so you need to train a model with no casing.
There is a config in a separate branch that perform exactly this. Here is [config](https://github.com/deepmipt/DeepPavlov/blob/feat/lower-ner/deeppavlov/configs/ner/ner_rus_lower.json). You can download and run it to train the model.

**Comment by AnnaShaleva** [comment]
Thank you!
