### ISSUE TITLE
Different results for same input 

### ISSUE THREAD

**Issue by MNCTTY** [deepmipt/DeepPavlov#795]
Hello 
I noticed that pretrained Rus NER model gives from run to run different answers to same inputs. For example, some times it sees Яндекс as an organization, some times - no (as a O tag)
Why is so?

**Comment by mu-arkhipov** [comment]
Neural Networks are different from dictionaries. The output of Neural Network heavily depends on the context. For instance, if network was trained on **sentences** containing some name of an organization there is no guaranties that model will recognize **singleton** names of the same organization.

**Comment by MNCTTY** [comment]
Ok, now it's clear

**Comment by mu-arkhipov** [comment]
Stained glass
