### ISSUE TITLE
Meaning of split train test val gobot

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#796]
Hello
I have a problem with undestanding how to create my own set for gobot because i cant see any difference between trn tst val files in dtsc2. 
Am i missing something?

**Comment by vikmary** [comment]
Hi
trn, tst and val files have the same format but serve different purporses. `trn` is used to train (update weights of the gobot network), `val` is used for calculating performance during training (the scores are then used to decide when to stop training), `tst` is used for calculating final score of the trained model.

Does it answer your question?

**Comment by serhio7** [comment]
Partly.
In this case should I provide absolutely different set for train valid and test?

**Comment by vikmary** [comment]
That’s right. There must be no shared samples in train, valid and test.

**Comment by vikmary** [comment]
Do you have per_item_dialog_accuracy on train too? Then it can’t be caused by wrong train/valid/test. The problem is somewhere else

**Comment by serhio7** [comment]
I have per_item_dialog_accuracy  just as metric. As I can see , I'm getting zero accuracy because not working slot_filling.
Instead of slot value I see in y predicted only #slotname.
Is there problem with dstc_slot_vals.json?

**Comment by vikmary** [comment]
Yes, the case seems to be in slot_filling component.
Did you retrain slot_filler component for your set of slots?

**Comment by serhio7** [comment]
Just in progress
Is that notebook 2 from tutorial?

**Comment by vikmary** [comment]
Notebook 2 is ok.

[The documentation page](http://docs.deeppavlov.ai/en/master/skills/go_bot.html) might be more useful.

**Comment by skbalahere** [comment]
In Go Bot, training takes lot of time and even in terminal it is not getting completed even after 6 hours, can we have any other solution to this

**Comment by vikmary** [comment]
Hi @skbalahere,

go_bot trains ok on DSTC-2 for all [configs](https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/configs/go_bot).
What dataset do you use to train the go_bot and which config file?
