### ISSUE TITLE
non cooperative dialogues

### ISSUE THREAD

**Issue by smartinsightsfromdata** [deepmipt/DeepPavlov#797]
I have tried to find reference in the documentation on non-cooperative dialogues, but I haven't found anything.

How deeppavlov gobot can cope with non-cooperative dialogues?
Is there any plan / future work in this direction?

**Comment by vikmary** [comment]
Hi @smartinsightsfromdata,

By coping with non-cooperative dialogues you mean measuring dialogues' non-cooperativity level (as discussed [here](https://www.aclweb.org/anthology/P10-3001), for example)?
We haven't planned such features so far.

**Comment by smartinsightsfromdata** [comment]
Hi @vikmary Thanks for the reply.  Yes I refer to these type of dialogues. It is not always bordering to the nonsensical as some of the example in the paper.

A `restaurant` oriented example is as follow:
I want to book a restaurant for tonight. I have specified type of food, location and price.
Then I ask "what is the weather like tonight?", apparently completely against the flow for the restaurant booking  conversation.
In reality I'm trying to ascertain if it would be good to look for a restaurant with outside dining facility.

Where do I find details of your plans, to see if eventually this is inserted?

**Comment by oserikov** [comment]
Hey! I'm now working on the gobot. Now my main objective is refactoring but then i'll proceed working on extensions. I'm usually working in some PR labeled as work-in-progress and the features targeted are listed in the PR description. That's where one could find info on what's planned for the near future.
