### ISSUE TITLE
Remove KerasWrapper in favor of raw KerasModel

### ISSUE THREAD

**Issue by yoptar** [deepmipt/DeepPavlov#799]
For now we have two basic classes: [KerasModel](https://github.com/deepmipt/DeepPavlov/blob/613d265f7371ba05365a7d44485066293c169674/deeppavlov/core/models/keras_model.py#L34-L36) and [KerasWrapper](https://github.com/deepmipt/DeepPavlov/blob/613d265f7371ba05365a7d44485066293c169674/deeppavlov/core/models/keras_model.py#L99-L102). `KerasWrapper` is used only once: for the [MorphoTagger](https://github.com/deepmipt/DeepPavlov/blob/613d265f7371ba05365a7d44485066293c169674/deeppavlov/models/morpho_tagger/network.py#L323-L329) class.

One should remove the `KerasWrapper` class and rewrite `MorphoTagger` to be inherited from `KerasModel`.

**Comment by AlexeySorokin** [comment]
KerasWrapper is used to wrap external models written in pure Keras outside DeepPavlov if they implement train_on_batch and predict_on_batch. I do not think we should loose the possibility to adopt an already existing Keras model using two lines of code.

**Comment by yoptar** [comment]
Resolved in #918
