### ISSUE TITLE
Problem with value_error, creating train_model on ner_rus

### ISSUE THREAD

**Issue by MNCTTY** [deepmipt/DeepPavlov#801]
Hello again

I tried to train ner_rus on some custom dataset, and it failed doing parse_ner_file(self, file_name).
It says:

> parse_ner_file(self, file_name)

>      64                         pos_tags.append(pos)
>      65                     else:
> ---> 66                         token, *_, tag = line.split()
>      67                     tags.append(tag)
>      68                     tokens.append(token)
> 
> ValueError: not enough values to unpack (expected at least 2, got 1)

But I have no information, which file is the reason, or what position in it.

I created my train, test, valid text files exactly as in the folder .deeppavlov/downloads/total_rus  ones. If I use only them, code for training from your tutorial runs without any errors.

But even if I add some text from these example files to my custom ones, it still doesn't work with the same error - not enough values to unpack. 

So I think that for some reason it see only token without corresponding tag. But if I add original tokens and tags - why it doesn't see them?

I attached a part from my train file:

`Федеральное	Oналоговое	Oведомство	OСША	Oпо	Oитогам	Oаудита	Oобвинило	Oамериканскую	Oкорпорацию	OCoca-Cola	OFFв	Oнеуплате	Oналогов	Oна O ...`

I separate strings with '\t', as I see the strings in the original files separated.
And, by the way, I use custom tags. But they can't be the reason of error, right?

**Comment by vikmary** [comment]
Hi! Do you separate tokens by line breaks? You file should look like

```Федеральное	O
налоговое	O
ведомство	O
США	O
по	O
итогам	O
аудита	O
обвинило	O
американскую O
корпорацию	O
Coca-Cola	O
FFв	O
неуплате	O
налогов	O
на O```

Also sentences should be separated by additional line breaks (two in total) and there should be `-DOCSTART- O)` line between different "documents" (paragraphs or other independent chunks of text).

**Comment by MNCTTY** [comment]
Hi
This is the code to form the train.txt

```
file = open('train.txt','w', encoding='utf-8') 
for i in range(0, int(0.8*len(list_of_texts))):
    for j in range(0, len(list_of_texts[i])):
        line = list_of_texts[i][j] + '\t' + list_of_tags[i][j] + ' '
        file.write(line)
file.close()
```
As we can see I separate token from tags with tab space, and the current tag from the next token with just space (before your answer there were no last space in the line).
What kind of set of spaces do you advise to use?

By the way, if we open the original train.txt file, that layed in the  .deeppavlov/downloads/total_rus, we can see, that they have the format, very different to the one, described [here](http://docs.deeppavlov.ai/en/master/components/ner.html) or by you.
We see lots of strings, current token and tag are separated just by tab, and current tag is not separated in any way with the next token.

![Capture](https://user-images.githubusercontent.com/37251686/56292392-cc45e280-612f-11e9-937e-6fd9feacb687.JPG)

**Comment by vikmary** [comment]
Can it be that your text editor displays the `valid.txt` from .deeeppavlov/downloads wrong?

1. Token and tag should be **separated by tab**
2. Tokens should be **separated by a line break**
3. Sentences should be **separated by additional line break** (2 line breaks in total).

**Comment by MNCTTY** [comment]
hi
>Can it be that your text editor displays the valid.txt from .deeeppavlov/downloads wrong?
Yeah, now I opened in Notepad++ and it appears more such in the tutorial. 

So, a final question about the format:
is it correct that "line break" is a symbol "\n"? I can't google what **exactly** "line break" is.

**Comment by vikmary** [comment]
Yes, linebreak equals “\n”

**Comment by MNCTTY** [comment]
ok, thank you for anwering
I've rewrite 3 files in coordance to the instructions:

```
file = open('train.txt','w', encoding='utf-8') 
for i in range(0, int(0.8*len(list_of_texts))):
    for j in range(0, len(list_of_texts[i])):
        line = list_of_texts[i][j] + '\t' + list_of_tags[i][j] + '\n'
        file.write(line)
    file.write('\n')
file.close()
```
It gave me the output like this 
![Capture](https://user-images.githubusercontent.com/37251686/56436957-589a0600-62e6-11e9-87e5-19e915ba4bed.JPG)
And nothing changed in error:

> parse_ner_file(self, file_name)
>      64                         pos_tags.append(pos)
>      65                     else:
> ---> 66                         token, *_, tag = line.split()
>      67                     tags.append(tag)
>      68                     tokens.append(token)
> 
> ValueError: not enough values to unpack (expected at least 2, got 1)

Still the same :(
What can we do?

**Comment by vikmary** [comment]
Please check that 
- the file dataset reader is loading is really the one you write on disk with the script,
- all lines of your train.txt, valid.txt and test.txt containt word and tag (word must be a non-space symbol).

The file from your screenshot seems to be in the right format
