### ISSUE TITLE
Example of train-v1.json and dev-v1.json files for multisquad_none

### ISSUE THREAD

**Issue by alissiawells** [deepmipt/DeepPavlov#805]
SQUAD model with defolt confugurations gets all the answers only from the first paragraph. Should be the context for each question divided on paragraphs? I supposed multisquad model is more appropriate in this case but it requires contexts with questions in train dataset. I coudn't find any information in documentation, neither on github  about the format of of train-v1.json and dev-v1.json files for multisquad_none. Could you, please, describe it or provide an example?

**Comment by yurakuratov** [comment]
Hi!

If we are talking about SQuAD model with `squad.json` (or `squad_ru.json`) configuration file it cuts input paragraph with length more than 400 tokens (check parameter `context_limit` in `squad_preprocessor`). You can make this parameter bigger until it fits into GPU (we used 4000 tokens for single 1080ti).

To find answers in longer documents you will have to split them on chunks. In that case `multi_squad_noans.json` is more suitable, because you can use its confidence output to rank answers from each chunk. This model was trained not only on paragraphs which contain the answer, but also on paragraphs without answers. 

Here is the link to dataset that we used for training `multi_squad_noans` model: [http://files.deeppavlov.ai/datasets/multiparagraph_squad.tar.gz](http://files.deeppavlov.ai/datasets/multiparagraph_squad.tar.gz)

All links to SQuAD dataset could be found in [squad_dataset_reader.py](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_readers/squad_dataset_reader.py).

**Comment by alissiawells** [comment]
Thank you, you have responded to my question.If feedback is interesting for you, here the results of some tests for multi_squad_none:1) When the answer is in the end of the text, the most frequent response from model is None (“ “).Despite the fact that I didn’t ask irrelevant questions as “How did Mr Klinger start?”2) When the question contains a typo, model doesn’t answer None, its output is a wrong answer (for example, when we ask about the year, model responds about the profession). However,  V. Malykh from you Lab has defended a dissertation, dedicated to robust word vector representations.3) When we mention some relation between NE “person” and NE  “company” in the question, model mixes up the contexts. I suppose, it choses the closest one to begining of the text. For example, on the question “Which company Mr X began his career in?”I understand that that question isn’t correct gramatically. On the correct question the answer in None.However, I do appreciate you work and used the NER component in production. Can I do something to improve the results of the model? I guess fine-tuning diesn’t make sense in this case. It would work for texts with terminology, slang, other languages. Maybe the problem is in Ranker based on tf-idf. I will try to solve the problem for my case for myself, this information is just a feedback.--Alice Khoroshavina17.04.2019, 16:07, "yurakuratov" <notifications@github.com>:Hi!
If we are talking about SQuAD model with squad.json (or squad_ru.json) configuration file it cuts input paragraph with length more than 400 tokens (check parameter context_limit in squad_preprocessor). You can make this parameter bigger until it fits into GPU (we used 4000 tokens for single 1080ti).
To find answers in longer documents you will have to split them on chunks. In that case multi_squad_noans.json is more suitable, because you can use its confidence output to rank answers from each chunk. This model was trained not only on paragraphs which contain the answer, but also on paragraphs without answers.
Here is the link to dataset that we used for training multi_squad_noans model: http://files.deeppavlov.ai/datasets/multiparagraph_squad.tar.gz
All links to SQuAD dataset could be found in squad_dataset_reader.py.

**Comment by yurakuratov** [comment]
yeah, this model was not trained on data with typos and is not using any typos-robust word vectors.
It has character embedding layer to deal with with OOV words and maybe typos (but we didn't tested quality of question-answering depending on typos).

On SQuAD-v1.1 dataset this model achieves 80.34 F-1.
In DeepPavlov we also have BERT-based model trained on SQuAD-v1.1, it achieves ~88 F-1 score.

Can you try to use [this BERT-based model](https://github.com/deepmipt/DeepPavlov/blob/0.2.0/deeppavlov/configs/squad/squad_bert.json) config file on your data?

**Comment by alissiawells** [comment]
I’ve just tested squad_bert on smaller contexts (150-200 words) and it works perfect! Though outputs for contexts of ~400 words are still incorrect. I’ve decided to use your model with defolt configuration with provided API. The business task is the case: “user sends bot a link and asks questions about this site”. The parsing component is hidden under the hood, so, we can slice the content of the site on contexts of 200 words. All the misspelled words in a question will be corrected with a spellcheker. Then we will chose 10 the most relevant of contexts relatively to the question using tf-idf. Each element in a sorted list of contexts will be sended to the service with squad_bert model as a POST requests until the output isn’t “ “. Then the answer will be sended to the user. Thank you for your help and very useful researches!--Alissia Khoroshavina18.04.2019, 11:17, "yurakuratov" <notifications@github.com>:yeah, this model was not trained on data with typos and is not using any typos-robust word vectors.
It has character embedding layer to deal with with OOV words and maybe typos (but we didn't tested quality of question-answering depending on typos).
On SQuAD-v1.1 dataset this model achieves 80.34 F-1.
In DeepPavlov we also have BERT-based model trained on SQuAD-v1.1, it achieves ~88 F-1 score.
Can you try to use this BERT-based model config file on your data?
