### ISSUE TITLE
No module named 'bert_dp'

### ISSUE THREAD

**Issue by jgochal** [deepmipt/DeepPavlov#808]
Hi - When trying to run a SQUAD model with the squad_bert config, I get an error saying that dp_bert cannot be found (see below).  Any advice is much appreciated.  Thanks!

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-31-aab838f3dfaf> in <module>()
      1 
----> 2 model2 = build_model(configs.squad.squad_bert, download=True)
      3 model2(['DeepPavlov is library for NLP and dialog systems.'], ['What is DeepPavlov?'])

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/commands/infer.py in build_model(config, mode, load_trained, download, serialized)
     59             component_serialized = None
     60 
---> 61         component = from_params(component_config, mode=mode, serialized=component_serialized)
     62 
     63         if 'in' in component_config:

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py in from_params(params, mode, serialized, **kwargs)
     92         log.exception(e)
     93         raise e
---> 94     cls = get_model(cls_name)
     95 
     96     # find the submodels params recursively

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/registry.py in get_model(name)
     69             raise ConfigError("Model {} is not registered.".format(name))
     70         return cls_from_str(name)
---> 71     return cls_from_str(_REGISTRY[name])
     72 
     73 

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/registry.py in cls_from_str(name)
     38                           .format(name))
     39 
---> 40     return getattr(importlib.import_module(module_name), cls_name)
     41 
     42 

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.6/dist-packages/deeppavlov/models/preprocessors/bert_preprocessor.py in <module>()
     15 from typing import Tuple, List, Optional
     16 
---> 17 from bert_dp.preprocessing import convert_examples_to_features, InputExample, InputFeatures
     18 from bert_dp.tokenization import FullTokenizer
     19 

ModuleNotFoundError: No module named 'bert_dp'`

**Comment by yurakuratov** [comment]
Hi! 

You can see that `squad_bert` config file has `requirements` section describing all dependencies for this model.

All requirements for particular model in DeepPavlov can be installed via:
```
python -m deeppavlov install config_file
```
So, all you need is to run `python -m deeppavlov install squad_bert`

**Comment by jgochal** [comment]
Hi - Thanks for super quick reply!  

I ran  `python -m deeppavlov install squad_bert`, which work as expected.  So I'll close the issue.

**Comment by neerajvashistha** [comment]
Thanks, @yurakuratov  and @jgochal  for the comments but squad_bert installation requires tensorflow==1.10.0 which was released an year ago, can we rebuild it on newer versions like 1.12.3 ?

**Comment by yoptar** [comment]
Hi @neerajvashistha,
We actually released a newer version of DeepPavlov with updated dependencies just yesterday.
So you can run 
```
pip install deeppavlov==0.5.0
```
and then
```
python -m deeppavlov install squad_bert
```
It will install `tensorflow==1.14.0` (or `tensorflow-gpu==1.14.0` if you have any version of `tensorflow-gpu` installed already)

**Comment by waleedkaimkhani** [comment]
i am getting same error i tried above given solution 
using anaconda enviroment python3.7 windows 10 64 bit
 ![error](https://user-images.githubusercontent.com/31384546/73740096-54ea4980-4769-11ea-94fd-0d69658ff34f.png)

**Comment by yoptar** [comment]
Hi @waleedkaimkhani,
1. Did you run `python -m deeppavlov install squad_bert` and what was the output?
2. How are you running your model?

**Comment by waleedkaimkhani** [comment]
@yoptar thanks
git was not installed on my enviroment
first i installed git then used below command 
python -m deeppavlov install ner_conll2003_bert

**Comment by MaxNikitinn** [comment]
Hello everyone!
I came to this thread contracting `ModuleNotFoundError: No module named 'bert_dp'`
As of now when i run
`python -m deeppavlov install squad_bert`
it returns an error:
`subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', 'install', 'tensorflow==1.15.2']' returned non-zero exit status 1.`
and `pip install tensorflow==1.15.2` returns `No matching distribution found for tensorflow==1.15.2`
i tried with deeppavlov and deeppavlov==0.5.0, and tried insalling latest tensorflow.
In the end, as of now i have no idea how to install bert_dp for my model and i can't find requirements file either.
Anything would help.
Thanks!
