### ISSUE TITLE
Add custom embedder NER

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#809]
How to add custom embedder in NER network?

**Comment by mu-arkhipov** [comment]
A possible way to do so is to create a module `my_module` which is a python file `my_module.py` in the working directory. A simple example of the content of the file:

```python
class MyComponent:
    def __init__(self, *args, **kwargs):
        pass

    def __call__(self, x):
        print(x)
        return x
```
Then add the following to the config:
```json
      {
          "class_name": "mymodule:MyComponent",
          "in": ["x_tok_ind"],
          "out": ["x_tok_ind"]
      }
```

**Comment by mu-arkhipov** [comment]
An easy way is to take an existing config as a draft and modify it. For instance you can replace
```json
{
        "in": ["x_san"],
        "id": "embedder",
        "class_name": "fasttext",
        "pad_zero": true,
        "load_path": "{DOWNLOADS_PATH}/embeddings/lenta_lower_100.bin",
        "out": ["x_emb"]
      }
```
with `MyComponent`

```json
        "in": ["x_san"],
        "id": "embedder",
        "class_name": "mymodule:MyComponent",
        "out": ["x_emb"]
      }
```
In the https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/ner/ner_rus.json.

**Comment by yoptar** [comment]
I assume that the question is answered.
