### ISSUE TITLE
If output_dim == 1 then returns list of list of tensors, rather then list o tensors

### ISSUE THREAD

**Issue by GeorgeKaspar** [deepmipt/DeepPavlov#810]
![image](https://user-images.githubusercontent.com/36761521/56477421-fee43800-64ad-11e9-9ec5-318801353787.png)
should be m[0] in else branch

**Comment by yoptar** [comment]
Hi,
Thank you for reporting this issue.
The fix is merged into the `dev` branch and will be released next week.
