### ISSUE TITLE
Unable to load odqa model.

### ISSUE THREAD

**Issue by Pem14604** [deepmipt/DeepPavlov#811]
from deeppavlov import configs
from deeppavlov.core.commands.infer import build_model
odqa = build_model(configs.odqa.en_odqa_infer_wiki, load_trained=True)

I'm trying to load the model but m getting below error, could you please help.

  File "C:\Users\vsolanki\AppData\Local\Programs\Python\Python36\lib\site-packages\deeppavlov\models\vectorizers\hashing_tfidf_vectorizer.py", line 262, in load
    <input type="hidden" class="js-site-search-type-field" name="type" >
FileNotFoundError: HashingTfIdfVectorizer path doesn't exist!

**Comment by yoptar** [comment]
Hi,
to download a pretrained model you should use the `download` argument instead of `load_trained`.
`load_trained` argument is used for loading a model from its `save_path` instead of its `load_path` if they are different.
