### ISSUE TITLE
Dialogue Bot for goal-oriented task issue.

### ISSUE THREAD

**Issue by Pem14604** [deepmipt/DeepPavlov#812]
from deeppavlov import build_model, configs
bot1 = build_model(configs.go_bot.gobot_dstc2, download=True)

----------------------------------------------------------------------
2019-04-22 06:18:37.365 INFO in 'deeppavlov.core.data.utils'['utils'] at line 63: Downloading from http://files.deeppavlov.ai/datasets/dstc2_v2.tar.gz to /root/.deeppavlov/downloads/dstc2_v2.tar.gz
100%|██████████| 506k/506k [00:00<00:00, 743kB/s]
2019-04-22 06:18:38.53 INFO in 'deeppavlov.core.data.utils'['utils'] at line 201: Extracting /root/.deeppavlov/downloads/dstc2_v2.tar.gz archive into /root/.deeppavlov/downloads/dstc2
2019-04-22 06:18:38.681 INFO in 'deeppavlov.core.data.utils'['utils'] at line 63: Downloading from http://files.deeppavlov.ai/embeddings/glove.6B.100d.txt to /root/.deeppavlov/downloads/embeddings/glove.6B.100d.txt
347MB [00:20, 17.1MB/s]
2019-04-22 06:18:59.505 INFO in 'deeppavlov.core.data.utils'['utils'] at line 63: Downloading from http://files.deeppavlov.ai/deeppavlov_data/slotfill_dstc2.tar.gz to /root/.deeppavlov/slotfill_dstc2.tar.gz
100%|██████████| 641k/641k [00:00<00:00, 951kB/s]
2019-04-22 06:19:00.185 INFO in 'deeppavlov.core.data.utils'['utils'] at line 201: Extracting /root/.deeppavlov/slotfill_dstc2.tar.gz archive into /root/.deeppavlov/models
2019-04-22 06:19:00.769 INFO in 'deeppavlov.core.data.utils'['utils'] at line 63: Downloading from http://files.deeppavlov.ai/deeppavlov_data/gobot_dstc2_v7.tar.gz to /root/.deeppavlov/gobot_dstc2_v7.tar.gz
100%|██████████| 969k/969k [00:01<00:00, 543kB/s]
2019-04-22 06:19:01.853 INFO in 'deeppavlov.core.data.utils'['utils'] at line 201: Extracting /root/.deeppavlov/gobot_dstc2_v7.tar.gz archive into /root/.deeppavlov/models
2019-04-22 06:19:01.874 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /root/.deeppavlov/models/gobot_dstc2/word.dict]
2019-04-22 06:19:01.878 WARNING in 'deeppavlov.core.models.serializable'['serializable'] at line 47: No load path is set for Sqlite3Database in 'infer' mode. Using save path instead
2019-04-22 06:19:01.880 INFO in 'deeppavlov.core.data.sqlite_database'['sqlite_database'] at line 63: Loading database from /root/.deeppavlov/downloads/dstc2/resto.sqlite.
2019-04-22 06:19:04.804 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /root/.deeppavlov/models/slotfill_dstc2/word.dict]
2019-04-22 06:19:04.814 INFO in 'deeppavlov.core.data.simple_vocab'['simple_vocab'] at line 103: [loading vocabulary from /root/.deeppavlov/models/slotfill_dstc2/tag.dict]
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeppavlov/core/layers/tf_layers.py:948: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeppavlov/core/layers/tf_layers.py:66: conv1d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.conv1d instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeppavlov/core/layers/tf_layers.py:69: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.batch_normalization instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeppavlov/models/ner/network.py:248: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeppavlov/models/ner/network.py:259: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeppavlov/core/models/tf_model.py:49: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-04-22 06:19:06.539 INFO in 'deeppavlov.core.models.tf_model'['tf_model'] at line 50: [loading model from /root/.deeppavlov/models/slotfill_dstc2/model]
INFO:tensorflow:Restoring parameters from /root/.deeppavlov/models/slotfill_dstc2/model
/usr/local/lib/python3.6/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
paramiko missing, opening SSH/SCP/SFTP paths will be disabled.  `pip install paramiko` to suppress
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-7d0b0559004d> in <module>()
      1 from deeppavlov import build_model, configs
      2 
----> 3 bot1 = build_model(configs.go_bot.gobot_dstc2, download=True)

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/commands/infer.py in build_model(config, mode, load_trained, download, serialized)
     59             component_serialized = None
     60 
---> 61         component = from_params(component_config, mode=mode, serialized=component_serialized)
     62 
     63         if 'in' in component_config:

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py in from_params(params, mode, serialized, **kwargs)
     95 
     96     # find the submodels params recursively
---> 97     config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
     98 
     99     try:

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py in <dictcomp>(.0)
     95 
     96     # find the submodels params recursively
---> 97     config_params = {k: _init_param(v, mode) for k, v in config_params.items()}
     98 
     99     try:

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py in _init_param(param, mode)
     49     elif isinstance(param, dict):
     50         if {'ref', 'class_name', 'config_path'}.intersection(param.keys()):
---> 51             param = from_params(param, mode=mode)
     52         else:
     53             param = {k: _init_param(v, mode) for k, v in param.items()}

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/params.py in from_params(params, mode, serialized, **kwargs)
     92         log.exception(e)
     93         raise e
---> 94     cls = get_model(cls_name)
     95 
     96     # find the submodels params recursively

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/registry.py in get_model(name)
     69             raise ConfigError("Model {} is not registered.".format(name))
     70         return cls_from_str(name)
---> 71     return cls_from_str(_REGISTRY[name])
     72 
     73 

/usr/local/lib/python3.6/dist-packages/deeppavlov/core/common/registry.py in cls_from_str(name)
     38                           .format(name))
     39 
---> 40     return getattr(importlib.import_module(module_name), cls_name)
     41 
     42 

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.6/dist-packages/deeppavlov/models/embedders/glove_embedder.py in <module>()
     17 
     18 import numpy as np
---> 19 from gensim.models import KeyedVectors
     20 from overrides import overrides
     21 

/usr/local/lib/python3.6/dist-packages/gensim/__init__.py in <module>()
      3 """
      4 
----> 5 from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
      6 import logging
      7 

/usr/local/lib/python3.6/dist-packages/gensim/models/__init__.py in <module>()
      5 
      6 # bring model classes directly into package namespace, to save some typing
----> 7 from .coherencemodel import CoherenceModel  # noqa:F401
      8 from .hdpmodel import HdpModel  # noqa:F401
      9 from .ldamodel import LdaModel  # noqa:F401

/usr/local/lib/python3.6/dist-packages/gensim/models/coherencemodel.py in <module>()
     34 from gensim import interfaces, matutils
     35 from gensim import utils
---> 36 from gensim.topic_coherence import (segmentation, probability_estimation,
     37                                     direct_confirmation_measure, indirect_confirmation_measure,
     38                                     aggregation)

/usr/local/lib/python3.6/dist-packages/gensim/topic_coherence/probability_estimation.py in <module>()
     10 import logging
     11 
---> 12 from gensim.topic_coherence.text_analysis import (
     13     CorpusAccumulator, WordOccurrenceAccumulator, ParallelWordOccurrenceAccumulator,
     14     WordVectorsAccumulator)

/usr/local/lib/python3.6/dist-packages/gensim/topic_coherence/text_analysis.py in <module>()
     19 
     20 from gensim import utils
---> 21 from gensim.models.word2vec import Word2Vec
     22 
     23 logger = logging.getLogger(__name__)

/usr/local/lib/python3.6/dist-packages/gensim/models/word2vec.py in <module>()
    119 
    120 from gensim.utils import keep_vocab_item, call_on_class_only
--> 121 from gensim.models.keyedvectors import Vocab, Word2VecKeyedVectors
    122 from gensim.models.base_any2vec import BaseWordEmbeddingsModel
    123 

/usr/local/lib/python3.6/dist-packages/gensim/models/keyedvectors.py in <module>()
    160 # If pyemd is attempted to be used, but isn't installed, ImportError will be raised in wmdistance
    161 try:
--> 162     from pyemd import emd
    163     PYEMD_EXT = True
    164 except ImportError:

/usr/local/lib/python3.6/dist-packages/pyemd/__init__.py in <module>()
     73 
     74 from .__about__ import *
---> 75 from .emd import emd, emd_with_flow, emd_samples

__init__.pxd in init pyemd.emd()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by yoptar** [comment]
Hello again,
The Internet suggests that this could be caused by incompatible packages version.
I would try to upgrade `pip install --upgrade numpy scikit-image dask` and see if it would help.

**Comment by yoptar** [comment]
I assume that the issue is resolved. Please, don't hesitate to write here again if it is not.
