### ISSUE TITLE
Question Answering Model Download Query

### ISSUE THREAD

**Issue by Pem14604** [deepmipt/DeepPavlov#813]
Hi 
M able to use model directly in google colab by using below command.

from deeppavlov import build_model, configs
model = build_model(configs.squad.squad, download=True)
model(['DeepPavlov is library for NLP and dialog systems.'], ['What is DeepPavlov?'])

However when i try to download pretrained model it says ""FileNotFoundError: [Errno 2] No such file or directory: 'deeppavlov\\configs\\squad\\squad.json'""

python -m deeppavlov download deeppavlov/configs/squad/squad.json

Please guide to resolve this.

just to clarify all requirements have been installed successfully.
python -m deeppavlov install squad

Also i want to this model in on my own data, please suggest how i can do this.
i want to give input many word document at once.
![image](https://user-images.githubusercontent.com/43243814/56498416-3212df80-651f-11e9-846b-8255c8a011f5.png)

**Comment by yoptar** [comment]
You can run `python -m deeppavlov download squad`, then `squad` will be resolved as a path to the provided configuration file. But if you run the model from python it's enough to add the `download=True` argument to the `build_model` function.

As for the second question, if I understood you correctly, the squad model usage is as follows:
```python3
answers_list, answers_starts_list, logits_list = model(contexts_list, questions_list)
```
Where `contexts_list` and `questions_list` are required to have the same length.

**Comment by yoptar** [comment]
I assume that the issue is resolved. Please, don't hesitate to write here again if it is not.

**Comment by SaroMeenu** [comment]
Even i too get the same error
 FileNotFoundError: [Errno 2] No such file or directory: 'deeppavlov/configs/squad/squad.json'
