### ISSUE TITLE
Question: How to cite DeepPavlov?

### ISSUE THREAD

**Issue by kartikeyaSh** [deepmipt/DeepPavlov#815]
How can one cite DeepPavlov in research papers?
It would be great if that is written in the README.md.

**Comment by dilyararimovna** [comment]
Hello!
It would be great if you will cite the following paper:
```
Burtsev M. et al. DeepPavlov: Open-Source Library for Dialogue Systems //Proceedings of ACL 2018, System Demonstrations. – 2018. – С. 122-127.
```
Thank you in advance!

**Comment by kartikeyaSh** [comment]
@dilyararimovna Thanks, I'll cite it
