### ISSUE TITLE
Inconsistent dependancies ABI

### ISSUE THREAD

**Issue by bavadim** [deepmipt/DeepPavlov#822]
I try:
- build docker image with my App in Linux or OsX
- try use that in Digital Ocean cloud provider (Ubuntu 18.04)
- my App crash with "Illegal Instruction code" on 
```
from deeppavlov.models.tokenizers.spacy_tokenizer import \
    StreamSpacyTokenizer
from deeppavlov.models.preprocessors.russian_lemmatizer import \
    PymorphyRussianLemmatizer
```

**Comment by yoptar** [comment]
Can you provide a stack trace?
And does this image work on any other machine?

**Comment by bavadim** [comment]
There is not stacktraces here, because it is crash. It works on machine where it has been create, for example on macbook pro.

**Comment by yoptar** [comment]
Can you provide your dockerfile and more detailed info on the target system so that we could reproduce the error?

**Comment by bavadim** [comment]
# Dockerfile
FROM node:10-alpine as build_frontend
WORKDIR /smarttax-client
COPY smarttax-client/package.json smarttax-client/package-lock.json ./
RUN npm install
COPY smarttax-client ./
RUN npm run build
RUN ls -lah /smarttax-client/build

FROM python:3.6
WORKDIR /www

COPY requirements.txt /www/
RUN pip install -r requirements.txt

COPY smarttax-server /www/
COPY model /www/model
COPY --from=build_frontend /smarttax-client/build /www/frontend

RUN export FLASK_APP=server.py
RUN export FLASK_ENV=development
EXPOSE 5000
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "server:web_app"]

# requirements.txt

deeppavlov==0.1.6
pybind11==2.2.3
spacy==2.0.5
pika
tornado
git+https://github.com/deepmipt/fastText.git#egg=fastText==0.8.22
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm==2.0.0
flask
flask_restful
gunicorn
pymorphy2

**Comment by yoptar** [comment]
This issue is probably not getting resolved because of how long it has been.
If you still have this problem, please open another issue and we'll try to solve it then.
