### ISSUE TITLE
How to get the Bert part of the Bert SQuAD model?

### ISSUE THREAD

**Issue by lcswillems** [deepmipt/DeepPavlov#825]
Hi,

DeepPavlov is really great! Thank you for all your work. I was looking for a Bert model trained on SQuAD, and yours works perfectly.

Now, I would like to only get the Bert part of the Bert SQuAD model. How could I do?

My code is as simple as:

```
from deeppavlov import build_model, configs

text = '...'
question = '...'

model = build_model(configs.squad.squad_bert, download=True)
answer = model([text], [question])[0][0]
```

More precisely, instead of getting the answer in `answer`, I would like to get the Bert `pooled_output` of the text.

Would you have some hint for me?

**Edit**:
After doing some `dir`, I found I can get the `pooled_output` with
```
model.pipe[2][2].bert.pooled_output
```
However, it is a tensor, not the real tensor. I am near the solution, but if you still have some hint, I would 
be happy :)

**Comment by yurakuratov** [comment]
Hi!
It's a pleasure to hear such kind words!

This way `model.pipe[2][2].bert.pooled_output` will only give you an access to tensorflow graph node.

To get actual values you will have to do some changes in `__call__` method of [BertSquadModel](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/bert/bert_squad.py#L38):
you can change line [#261](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/models/bert/bert_squad.py#L38)
```
st, end, logits, scores = self.sess.run([self.start_pred, self.end_pred, self.yp_logits, self.yp_score], feed_dict=feed_dict)
```
to
```
pooled_output, st, end, logits, scores = self.sess.run([self.bert.pooled_output, start_pred, self.end_pred, self.yp_logits, self.yp_score], feed_dict=feed_dict)
```
and also return `pooled_output` in this method.

The next step would be adding `pooled_output` to [squad_bert](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/squad/squad_bert.json) configuration file:
you should add `pooled_output` to `out` section of `squad_bert_model` and to `out` of `chainer`.

**Comment by lcswillems** [comment]
Thank you so much for your answer!! It works perfectly!!
