### ISSUE TITLE
Is your trained BERT model the same than Google Research's one?

### ISSUE THREAD

**Issue by lcswillems** [deepmipt/DeepPavlov#826]
Hi,

When I do:

```
from deeppavlov import build_model, configs

text = '...'
question = '...'

model = build_model(configs.squad.squad_bert, download=True)
```

Is the trained BERT model downloaded the same than Google Research's one that is available on TensorFlow Hub? Or did you train it specifically for the SQuAD task?

**Comment by yurakuratov** [comment]
Hello again!

We use models from Google Research for English language as initialization for `squad_bert` model. Then we trained it especially for the SQuAD task on SQuAD dataset.

**Comment by lcswillems** [comment]
Thank you for this fast answer!
