### ISSUE TITLE
Difference between ELMo embedding for sentence/separate tokens

### ISSUE THREAD

**Issue by joistick11** [deepmipt/DeepPavlov#829]
Hello,

I am trying to use ELMo embedder for further text classification task. I cannot find information on that, so forced to ask a question here.

What is the conceptual difference between this 
`elmo([['вопрос', 'жизни', 'и' ,'смерти']])`
and this
`elmo([['вопрос жизни и смерти']])`
The embedding size is the same, but the values are different. 

Thanks in advance.

**Comment by kudep** [comment]
Hello! You can tokenize the text in any correct way. Or use a split on space giving the whole sentence

**Comment by joistick11** [comment]
ok, thank you.
