### ISSUE TITLE
Masked LM task

### ISSUE THREAD

**Issue by lcswillems** [deepmipt/DeepPavlov#840]
Hi,

Does DeepPavlov include a trained model for the masked LM task?

Thank you :)

**Comment by mu-arkhipov** [comment]
We have trained BERT for Russian language. http://files.deeppavlov.ai/deeppavlov_data/bert/rubert_cased_L-12_H-768_A-12_v1.tar.gz
Check out the docs page http://docs.deeppavlov.ai/en/master/components/bert.html

**Comment by lcswillems** [comment]
Hi,

I don't understand why you are mentioning the russian model?

I just want to know if you have trained an end-to-end network for the masked LM task?

I.e. a network that takes a text with a masked word and outputs a suggestion for the masked word.

**Comment by mu-arkhipov** [comment]
The model I mentioned was **trained** on the **Masked LM** task. We use these models as embedders only.  If you are talking about inference of these model exactly in the Masked LM mode, currently we don't have such options.

**Comment by lcswillems** [comment]
Okay, thanks for the answer!

**Comment by dsoloviev** [comment]
Hi! I'm trying to use Deep Pavlov models for Russian masked LM task in Hugging Face. But there are no adequate results. Why so? May be I've missed something =)

from transformers import pipeline

fill_mask = pipeline(
    "fill-mask",
     model = 'DeepPavlov/rubert-base-cased', 
     tokenizer = 'DeepPavlov/rubert-base-cased'
)

result = fill_mask(f"Александр Пушкин - великий русский {fill_mask.tokenizer.mask_token} .")
print(result)
