### ISSUE TITLE
Setting `DP_MODELS_PATH` and `DP_DOWNLOADS_PATH` variables doesn't really work

### ISSUE THREAD

**Issue by my-master** [deepmipt/DeepPavlov#844]
All configs in DeepPavlov library have their own way of what is written in `MODELS_PATH`:
* some configs have just `{ROOT_PATH}/models`
* some configs have one more folder, ex. `{ROOT_PATH}/models/kbqa_mix_lowercase`
* some configs have a lot of additional folders, ex. `{ROOT_PATH}/models/classifiers/insults_kaggle_v3`

This makes pointless setting `DP_MODELS_PATH` environment variable because it will overwrite `MODELS_PATH` and all paths that have additional folders cannot be found then.

I think it could be fixed by standardizing `MODELS_PATH` in all configs as `{ROOT_PATH}/models`, and all additional folders should be in a different variable (` MY_FOLDER = {MODELS_PATH/whatever/folders}`).

**Comment by yoptar** [comment]
Resolved with #888
