### ISSUE TITLE
Dump NerNetwork model

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#846]
How  to dump nernetwork model?

**Comment by mu-arkhipov** [comment]
The network is dumped automatically based on the best validation score. See the config `save_path` parameters. Most of the models dump their files in a separate folders in the `~/.deeppavlov/models/` directory.

**Comment by serhio7** [comment]
Maybe it's because I'm using code from tutorial  02_deeppavlov_ner.ipynb
As far as I can see this tutorial is not contain interface for save/load model
