### ISSUE TITLE
QA System using predict_on_stream()

### ISSUE THREAD

**Issue by gulatig** [deepmipt/DeepPavlov#847]
Hi,

I am trying to use deeppavlov for building a QA system. I tried using interact_model, which I am able to do. Now I was trying to predict_on_stream(). We need to send a file as an argument . But I am getting an error. Please let me know how to use predict_on_stream() api. Please share if you have any examples to study.

Regards,
Gaurav

**Comment by yoptar** [comment]
Hi,

If you're working from command line, you can run something like:
```bash
python -m deeppavlov predict <path-to-config> -b <batch-size> -f <path-to-data>
```

The same can be achieved with this python code:
```python3
predict_on_stream(config=path_to_config, batch_size=batch_size, file_path=path_to_data)
```
Results will be printed to stdout
