### ISSUE TITLE
Ошибка при использовании модели tfidf_logreg_autofaq

### ISSUE THREAD

**Issue by Skvortsovg** [deepmipt/DeepPavlov#848]
Добрый день!
Пытаюсь обучить модель tfidf_logreg_autofaq на своем датасете. 
Выполнение 
```
faq = SimilarityMatchingSkill(data_path = 'mydataset.csv',
                                  x_col_name = 'question',
                                  y_col_name = 'answer',
                                  save_load_path = 'testmodel/',
                                  config_type = 'tfidf_logreg_autofaq',
                                  edit_dict = {},
                                  train = True)
```
прерывается со следующей ошибкой.

/opt/chatbotvenv/lib/python3.7/site-packages/deeppavlov-0.3.0-py3.7.egg/deeppavlov/core/data/simple_vocab.py in load_line(self, ln)
    125             cnt = self._min_freq
    126         else:
--> 127             token, cnt = ln.split('\t', 1)
    128         return token, cnt
    129 

ValueError: not enough values to unpack (expected 2, got 1)

Если я правильно понимаю, то у меня проблема с генерацией словаря. Пробовал убрать этот модуль из конфига, но ничего не получилось. Что мне можно попробовать для работы с этой моделью?

**Comment by vaskonov** [comment]
Приветствую Григорий,
Тут может быть несколько проблем, пожалуйста убедитесь что ваш mydataset.csv действительно tab-separated c заголовками question и answer. Дополнительно запустите код под Python3.6

**Comment by Skvortsovg** [comment]
Василий, добрый день!
Согласно описанию SimilarityMatchingSkill, датасет должен быть с разделителями-запятыми. На Python 3.6 ситуация аналогична

Уточню, что пример с тестовым датасетом у меня работает корректно. Помимо этого модель tfidf_autofaq запускается на моем датасете.

Рассмотртрев конфиг модели tfidf_logreg_autofaq, я понял, что ошибка возникает при выполнении следуюего блока
```
{
        "id": "answers_vocab",
        "class_name": "simple_vocab",
        "fit_on": [
          "y"
        ],
        "save_path": "{MODELS_PATH}/faq/ru_my_answers.dict",
        "load_path": "{MODELS_PATH}/faq/ru_my_answers.dict",
        "in": "y",
        "out": "y_ids"
      },
```

Если я правильно понял, то именно файл ru_my_answers.dic должен иметь tab-separated структуру из двух полей. В моем же случае встречаются строки и одним полем. Не могу понять почему так происходит:(

**Comment by vaskonov** [comment]
It seems like something wrong with the csv file. Please make sure that the csv dataset is consistently formatted, particularly the strings should be double-quoted, i.e.
"What's DeepPavlov?", "DeepPavlov is an open-source conversational AI library"

**Comment by Skvortsovg** [comment]
Hello! I caught a situation why so can occur. And so, such an error can occur if there is a line break in the field. 

```csv
question,answer
"Что такое МФТИ?","МФТИ 
- это московской физико-технический институт"
"Что такое Яндекс", """Яндекс"" - это поисковая система"
```

**Comment by brandonra97** [comment]
Um this was never resolved? Why was it closed?
