### ISSUE TITLE
Вопрос о levenshtein_corrector_ru

### ISSUE THREAD

**Issue by Skvortsovg** [deepmipt/DeepPavlov#850]
Добрый день!
При работе с моделями коррекции ошибок, получил следующий случай.

https://gist.github.com/Skvortsovg/65ec7a9b4a16af5d19186e97404e2424

Подскажите, пожалуйста, почему в одном случае слово Изменяется на верный вариант, а в другом нет.

Заранее спасибо за помощь.

**Comment by acriptis** [comment]
Вероятно, модель приучена корректировать слова в зависимости от контекста (в первом случае контекст есть, во втором он пустой). 
Корректировки с пустым контекстом возможно нужно обучать дополнительно ("сон це" или "солнце" - каждый вариант может оказаться верной корректировкой, хотя второй правдоподобнее для русского языка).

**Comment by yoptar** [comment]
Здравствуйте!
В пайплайне модели используется языковая модель, обученная на предложениях из Википедии, которая обеспечивает исправление слов в контексте соседних слов предложения, поэтому в разных предложениях одно и то же слово может быть исправлено по-разному.

**Comment by Skvortsovg** [comment]
Спасибо за исчерпывающие ответ!
