### ISSUE TITLE
riseapi error

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#852]
![image](https://user-images.githubusercontent.com/4029753/58387367-259a0f00-8016-11e9-8b5a-66c87b8b6590.png)
Keep got error with rise api but command line say that is all good 
![image](https://user-images.githubusercontent.com/4029753/58387373-406c8380-8016-11e9-97f9-91276a25a6d1.png)
What could be wrong with that?

**Comment by yoptar** [comment]
Hi,
Please, try to open http://localhost:5000/ or http://127.0.0.1:5000/
On Windows trying to access 0.0.0.0 ip can lead to an error.

**Comment by serhio7** [comment]
Thanks a lot. It works
