### ISSUE TITLE
Download weights from command line

### ISSUE THREAD

**Issue by lcswillems** [deepmipt/DeepPavlov#857]
Hi,

Is there a way to download the weights from command line?

For example, when I do `python -m deeppavlov install squad_bert`, it only downloads the code, not the weights.

Lucas

**Comment by yoptar** [comment]
Hi Lucas,
You can run `python -m deeppavlov download squad_bert` to download all model files and embeddings.

**Comment by lcswillems** [comment]
THANK YOU!

**Comment by lcswillems** [comment]
Is it possible to do both in the same command?

**Comment by yoptar** [comment]
Yes, actually. You can run `python -m deeppavlov install -d squad_bert`.

**Comment by lcswillems** [comment]
Perfect! Thank you :)
