### ISSUE TITLE
Word similarity in NER

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#860]
What's the best way to add word similarity in NER - add training sample with similar word to tagged word or check word similarity on the running model?
Example suppose I'm having tag B-reward, and I want to recognize all sample:
Command win first **trophee**.  
PSG win the **title** this year. 
Bjorndalen won **gold medal**.

**Comment by mu-arkhipov** [comment]
Hello!
The easiest way to do so is to use ELMo as an embedder and build classifier on top of it. Check out [Few-Shot NER documentation](http://docs.deeppavlov.ai/en/latest/components/ner.html#few-shot-language-model-based).

**Comment by serhio7** [comment]
Thanks for an answer!
I will try it out
