### ISSUE TITLE
Custom training for context question answering

### ISSUE THREAD

**Issue by kmsravindra** [deepmipt/DeepPavlov#865]
Hi,

Thanks for this library. I was able to successfully install and test the context question answering component. However I would like to know how should I go about custom training (on top of the pre-trained weights) the model with my own set of vocabulary? Specifically, the questions that I am seeking your help are wrt - 

1. Where and how should I specify the commands for custom training on question answer component.
2. In what fashion should I prepare my training data to accomplish this. Any template for the format of the training data?

Thanks a lot!

regards,
Ravindra

**Comment by yurakuratov** [comment]
Hi!
1. To continue training of already trained model you can just run `python -m deeppavlov train config_name`
2. Every configuration file has `dataset_reader` section describing source of data. E.g. when you start training of model it will download original SQuAD dataset and store at `"data_path": "{DOWNLOADS_PATH}/squad/"`. You can check its format and you can put you data to this path.

**Comment by colipso** [comment]
I also have the same question , Any template for the format of the training data?

**Comment by cyrilthank** [comment]
i found this https://github.com/deepmipt/DeepPavlov/issues/423 for entity
but i am looking for similar steps for intent 
can you please advise

**Comment by srishtikohli99** [comment]
Can you please provide with a code snippet or a template

**Comment by yurakuratov** [comment]
Data format for context question answering should be the same as used for every pre-trained model for context question answering in DeepPavlov. This format is not documented but is the same as used in SQuAD v1.1 https://rajpurkar.github.io/SQuAD-explorer/. 
This dataset can be found [here](http://files.deeppavlov.ai/datasets/squad-v1.1.tar.gz).

Context question answering models use [SquadDatasetReader](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_readers/squad_dataset_reader.py#L26) to read the data from disk and [SquadIterator](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_iterators/squad_iterator.py#L26) to extract context-question-answer from dataset.
