### ISSUE TITLE
ODQA answers from ru_odqa_infer_wiki and from demo.ipavlov.ai mismatch

### ISSUE THREAD

**Issue by vitalyuf** [deepmipt/DeepPavlov#866]
Hi!
When I ask russian ODQA at demo.ipavlov.ai it gives me more or less relevant answers.
But when I try to use russian ODQA, using python -m deeppavlov interact ru_odqa_infer_wiki -d it gives irrelevant answers. For example:
```
question_raw::кто такой Владимир Путин
>> 29 %
question_raw::Рим это столица чего?
>> Atelier des båtisseurs
question_raw::Рим - это солица 
>> лембос
question_raw::Как отводятся излишки тепла у млекопитающих?
>> Leptoptilos robustus

```
What is the problem?

**Comment by yoptar** [comment]
Hi @vitalyuf,
at [demo.ipavlov.ai](demo.ipavlov.ai) we actually have the `ru_odqa_infer_wiki_rubert_noans` config running. You can find it in the latest release.

**Comment by vitalyuf** [comment]
Thank you!
It works! She is alive!))
