### ISSUE TITLE
Rubert results on FactRuEval scores

### ISSUE THREAD

**Issue by king-menin** [deepmipt/DeepPavlov#872]
Если ли у вас метрики на корпусе FactRuEval для модели NER Rubert.

**Comment by bond005** [comment]
Мы пробовали запустить наши стандартные модели NER на датасете FactRuEval-2016 и получили следующие результаты:

1) классический NER на основе FastText и BiLSTM-CRF: **Val. F1** = 84,54%, **Test F1** = 69,38%
2) RuBERT-NER: **Val. F1** = 92,08%, **Test F1** = 82,66%

Но это нельзя пока что сравнить с алгоритмами NER участников соревнования FactRuEval-2016, потому что мы использовали CoNLL-овскую методику расчёта F1, при которой любое, даже частичное, несовпадение сущностей засчитывается как ошибка, а организаторы соревнования FactRuEval использовали нечёткое сопоставление эталонных и распознанных сущностей, при котором частичное совпадение - тоже успех (см. раздел 6 статьи http://www.dialog-21.ru/media/3430/starostinaetal.pdf). Т.е., к примеру, если наш NER должен был распознать "Московский Физтех" как именованную сущность класса ORG, а распознал только "Физтех", то по используемой нами методике CoNLL-2003 это однозначная ошибка, а согласно методике FactRuEval-2016 это "почти правильный" результат.

Мы пока что не реализовывали методику расчёта FactRuEval-2016. А вообще, на наш взгляд, более интересными русскоязычными датасетами для оценки машинно-обучаемых NER являются **Named_Entities_5** и **Named_Entities_3** http://www.labinform.ru/pub/named_entities/descr_ne.htm

**Comment by king-menin** [comment]
А какой скор на этих датасетах или может у вас есть статья?

**Comment by king-menin** [comment]
И можно указать на код в репозитории где считается ваша метрика (я нашел f1 только по токенам).
