### ISSUE TITLE
Установить длину ответа в ODQA

### ISSUE THREAD

**Issue by nikolas2223** [deepmipt/DeepPavlov#873]
Какую строчку в конфигах можно изменить, чтобы поменять длину ответа?
В документации найти не удалось.
Присутствует ли такая возможность?

**Comment by fleandr** [comment]
неа там нет такого ответ минимальный всегда

пт, 7 июн. 2019 г. в 12:07, nikolas2223 <notifications@github.com>:

**Comment by yurakuratov** [comment]
Да, длина ответа не регулируется.
Но можно найти ответ в исходной статье википедии и извлечь, например, предложение содержащее ответ.

**Comment by nikolas2223** [comment]
> Да, длина ответа не регулируется.
> Но можно найти ответ в исходной статье википедии и извлечь, например, предложение содержащее ответ.

А каким образом это можно сделать?

**Comment by yurakuratov** [comment]
Без изменений кода компонент ODQA не получится.
ODQA состоит из двух основных моделей: ранкер статей википедии и модель поиска ответа.

В конфиге есть `logit_ranker` который принимает на вход чанки текста и возвращает лучший ответ. Код этой компоненты можно изменить так, чтобы вернуть чанк в котором был найден лучший ответ и его позицию.
