### ISSUE TITLE
DSTC2 intents output

### ISSUE THREAD

**Issue by bhavykhatri** [deepmipt/DeepPavlov#878]
I am unable to see DSTC2 intent output. I have tried changing the source code by printing them but it failed. There are 28 intents but able to find only 18 of them manually (including inform_food, negate etc.). Please tell me a way to print all of them by their index value. The closest problem I got was this one: https://github.com/deepmipt/DeepPavlov/issues/680 . 

`from deeppavlov import build_model, configs`
`CONFIG_PATH = configs.classifiers.intents_dstc2_bert`
`model = build_model(CONFIG_PATH, download=True`

The output is intent such as inform_food along with a 28 dimensional array. I am unable to find that mapping.

**Comment by bhavykhatri** [comment]
@yoptar, any solutions. Manually i am able to find 20 of them especially after 22 index, no success. Also fed them with dstc3 examples for a long time but didn't find any unique one. I think they are very sparse.

**Comment by yoptar** [comment]
Hi, @bhavykhatri,
If you're using the latest `DeepPavlov` version, you can see all classes by running
```python3
list(model['classes_vocab'].items())
```
