### ISSUE TITLE
Metrics problem while evaluating a list of lists

### ISSUE THREAD

**Issue by cuent** [deepmipt/DeepPavlov#882]
While trying the FAQ example with a different dataset, I found a problem with metrics. It prints `0.0` always.

What I did: 
- Added a new reader that supports a test set for question/answer 
- Added the evaluation target and metrics _accuracy_.

I see that is implemented as follows. The problem is that y_predicted is a list of lists and y _true is a list of strings. So, there is never a match. 

I made a quick fix for this but I was wondering if this is a bug, or I am using some component incorrectly. 

For example, lists are as follows:
`y_true = ['answer 1', 'answer 2']`
`y_predicted = [['answer 1'], ['answer 2']]`

```
    examples_len = len(y_true)
    correct = sum([y1 == y2 for y1, y2 in zip(y_true, y_predicted)])
    return correct / examples_len if examples_len else 0
```

This is the config:
```
    "metrics": [
      {
        "name": "accuracy",
        "inputs": ["y", "answer"]
      }
    ]

```

**Comment by vaskonov** [comment]
Hey @cuent , could you paste the entire config here.

make sure that the `out` value of `chainer` fits your `y_true`. Try leaving the `metrics` as  `"metrics": ["accuracy"]`.
