### ISSUE TITLE
Bert for classification

### ISSUE THREAD

**Issue by Aygera** [deepmipt/DeepPavlov#890]
Здравствуйте!
Я новичок в deep learning, хотела бы претренированную модель руберт использовать для своих данных. Задача обычная классификация русских текстов - 5 классов. Работаю на гугл колаб.
Есть ли у вас туториалы пошагово как применять bert от deeppavlov для собаственных данных? как менять конфиг файл? Для примера взяла rusentiment_bert.json, но не могу разобраться как привести свои данные в тот формат, который требуется для MODELS_PATH.
Спасибо!

**Comment by dilyararimovna** [comment]
Здравствуйте!

Готового тюториала по использованию Bert classifier нет. Есть тюториал просто по классификации в DeepPavlov ttps://github.com/deepmipt/DeepPavlov/blob/master/examples/classification_tutorial.ipynb.
В данном тюториале описано в каком виде должен быть сохранен датасет для классификации. Путь к папке и названия файлов, а также навзания соответсвующих колонок `x` и `y` вы должны указать в `dataset_reader`, а также убрать из текущего конфига разбиение train файла на train и valid (если у вас уже есть valid в отдельном файле. если нет - оставьте текущий вариант `dataset_iterator`):
```
  "dataset_reader": {
    "class_name": "basic_classification_reader",
    "x": "text",
    "y": "label",
    "data_path": "{DOWNLOADS_PATH}/rusentiment/",
    "train": "rusentiment_random_posts.csv",
    "test": "rusentiment_test.csv"
  },
  "dataset_iterator": {
    "class_name": "basic_classification_iterator",
    "seed": 42,
    "split_seed": 23,
    "field_to_split": "train",
    "split_fields": [
      "train",
      "valid"
    ],
    "split_proportions": [
      0.9,
      0.1
    ]
  },
```
заменить на
```
  "dataset_reader": {
    "class_name": "basic_classification_reader",
    "x": "text",
    "y": "label",
    "data_path": "/path_to_my_data_folder/",
    "train": "my_train_file.csv",
    "valid": "my_valid_file.csv",
    "test": "my_test_file.csv"
  },
  "dataset_iterator": {
    "class_name": "basic_classification_iterator",
    "seed": 42
  },
```
Далее вам необходимо скачать rubert файлы. Для этого надо запустить команду
```
python -m deeppavlov download paraphraser_rubert
```

Для использования Bert classifier скопируйте конфиг `rusentiment_bert.json`, 
замените пути к файлам берта на соответствущие rubert:

для `bert_preprocessor`:
```
"vocab_file": "{DOWNLOADS_PATH}/bert_models/multi_cased_L-12_H-768_A-12/vocab.txt",
```
на
```
"vocab_file": "{DOWNLOADS_PATH}/bert_models/rubert_cased_L-12_H-768_A-12_v1/vocab.txt",
```

для `bert_classifier`:
```
"bert_config_file": "{DOWNLOADS_PATH}/bert_models/multi_cased_L-12_H-768_A-12/bert_config.json",
        "pretrained_bert": "{DOWNLOADS_PATH}/bert_models/multi_cased_L-12_H-768_A-12/bert_model.ckpt",
```
на 
```
"bert_config_file": "{DOWNLOADS_PATH}/bert_models/rubert_cased_L-12_H-768_A-12_v1/bert_config.json",
        "pretrained_bert": "{DOWNLOADS_PATH}/bert_models/rubert_cased_L-12_H-768_A-12_v1/bert_model.ckpt",
```

It is also necessary to change models_path to new one (to save new model):
```
"MODELS_PATH": "{ROOT_PATH}/models/classifiers/rusentiment_bert_v0/"
```
на
```
"MODELS_PATH": "{ROOT_PATH}/models/classifiers/mydata_rubert_v0/"
```

**Comment by Aygera** [comment]
Спасибо! я сделала все как было описано вами, кроме того что  модель руберт ранее я уже скачала и напрямую указала ссылку где находся скаченные файлы. 
итоговый json:
`{
  "dataset_reader": {
    "class_name": "basic_classification_reader",
    "x": "Text",
    "y": "Label",
    "data_path": "bert/",
    "train": "train2.csv",
    "valid": "dev2.csv",
    "test": "test2.csv"
  },
  "dataset_iterator": {
    "class_name": "basic_classification_iterator",
    "seed": 42
  },
  "chainer": {
    "in": ["text_a", "text_b"],
    "in_y": ["y"],
    "pipe": [
      {
        "class_name": "bert_preprocessor",
        "vocab_file": "bert/vocab.txt",
        "do_lower_case": false,
        "max_seq_length": 64,
        "in": ["text_a", "text_b"],
        "out": ["bert_features"]
      },
      {
        "class_name": "bert_classifier",
        "n_classes": 5,
        "one_hot_labels": true,
        "multilabel":true,
        "bert_config_file": "bert/bert_config.json",
        "pretrained_bert": "bert/bert_model.ckpt",
        "save_path": "model_rubert",
        "load_path": "model_rubert",
        "keep_prob": 0.5,
        "optimizer": "tf.train:AdamOptimizer",
        "learning_rate": 2e-05,
        "learning_rate_drop_patience": 3,
        "learning_rate_drop_div": 2.0,
        "in": ["bert_features"],
        "in_y": ["y"],
        "out": ["predictions"]
      }
    ],
    "requirements": [
      "{DEEPPAVLOV_PATH}/requirements/tf.txt",
      "{DEEPPAVLOV_PATH}/requirements/bert_dp.txt"
    ],
    "out": ["predictions"]
  }
}`

и ошибка которую выдает следующая команла когда я хочу запустить трэйн !python -m deeppavlov train /content/drive/My\ Drive/bert/intent_chat.json

2019-06-20 20:31:42.915 WARNING in 'deeppavlov.core.commands.train'['train'] at line 100: Train config is missing. Populating with default values
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/deep.py", line 85, in main
    start_epoch_num=args.start_epoch_num)
  File "/usr/local/lib/python3.6/dist-packages/deeppavlov/core/commands/train.py", line 106, in train_evaluate_model_from_config
    if 'evaluation_targets' not in train_config and ('validate_best' in train_config
TypeError: argument of type 'NoneType' is not iterable

**Comment by dilyararimovna** [comment]
Вы упустили параметры тренировки(
Плюс насколько я поняла, у вас один текст на входе для кжадого примера?
вот так должен выглядеть ваш конфиг
```
{
  "dataset_reader": {
    "class_name": "basic_classification_reader",
    "x": "Text",
    "y": "Label",
    "data_path": "bert/",
    "train": "train2.csv",
    "valid": "dev2.csv",
    "test": "test2.csv"
  },
  "dataset_iterator": {
    "class_name": "basic_classification_iterator",
    "seed": 42
  },
  "chainer": {
    "in": [
      "x"
    ],
    "in_y": [
      "y"
    ],
    "pipe": [
      {
        "class_name": "bert_preprocessor",
        "vocab_file": "bert/vocab.txt",
        "do_lower_case": false,
        "max_seq_length": 64,
        "in": [
          "x"
        ],
        "out": [
          "bert_features"
        ]
      },
      {
        "id": "classes_vocab",
        "class_name": "simple_vocab",
        "fit_on": [
          "y"
        ],
        "save_path": "model/classes.dict",
        "load_path": "model/classes.dict",
        "in": "y",
        "out": "y_ids"
      },
      {
        "in": "y_ids",
        "out": "y_onehot",
        "class_name": "one_hotter",
        "depth": "#classes_vocab.len",
        "single_vector": true
      },
      {
        "class_name": "bert_classifier",
        "n_classes": 5,
        "one_hot_labels": true,
        "multilabel": true,
        "bert_config_file": "bert/bert_config.json",
        "pretrained_bert": "bert/bert_model.ckpt",
        "save_path": "model_rubert",
        "load_path": "model_rubert",
        "keep_prob": 0.5,
        "optimizer": "tf.train:AdamOptimizer",
        "learning_rate": 2e-05,
        "learning_rate_drop_patience": 3,
        "learning_rate_drop_div": 2.0,
        "in": [
          "bert_features"
        ],
        "in_y": [
          "y_onehot"
        ],
        "out": [
          "y_pred_probas"
        ]
      },
      {
        "in": "y_pred_probas",
        "out": "y_pred_ids",
        "class_name": "proba2labels",
        "max_proba": true
      },
      {
        "in": "y_pred_ids",
        "out": "y_pred_labels",
        "ref": "classes_vocab"
      }
    ],
    "out": [
      "y_pred_labels"
    ]
  },
  "train": {
    "epochs": 10,
    "batch_size": 64,
    "metrics": [
      "sets_accuracy"
    ],
    "validation_patience": 5,
    "val_every_n_epochs": 1,
    "log_every_n_epochs": 1,
    "show_examples": false,
    "evaluation_targets": [
      "train",
      "valid",
      "test"
    ],
    "class_name": "nn_trainer",
    "tensorboard_log_dir": "model/"
  },
  "metadata": {
    "requirements": [
      "{DEEPPAVLOV_PATH}/requirements/tf.txt",
      "{DEEPPAVLOV_PATH}/requirements/bert_dp.txt"
    ]
  }

}
```

**Comment by Aygera** [comment]
Спасибо!!!

**Comment by Aygera** [comment]
Теперь у меня другая ошибка))))

tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /content/drive/My Drive/model_rubert: Failed precondition: /content/drive/My Drive/model_rubert; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

model_rubert это у меня пустая директория, я думала он сам сохранит туд натренированную маодель, но почему-то ищет там файл...(

**Comment by dilyararimovna** [comment]
Вы же хотите использовать претренированный rubert? Для этого надо его скачать сначала. 
Выше я написала, что вы можете скачать rubert файлы. Для этого надо запустить команду:
```
python -m deeppavlov download paraphraser_rubert
```

**Comment by dilyararimovna** [comment]
При это убедитесь, что пути к bert config, vocab и chekcpoint соответствуют тем, куда скачается rubert (это тоже есть выше). при этом не забудьте, что вы из конфига убрали переменные, так что вам следут прописать полный путь.

**Comment by Aygera** [comment]
Я не совсем понимаю следующее (спасибо что обьясняете):
Вот эти три файла являются претренированным рубертом, который содержится в файле rubert_cased_L-12_H-768_A-12_v1.tar.gz и пути к ним указываются здесь:
         "vocab_file": "bert/vocab.txt",
         "bert_config_file": "bert/bert_config.json",
         "pretrained_bert": "bert/bert_model.ckpt".
Однако, следующее требует пути к модели натренированную на определенную задачу (интент, парафрейз).:
        "save_path": "model_rubert",
        "load_path": "model_rubert",
В моем случае, у меня свои данные по классификации и у меня нет такой модели есть только файлы трэйн, дев и тест. Что я должна указать в "save_path и  "load_path"? Ранее вы писали:
It is also necessary to change models_path to new one (to save new model):

"MODELS_PATH": "{ROOT_PATH}/models/classifiers/rusentiment_bert_v0/"
на

"MODELS_PATH": "{ROOT_PATH}/models/classifiers/**mydata_rubert_v0**/"
В "MODELS_PATH" я должна указать ссылку на скаченную paraphrase_rubert и берт сам дообучит его на моих данных?

**Comment by dilyararimovna** [comment]
Вы должны указать пути к претренированному rubert (те, куда он скачается), как вы верно написали к овкабу, конфигу и чекпоинту. А вот уже пути `save_path` and `load_path` к файлам тренируемой поверх берта модели (в вашем случае, классификатору) пишете пусте - те, куда хотите, чтобы он вам ее сохранил.

**Comment by Aygera** [comment]
Спасибо! Вроде запустилось на колабе уже более 4 часов трейнится.
но еще пару вопросов осталось:
1. Получается когда поверх руберта классифкация происходит, то там еще одна прослойка нейронки тренируется только? правильно понимаю? это и есть fine-tuning? если скоорденируете в исходниках на место где создается слой для классификации буду благодарна!
2. на колабе только на 12 часов дается время, вдруг если подключение сорвется, могу ли из чекпойнтов продложить трениоровку?

**Comment by dilyararimovna** [comment]
1. BertModel слои тоже тренируются, когда тренится классификатор. См. `deeppavlov/models/bert/bert_classifier.py`.
2. Вы можете сохранить веса, а потом подгрузить, чтобы дотренировать (проверьте главное, чтобы `load_path` для `bert_classifier` совпадал с путем к сохраненным моделям. Однако учтите, что это будет не то же самое, что тренировать непрерывно, так как при сохранении модели классификатора состояние оптимайзера не сохраняется, он инициализируется заново при подгрузке предобученного классификатора.

**Comment by Aygera** [comment]
Здравствуйте!
Тенсорфлоу запрашивает libcublas 9.0, у меня стоит CUDA 10.1... На Colab.google та же самая ошибка. 
python3 -m deeppavlov train /home/cheese/aigerim_dl/intent_chat.json
2019-07-04 01:55:37.658 WARNING in 'deeppavlov.core.trainers.fit_trainer'['fit_trainer'] at line 84: TensorFlow could not be imported, so tensorboard log directory`/home/cheese/aigerim_dl/Bert-Multi-Label-Text-Classification/pybert/model/pretrain/uncased_L-12_H-768_A-12/model/` will be ignored
[nltk_data] Downloading package punkt to /home/cheese/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/cheese/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to
[nltk_data]     /home/cheese/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /home/cheese/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
Traceback (most recent call last):
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/cheese/env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cheese/env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/__main__.py", line 3, in <module>
    main()
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/deep.py", line 85, in main
    start_epoch_num=args.start_epoch_num)
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/core/commands/train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/core/trainers/nn_trainer.py", line 291, in train
    self.fit_chainer(iterator)
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/core/trainers/fit_trainer.py", line 103, in fit_chainer
    component = from_params(component_config, mode='train')
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/core/common/params.py", line 94, in from_params
    cls = get_model(cls_name)
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/core/common/registry.py", line 71, in get_model
    return cls_from_str(_REGISTRY[name])
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/core/common/registry.py", line 40, in cls_from_str
    return getattr(importlib.import_module(module_name), cls_name)
  File "/home/cheese/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cheese/env/lib/python3.6/site-packages/deeppavlov/models/preprocessors/bert_preprocessor.py", line 21, in <module>
    from bert_dp.tokenization import FullTokenizer
  File "/home/cheese/env/lib/python3.6/site-packages/bert_dp/tokenization.py", line 25, in <module>
    import tensorflow as tf
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cheese/env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/cheese/env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/cheese/env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by yoptar** [comment]
В колабе девятую куду можно установить следующим набором команд:
```
!wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run
!chmod +x cuda_9.0.176_384.81_linux-run
!./cuda_9.0.176_384.81_linux-run --override --silent --toolkit
!echo '/usr/local/cuda-9.0/lib64' > /etc/ld.so.conf.d/cuda-9-0.conf
!ldconfig
```

Или можно попробовать поработать с веткой [feat/python37](https://github.com/deepmipt/DeepPavlov/tree/feat/python37), там уже должен работать `tensorflow==1.14.0`, но для него всё равно нужна cuda 10.0, а не 10.1 (нужная версия установлена на колабе)

**Comment by romariosar** [comment]
Здравствуйте у меня ошибка стала появляться:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/__main__.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/deep.py", line 75, in main
    start_epoch_num=args.start_epoch_num)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/core/commands/train.py", line 121, in train_evaluate_model_from_config
    trainer.train(iterator)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/core/trainers/nn_trainer.py", line 336, in train
    self.train_on_batches(iterator)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/core/trainers/nn_trainer.py", line 282, in train_on_batches
    self.last_result = self._chainer.train_on_batch(x, y_true)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/core/common/chainer.py", line 169, in train_on_batch
    return component.train_on_batch(*preprocessed)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/core/models/tf_backend.py", line 28, in _wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/deeppavlov/models/bert/bert_classifier.py", line 221, in train_on_batch
    _, loss = self.sess.run([self.train_op, self.loss], feed_dict=feed_dict)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1149, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 2) for Tensor 'y_ph:0', which has shape '(?,)'
```

подскажите в чем может быть проблема?

**Comment by dilyararimovna** [comment]
Добрый день!
Скорее всего возникаемая проблема связана со словарем по имеющимся классам. Словраь либо не скачался, либо вы его не обновили, если у вас свои классы в датасете, либо не передали количество классов в `bert_classifier`.

Так как ваша проблема не имеет отношения к данному issue, рекомендуется заводить нвоое issue для обсуждения.
Спасибо!
