### ISSUE TITLE
Downgrade tensoflow version AttributeError

### ISSUE THREAD

**Issue by artyerokhin** [deepmipt/DeepPavlov#892]
There is no fixed tensorflow version in requirments.txt. 
So, if I downgrade tensorflow to version 1.10, I'll catch error: "AttributeError: module 'tensorflow' has no attribute 'init_scope'.

**Comment by yoptar** [comment]
We have additional requirements for specific configs. You can run `python -m deeppavlov install <config_name>` to install those.

**Comment by yoptar** [comment]
Assuming the issue is resolved.
