### ISSUE TITLE
Conll 2003 with pos russian

### ISSUE THREAD

**Issue by serhio7** [deepmipt/DeepPavlov#899]
Is there possibility of syntax tagging trainset for russian language  by deeppavlov tools?
UPD. I need an example for input format of ner conll2003 pos because when trying to execute this prorgram I've got keyerror:
`from deeppavlov import build_model,train_model, configs

CONFIG_PATH = configs.ner.ner_conll2003_pos
model = build_model(CONFIG_PATH, download=True)

wert = model([('год подряд'),('JJ DT')])
  File "<ipython-input-6-ce7302899faf>", line 12, in <module>
    wert = model([('год подряд'),('JJ DT')])

  File "Python\Python36\site-packages\deeppavlov\core\common\chainer.py", line 204, in __call__
    return self._compute(*args, param_names=self.in_x, pipe=self.pipe, targets=self.out_params)

  File "Python\Python36\site-packages\deeppavlov\core\common\chainer.py", line 224, in _compute
    x = [mem[k] for k in in_params]

  File "\Python\Python36\site-packages\deeppavlov\core\common\chainer.py", line 224, in <listcomp>
    x = [mem[k] for k in in_params]

KeyError: 'pos'`

**Comment by yoptar** [comment]
Hi @serhio7,

a working example would be:
```python3
tokens, tags = model([['Only', 'France', 'and', 'Britain', 'backed', 'Fischler', "'s", 'proposal', '.']],
                     [['RB', 'NNP', 'CC', 'NNP', 'VBD', 'NNP', 'POS', 'NN', '.']])
```
The first argument is a batch of tokenized sentences, the second one is a batch of lists of POS-tags

**Comment by yoptar** [comment]
You can use our [morphological tagger](http://docs.deeppavlov.ai/en/master/components/morphotagger.html) to generate POS-tags, but you would have to parse the results.

**Comment by serhio7** [comment]
@yoptar  Thank you! it works!
But I have one more question 
How could I get  output from morphological tagger in CONLL-U format?
I added string  "format_mode": "ud", in morpho_ru_syntagrus_pymorphy.json, but output was with '-' instead of result.
![image](https://user-images.githubusercontent.com/4029753/60175299-d6fdb180-981b-11e9-988b-1f8fb6af33f6.png)

**Comment by yoptar** [comment]
It is in CONLL-U format, but since it returns only POS-tags and morphological features, everything else is set to `_` as per the [format description](https://universaldependencies.org/format.html):
> Underscore (_) is used to denote unspecified values in all fields except ID

**Comment by serhio7** [comment]
Okay. Is it a way to get tag like this format (for ner conll with pos) but for russian language
![image](https://user-images.githubusercontent.com/4029753/60177010-82a90080-9820-11e9-9c94-da2991ba1ee8.png)

**Comment by yoptar** [comment]
These are the [Penn Treebank tags](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html) and our morphotagger returns [UD tags](https://universaldependencies.org/u/pos/). You can use raw tags from our morphotagger, I think, it should just rebuild the POS-vocabulary, but if you want to use the same tags, you can try and use [the conversion table at https://universaldependencies.org/tagset-conversion/en-penn-uposf.html](https://universaldependencies.org/tagset-conversion/en-penn-uposf.html)

**Comment by serhio7** [comment]
Thanks a lot!
