### ISSUE TITLE
Training multi_squad_noans model?

### ISSUE THREAD

**Issue by jayachandra2128** [deepmipt/DeepPavlov#902]
When i run "python -m deeppavlov train deeppavlov/configs/squad/multi_squad_nouns.json" it is getting stuck and running through ages at line "Loading saved tokens vocab from */vocab_embedder.pckl" and finally server getting killed. Im even using GPU's. Have you faced such issue while training multi_squad_noans model. Can you please guide me on how to train multi_squad_noans model.

**Comment by yurakuratov** [comment]
Hi!

`vocab_embedder.pckl` is loaded on CPU. It looks like you might have problems with available RAM. Could you check RAM usage when you run training?
