### ISSUE TITLE
Errors in rule-based obscenity detection for Russian

### ISSUE THREAD

**Issue by strawberrypie** [deepmipt/DeepPavlov#917]
Some Russian words are considered obscene, while they aren't:
```bash
$ python -m deeppavlov interact ru_obscenity_classifier

text::ебург
>> True
text::бляшка
>> True
text::застрахуйте
>> True
text::корабля
>> True
```

**Comment by kudep** [comment]
Thanks for the issue. Yes, it is a frequent weakness for rule-based ones.

**Comment by kudep** [comment]
You can add excepted words  to a file `~/.deeppavlov/downloads/obscenity_dataset/obscenity_words_exception.json` for easy to use.
And we are all glad to welcome you to your pulls requests.

**Comment by yoptar** [comment]
These exceptions were added to the `obscenity_words_exception.json` file on our server, so it should be fixed after redownloading.
