### ISSUE TITLE
Train ODQA using own data set

### ISSUE THREAD

**Issue by AbhilashChalla** [deepmipt/DeepPavlov#919]
How can I train ODQA with my own set of articles instead of using the pre-trained model? I was not able to find much in the documentation.

**Comment by my-master** [comment]
Hi @AbhilashChalla,

Until we updated our official documentation, please refer to this comprehensive [`Medium post`](https://medium.com/deeppavlov/open-domain-question-answering-with-deeppavlov-c665d2ee4d65), `Training the model` section.
