### ISSUE TITLE
Pretrained model usage

### ISSUE THREAD

**Issue by AlexeySorokin** [deepmipt/DeepPavlov#92]
There should be an easy way to apply a pretrained model (e.g. NER) to the user data by passing the same steps as in train_model_from_config except of train_on_batches. interact_model is by no means such a way since it requires redirecting stdin passing test sentences one by one.

**Comment by yoptar** [comment]
resolved with #179

**Comment by AlexeySorokin** [comment]
#179 does not close it since da66a06 reads input file "as is" and does not allow to apply custom DatasetReader. Please reopen the issue again.
