### ISSUE TITLE
Can't make spelling correction demo actually correct spelling

### ISSUE THREAD

**Issue by Saluev** [deepmipt/DeepPavlov#923]
I followed [docs](http://docs.deeppavlov.ai/en/master/components/spelling_correction.html) on spelling correction to run the demo:

    python -m deeppavlov interact brillmoore_kartaslov_ru

But I couldn't find any cyrillic string it would modify. Then I took the entire [test set](http://www.dialog-21.ru/media/3838/test_sample_testset.txt) to find any differences.

    python -m deeppavlov interact brillmoore_kartaslov_ru < test_sample_testset.txt > test_output.txt
    # removing ^x:>> with vim
    vimdiff test_sample_testset.txt test_output.txt

And all I see is differences in whitespaces. What am I doing wrong?

**Comment by Saluev** [comment]
Damerau-Levenshtein model works though.

**Comment by yoptar** [comment]
Hi there,

Does `python -m deeppavlov interact brillmoore_kartaslov_ru -d` do anything differently?
It looks like the Brill-Moor error model was not downloaded nor trained.

**Comment by Saluev** [comment]
Oh, it was indeed so. I expected an error message in that case.
