### ISSUE TITLE
DeepPavlov's NER to Spacy conversion and usage

### ISSUE THREAD

**Issue by GraphGrailAi** [deepmipt/DeepPavlov#925]
Hi, could anyone suggest a simple way how to use or convert Deeppavlov's RU NER to Spacy's NER RU (no ru model for now)?

Seems both are quite similar in terms of objects and even datasets used for training.
Maybe there are some code snippet where i can take deepavlov ner and integrate it easily ?

https://spacy.io/api/annotation#named-entities 
http://docs.deeppavlov.ai/en/master/components/ner.html

**Comment by theanhle** [comment]
Hi, I don't really guess what you mean. Here is some code you can use to integrate a DeepPavlov NER model in your system:

`from deeppavlov import configs, build_model
ner_model = build_model(configs.ner.ner_ontonotes_bert, download=True)
ner_model(['Bob Ross lived in Florida'])
>>> [[['Bob', 'Ross', 'lived', 'in', 'Florida']], [['B-PERSON', 'I-PERSON', 'O', 'O', 'B-GPE']]]`
