### ISSUE TITLE
Is it possible to train NER model using BILUO data format?

### ISSUE THREAD

**Issue by swicaksono** [deepmipt/DeepPavlov#926]
Hey, I have a NER data set written in BILUO data format. I just see the ner docs here in [training data](http://docs.deeppavlov.ai/en/master/components/ner.html#training-data), I guess it using IOB format. So, if I want to try to train a new pre train NER model by using my BILUO dataset format, is it possible?   
Thank you in advance.

**Comment by mu-arkhipov** [comment]
Hey! There should be no problem except metrics computation. [Chunk-wise F-measure](https://github.com/deepmipt/DeepPavlov/blob/8726173c92994b3f789790b5879052d2f7953f47/deeppavlov/metrics/fmeasure.py#L32) used at the moment does not support this format at the moment.
