### ISSUE TITLE
Slot fillis and fastText, why did make this?

### ISSUE THREAD

**Issue by BetoFernandess** [deepmipt/DeepPavlov#937]
Hi, I want know why were done the slot fill and the fastText model of the Deeppavlov's DSTC, and how to make simillar models. I'm creating an DSTC-simillar chatbot in my enterprise, and my model does not work acceptabliy with the DSTC's conventional model.
If anybody will be reply me this, I thanks for this.

**Comment by vikmary** [comment]
Hi
DSTC model is best documented [here](http://docs.deeppavlov.ai/en/master/skills/go_bot.html). The idea is that the `go_bot` models consists of three modules: intent classifier, slot filler (or named entity recognition model) and a dialogue policy module. Intent classifier is optional. Therefore to train your own model you have to
* train a [ner model](http://docs.deeppavlov.ai/en/master/components/ner.html) for your type of slots
* train a final [policy network](http://docs.deeppavlov.ai/en/master/skills/go_bot.html).
