### ISSUE TITLE
How to begin building own go_bot?

### ISSUE THREAD

**Issue by a-malagayo** [deepmipt/DeepPavlov#939]
Hi, I'm trying to build my own bot using the goal-oriented skill and was struggling with how and where to start? I have read thru the documentation, but I am still confused with how to begin.  

Do I just have to change the variables within the go_bot config file, provide templates, and a bot training.json file? Can I get guidance over the file structure of what I would need in order to start building one?

Any help is appreciated.

**Comment by vikmary** [comment]
Hi,
We've just released a new DeepPavlov version with updated gobot tutorial. For info, see https://github.com/deepmipt/DeepPavlov/blob/master/examples/gobot_tutorial.ipynb
