### ISSUE TITLE
automatic parameter tuning is not giving good accuracy 

### ISSUE THREAD

**Issue by SekharDhana** [deepmipt/DeepPavlov#940]
hi,
i tried giving 5 or 10 iterations for evolution process, it is iterating only 5 or 10 times only, but the accuracy is very very less, then i went for paramsearch as well if i give n folds its iterating till n number if i give leave one out cross validation (loo) it is iterating infinetly but still i am not able to get good accuracy can you help me so that i could get best accuracy.

**Comment by kishore0905** [comment]
yes i am also facing the same issue as @SekharDhana . Could you give any idea to solve this problem

**Comment by dilyararimovna** [comment]
Hello!
I am very sorry for such delayed answer.
The evolutionary search is time-consuming, and requires a lot of iterations to find a good set of parameters.
