### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by ugrozkr** [deepmipt/DeepPavlov#952]
I want to integrate Turkish language support for Deep Pavlov. Is it possible or how can i do this on project ??

**Comment by yoptar** [comment]
Hi @ugrozkr,
Sorry for the late reply.
We would appreciate your contributions. Are there any interesting tasks for Turkish language that you would like to solve? Theoretically you could just take an existing DeepPavlov configuration and train it on your data.
You can also take a look at our [multi-language BERT-based models](https://demo.ipavlov.ai/#/mu/ner) and think on what could be improved in them specifically for Turkish.
But for most tasks, I think, the difficulties would be some specific tokenization rules and algorithms of word vectorization, as Turkish has potentially infinite vocabulary, so word2vec can perform poorly.
