### ISSUE TITLE
ValueError: Error when checking target: expected activation_5 to have shape (2,) but got array with shape (1,)

### ISSUE THREAD

**Issue by drorvinkler** [deepmipt/DeepPavlov#954]
Hi,
I'm training a binary classifier, and I keep getting the error in the title whenever my training data is 1282 samples long.
I have this in my configuration:
```
    "split_fields": [
      "train",
      "valid"
    ],
    "split_proportions": [
      0.9,
      0.1
    ]
```
I did some debugging, and I'm pretty sure the problem is the data is split into training that is 1153 samples long, and validation which is the rest.
This causes `DataLearningIterator.gen_batches` to generate a batch which is 1 sample (because 1153 divided by 64 has a remainder of 1).
This, in turn, causes a problem in `KerasClassificationModel.train_on_batch`.
Specifically, it seems like `np.squeeze(np.array(labels))` creates an array of shape `(2,)` instead of `(1,2)` when `len(labels)==1`.
The exception is then caused by `training_utils.standardize_input_data` in `Keras` reading this as it would an array with shape `(2,1)`, i.e. two label vectors of length 1 instead of one label vector of length 2.

Thanks

**Comment by dilyararimovna** [comment]
Thank you for the issue!
Fixed in pull-request #973
