### ISSUE TITLE
paramsearch is not creating model files its just creating cv_tmp folder and its deleting even i got best score

### ISSUE THREAD

**Issue by kishore0905** [deepmipt/DeepPavlov#956]
hello, when i do paramsearch it is creating a folder cv_tmp even though i am getting best score its not creating the models files in intents_snips_v9 folder.

**Comment by yoptar** [comment]
Hi @kishore0905,
Paramsearch does not save models as it uses cross-validation to score them. But it does save a configuration file for the best model and outputs its path to `stderr`

**Comment by yoptar** [comment]
I'll assume that the issue is resolved for now. Feel free to reopen it or open a new one if you have any other questions.
