### ISSUE TITLE
Is it possible to get relations between NER?

### ISSUE THREAD

**Issue by tinkermachine** [deepmipt/DeepPavlov#965]
Is it possible to get relations (REL) between NER entities using this library?

For e.g. If I were to pass in the following sentence "Moscow is the capital of Russia", I can extract Moscow and Russia as the NER. How can I extract 'is capital of" as the relation between the two NER entities?

**Comment by mu-arkhipov** [comment]
Hello!
We have no Information Extraction in the library at the moment.  However, a good starting point for such task can be [OpenIE](https://nlp.stanford.edu/software/openie.html).
