### ISSUE TITLE
Why NER tagging gives such an output scheme?

### ISSUE THREAD

**Issue by danyanyam** [deepmipt/DeepPavlov#975]
In docs it’s said that for the input
`[‘Bob lives in Moscow’]` 
the output of NER-tagger will be something like that:
`[“B-PER”, “O”, “O”, “B-LOC”]`
But in fact my output is something like:
`[“B-B-PER”, “O”, “O”, “B-B-LOC”]`

So my question is why it could be the case and what is the difference between two predictions I-B-PER and B-I-PER.

Many thanks!!!!!!!!!

**Comment by vikmary** [comment]
Hello, do you use one of deeppavlov pretrained ner models or a model trained on your own dataset?

**Comment by danyanyam** [comment]
I used my own dataset to train ner model with standard BIO-tagging scheme

**Comment by vikmary** [comment]
What config file did you use as a base? Particularly, it is important which `dataset_reader` did you use and which `dataset_iterator`.

For example, `snips_ner_iterator` as a `dataset_iterator` adds "B-" and "I-" prefixes by default (it expects tags without prefixes). If your dataset instead contains prefixes already, then you can write your own `dataset_iterator`, copying [`SnipsDatasetIterator`](https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/dataset_iterators/snips_ner_iterator.py) and [registering](http://docs.deeppavlov.ai/en/master/devguides/registry.html) it.
