### ISSUE TITLE
Files not found while running telegram bot 

### ISSUE THREAD

**Issue by ohld** [deepmipt/DeepPavlov#98]
I run telegram bot interface (copy-paste from readme)
```
python -m deeppavlov.deep interactbot deeppavlov/configs/go_bot/gobot_dstc2.json -t TELEGRAM_TOKEN
```

But the error is given:

```  
File "/home/ubuntu/work/ipavlov/DeepPavlov/deeppavlov/core/common/file.py", line 22, in read_json
    with open(fpath) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '../telegram_utils/models_info.json' 
```

All files have been downloaded and successfully used in training.

**Comment by seliverstov** [comment]
It's a bug. We will fix it soon. Workaround: try to `cd deeppavlov` (there is a folder inside root directory) and run from this directory (not from the root directory of the project).

**Comment by ohld** [comment]
That worked, thanks
