### ISSUE TITLE
Docs for trained model telegram test

### ISSUE THREAD

**Issue by ohld** [deepmipt/DeepPavlov#99]
I can't find the want how to deploy a model trained on my own dataset for intent classification (train.csv) and test it via telegram bot. 

I've used this config for training:
https://github.com/deepmipt/DeepPavlov/blob/master/deeppavlov/configs/intents/intents_snips.json
And this readme:
https://github.com/deepmipt/DeepPavlov/tree/master/deeppavlov/models/classifiers/intents

**Comment by seliverstov** [comment]
Do you want to interact with your trained model throw Telegram interface? You cant use command like python -m deeppavlov.deep interactbot <path to config>  -t <telegram token>

**Comment by ohld** [comment]
It was not obvious that I can use the same config I used for training. Thanks.
