### ISSUE TITLE
Source corpus for the Russian KenLM language model

### ISSUE THREAD

**Issue by vadimkantorov** [deepmipt/DeepPavlov#995]
What was the source data for the http://files.deeppavlov.ai/lang_models/ru_wiyalen_no_punkt.arpa.binary.gz language model? What KenLm arguments were used for the estimation?

Thank you!

**Comment by yoptar** [comment]
Hi @vadimkantorov,
The 3-gram model was trained on russian wikipedia and a closed news dataset. All punctuation characters were removed.
